### ISSUE TITLE
ASS alpha does not detect seasons like S03

### ISSUE THREAD

**Issue by FallingSnow** [ZeroQI/Absolute-Series-Scanner#10]
Instead of dividing the show up into seasons, it just adds all the episodes to season 1. Do I have to rename all my seasons folders from `S##` to `Season ##`?

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner%20-%20Alpha.py

uploaded new version
grouping folders needs adding separately but code way simpler and no longer a hack

**Comment by FallingSnow** [comment]
Thank you!
