### ISSUE TITLE
Dragon Ball Super Naming Issues?

### ISSUE THREAD

**Issue by xnaas** [ZeroQI/Absolute-Series-Scanner#104]
Preface: Sorry if this is the wrong place for this.

I made [a post](http://forums.plex.tv/discussion/comment/1498793/#Comment_1498793) about my issues with _Dragon Ball Z_ on the Plex forums, but quickly found tvdb4 to be the fix after making said post.

Since _Dragon Ball Super_ wasn't working right either, I [figured I would try the same approach](http://forums.plex.tv/discussion/comment/1498803/#Comment_1498803). Named the show just like _Dragon Ball Z_ (but obviously called _Super_) and tried tvdb4...doesn't work quite right. It makes 6 seasons, but then pulls no episode names.

**Additional Info**
Path: `M:\Anime\Dragon Ball Super [tvdb4-295068]`
File Name Examples:

- Dragon Ball Super - S01E001.mkv
- Dragon Ball Super - S01E016.mkv
- Dragon Ball Super - S01E096.mkv

This is the same naming scheme used for _Dragon Ball Z_, which seems to work without issue.

I did try removing the `S01E` part from every episode, but that didn't seem to help either.

Any particular logs I should attach to help diagnose this? Is anyone else running into the same problem with _Super_? Is this as simple as fixing the naming?

**Comment by sven-7** [comment]
Hi -

I do agree with what you did in dropping the `S01E` part.  For TVDB2/3/4 it's best to use absolute numbering.  I have all mine labeled:  `Dragon Ball Super - 01.mkv` etc... through the latest ep at 103. 

Have you tried tvdb3 at all? That will use the TVDB defined seasons (only has five seasons as it includes the fourth filler-ish season listed on ASS within on of theirs).

@ZeroQI will likely was the Scanner log and HAMA log for this.

**Comment by xnaas** [comment]
TVDB3 does the same thing where it makes the seasons, but doesn't pull a single episode name.

I hope these are the right logs? (Note: Only episodes 1 through 46 are currently present in the folder)

Recent Logs:
- [PMS-Media-Scanner.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1232028/PMS-Media-Scanner.zip)
- [PMS-Plugin-Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1232029/PMS-Plugin-Logs.zip)

**Comment by xnaas** [comment]
Some updated logs after adding in episodes after 46 (note: 77-83 are not present):
- [Hama.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1232053/Hama.zip)
- [Scanner.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1232054/Scanner.zip)

**Comment by xnaas** [comment]
Plex Dance was no help, unfortunately. Still just throws episodes into seasons but grabs no episode names.

**Comment by sven-7** [comment]
Can you delete your scanner and HAMA logs, then go into Dragon Ball Super and click "Refresh Metadata" for that show only?  It looks like the Scanner is fully doing it's job.  From what I can see in HAMA, it's pulling, but another look might be good.  I assume you're using the official release for HAMA and ASS?  I'm currently on the Beta, but I believe that everything with TVDB3/4 was smoothly working before @ZeroQI  started working hard on the beta.

Additionally, I've found that occasionally I have to hit Refresh Metadata twice to get everything to pull down.  

You should also go into `\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\` for both AniDB and theTVDB and delete the XML files for Dragon Ball Super (AniDB:  11210 and TVDB:  295068)

HAMA:  [com.plexapp.agents.hama.log.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1232262/com.plexapp.agents.hama.log.zip)

**Comment by xnaas** [comment]
>I assume you're using the official release for HAMA and ASS?

Yup. Latest of both. I could _try_ beta builds, but idk.

>Can you delete your scanner and HAMA logs,

>You should also go into `\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\` for both AniDB and theTVDB and delete the XML files for Dragon Ball Super (AniDB: 11210 and TVDB: 295068)

Did all of this then tried to pull data again. Tried to pull metadata a few times. Still no episode names.

[com.plexapp.agents.hama.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1232289/com.plexapp.agents.hama.zip)

**Comment by xnaas** [comment]
I can see in the logs it pulls the XML from http://thetvdb.com/api/A27AD9BE0DA63333/series/295068/all/en.xml, but...is it just not reading that or...?

**Comment by ZeroQI** [comment]
i remove from scanner log anything not db super
created with batch file the folder with dummy file
scanned it in the beta as that is the latest...
works ...

I need to replace current code with the beta but need to remove all remaining bugs so need them all identified

**Comment by xnaas** [comment]
So works in the beta but I guess I'm SOL at the moment on stable? Oh well. I suppose I'll live without episode titles. 😜

**Comment by ZeroQI** [comment]
Please use the beta, while not perfect it has less issues than current official version.
The beta will be replacing the code so i need testers.
It does group scanner and agent logs on a per serie basis... I thought that was super cool...

**Comment by xnaas** [comment]
Sure! Where can I get the latest beta? (Saw it mentioned eons ago in another issue, but haven't really followed since then.)

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/releases
https://github.com/ZeroQI/Hama.bundle/releases/download/Beta/Hama.bundle.2017-06-30.00h11.zip is the latest to date

**Comment by xnaas** [comment]
Beta instantly fixed it. Grabbed the metadata for it without a hitch. ❤️ 

Where's your donate button? 😉

**Comment by ZeroQI** [comment]
Download link is in Plex forums in my signature but here is a shortcut
[donation link](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=S8CUKCX4CWBBG&lc=IE&item_name=ZeroQI&item_number=Absolute%20Series%20Scanner%20%2b%20Http%20AniDB%20Metadata%20Agent&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by ZeroQI** [comment]
Holly Molley you about doubled all i got in donations in total, the highest i had was 20 before, thanks.
You can select in agent settings which meta source you want, in which order.
logs moved to the agent data folders, theme songs have a source for full songs (televisiontunes.com), it is a better version..
Thank you, and let me know if you have any issue

**Comment by xnaas** [comment]
>Holly Molley you about doubled all i got in donations in total, the highest i had was 20 before, thanks.

Really? This has to be one of the greatest resources to ever enter my life. 😭 

>You can select in agent settings which meta source you want, in which order.
logs moved to the agent data folders, theme songs have a source for full songs (televisiontunes.com), it is a better version..

I'll dig around settings and stuff after work today, thanks! 😄

**Comment by xnaas** [comment]
@ZeroQI I do have one question.

What are my language options? Standard two-letter language codes?

What are `main` and `x-jat` supposed to be?

![img](https://i.imgur.com/k8HXeje.png)

**Comment by ZeroQI** [comment]
The language are the ones used by anidb in their title xml file cached here for me:
\\nas\Plex\Library\Application Support\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\AniDB\anime-titles.xml
for Code Geass:
```
	<anime aid="4521">
		<title type="official" xml:lang="th">โค้ด กีอัส ภาคการปฏิวัติของลูลูช</title>
		<title xml:lang="ko" type="official">코드기어스 반역의 를르슈</title>
		<title xml:lang="ja" type="short">cg1</title>
		<title xml:lang="x-jat" type="short">cghnl</title>
		<title type="short" xml:lang="x-jat">cg r1</title>
		<title xml:lang="x-jat" type="short">CodeGeass</title>
		<title xml:lang="x-jat" type="syn">code geass</title>
		<title type="official" xml:lang="fr">Code Geass</title>
		<title xml:lang="x-jat" type="syn">Code Geass 1</title>
		<title type="syn" xml:lang="vi">Code Geass: Cuộc khởi nghĩa của Lelouch</title>
		<title type="main" xml:lang="x-jat">Code Geass: Hangyaku no Lelouch</title>
		<title type="syn" xml:lang="pt-BR">Code Geass: Lelouch da Rebelião</title>
		<title type="syn" xml:lang="es">Code Geass: Lelouch de la Rebelión</title>
		<title type="syn" xml:lang="ca">Code Geass: Lelouch de la Rebel·lió</title>
		<title xml:lang="fr" type="syn">Code Geass ~ Lelouch de la rébellion</title>
		<title xml:lang="pl" type="official">Code Geass: Lelouch of the Rebellion</title>
		<title type="official" xml:lang="en">Code Geass: Lelouch of the Rebellion</title>
		<title xml:lang="it" type="official">Code Geass: Lelouch of the Rebellion</title>
		<title type="official" xml:lang="de">Code Geass: Lelouch of the Rebellion</title>
		<title xml:lang="tr" type="syn">Code Geass: Lelouch`un Başkaldırısı</title>
		<title xml:lang="x-jat" type="syn">Code Geass R1</title>
		<title xml:lang="zh-Hant" type="official">Code Geass 反叛的魯路修</title>
		<title xml:lang="zh-Hans" type="official">Code Geass 反叛的鲁鲁修</title>
		<title xml:lang="pt-BR" type="syn">Código Geass: Lelouch da Rebelião</title>
		<title xml:lang="pt-BR" type="syn">Código Geass R1</title>
		<title xml:lang="x-jat" type="short">geass</title>
		<title type="short" xml:lang="x-jat">geass1</title>
		<title type="syn" xml:lang="lt">Kodas Geass: Leloušio sukilimas</title>
		<title type="syn" xml:lang="he">קוד ג`יאס</title>
		<title xml:lang="bg" type="syn">Код Геас: Бунтът на Люлюш</title>
		<title xml:lang="ru" type="syn">Код Гиас: Восставший Лелуш</title>
		<title xml:lang="ru" type="syn">Код Гиасс: Восстание Лелуша</title>
		<title type="syn" xml:lang="uk">Код Ґіас: Повстання Лелуша (R1)</title>
		<title type="official" xml:lang="ja">コードギアス 反逆のルルーシュ</title>
		<title xml:lang="zh-Hans" type="syn">叛逆的鲁鲁修</title>
	</anime>
```
main title is the main title in anidb.net, x-jat is the title in romaji, for japanese anime they always match.
For Code Geass main title is "Code Geass: Hangyaku no Lelouch"
mostly 2 letters as you can see but portuguese is split in variants

**Comment by xnaas** [comment]
>jap is shorthand for japanese language in french so i didn't took it as racial slur... Thnaks for letting me know

I figured. It's mostly a problem in America, but just figured I'd let you know before someone had a hissy fit about it. 😄
