### ISSUE TITLE
Slow Scanner

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#105]
I am not sure this is an ASS issue, but I wanted to see if anyone else had experienced this on the off-chance it is ASS.

I've been noticing that the scanner has been running very slowly.  Think 10-15 minutes per scan. 

It seems to run some, then get caught up.  While I didn't see anything in the individual ASS logs, I did notice in the 'Plex Media Scanner' log this coming up a few times:

`Aug 20, 2017 10:27:14.874 [8912] DEBUG - File 'F:\Series\Made in Abyss\Made in Abyss - 2 - Resurrection Festival.mkv' didn't exist, can't skip.`

It's not just with Made in Abyss, I've seen it with others as well. It's getting caught on files that have long been in the library. Here are the logs for that:

[Plex Media Scanner log.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1237143/Plex.Media.Scanner.log.zip)

**Comment by sven-7** [comment]
Also, I'm using the scanner that came with the beta.

**Comment by ZeroQI** [comment]
I don't have the problem that i noticed, will pay more attention but could have been corruption...
Have to do more coding tonight, can no longer do while at work

**Comment by sven-7** [comment]
Thanks. I've even deleted and replaced the file, which should have hopefully mitigated the corruption as being an issue, but it's still getting caught.

**Comment by sven-7** [comment]
Looks like this was talked about on the Plex forums before:  

https://forums.plex.tv/discussion/comment/970433#Comment_970433
https://forums.plex.tv/discussion/comment/1071890#Comment_1071890

**Comment by sven-7** [comment]
I went through one by one on the files that were causing this to pause, and Plex dance'd each series.  I think overall, it was about 10 series.  

A few issues noted along the way.

`[C] The Money of Soul and Possibility Control` had issues. When I removed the '[]' from the folder name, the series popped up as if it was not there before. I didn't remove it, but it showed up as a recently added series within Plex. 

The latest issue I'm seeing is this line:  `Aug 22, 2017 09:54:32.577 [9988] ERROR - Exception caught determining whether we could skip '' ~ Null value not allowed for this type`

**Comment by ZeroQI** [comment]
EndOfLine369 spotted a dual-scan of some folders issue, might be the cause
We are discussing and seem like adding seamless support of grouping folders with the downside of having to scan every scan is tolerable if other normal folders are cached properly. That avoid a scanner option in the agent and two versions of the scanner and do not impact users without grouping folders

**Comment by sven-7** [comment]
Should I try out the latest beta?

**Comment by ZeroQI** [comment]
yes please try latest scanner

**Comment by sven-7** [comment]
It did not help, but I may have found additional issues.  I've been using the scanner that came with the beta on 30 June. 

Using the beta scanner from today: 

1.  The next up for a 'didn't exist, can't skip' was Ajin.  I removed the series, but the scanner stopped reading it.  It would remove every episode up until 14 (the one it said was missing) and then do nothing.  It would continue to scan others, but Ajin was never removed from my library.

This error popped up:
```
Aug 24, 2017 16:11:30.376 [6920] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 324, in Scan
    Scan(subdir, subdir_files, mediaList, [], language, root)
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 621, in Scan
    else:    add_episode_into_plex(mediaList, file, root, path, show, 0, counter, title.strip(), year, None, "", length, None, None, None, None, None)
  File "C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 232, in add_episode_into_plex
    if ep_orig_single in mappingList:
TypeError: argument of type 'NoneType' is not iterable
```

Using ASS master branch:
2.  All of a sudden, the scanner was as fast as it used to be. I can see in the logs files that say "didn't exist, can't skip" but it does not stall the scanner like the new ones do. It also picked up Ajin and removed it instantly.  @ZeroQI / @EndOfLine369 , please see the attached.

3.  I moved back to the beta and hit scan.  Immediately, the scan started and stalled.  A new episode showing an error:  `Aug 24, 2017 16:26:36.538 [7832] DEBUG - File 'E:\Series\Assassination Classroom\Assassination Classroom - 23 - Time for the Summer Festival.mkv' didn't exist, can't skip.` This error shows up in the new and old scanner.  While I don't know the cause of the error, the scanners handle them very differently. 

A variety of logs:
[Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1250176/Logs.zip)

**Comment by EndOfLine369** [comment]
@sven-7, please re-pull the beta and check now.

**Comment by sven-7** [comment]
@EndOfLine369  - on the inital scan, the beta scanner seems to work as quickly as the production scanner. What was the issue?

I still see the "didn't exist" line, but the scanner now seems to continue and not stall.  I assume this 'error', if it indeed an actual error, has been prevalent for a long time.

**Comment by EndOfLine369** [comment]
The speed was from the addition of a internal scan loop that was added to the beta by ZeroQI that I was always confused on the need/requirement [Noted Here](https://github.com/ZeroQI/Absolute-Series-Scanner/commit/bd4abf342e3f774c965b7419784a1b6d9b3a6071##commitcomment-23783671).

The error was a bug on my part from when I enhanced fir grouping folders ☹️.  But is now fixed 😃.

**Comment by sven-7** [comment]
Sweet! I'll consider this closed then. 😃

I posted on the Plex forums about the "didn't exist, can't skip" part.  Will advise if I get any info out of it.
