### ISSUE TITLE
Adding Info to Season Summary

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#107]
I was thinking about how with the various TVDB modes there is a heavy emphasis on supporting seasonal and arc organization.  Is there any way to take description we place in TVDB4 and have that append to the Season Summary field in Plex?  TVDB does not support season descriptions at this time.  AniDB does not split shows into seasons.

```
    01|001|030|East Blue - Gathering the Crew
    02|031|044|Arlong Park
    03|045|063|Entering into the Grand Line 
    04|064|077|Whiskey Peak and Little Garden
    05|078|092|Drum Island
```

<img width="704" alt="screen shot 2017-08-23 at 2 22 48 pm" src="https://user-images.githubusercontent.com/18091557/29631743-9c6f7ea0-880e-11e7-81bf-0f1f828b5855.png">

We could make it look like:
<img width="708" alt="screen shot 2017-08-23 at 2 35 18 pm" src="https://user-images.githubusercontent.com/18091557/29632221-5142d72c-8810-11e7-9d54-f86414e73d02.png">

I was thinking of how we could support this in TVDB2 or 3, but I don't think it can work.  For some it might, but not all. 

I thought TVDB2, could may be able to fill the Season Summary field from AniDB, as it will have it as two separate shows, whereas TVDB has it as one.  

AniDB 9541's show description could fill the season one summary.
```
  <anime anidbid="9541" tvdbid="267440" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Shingeki no Kyojin</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;2-3;3-4;4-5;5-6;6-7;8-9;9-10;10-11;</mapping>
    </mapping-list>
  </anime>
```
AniDB 10944's description  could fill the season two summary. 
```
  <anime anidbid="10944" tvdbid="267440" defaulttvdbseason="2" episodeoffset="" tmdbid="" imdbid="">
    <name>Shingeki no Kyojin Season 2</name>
  </anime>

```

TVDB3 there isn't any way, unfortunately. TVDB does not keep season summaries (yet). 

Thoughts?

**Comment by ZeroQI** [comment]
The field is there like for "original_title" but the agent cannot populate it
Wanted to use anidb serie summary as tvdb season summary but Plex need to allow it....

**Comment by sven-7** [comment]
Ahh, okay. I was just wondering. Hopefully in the future TVDB will support season summaries.

**Comment by sven-7** [comment]
Thanks for the answer!
