### ISSUE TITLE
Versioned Specials added as additional copy

### ISSUE THREAD

**Issue by avluis** [ZeroQI/Absolute-Series-Scanner#110]
Noted this behavior today and I'm hoping on some tips that will help me automate my renaming tools to keep this behavior from repeating itself.

In summary, it seems that if a special is versioned (v2, v3, etc) then that special may end up matching existing entries.

Here are several snapshots to help illustrate this:

##### Directory Listing
![Directory Listing](https://user-images.githubusercontent.com/875593/30123576-21b9aefc-92f8-11e7-927e-3c465789548a.PNG)

##### Plex Entry
![Plex Entry](https://user-images.githubusercontent.com/875593/30123593-2cfbc48a-92f8-11e7-9e05-4262f3d092c7.PNG)

##### Series: Season 1
![Series: Season 1](https://user-images.githubusercontent.com/875593/30123615-3bf5ce2c-92f8-11e7-9bde-b11589d5d155.PNG)

##### Series: Specials
![Series: Specials](https://user-images.githubusercontent.com/875593/30123635-491215fc-92f8-11e7-939d-d6288f39bd6c.PNG)

##### Plex Entry: Episode 01 Details
![Plex Entry: Episode 01 Details](https://user-images.githubusercontent.com/875593/30123657-5bc81aca-92f8-11e7-9809-d1aef5273378.PNG)

##### Plex Entry: Special 01 Details
![Plex Entry: Special 01 Details](https://user-images.githubusercontent.com/875593/30123675-694f5bae-92f8-11e7-8e5a-10e5de212405.PNG)

**Comment by ZeroQI** [comment]
Versioned special end up in season 1, probably a regex issue.
```
ANIDB_OFFSET = [0, 100, 150, 200, 400, 0, 0]; ANIDB_RX  = [                                                                                                             ######### AniDB Specials regex ### 
  '(^|(?P<show>.*?)[ _\.\-]+)(SP|SPECIAL|OAV) ?(?P<ep>\d{1,2})(-(?P<ep2>[0-9]{1,3}))? ?(?P<title>.*)$',                                                                 #  5 # 001-099 Specials
  '(^|(?P<show>.*?)[ _\.\-]+)(OP|NCOP|OPENING) ?(?P<ep>\d{1,2}[a-z]?)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                      #  6 # 100-149 Openings
  '(^|(?P<show>.*?)[ _\.\-]+)(ED|NCED|ENDING) ?(?P<ep>\d{1,2}[a-z]?)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                       #  7 # 150-199 Endings
  '(^|(?P<show>.*?)[ _\.\-]+)(TRAILER|PROMO|PV|T) ?(?P<ep>\d{1,2}) ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                          #  8 # 200-299 Trailer, Promo with a  number  '(^|(?P<show>.*?)[ _\.\-]+)((?<=E)P|PARODY|PARODIES?) ?(?P<ep>\d{1,2})? ?(v2|v3|v4|v5)?(?P<title>.*)$',                                                                        # 10 # 300-399 Parodies
  '(^|(?P<show>.*?)[ _\.\-]+)(O|OTHERS?)(?P<ep>\d{1,2}) ?(v2|v3|v4|v5)?[ _\.\-]+(?P<title>.*)$',                                                                        #  9 # 400-499 Others
  '(^|(?P<show>.*?)[ _\.\-]+)(e|ep|e |ep |e-|ep-)?(?P<ep>[0-9]{1,3})((e|ep|-e|-ep|-)(?P<ep2>[0-9]{1,3})|)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                  # 10 # E01 | E01-02| E01-E02 | E01E02                                                                                                                       # __ # look behind: (?<=S) < position < look forward: (?!S)
  '(^|(?P<show>.*?)[ _\.\-]+)S ?(?P<ep>\d{1,2}) ?(?P<title>.*)$']      
```
Try to replace the above in the source with:
```
ANIDB_OFFSET = [0, 100, 150, 200, 400, 0, 0]; ANIDB_RX  = [                                                                                                             ######### AniDB Specials regex ### 
  '(^|(?P<show>.*?)[ _\.\-]+)(OP|NCOP|OPENING) ?(?P<ep>\d{1,2}[a-z]?)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                      #  5 # 100-149 Openings
  '(^|(?P<show>.*?)[ _\.\-]+)(ED|NCED|ENDING) ?(?P<ep>\d{1,2}[a-z]?)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                       #  6 # 150-199 Endings
  '(^|(?P<show>.*?)[ _\.\-]+)(TRAILER|PROMO|PV|T) ?(?P<ep>\d{1,2}) ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                          #  7 # 200-299 Trailer, Promo with a  number  '(^|(?P<show>.*?)[ _\.\-]+)((?<=E)P|PARODY|PARODIES?) ?(?P<ep>\d{1,2})? ?(v2|v3|v4|v5)?(?P<title>.*)$',                                                                        # 10 # 300-399 Parodies
  '(^|(?P<show>.*?)[ _\.\-]+)(O|OTHERS?)(?P<ep>\d{1,2}) ?(v2|v3|v4|v5)?[ _\.\-]+(?P<title>.*)$',                                                                        #  8 # 400-499 Others
  '(^|(?P<show>.*?)[ _\.\-]+)(e|ep|e |ep |e-|ep-)?(?P<ep>[0-9]{1,3})((e|ep|-e|-ep|-)(?P<ep2>[0-9]{1,3})|)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                  #  9 # E01 | E01-02| E01-E02 | E01E02  # __ # look behind: (?<=S) < position < look forward: (?!S)
  '(^|(?P<show>.*?)[ _\.\-]+)(SP|SPECIAL|OAV|S) ?(?P<ep>\d{1,2})(-(?P<ep2>[0-9]{1,3}))? ?(?P<title>.*)$']                                                               # 10  # Specials
```

**Comment by EndOfLine369** [comment]
@ZeroQI Not a regex issue. He's using 'S' (which is a season flag) instead of one of these three 'SP|SPECIAL|OAV' expected special strings.
So `"S1 - OVA 1" => Season 1 Ep 1` as expected.
@avluis 
Correct your special naming to be 'SP'
`"SP1 - OVA 1" => Season 0 Ep 1`

**Comment by avluis** [comment]
Got it -- so don't use `S` as a special (anidb naming) and use `SP` for correct parsing of specials.
Thank you!

**Comment by EndOfLine369** [comment]
As AniDB doesn't see seasons, it has no problems with using 'S' as specials. Which in use, it is not realistic to differentiate with season labels. Note, the scanner would see it as a special if there were no other numbers in the filename. (IE: "S1 - OVA" would be added as S0E1 but as there is a viable episode number with the "1" from "OVA 1" it puts it in as S1E1)

**Comment by EndOfLine369** [comment]
@ZeroQI , you also can't do that rearrange from https://github.com/ZeroQI/Absolute-Series-Scanner/issues/110#issuecomment-327798970
ALL specials have to be pulled out before it gets to the primary `'(^|(?P<show>.*?)[ _\.\-]+)(e|ep|e |ep |e-|ep-)?(?P<ep...` entry.
If you changed it around as you recommended, it would mess up many specials to be incorrectly mapped outside of S0.
EX: "SP1 - OVA 1" => would incorrectly be seen as S1E1 as it would hit the "1" from regex `'(^|(?P<show>.*?)[ _\.\-]+)(e|ep|e |ep |e-|ep-)?(?P<ep...` before it hit the "SP1" from regex `'(^|(?P<show>.*?)[ _\.\-]+)(SP|SPECIAL|OAV) ?(?P<ep...`

**Comment by avluis** [comment]
Thank you for going into detail. I went ahead and renamed the specials in this series.
Works as intended:

![capture](https://user-images.githubusercontent.com/875593/30172652-142a42a6-93bb-11e7-9732-a9625c224563.PNG)

**Comment by ZeroQI** [comment]
@EndOfLine369 thx. Sometimes you know my code better than i do :/ I need sleep... And reaching level 20 on Destiny 2, but especially sleep...

**Comment by avluis** [comment]
@EndOfLine369 While I have your attention -- how should I name OVAs to keep them from being grouped as well:

![capture](https://user-images.githubusercontent.com/875593/30190880-d19cdee2-9402-11e7-837d-7fa140a0d55c.PNG)

**Comment by EndOfLine369** [comment]
That is a separate series in AniDB.
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=9187
You will need to place it into a separate folder w/ [anidb2-9187] and it will be mapped to its corresponding TVDB placement when added into Plex.

**Comment by EndOfLine369** [comment]
nvm. misread your screenshot.

**Comment by EndOfLine369** [comment]
Looks like thats an issue with the ScudLee mapping definitions.
Your '9187' S1E2 is not being mapped to TVDB S0E10.
Also the '8691' S0E3-8 will not be mapped up +1 episode number.

![image](https://user-images.githubusercontent.com/16750699/30195928-837d7c56-9422-11e7-85bb-501087b353e1.png)

I've put in the commit into the online tmp corrections file we maintain as ScudLee is historically slow on making updates.
https://github.com/ZeroQI/Absolute-Series-Scanner/commit/5b3543e7fd0f1ba85ce81e55f01fb8d4e7d1d7dd

You might have to wait a day for the file age to reach 24hrs to be downloaded fresh. Or find a 'anime-list-corrections.xml' in your Plex temp directory and delete it so the scanner will see it missing and pull it.

**Comment by EndOfLine369** [comment]
@avluis hold, one more issue.

@ZeroQI, why does the code in live&beta refrence an incorrect file outside our base?

ANIDB_TVDB_MAPPING_MOD    = 'http://rawgit.com/Dingmatt/AMSA/master/Plug-in%20Support/Data/com.plexapp.agents.amsa/DataItems/anime-list-corrections.xml'

**Comment by EndOfLine369** [comment]
Should be:
http://rawgit.com/ZeroQI/Absolute-Series-Scanner/master/anime-list-corrections.xml

**Comment by EndOfLine369** [comment]
https://github.com/ScudLee/anime-lists/issues/96 submitted to correct the source.

**Comment by avluis** [comment]
@EndOfLine369 I have a fairly extensive collection and I wouldn't mind taking the time to address other issues like the one above (there are quite a few of them).

Is there a particular format I should follow? -- Can I create local corrections per series folder for each of the affected series and them post them here once I have everything mapping correctly?

I'm familiar with the ScudLee mapping definitions as well; if I can assist with corrections, I'm glad to do so.

**Comment by Dingmatt** [comment]
@EndOfLine369 Thats simple to explain, AMSA was the first to offer a correction file when scudlee's project went dormant though it's pretty out of date now a days; collaborations between ZeroQi and myself means we trade code where needed.

**Comment by deusxanime** [comment]
@EndOfLine369 you are missing option #0 there - anime-list-custom.xml directly in the anime series folder. That is still an option and the first place it looks right?

**Comment by Dingmatt** [comment]
@EndOfLine369 @deusxanime If the code shared by HAMA (including ASS) and AMSA hasn't changed then its actually.

1. Local library root "anime-list-custom.xml" file
2. Local library root "anime-list-corrections.xml" file
3. Local library root "anime-list-master.xml" file

With options 2 & 3 being periodically updated from the remote HAMA/ASS and ScudLee Git when the agent/scanner starts up; option 1 is never updated from a remote location.

**Comment by sixtenbe** [comment]
@EndOfLine369 ScudLee may be slow, but I currently have access to the project and at least for the time being will usually respond within a day to issue/pull request.

@avluis create an issue in the [ScudLee list](https://github.com/ScudLee/anime-lists) with the corrections or just the AniDB ids/series names of entries that need fixing and I should get around to fixing them. You can also fork the project, make changes and create a pull request.

**Comment by EndOfLine369** [comment]
ScudLee is already updated. 😁

**Comment by EndOfLine369** [comment]
Thanks sixtenbe

**Comment by EndOfLine369** [comment]
@Dingmatt @deusxanime
In looking at the code, for the ASS & HAMA it's mostly same.
ASS pulls in order and dosn't pull the rest if entry is found. 
HAMA pulls all three with the addition if a 'anime-list-custom.xml' is found in the series folder.

1. Local library root 'anime-list-custom.xml'
2. Remote 'ZeroQI/Absolute-Series-Scanner/master/anime-list-corrections.xml'
3. Remote 'ScudLee/anime-lists/master/anime-list-master.xml'
Both remote files are cached for a min of 1day's age locally before pulling from GigHub again.

**Comment by EndOfLine369** [comment]
Closing issue as I believe all questions are answered & avluis has the info on how to test then submit any mapping issues found.

**Comment by avluis** [comment]
@EndOfLine369 Yep, fine by me -- I'm a bit busy with a bit of programming and system ops but I'll get to submitting those mapping fixes as soon as time permits~

**Comment by avluis** [comment]
@EndOfLine369 Hey there~

I'm having a bit of trouble separating the following:
![re-zero-snip](https://user-images.githubusercontent.com/875593/30718179-beea42ca-9ee4-11e7-9594-c37964a92d64.PNG)

That is a snipped of Re:Zero [[anidb](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=11370)] [[tvdb](https://www.thetvdb.com/?tab=series&id=305089&lid=7)] you see above.

I noticed several entries on theTVDB.com for this series but the main series entry seems to have the [notation](https://www.thetvdb.com/?tab=season&seriesid=305089&seasonid=656941&lid=7) I'm looking for, though there are a few issues I'm having along the way:

- Specials are being merged along regular episodes: this affects episodes 1 -11.
- AniDB has a special listed before the matching specials on tvdb - so specials should be offset by one.

The first issue seems to be a scanner issue with having the regular episodes carry the series title while the specials begin with SP* -- if I remove the `P` from each title [ex; `SP2 - ReZero - Starting Break Time from Zero - 01 [BlurayDesuYo][Blu-ray](6eaa05b6)` --> `S2 - ReZero - Starting Break Time from Zero - 01 [BlurayDesuYo][Blu-ray](6eaa05b6)`], then the specials are not merged with the regular episode (as desired).

As for the second issue, I just need a few pointers for offsetting the specials by one and mapping them accordingly, if you don't mind.

**Comment by sixtenbe** [comment]
@avluis Can't help with the scanner, but for the mapping see this [commit](https://github.com/ScudLee/anime-lists/commit/030e18e0da3ba7dca173059a66b23b66f6dfc1a9) where I added the offset for the specials of Re:Zero Kara....

**Comment by ZeroQI** [comment]
@avluis test this arrangement please..
```
ANIDB_OFFSET = [0, 100, 150, 200, 400, 0, 0]; ANIDB_RX  = [                                                                                                                         ######### AniDB Specials regex ### 
  #'(^|(?P<show>.*?)[ _\.\-]+)(SP|SPECIAL|OAV) ?(?P<ep>\d{1,2})(-(?P<ep2>[0-9]{1,3}))? ?(?P<title>.*)$',                                                                             #  5 # 001-099 Specials
  '(^|(?P<show>.*?)[ _\.\-]+)(OP|NCOP|OPENING) ?(?P<ep>\d{1,2}[a-z]?)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                                  #  6 # 100-149 Openings
  '(^|(?P<show>.*?)[ _\.\-]+)(ED|NCED|ENDING) ?(?P<ep>\d{1,2}[a-z]?)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                                   #  7 # 150-199 Endings
  '(^|(?P<show>.*?)[ _\.\-]+)(TRAILER|PROMO|PV|T) ?(?P<ep>\d{1,2}) ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                                                                      #  8 # 200-299 Trailer, Promo with a  number  '(^|(?P<show>.*?)[ _\.\-]+)((?<=E)P|PARODY|PARODIES?) ?(?P<ep>\d{1,2})? ?(v2|v3|v4|v5)?(?P<title>.*)$',                                                                        # 10 # 300-399 Parodies
  '(^|(?P<show>.*?)[ _\.\-]+)(O|OTHERS?)(?P<ep>\d{1,2}) ?(v2|v3|v4|v5)?[ _\.\-]+(?P<title>.*)$',                                                                                    #  9 # 400-499 Others
  '(^|(?P<show>.*?)[ _\.\-]+)(e|ep|e |ep |e-|ep-)?(?P<ep>[0-9]{1,3})((e|ep|-e|-ep|-)(?P<ep2>[0-9]{1,3})|)? ?(v2|v3|v4|v5)?([ _\.\-]+(?P<title>.*))?$',                              # 10 # E01 | E01-02| E01-E02 | E01E02                                                                                                                       # __ # look behind: (?<=S) < position < look forward: (?!S)
  '(^|(?P<show>.*?)[ _\.\-]+)SP? ?(?P<ep>\d{1,2}) ?(?P<title>.*)$']                                                                                                                   # 11 # 001-099 Specials #'S' moved to the end to make sure season strings are not caught in prev regex

```

**Comment by avluis** [comment]
The change above results in the following when using `SP` for specials:

![re-zero-snip1](https://user-images.githubusercontent.com/875593/30734897-aab9e266-9f42-11e7-80c8-dedc8e17f758.png)
![re-zero-snip2](https://user-images.githubusercontent.com/875593/30734901-ae42fb8e-9f42-11e7-8d3f-c43dd53b50fd.png)
