### ISSUE TITLE
Beta - Logs

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#112]
I'm running both the latest HAMA and ASS beta versions.  While in `_Logs` it splits out my HDDs to make the logging folders, no logs are being generated.  I have under 5 showing up in each folder.  Any indication I can look for to send you guys?

<img width="662" alt="screen shot 2017-09-11 at 10 39 30 am" src="https://user-images.githubusercontent.com/18091557/30280360-8a1bbede-96dd-11e7-8269-0fa423ca710c.png">

**Comment by ZeroQI** [comment]
Need to match scanner logging to hama logging and alleviate EndOfLine369's worries and issues about that method

**Comment by EndOfLine369** [comment]
For old logs, large logs, and log we can't properly determine when to truncate. There will need to be some kind of cleanup done by probably ASS at initial root directory scan or initial startup of HAMA. This will keep the logs in check and not max out space.

How is logging maintained in HAMA? On every refresh, does it truncate its specific series log then repopulate it? Would have to have separate scanner/agent logs if that was the case as you would loose all scanner log info. You can also have multiple series folders to make up a single Plex series entry (sole purpose of anidb2) so you can't have hama log names determined by the path of episode parts. Would have to be done based on series name.

**Comment by ZeroQI** [comment]
@EndOfLine369 
I use the scanner to reset the log size to zero on each scan. 
i use the folder name (including force id if present) so both the scanner and agent are using the same ones. the file is common to the serie folder (or grouping folder) that way, which is simpler i believe..

I considered deleting the logs but i cannot delete a folder with files in it, or at least don't have the commands to do so.

**Comment by EndOfLine369** [comment]
That is Very problematic on relying on the scanner to reset the HAMA logs. 

As the scanner (if not in grouping folder mode) only hits a small handful of folders on each scan. If a full metadata refresh is done just more than once, that means every single file will have 2x the amount of data and taking up a large waste of space (especially if someone has OnePiece/Bleach/Naruto/NarutoS/...). Also as you can refresh any number of times apart from scanning. 

There should probably be a log for the scanner:
* based on series folder name for log name (already done in beta)

And a separate log for the agent:
* If **only one series folder** in a Plex series: 
Log name based on series folder name & postfixed with 'hama' to make it unique from the scanner log
* If **more than one series folder** in a Plex series: 
Log name based on id string 

The agent should then truncate and repopulate the log on each refresh of a series which will guarantee the log is maintained

**Comment by sven-7** [comment]
Even if temporary, would it be possible to get the logs listed in a single place? I don't see anywhere I can see ASS logs right now consistently.  Unless I'm missing it?

**Comment by ZeroQI** [comment]
@sven-7 Have been trying to work on that but my scanner scan nothing. Replaced it with the latest scanner code from beta branch, same thing. Can you test and confirm if when creating a new library it scans for you ?

**Comment by sven-7** [comment]
It did scan when I made a new library, it even seemed to provide scanner logs for that library.  When I went and ran a full refresh of my existing library, the scanner did NOT leave logs for everything.  It left about 2-3 series logs per hard drive.

**Comment by sven-7** [comment]
Here are logs that were generated after I deleted everything and ran a refresh all metadata.

[_Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/1376880/_Logs.zip)

**Comment by ZeroQI** [comment]
i am now creating a log per serie separate for agent and scanner, that solve all
