### ISSUE TITLE
Clarification on instructions

### ISSUE THREAD

**Issue by anohren** [ZeroQI/Absolute-Series-Scanner#115]
Hello,

I just installed the scanner to the correct location and restarted the server.

The next step is unclear to me. I was under the impression that -- according to [this post](https://forums.plex.tv/discussion/19396/how-to-install-a-custom-scanner/p1) -- I would "be able to select the scanner when you create a new library". I create a Tv shows library and cannot see any way to select scanners. I ask here because the OP does not seem to answer people in that thread.

Your troubleshooting section says: "If the scanner not listed in scanner list" -- which scanner list would that be? I've looked around in advanced settings and in the dialogue for editing a library. Nothing.

The closest I could find was an "agents" section in the settings.

**Comment by ZeroQI** [comment]
You can only see the drop down if it detected the additionnal scanner
%LOCALAPPDATA%\Plex Media Server\Scanners\Series\Absolute Series Scanner.py
Check rights and if the file contain html tags and if it does you saved it incorrectly...

**Comment by anohren** [comment]
Looks good in `nano`

![scanner](https://user-images.githubusercontent.com/3519879/30889700-988fc152-a328-11e7-9ae3-3b71c1781f2b.PNG)

```
$ ls -l
-rw-r--r-- 1 root root 66644 sep 27 00:57 Absolute Series Scanner.py
```

**Comment by ZeroQI** [comment]
Is there not another plex folder in user profile?

**Comment by anohren** [comment]
You're right, there is another set of plex folders. Apparently the server doesn't run as its own user. 

(what the folders I worked in are used for, I have no idea)

Thank you for your help!

Knowing that the drop-down menu is not even visible when it can't find any scanners is very helpful, otherwise you'd suspect that Plex might simply have removed the feature in the UI. That might be a good point to make in the troubleshooting section.
