### ISSUE TITLE
.Plexignore

### ISSUE THREAD

**Issue by qtv** [ZeroQI/Absolute-Series-Scanner#117]
Is there a reason why you don't have .plexignore support? ASS does great in figuring out things but sometimes there are just crazy names for things (OVA1v0 and OVA12v0 get picked up as the same thing, for example). You can't rename because you have to seed, so I usually create a softlink/hardlink to the files, renaming them, and put the originals in a .plexignore file. Moving to ASS really screwed up my file system since I do it semi-often.

Is there any planned support for .plexignore?

**Comment by ZeroQI** [comment]
The legacy ass scanner did support it
Never talked to aomebody actually using it that i can remember...
Please give me full path for both files so the scanner handle it as it
should

**Comment by qtv** [comment]
Hm, plenty of people seem to use it over at reddit.com/r/Plex and in the plex forums. I use it in even more scenarios other than for renaming, like ignoring files from torrents I downloaded that I don't personally want but need to seed. Anyway, the full path for what the anime example I gave was 
`Monster Musume OVA 10-bit FLAC[anidb-11926]/Monster Musume no Iru Nichijou - OVA1v0 [Softsubs] [BDRip] [1080p] [10-bit] [CRF16] [FLAC] [OGG] [32A013C0].mkv` and `Monster Musume OVA 10-bit FLAC[anidb-11926]/Monster Musume no Iru Nichijou - OVA2v0 [Softsubs] [BDRip] [1080p] [10-bit] [CRF16] [FLAC] [OGG] [9CBB129B].mkv` , which currently shows up as "OVA1v0" for both episodes. It is not entirely uncommon for people to name OVA's as OVA1 and OVA2. Neither appears as an Episode like in their animdb entry.

**Comment by larpo** [comment]
I do use .plexignore files quite a lot too! Mostly for the reasons qtv already mentioned.

**Comment by ZeroQI** [comment]
.plexignore need to access multiple levels of folders to sort out, it is not convenient if not scanning all at root level. will include OVA2v0 format in scanner.

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/121
Am calling manually the scan function for sub-folders in this hybrid scanner test, feed-backing the grouping folder files back to the root folder call instance for addition, and i could provide plexignore subfolders restrictions to each sub-folder instance to bring support back easily but basically taking the already working behaviour of the legacy scanner
(OVA1v0 and OVA12v0 formats now supported)

Official plex scanner support thread is on plex forums... 
Nobody will get support from me on reddit.com/r/Plex 

I should be able to push all modifications to beta and from beta to main branch soon

**Comment by ZeroQI** [comment]
I did manage to have grouping folders working and calling manually each sub-folder instead of relying on Plex calling scan function externally so i should be able to re-use the legacy scanner code for '.plexignore' files since i can pass information back and forth without reloading the whole folder tree for each folder. will take a bit of time

**Comment by ZeroQI** [comment]
https://gist.githubusercontent.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d/raw/7ed86a86ffccb9433c43f650422dffc9e87cbd06/Absolute%2520Series%2520Scanner.py
changes:
- added .plexignore support
- added grouping folder support
- solved skipped folders not skipped
- ova1v0 type numbering support
It doesn't crash, but i did not test much grouping nor .plexignore...
I have too little time since work blocked my nas so can somebody test all and confirm what works what doesn't?

**Comment by qtv** [comment]
I was not able to get plexignore support to work with anything, using wildcard or just doing the filename.

**Comment by ZeroQI** [comment]
Just saw the edit...
Can you give the filenames and patterns? i used the same rules as the legacy scanner so all should work

**Comment by ZeroQI** [comment]
qtv, can  you give the filenames and patterns? i used the same rules as the legacy scanner so all should work
Disabled anything in scanner regarding plexignore and error still there if brackets escaped or not in the .plexignore file... Seem to be plex related and maybe third party scanner don't need to implement support... I can fix it still as i have recursive calls to the scanner so it is easy enough to implement

Without answers i will close this ticket.

**Comment by qtv** [comment]
Let me make sure I've got this right (just updated to latest version also).

Let's say I have a folder name "Saiki Kusuo no Sainan (2018)". Matches to the show fine. The files are 
[Davinci] Saiki Kusuo no Psi-nan 2 - 01 [720p][C53F5DBC].mkv  [Davinci] Saiki Kusuo no Psi-nan 2 - 02v2 [720p][32AD451E].mkv

First there's an error because they both match to episode 2 because of that 2 in "Saiki Kusuo no Psi-nan 2" , but that's not the point.

I create a .plexignore file in that directory.
It's contents are just *Psi-nan*
Nothing gets ignored. In fact, I can't get anything to ever ignore so far. Even putting the full filename doesn't make it get ignored.

**Comment by ZeroQI** [comment]
Doing a new version of beta scanner with Plexignore support.
Need to test it and can no longer test from work sadly. 
Current code: https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d
Will keep you posted when tested

**Comment by ZeroQI** [comment]
Please test https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d
grouping folder support while keeping caching if ep folders present in season folder
Plexignore seem to work
Should be better system wise

**Comment by qtv** [comment]
Hmm, I am actually having the weirdest problem with that new version

Plex now finds .plexignore as episodes. I have an episode in Specials for 501 and it's just a .plexignore file. It doesn't ignore anything in that folder, but it does work in another (the Saiki one I mentioned above it works in). The structures are identical - doesn't work in Overlord II, with files like [grp] Overlord 2 - 0x [WEB][CRC32].mkv and a plexignore file of just `*WEB`.

The file is in my /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scanners/Series folder in Ubuntu, btw, and owned by plex with all permissions.

**Comment by ZeroQI** [comment]
updated beta branch, didn't have the .plexignore and tvdb4.id showing as specials
Not sure the double star is supported with current code but "*.mkv" worked folders depth should be supported. Will test

**Comment by ZeroQI** [comment]
Should work fully now. took the whole day (am self taught python and when the scanner crash, it doesn't say where...)
Please report any scanner issue

**Comment by ZeroQI** [comment]
Please test and report, my tests worked, wil lclose this bug report without any replies

**Comment by qtv** [comment]
Sorry for not getting back to you sooner.

Everything looks like its working fine! I am ecstatic
