### ISSUE TITLE
Scanner not working with similar series names differentiated by exclamation mark

### ISSUE THREAD

**Issue by fatflyingpigs** [ZeroQI/Absolute-Series-Scanner#120]
A series ending with an exclamation mark (!) will cause one series to not show up, and all episodes to be treated as a duplicate to the other series. For example:

Show/folder name:
"New Game! [1080p]" vs "New Game!! [1080p]"
Also tested:
"New Game! (2016) [1080p]" vs "New Game!! (2017) [1080p]"
"New Game! [1080p]" vs "New Game!! Season 2 [1080p]"

Episodes named:
"New Game! - 01 [1080p].mkv" vs "New Game!! - 01 [1080p].mkv"

Obviously not a critical issue, as the series can be manually split apart.

**Comment by deusxanime** [comment]
If you name the folder something, follow through with the file names as well. For series/folder named "New Game!! Season 2 [1080p]" put episode names as "New Game!! Season 2 - 01 [1080p].mkv" as well.

The name are similar enough though that you may need to force tagging with [anidb-NNNN] tags at the end of the folder instead, if nothing else works.

**Comment by ZeroQI** [comment]
Tried with beta with the 4 different series title and it works (creating series 1 and 2) as it should without forcing the series id...
