### ISSUE TITLE
Unable to find media in folder

### ISSUE THREAD

**Issue by diksm8** [ZeroQI/Absolute-Series-Scanner#122]
Log: https://hastebin.com/iriqoxeqom.rb

**Comment by ZeroQI** [comment]
Scanner code crash...
Did you save the python file correctly?
If you see xml tags in it it is saved wrong

**Comment by diksm8** [comment]
I used
```
wget https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py
```

while inside the correct directory and I gave it and the folders 775 and changed the owner to plex.

**Comment by ZeroQI** [comment]
i put https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py in the browser and i see an HTML page showing the file not the file itself....

Please let me know where you got that link so i can ammend it.

That is the url to the actual file
https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/Scanners/Series/Absolute%20Series%20Scanner.py

**Comment by diksm8** [comment]
I found it under the install instructions for Hama

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Hama.bundle/blob/master/README.md
point to
https://github.com/ZeroQI/Hama.bundle/wiki/Installing-Hama-and-ASS-on-Ubuntu
all urls start with raw.github.com ...

did you mean that line from the hama readme:
* Update scanner file with the latest from https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py

**Comment by diksm8** [comment]
Both the update and the scanner sections of the readme has it.

**Comment by ZeroQI** [comment]
both list wget on https://raw.githubusercontent.com/...
I do mention to get the file at the url, but that is the github web page showing the page itself, despite ending in py... have removed in scanner readme link to the github page.
Please reopen if the issue persist with the new url but i doubt it
