### ISSUE TITLE
Some shows not being found

### ISSUE THREAD

**Issue by sachaw** [ZeroQI/Absolute-Series-Scanner#127]
As I have a combined Movie/Series library, series tend to be in folders while not all movies are, and somethimes then a movie is in the root directory it works find, other times it doesn't, here is an example from my log

> Scanner call - root: '/home/sachaw/torrents/rtorrent/Anime', path: '', dirs: '1', files: '7'                                                                            
>-----------------------------------------------------------------------------------------------------------------    
>No forced ID - file: /home/sachaw/torrents/rtorrent/Anime/, present: False                                                                                              
>show: '', s00e501-501, file: '/home/sachaw/torrents/rtorrent/Anime/[Anime Land] Blame! Movie (Dual >Audio) (BDRip 1080p Hi10P TrueHDx2) [F976BA25].mkv' has show empty, r
>eport logs to dev ASAP                                                                                                                                                  
>"" s0000e501 "[Anime Land] Blame! Movie (Dual Audio) (BDRip 1080p Hi10P TrueHDx2) [F976BA25].mkv"                                                                       
>"Godzilla Part" s0001e001 "[DragsterPS] Godzilla Part 1 [1080p] [Multi-Audio] [Multi-Subs] [4873FB81].mkv"                                                              
"Godzilla - Part" s0001e001 "[Sorin] Godzilla - Part 1 (1920x1080).mp4"

**Comment by ZeroQI** [comment]
You made no efforts to follow the movie file naming instructions in the read-me, which states:
```
Movie files in Series libraries (since this is a Series Scanner) are supported if:
Files are in a folder with the same name or with a single file inside it
Files are numbered (01|ep 01|s01e01)
Filename contain " - Complete Movie"
```
Are the instructions unclear or you didn't read the read-me?
Please realize it is a movie scanner that i hacked to accept movies...

Part 1 is seen as episode one and a serie was created as a result but with " - part" in the title...
Please confirm if renaming works:
- "[DragsterPS] Godzilla - Complete Movie [1080p] [Multi-Audio] [Multi-Subs] [4873FB81].mkv"
- "[Anime Land] Blame! Movie  - Complete Movie [Dual Audio BDRip 1080p Hi10P TrueHDx2]
 [F976BA25].mkv"
Note: parenthesis with studd inside not being years is super bad for parsing and may not be removed

**Comment by sachaw** [comment]
Yes, I fully understand what you are saying but as I wish to leave these files as is so I can continue to seed them I cannot rename them, also I wash to combine anime movies and series in one library, is this at all possible even if I can do it manually somehow (possibly symlinks?)

**Comment by ZeroQI** [comment]
Thanks for responding, i understand better why now.
Notes:
- You could create a movie only library pointing to the same folder to have access to these movies
- you could have had a seeding folder separate from the root folder used by the library. That is what i do as I do not want potentially incomplete/corrupted/unsorted stuff with the stuff i know is complete and sorted and therefore double store some stuff as a result... 
- Plex do not support movie and series in the same library normally, however as you probably know my scanner hack that, and is possibly the only tool to have movies and series in a single place all software considered and could be amended possibly so root file create separate series if flagged as having no ep numbers.  i think i can add support for that but might take some time. I will keep you posted

**Comment by sachaw** [comment]
Thanks for the input, I decided to rearrange how I structure media removing the need for the combined library, I'll close the issue now
