### ISSUE TITLE
Log file should be added automatically

### ISSUE THREAD

**Issue by rmartyna** [ZeroQI/Absolute-Series-Scanner#128]
NAS: QNAP TS-251
OS: QTS 4.3.4
Plex Server Version: 1.10.0.4523

After installing Scanner according to instruction from readme and setting 777 permissions on whole folder I got the following error:
```
Jan 26, 2018 02:14:29.382 [0x7f309679f800] ERROR - No module in Absolute Series Scanner
Jan 26, 2018 02:14:29.384 [0x7f309679f800] ERROR - Error in Python: Looking up module:
Traceback (most recent call last):
  File "/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-648bc61d4/Scanners.bundle/Contents/Resources/Movies/Absolute Series Scanner.py", line 124, in <module>
    set_logging("Root", LOG_FILE_LIBRARY)
  File "/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-648bc61d4/Scanners.bundle/Contents/Resources/Movies/Absolute Series Scanner.py", line 107, in set_logging
    handler = logging.handlers.RotatingFileHandler(os.path.join(LOG_PATH, filename), maxBytes=10*1024*1024, backupCount=backup_count)    #handler = logging.FileHandler(os.path.join(LOG_PATH, filename), mode)
  File "/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/logging/handlers.py", line 117, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/logging/handlers.py", line 64, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: (2, 'No such file or directory', '/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-648bc61d4/Scanners.bundle/Contents/Logs/Plex Media Scanner (custom ASS).log')
Jan 26, 2018 02:14:29.385 [0x7f309679f800] ERROR - We got an error scanning in /share/Multimedia/Anime
```

By default only `/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-648bc61d4/Scanners.bundle/Contents` path exists.

After manually adding `Logs` directory and `Plex Media Scanner (custom ASS).log` file, scanner ran fine without any error.

Applications should run by default without any tweaking, so I think that log file (including parent directories) should be added automatically.

**Comment by ZeroQI** [comment]
Hi, thanks for the best documented post i have seen in a while.
Here is the install process from the readme:
```
Install / Update
Download https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/Scanners/Series/Absolute%20Series%20Scanner.py
Save into [...]/Plex/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py Note:
"Scanners" and "Series" folder are not created by default and will need creating.
"Scanners" folder will be at the same level as "Plug-in Support" folder (in other words the same parent directory)
"Absolute Series Scanner.py" resides in Series folder, do not create an additional folder not listed like "absolute-series-scanner-master" and add the correct permissions on the init.py file. This should be done with chmod +x under linux
Once the scanner is installed correctly, when creating a library you can select the custom scanner, otherwise the drop-down selection list is not shown
```

Something seem off with the path, it look like you put the scanner together with plex default ones and in a Movies folder when it is a series scanner:
`/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-648bc61d4/Scanners.bundle/Contents/Resources/Movies/Absolute Series Scanner.py
`
Can you try with:
`/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Scanners/Series/Absolute Series Scanner.py
`

**Comment by ZeroQI** [comment]
Something seem off with the path, it look like you put the scanner together with plex default ones and in a Movies folder when it is a series scanner:
/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-648bc61d4/Scanners.bundle/Contents/Resources/Movies/Absolute Series Scanner.py
Can you try with:
/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Scanners/Series/Absolute Series Scanner.py

Will close if no answer...

**Comment by ZeroQI** [comment]
Hello?

**Comment by rmartyna** [comment]
Hi, I am really sorry for late response.

I completely forgot about your first message, and only remembered this bug
from your yesterday message. I will look at it today, after work.

Again, really sorry.

2018-02-15 9:52 GMT+01:00 ZeroQI <notifications@github.com>:

**Comment by rmartyna** [comment]
> Can you try with:
> /share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Scanners/Series/Absolute Series Scanner.py

Hmm, I assume you meant the path that is similar to the one in README here: https://github.com/ZeroQI/Hama.bundle, that is `/share/CE_CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Scanners/Series/Absolute Series Scanner.py`, but yes, after putting it in that directory, scanner ran without any problem.

Technically not a bug and can be closed, but in the line 122 of python script i can see:
`  except: pass #os.makedirs(LOG_PATH)  # User folder on MacOS-X`, so i guess that someone ran into similar problem in the past.

Good to know that this issue is already resolved in beta branch.
