### ISSUE TITLE
Dagashi Kashi 2 not being detected properly

### ISSUE THREAD

**Issue by sachaw** [ZeroQI/Absolute-Series-Scanner#129]
straight from my seedbox the first 3 episodes file names are as follows
[Erai-raws] Dagashi Kashi 2 - 01 [1080p].mkv
[Erai-raws] Dagashi Kashi 2 - 02 [1080p][Multiple Subtitle].mkv
[HorribleSubs] Dagashi Kashi S2 - 03 [1080p].mkv

Firstly it was automatically identified as season one, but as soon as I specified season 2, episodes 1 and 2 were both identified as `Dagashi Kashi 2 season 1 episode 2` then episode 3 was identified as `Dagashi Kashi 2 specials episode 2`

I understand that it mapped the 2 (as in season 2) as episode 2 and s2 as specials 2, is there any way to fix this or is it a bug?

**Comment by ZeroQI** [comment]
You should avoid scanning your seed box as you cannot conform to Plex nor my scanner naming conventions that way. At the very least, I would have placed straight away in a folder "Dagashi Kashi 2" while adding the file to the torrent client, as the scanner subtract the series name from the series folder to cleanse the file name, and you wouldn't have had any issues...
As per the read-me S2 is for specials ep 2.

If i could just make it work without impacting clients that follow naming conventions i would.
I could improve scanning at root level maybe, but i need you to use the beta branch scanner and attach scanner logs

**Comment by sachaw** [comment]
Ok, thanks for trying, looks like i will have to sort out some regex for moving once completed.
