### ISSUE TITLE
Does not support seasons with only numbers as folder name

### ISSUE THREAD

**Issue by Nyaran** [ZeroQI/Absolute-Series-Scanner#130]
I have the following structure:

- Show name
  - 01
    - Show name - 001 - Ep Name.ext
    - Show name - 002 - Ep Name.ext
    - Show name - 003 - Ep Name.ext
  - 02
    - Show name - 004 - Ep Name.ext
    - Show name - 005 - Ep Name.ext
    - Show name - 006 - Ep Name.ext

And is not detected by the scanner, I'm forced to use
- Show name
  - Season 01
    - Show name - 001 - Ep Name.ext
    - Show name - 002 - Ep Name.ext
    - Show name - 003 - Ep Name.ext
  - Season 02
    - Show name - 004 - Ep Name.ext
    - Show name - 005 - Ep Name.ext
    - Show name - 006 - Ep Name.ext

Is possible to add the option to use only numbers for season folder (without "Season" keyword?

Regards

**Comment by dgw** [comment]
Plex itself prefers to have "Season" in season folder names, fwiw. https://support.plex.tv/articles/200220687-naming-series-season-based-tv-shows/

**Comment by Nyaran** [comment]
Yes, but it can detect without problems folders without "Season" keyword, I'm using in that way for years.

**Comment by dgw** [comment]
With the default Plex scanners, "working" doesn't mean "supported". They try to make their scanners forgiving, but if you have any issues they tend to point at the naming guidelines rather than changing how the scanners work. (I know this from personal experience, lol.)

**Comment by Nyaran** [comment]
I made the change, I will be testing a few days and if don't present troubles I will make the PR.

**Comment by ZeroQI** [comment]
It is a weird convention, but i am concerned some may have episodes in absolute numbering inside the folder with the same name but just numbers should be ok.
Please make the PR and i will commit it

**Comment by ZeroQI** [comment]
I find that an atrocious naming convention to be honest, but should not impact users with filenames placed in identically named folders so added support
