### ISSUE TITLE
When using beta version show root location / path attribute remains empty

### ISSUE THREAD

**Issue by RickDB** [ZeroQI/Absolute-Series-Scanner#131]
**Issue**

It seems when a show has season folders like so:

\\server\Anime\Darling in the Franxx\Season 1

The Plex attribute Location / Path for the show itself doesn't get set, not sure what it's called in ASS but PlexKodiConnect references it like this:

https://github.com/croneter/PlexKodiConnect/blob/master/resources/lib/PlexAPI.py#L1245-L1248

tested without season folders and then I get \\server\Anime for that attribute, not sure if ASS or HAMA bug but probably scanner as it handles the matching.

Stumbled onto this bug while using Kodi + PlexKodiConnect, it reads the show folder / path when using direct paths there, it will fallback to non-native for the show if it can't find the location attribute.
Files themselves are fine so it's just the show root path that is empty, at first thought PlexKodiConnect was at fault so debugged it but only affects shares using ASS + HAMA so pretty sure it's scanner related.

**Steps to reproduce**

Kinda need PlexKodiConnect for this or able to read Plex API XML results for shows but here are the steps I used:

- Add new show and use season folders for episodes
- Let it import to Plex Media Server
- Start Kodi and setup PlexKodiConnect with direct paths
- Check Info for show and will show up as plugin path instead of direct path:

<img width="1920" alt="36177647-b1415718-1116-11e8-88ea-78fd271c5373" src="https://user-images.githubusercontent.com/347084/36209886-4c68be44-119d-11e8-80a1-6968824e3db9.PNG">

**System information**

Latest beta ASS and Hama (from beta branches)
PlexKodiConnect 2.0.2 (latest beta)
PMS 1.11.3.4793
Windows 10 x64

**Comment by ZeroQI** [comment]
hama do not set path
files are added by the scanner so a scanner issue maybe, however if in plex you click on the video and it works, then the scanner added it correctly...
Nevertheless, i use a bit unusual way of scanning to add functionality that could possibly trigger it, so you might want to try the legacy scanner...

The path show is the plexkodiconnect one so i would guess it is a bug of theirs possibly?

**Comment by RickDB** [comment]
ASS works fine when I don't use season folders though so seems like it isn't setting path when it has a sub directory (season #) for some reason, added temporary share and tested with regular scanner as well which shows up with root path set.
You're right that the files show up correctly and playback works, it's just the root path for the show itself is empty.

Will roll back PlexKodiConnect just to be sure but odd thing is that it only affects shares using ASS and only those with season folders.
HAMA beta has a lot of bugfixes / improvements and it's not a showstopper, will do more testing today.

**Comment by ZeroQI** [comment]
There is no root to be set by the scanner.
```
tv_show = Media.Episode(show, season, epn, title, year)
tv_show.parts.append(file)
```
i do manual recursive calls for sub-folders so that a tool use undocumented database entries and subfolders are missing doesn't surprise me, but if that is the case, i cannot do much...
If the is the case, files in a "transparent" folder like "Ark 'test'" should behave the same. if so, you can use the non beta scanner but the tvdb force id functionality might be missing to some extend

**Comment by RickDB** [comment]
Yeah most of the Plex API is undocumented sadly, tried legacy scanner but getting same results.

Checked in Plex Web just to completely rule out any 3rd party tool issue (PlexKodiConnect), using Firefox developer tools can see the XML output when viewing a show.
For instance Devilman Crybaby with no season folders it shows an location node:

https://gist.github.com/RickDB/a6b4b391c0c8b1223d4f5250e67d254a

While with Seven Deadly Sins and season 1 folder it's missing the location node:

https://gist.github.com/RickDB/d4aac9eef049b6071ae8d420267b77d2

Could be some Plex Media Server bug but with generic tv scanner it picks these up and shows the location node.

**Comment by RickDB** [comment]
Just checked Plex Anime Scanner combined with HAMA and shows the location node in XML for shows with seasons, that scanner is a bit too basic for my taste but it must be handling it differently for it to work.

**Comment by ZeroQI** [comment]
What is "Plex Anime Scanner"? Default Plex scanner? BABS?
Beta branch use now manual recursive calls, possibly at fault there
does the normal branch works ?
- https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py
Does legacy scanner work ?
- https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner%20(legacy).py

**Comment by RickDB** [comment]
Plex Anime Scanner is a very basic anime scanner, only used it for testing yesterday to see if Plex Media Server was at fault when using 3rd party scanners nothing more:

https://forums.plex.tv/discussion/299631/release-plex-anime-scanner

With the Default Plex TV Scanner the location attribute also shows up so can only replicate it with ASS consistently
Legacy scanner has the same issue however Plex Media Server does have some persistent caching, clear bundles + trash on every try but not sure if data is cached elsewhere.

**Comment by ZeroQI** [comment]
@RickDB:
Shame on me, i even put a comment in their thread... Forgot about it...
Ok that summarizes it.
- If the files are added by the genuine Plex call to the scanner, no problem.
- if the files are added on the root folder call (legacy scanner) or manual (recursive) scanner call then you are impacted
I need the custom scanner logs for anime with seasons impacted, in your agent data folders for ASS Beta Branch

**Comment by RickDB** [comment]
Correct, PM'ed logs via Plex forums.
This is a clean import run, added Seven Deadly Sins folder and let it run import on the Anime share.

Odd thing is though sometimes new shows don't have poster / fanart images unless I manually run refresh metadata for that show afterwards, not sure why but hopefully logs will show more.
Thanks for looking into this and let me know if you need more info.

**Comment by RickDB** [comment]
For testing setup a new Plex Media Server instance on my workstation, used the same setup (Absolute-Series-Scanner + HAMA) and it imports fine with location attribute set for both season or non-season folder shows.

Think something got messed up in the Anime library at some point but why it would only affect certain shows I'm not sure, it was a library using HAMA from the start so no conversion afterwards.

**Comment by ZeroQI** [comment]
Yeah seem corrupted.
Do the Plex dance...

**Comment by RickDB** [comment]
Trying to see if a path change will fix otherwise will re-add it, other libraries are fine so Plex was oddly selective this time :P

**Comment by RickDB** [comment]
Think I've found the cause, when using the scanner from the beta branch the location attribute for all shows stays empty.
Just tried that with a new library and even after replacing the scanner with the master branch version afterwards it requires creating a new share as otherwise the problems persist, something lingering in Plex DB I guess.

**Comment by ZeroQI** [comment]
It is possible the type of call i do to make the scanner work create an issue, but all fields provided to Plex are the right ones, and i do not have a field to specify a root of file folder. if the media play, then the path provided while adding was fine.

It is possible if the files were formwerly in hte database that that field is kept so it could be an issue with the beta scanner. knowing which cause issues or not will allow me to know what introduce the issue depending on the clling method in the scanner, but i cannot fix without changing the method however

Main branch scanner might work better than beta branch one.

**Comment by RickDB** [comment]
Yeah will use the main branch scanner which works perfectly with all folder types :) , what I'll do this weekend though is create a fresh Plex Media Server for testing and see how it does with beta scanner.
If it doesn't add a location attribute there as well can at least rule out caching altogether.

**Comment by ZeroQI** [comment]
The issues i have scanning are plexignore support, supporting grouping folders without specific tags, use of plex natural scanning of changes in folders only which led to current beta scanner which seem to break things for you so will need to keep 2 versions at best to account for all situations...

Please keep me posted as it will change the versions are keep on github

**Comment by RickDB** [comment]
Tested the following:

- Installed completely Plex Media Server on different machine
- Installed HAMA and Absolute Series Scanner from their beta branches
- Kept HAMA and PMS settings default
- Let it import the same Anime share as before, scanner set to absolute scanner and agent to HAMA TV
- Result is location attribute missing from all shows it imported, example:

https://gist.github.com/RickDB/5845bad59bf5319824cd0e3ffe16a330

Can send you the logs of the initial import if you want them :)

**Comment by ZeroQI** [comment]
Master branch has: <Location path="\\rick-server\Anime\citrus" />
seem like calling the folder manually without using the natural plex folder call is good enough for plex but results in this difference
If ASS legacy does the same (gather all in initial root folder call) then we need to use the natural folder call for this field populated

**Comment by RickDB** [comment]
Will use a clean PMS install and retry with legacy version.

**Comment by RickDB** [comment]
Scanner legacy version has the same issue with location attribute, Plex Web example:

https://gist.github.com/RickDB/a9cb9b76df6f9dadd6bf70302423a06d

**Comment by ZeroQI** [comment]
Well that precise it,
PlexKodiConnect requires a field in that xml file, only put when scanner function is called directly by plex, but not when the root folder is called, just original calls to the series folder. If the scanner call manually the sub-folders apparently despite filling all fields for the update() function call.
need to re-code the beta scanner to retain grouping folders support, logging to agent data folders...
will need to mix both versions, will take time

**Comment by RickDB** [comment]
It's an edge case as well because the native Plex apps are not affected, take your time as I'm perfectly happy with the master branch version in the meantime :)

**Comment by ZeroQI** [comment]
Please test https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d
grouping folder support while keeping caching if ep folders present in season folder
Plexignore seem to work
Should be better system wise

**Comment by RickDB** [comment]
Getting a module error during scanning which results in nothing being added to library, small snippet of plex media scanner log:

````
Feb 28, 2018 10:46:35.813 [9700] DEBUG -     * Scanning directory \\rick-server\Anime\009-1 (parent: yes)
Feb 28, 2018 10:46:35.825 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 01 - Infiltrators - [E-D](55b3f354).mkv"
Feb 28, 2018 10:46:35.825 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 02 - Holy Night - [E-D](3f70f86f).mkv"
Feb 28, 2018 10:46:35.826 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 03 - Hard Boiled - [E-D](fb9e7124).mkv"
Feb 28, 2018 10:46:35.826 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 04 - Invitation from an Old Castle - [E-D](d56d2ef0).mkv"
Feb 28, 2018 10:46:35.826 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 05 - Woman of Gold - [E-D](ccdceca0).mkv"
Feb 28, 2018 10:46:35.826 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 06 - Pop - [E-D](0d8c2ef5).mkv"
Feb 28, 2018 10:46:35.826 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 07 - Port - [E-D](dd482664).mkv"
Feb 28, 2018 10:46:35.827 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 08 - Calendar of the Past - [E-D](9780a29a).mkv"
Feb 28, 2018 10:46:35.827 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 09 - Revenge - [E-D](d80e871f).mkv"
Feb 28, 2018 10:46:35.827 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 10 - Reverse Explosion - [E-D](974bd1b8).mkv"

Feb 28, 2018 10:46:35.827 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 11 - Exodus - [E-D](b0f6f681).mkv"

Feb 28, 2018 10:46:35.828 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - 12 - Daybreak - [E-D](f7400822).mkv"

Feb 28, 2018 10:46:35.828 [9700] DEBUG - Adding file for scanner: "\\rick-server\Anime\009-1\009-1 - S1 - Extra Mission R && B - [E-D](4a940426).mkv"

Feb 28, 2018 10:46:35.836 [9700] DEBUG - Directory had 13 files, database had 0 files, can't skip.

Feb 28, 2018 10:46:35.836 [9700] ERROR - No module in Absolute Series Scanner.py

Feb 28, 2018 10:46:35.837 [9700] ERROR - We got an error scanning in \\rick-server\Anime
````

**Comment by ZeroQI** [comment]
please check there is no html tags in your scanner file, works for me

**Comment by RickDB** [comment]
Was indeed some html junk in it, re-downloaded with firefox directly over the old scanner file and scanning is working.
Will let you know the results later.

**Comment by RickDB** [comment]
So far so good 👍 , still running but shows are getting the correct location attribute:

https://gist.github.com/RickDB/b2312ff25af965043a2a84cba68c647f

**Comment by ZeroQI** [comment]
Excellent. I like when a plan come together.

**Comment by RickDB** [comment]
Thanks for the redesign :)

![orginal_john_hannibal_smith 1](https://user-images.githubusercontent.com/347084/36790056-dbc4cece-1c93-11e8-8892-9cb3c23a1367.jpg)
