### ISSUE TITLE
Beta Scanner - Issues (TVDB3 Failure)

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#134]
**TVDB3 Failure** - For Yu Yu Hakusho, TVDB3 is failing to initiate and is placing the entire show into one season.  A scan and file list log formed, but the scan log is empty.  Entire log folder plus Plex log attached in #133). I've Plex Danced this show several times and no success.

**Comment by ZeroQI** [comment]
Cannot see in logs, if master branch scanner works will do a new scanner using more proper function calls

**Comment by sven-7** [comment]
Thanks.  Let me know when you need me to test it.

**Comment by sven-7** [comment]
Because I switched to the main scanner, I figured what happened here.  Someone added an extra ep on TVDB somewhere, so that caused the scanner to make everything S1.  With the Beta, I couldn't find logs to identify it, but found them via the master. 

If I recall, this is a normal function of the scanner to place it all in S1 if the Absolute numbers get messed up. Essentially someone made an ep without an absolute number, which seems to throw it off.

```
Scanner call - root: 'H:\Series', path: 'Yu Yu Hakusho', dirs: '0', files: '113'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Forced ID file in serie folder
folder_show: 'Yu Yu Hakusho [tvdb3-76665]', folder_season: 'None', tvdb mode: '3', tvdb id: '76665'
TVDB season mode (3) enabled, serie url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/76665/all/en.xml'
different abs number found on ep (s3e1) after starting to manually place our own abs numbers. all episodes will be added as season 1.
```

My guess is this can be closed.

**Comment by ZeroQI** [comment]
Will close
same code on beta scanner, but the ssl issue problably made it crash beforehand
