### ISSUE TITLE
Location of X-Plex-Token

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#135]
> "X-Plex-Token.id: Allow to get the library name to get a log per library (optional). Fill with plex token by following https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token. Do not share that file when uploading the whole Logs folders

According to the readme, a X-Plex-Token is used...but where do you want it located?

In `\Plex Media Server\Logs`?

I have a single library, 'Anime Series', that pulls from four different hard drive locations.  Does each source Folder (i.e. E/Anime/; F/Anime/) all need one in their locations?

Additionally, I see in a lot of my scanner-beta individual logs:  Library: 'no valid X-Plex-Token.id', root: 'H:\Series', Plex non-root uncalled scan - path: 'Yu Yu Hakusho', dirs: '0', files: '112', date: 2018-02-19 09:06:56

**Comment by ZeroQI** [comment]
In logs folder, yes: \Plex Media Server\Logs\X-Plex-Token.id
Will have to redo the beta scanner, used recursive calls, work well enough provided all fields i am meant to but some xml get no root folders and have to change the way i call it so will go back from the master branch to add the grouping folder support.

**Comment by ZeroQI** [comment]
X-Plex-Token.id in Plex root in beta scanner. That avoid zipping logs and mistakenly including it...

**Comment by sven-7** [comment]
So just here: ` \Plex Media Server\`

?

**Comment by ZeroQI** [comment]
Yes. Instead of plex logs folder, its parent folder.

**Comment by sven-7** [comment]
Great. Thanks!
