### ISSUE TITLE
TVDB Mapping Issue

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#14]
I'm getting an error that says "Error in TVDB Mapping Issue".  Is this the scanner or HAMA....or perhaps something else?

It's for My Hero Academia.  There are descriptions for both episodes in TVDB.

![image](https://cloud.githubusercontent.com/assets/18091557/14538150/32b58c70-0272-11e6-9967-9c69c389b791.png)

**Comment by EndOfLine369** [comment]
Hi seven-7,
I checked my own 'My Hero Academia' info and it is missing the summaries but I do see them in TVDB. I suspect that this is a non-issue. Do you know if the summaries were just added in the last 24hrs? That is the cache time in Plex for the TVDB api url. If the abs number was just added as well in TVDB (is there) that could possibly explain the summary text you got on ep one.

**Comment by EndOfLine369** [comment]
Oh, this is Hama btw. not ASS.

**Comment by EndOfLine369** [comment]
Actually, I think I found the issue. There is a bug in Hama.

@ZeroQI 
Please look at updating the Hama "\_\_init\_\_.py" with the below addition of `and mappingList [ 'episodeoffset' ].isdigit()`:
```python
            ### TVDB mapping episode summary ###
            try:
              if tvdbid.isdigit():
                anidb_ep, tvdb_ep, summary= 's' + season + 'e' + epNumVal, "", "No summary in TheTVDB.com" #epNum
                if anidb_ep in mappingList and mappingList[anidb_ep] in tvdb_table:  tvdb_ep = mappingList [ anidb_ep ]
                elif 's'+season in mappingList and int(epNumVal) >= int (mappingList['s'+season][0]) and int(epNumVal) <= int(mappingList['s'+season][1]): tvdb_ep = str( int(mappingList['s'+season][2]) + int(epNumVal) )  # season offset + ep number
                elif defaulttvdbseason=="a" and epNumVal in tvdb_table:              tvdb_ep = str( int(epNumVal) + ( int(mappingList [ 'episodeoffset' ]) if 'episodeoffset' in mappingList and mappingList [ 'episodeoffset' ].isdigit() else 0 ) )
                elif season=="0":                                                    tvdb_ep = "s"+season+"e"+epNumVal
                else:                                                                tvdb_ep = "s"+defaulttvdbseason+"e"+ str(int(epNumVal) + ( int(mappingList [ 'episodeoffset' ]) if 'episodeoffset' in mappingList and mappingList [ 'episodeoffset' ].isdigit() else 0 ))
                summary = "TVDB summary missing" if tvdb_ep=="" or tvdb_ep not in tvdb_table else tvdb_table [tvdb_ep] ['Overview'].replace("`", "'")
                mapped_eps.append( anidb_ep + ">" + tvdb_ep )
                if tvdb_ep in tvdb_table and 'filename' in tvdb_table[tvdb_ep] and tvdb_table[tvdb_ep]['filename']!="":  self.metadata_download (episodeObj.thumbs, TVDB_IMAGES_URL + tvdb_table[tvdb_ep]['filename'], 1, "TVDB/episodes/"+ os.path.basename(tvdb_table[tvdb_ep]['filename']))            
                Log.Debug("TVDB mapping episode summary - anidb_ep: '%s', tvdb_ep: '%s', season: '%s', epNumVal: '%s', defaulttvdbseason: '%s', title: '%s', summary: '%s'" %(anidb_ep, tvdb_ep, season, epNumVal, defaulttvdbseason, ep_title, tvdb_table [tvdb_ep] ['Overview'][0:50].strip() if tvdb_ep in tvdb_table else "") )
                episodeObj.summary = summary.replace("`", "'")            
            except Exception as e:
              Log.Error("Issue in 'TVDB mapping episode summary', epNumVal: '%s'", epNumVal)
              Log.Error("mappingList = %s" % mappingList)
              Log.Error(e)
```

The issue is that `mappingList['episodeoffset']` is '' so it can't be cast into an int in the 'TVDB mapping episode summary'->'elif defaulttvdbseason=="a" and epNumVal in tvdb_table'
It was missing the `and mappingList [ 'episodeoffset' ].isdigit()` that was already in the `else` part.

**Comment by EndOfLine369** [comment]
@sven-7,
I have uploaded the change here to test https://gist.github.com/EndOfLine369/b2708dd4a5d8c6cb9f30b8889e047d75
This is a direct change from the master so does not include the other issue thread of missing tvdb abs numbing. But I have updated my main gist linked in that ticket with this fix as well.

**Comment by ZeroQI** [comment]
Included all fixes to date untested to the master code

**Comment by EndOfLine369** [comment]
Thanks ZeroQI. I had tested fine :wink: so there was testing on this but always good to have more than me test. I see the changes in the master commit fine.

**Comment by EndOfLine369** [comment]
@sven-7: if you can re-pull from the master and confirm all good now, we can close out this issue ticket.
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py

**Comment by sven-7** [comment]
Sorry for the delay. I've been out of the country and will be until Monday. Will try to access my server remotely today, but if that doesn't go through it'll be a few days.

 Reading through all the posts from various issues, it sounds like it's handled. But I'll test as soon as I can when I get back to Plex.

**Comment by sven-7** [comment]
Working correctly with new updates. Can close this.
