### ISSUE TITLE
add a deep folder

### ISSUE THREAD

**Issue by Akior** [ZeroQI/Absolute-Series-Scanner#140]
It's a possible to add an additional scan for folder in folder?
example:
NAME/SEANSONXXX/EXTRA_FOLDER
files  in Extra_folder will be add like seasonXXX files

**Comment by ZeroQI** [comment]
It already works if the extra folder match the last entry of season folders like 'Ark xxx'. Never tried but multiple 'Season 1 xxx' and 'Season 1 yyy' should also work. Beta branch should support. Am redoing a big overall of beta branch scanner that will support this under the grouping folder functionality even though this is not how you will use it.

**Comment by ZeroQI** [comment]
Still working on mew beta scanner release
Re-read your issue and:
- "Specials" folder is seen a season 0 by Plex. I number the unrecognised files s00e501+ already. You want to put them in Specials folder....
- "Extras" folder is seen and skipped by Plex

**Comment by Akior** [comment]
For be correct:
I have an Anime sort by:
root:
X:\Anime\Nanatsu no Taizai
folders:
Season 0\S00E01 .. S00E06 .mkv
Season 1\S01E01 .. S01E06 .mkv
Seanoт 2\[AniDub]_Nanatsu_no_Taizai_-_Imashime_no_Fukkatsu_[720p]_[JAM]\e01 .. e06 .mkv
So It's possible to parse [AniDub]_Nanatsu_no_Taizai_-_Imashime_no_Fukkatsu_[720p]_[JAM] (Thanks for releasers) folder like Season 2 ?
Current version skip folder...

**Comment by ZeroQI** [comment]
The season folder would be ignored right now...
"Seanoт 2[AniDub]Nanatsu_no_Taizai-Imashime_no_Fukkatsu[720p][JAM]" is bad but i can add "Seanoт" to seasons keyword and make it so you don't need a space after the season number

**Comment by Akior** [comment]
Sorry, that was mistake:
Season 2\[AniDub]Nanatsu_no_Taizai-Imashime_no_Fukkatsu[720p][JAM]\e01 .. e06 .mkv

**Comment by ZeroQI** [comment]
Makes more sense now.
I can make that work without using grouping folders, will need some time

**Comment by ZeroQI** [comment]
Please test https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d
grouping folder support while keeping caching if ep folders present in season folder
Plexignore seem to work
Should be better system wise

**Comment by ZeroQI** [comment]
Excellent!
