### ISSUE TITLE
Incorrect meta-information being loaded

### ISSUE THREAD

**Issue by HardReposter** [ZeroQI/Absolute-Series-Scanner#141]
Problem: Meta-information
I have downloaded an Anime called "Maison Ikkoku." ASS already got the wrong information saying it was the Maison Ikkoku movie ("Maison Ikkoku: Kanketsu-hen"). I changed the directory name, adding the AniDB-ID at the end of the folder name ("[anidb-288]") but that didn't do a thing. I thought that if I added that AniDB-ID at the end of a folder name, it would forcibly search for that anime's meta information but it doesn't. Is ASS malfunctioning or am I just dumb?

And the given AniDB-ID does exist: http://anidb.net/perl-bin/animedb.pl?show=anime&aid=288

**Comment by ZeroQI** [comment]
That's an oldie, passed on french TV ages ago....

The read-me indicates the Metadata is managed by the agent, not by the scanner.
The actual id is selected by the agent search function and i need the agent logs. I would recommend you use the beta branch and attach the result of the agent search function, it will put it in agent data folders...

**Comment by HardReposter** [comment]
Replacing the old version with the newer beta version actually solved my problem. Thank you.
