### ISSUE TITLE
[BETA] tvdb4 posters.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Absolute-Series-Scanner#152]
I'm not sure if this belongs here or on the Hama repo.

Using One Piece [tvdb4-81797], I expected something like this regarding the season posters:

![image](https://user-images.githubusercontent.com/14930057/39722772-9b537cf4-523b-11e8-9d72-5e3201a7ac6c.png)

What I actually got (ignore missing seasons):

![image](https://user-images.githubusercontent.com/14930057/39722800-abf1ce58-523b-11e8-9f2e-d913a13857ba.png)

Episodes names/pictures seems to be correct, even the season splits are okay, just missing the covers from tvdb4.posters.xml

Using latest BETA on both ASS and HAMA.

**Comment by ZeroQI** [comment]
that's an agent issue.
Tried with "One Piece [tvdb4-81797]" and it works for me
Did you let the agent decide the season folders automatically or forced them ?

**Comment by KurtzPT** [comment]
Just tried out again, still nothing. I found this on the logs:

`2018-05-08 10:52:24,807 (6d8d72f15700) :  INFO (common:379) - common.GetMetadata() - tvdb4 mode
2018-05-08 10:52:24,815 (6d8d72f15700) :  INFO (common:388) - common.GetMetadata() - No 'tvdb4.posters.xml' file detected locally
2018-05-08 10:52:24,817 (6d8d72f15700) :  DEBUG (common:248) - common.LoadFile() - CacheTime: 'Sun Feb  4 17:30:09 2018', Limit: 'Mon May 14 10:52:24 2018', url: 'http://rawgit.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml', Filename: 'tvdb4.posters.xml' needs reloading..
2018-05-08 10:52:24,819 (6d8d72f15700) :  DEBUG (networking:166) - Requesting 'http://rawgit.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
2018-05-08 10:52:24,877 (6d8d72f15700) :  WARNING (common:248) - common.LoadFile() - issue loading url: 'http://rawgit.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml', filename: 'tvdb4.posters.xml', Exception: '<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure `(_ssl.c:590)>`

It seems it's having troubles of getting the tvdb4.posters.xml remotely.

**Comment by KurtzPT** [comment]
Yes, while I was searching for this error it seems it's unrelated to plex. I'm using Ubuntu and not OS X, so if I find a solution I'll update this so you can add it to the readme log.

**Comment by KurtzPT** [comment]
I just found out that this can be avoided by using requests library in your plugin (I think you are using the plex loadfile or something which doesn't use requests)

More info in: https://forums.plex.tv/discussion/298500/https-broken

**Comment by ZeroQI** [comment]
Excellent, thanks for that, will include on all calls internally.
will include other posters like tvdb at lower priority so that poster will works all the time even if no tvdb4 psoters or file unavailable

**Comment by ZeroQI** [comment]
SSLV3_ALERT_HANDSHAKE_FAILURE
1. Do not verify certificates. A bit like how older Python versions worked:
Import ssl and urllib2
Use urllib2 with a default ssl context (which does not verify the certificate).
Or:
2. Use external Python libraries
Add those libraries to your project bundle and use them.
Set PlexPluginCodePolicy to Elevated in Info.plist
Import certifi and requests into your Python code
Use requests in your code

Went with number 1 for now, using generic function to change in 1 place latter id needed
solved animetitles downloaded each restart, was removing .tgz after local path calculation
still doimg new version

**Comment by ZeroQI** [comment]
My poster priority in agent settings: tvdb4, TheTVDB, TheMovieDb, FanartTV, AniDB

**Comment by KurtzPT** [comment]
Mine is tvdb4, AniDB, TheTVDB, TheMovieDb, FanartTV (I prefer AniDB posters somehow :smile:)

**Comment by ZeroQI** [comment]
I actually have put the lowest priority for AniDB since the size and quality was inconsistent. now that we can select the order i could change that back

**Comment by KurtzPT** [comment]
Gonna close this one since it's been resolved the downloading of the file now.
