### ISSUE TITLE
Scanner stalled upon bad XML

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#156]
Hello -

I don't think this is an issue, but wanted to pass it along to you.

I added a single episode of Detective Conan and the scanner stalled out upon adding it.  It's getting a bad XML back from TVDB (screenshot and xml copy below).  I cancelled the scan and then opted to scan the whole library.  This time it scanned and gave an error in the scanner about the bad XML, but the first time the scanner just kept going.  Here are the logs:

First scan:
```
Library: 'Anime Series', root: 'E:\Series', path: 'Detective Conan', files: '884', dirs: '0', Plex scan date: 2018-05-26 12:18:25
=============================================================================================================================================================
Forced Series folder ID file: 'tvdb3.id' with id '72454'
TVDB season mode (tvdb3) enabled, serie url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/72454/all/en.xml'
```

Second Scan:
```
Library: 'Anime Series', root: 'E:\Series', path: 'Detective Conan', files: '884', dirs: '0', Plex scan date: 2018-05-26 12:27:23
=============================================================================================================================================================
Forced Series folder ID file: 'tvdb3.id' with id '72454'
TVDB season mode (tvdb3) enabled, serie url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/72454/all/en.xml'
xml loading issue, Exception: 'Premature end of data in tag Data line 2, line 31291, column 1''
-------------------------------------------------------------------------------------------------------------------------------------------------------------
```

I went in to TVDB and tried to find the issue, but it wasn't apparent.  I updated some episodes to see if it would fix the XML file and it did. I included the bad XML in the zip file. 

Logs:  
[Conan Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2041772/Conan.Logs.zip)

<img width="1424" alt="screen shot 2018-05-26 at 12 28 17 pm" src="https://user-images.githubusercontent.com/18091557/40578439-0812ffc2-60e2-11e8-9ca0-b5983380d974.png">

**Comment by ZeroQI** [comment]
I have coded TheTVDB v2 API which is using json for a few versions in Hama but the scanner still uses xml files. I am not sure i can use json api as i cannot keep the token in memory :/
should i load from the cache if present and then if not from json ?

**Comment by sven-7** [comment]
I don’t know if pulling from the cache is best. With a lot of these shows, they’re getting updates, so the cache might not be up to date. Wouldn’t that cause problems?

**Comment by ZeroQI** [comment]
i cannot prevent xml errors unless i use json but libraries different under scanner
spent 12 hours on coding getting there
Please test and check last ep metadata at least
https://gist.githubusercontent.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d/raw/b88126550524dd65186f58967235877baa72f4ae/Absolute%2520Series%2520Scanner.py

Would you know hot to merge Hama beta branch into master branch btw?

**Comment by sven-7** [comment]
I haven't seen a bad XML yet, but I've noticed the tvdb3 function is broken.  Metadata is coming down just fine, but the absolute numbering is not being kept in place.  It's acting like tvdb2. It looks like all other modes (from a spot test) are working. 

[New folder.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2048848/New.folder.zip)
<img width="1241" alt="screen shot 2018-05-29 at 11 17 24 am" src="https://user-images.githubusercontent.com/18091557/40668195-e1cc78a0-6331-11e8-8809-959123035dc3.png">

**Comment by ZeroQI** [comment]
Indeed it was the case
Please test and feedback, and close if resolved. Thanks
