### ISSUE TITLE
Issue related to handling multi episode files

### ISSUE THREAD

**Issue by xeroiv** [ZeroQI/Absolute-Series-Scanner#157]
I have a few shows that don't handle well with ASS.  I tried reading the logs for those shows but could not decern any helpful information as it recognizes the correct number of files and even appears to map them, but in my web interface either no record for that show is created or in the shows that have season folders only one season shows up.  What logs would be helpful in troubleshooting this issue?

```
F:\Anime\Naruto Shippuuden\Naruto Shippuuden - 001-002.avi
F:\Anime\Naruto Shippuuden\Naruto Shippuuden - 003.avi
F:\Anime\Naruto Shippuuden\Naruto Shippuuden - 004.avi

F:\Anime\Avatar The Last Airbender\Season 01\Avatar The Last Airbender - 1x01-02.mp4
F:\Anime\Avatar The Last Airbender\Season 01\Avatar The Last Airbender - 1x03.mp4
F:\Anime\Avatar The Last Airbender\Season 01\Avatar The Last Airbender - 1x04.mp4
```

**Comment by ZeroQI** [comment]
Include the following logs (in any case, specify if file not present):

[...]/Plex Media Server/Logs/Plex Media Scanner.log (scanner crash info, no new files added, etc...)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Library_name/Logs/root_folder_name.filelist.log
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Library_name/Logs/root_folder_name.scanner.log
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Logs/root_folder_name.filelist.log
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Logs/root_folder_name.scanner.log
You will find per-serie logs there with the following extensions as HAMA and ASS gather all logs in one place

root/root folder name.filelist.log - Scanner filelist and 'plexignore logs
root/root folder name.scanner.log - Scanner logs including: serie title season, episode number and preliminary title
root/root folder name.agent-search.log - Agent search, show the assignment to the right serie
root/root folder name.agent-update.log - Agent metadata update logs grom the guid assigned by the agent search function.

**Comment by xeroiv** [comment]
I was not able to find the library log files.  Attached are some of the folder scan logs and the pms scanner log.
[Plex Media Scanner.1.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2056454/Plex.Media.Scanner.1.log)
[Avatar The Last Airbender.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2056455/Avatar.The.Last.Airbender.filelist.log)
[Avatar The Last Airbender.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2056456/Avatar.The.Last.Airbender.scanner.log)
[Naruto Shippuuden.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2056457/Naruto.Shippuuden.filelist.log)
[Naruto Shippuuden.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2056458/Naruto.Shippuuden.scanner.log)





```
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Library_name/Logs/root_folder_name.filelist.log
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Library_name/Logs/root_folder_name.scanner.log
```

**Comment by ZeroQI** [comment]
reproduced library and Plex Media Scanner.log show crash in multi episode indeed
```
May 31, 2018 04:22:27.149 [1288] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "C:\Users\benja\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner - Beta2.py", line 704, in Scan
    add_episode_into_plex(media, file, root, path, show, season, int(ep), title, year, int(ep2) if ep2 and ep2.isdigit() else None, rx, tvdb_mapping, unknown_series_length, offset_season, offset_episode, mappingList)
  File "C:\Users\benja\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner - Beta2.py", line 297, in add_episode_into_plex
    Log.info('"{show}" s{season:>02d}e{episode:>03d}{before} "{regex}" "{title}" "{file}"'.format(show=show, season=season, episode=ep if ep==ep2 or not ep2 else ep1+'-'+ep2, before=" (Orig: %s)" % ep_orig_padded if ep_orig!=ep_final else "".ljust(15, ' '), regex=index or'__', title = title if clean_string(title).replace('_', '') else "", file=filename))
NameError: global name 'ep1' is not defined
May 31, 2018 04:22:27.149 [1288] ERROR - We got an error scanning in C:\Users\benja\Videos\_temp2
```
Fixed issue then display. Please test and report, and close bug report if resolved

**Comment by xeroiv** [comment]
I updated to the new script but now my tvdb2.id files aren't working.
