### ISSUE TITLE
TVDB2 Mode not working

### ISSUE THREAD

**Issue by xeroiv** [ZeroQI/Absolute-Series-Scanner#158]
After updating to get the multi-episode crash fix in [157](https://github.com/ZeroQI/Absolute-Series-Scanner/issues/157).  I was unable to get TVDB2 mode working.  Looking at the logs it shows that the scanner finds the ID file but the right mode doesnt get enabled.
```
Forced Series folder ID file: 'tvdb2.id' with id '74796'
TVDB season mode (%s) enabled
```
that log output vs a known good one you posted in issue [151](https://github.com/ZeroQI/Absolute-Series-Scanner/issues/151) seems to indicate that the mode token is not being passed.  Attached are some full logs for help.

[Naruto.Shippuuden.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2062759/Naruto.Shippuuden.scanner.log)
[Bleach.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2062760/Bleach.filelist.log)
[Bleach.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2062761/Bleach.scanner.log)
[Naruto.Shippuuden.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2062762/Naruto.Shippuuden.filelist.log)
[Plex.Media.Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2062764/Plex.Media.Scanner.log)

**Comment by ZeroQI** [comment]
not authorised, HEADERS: {'Content-type': 'application/json'}
json loading issue, Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

Was missing SSL context, only linux and MacOS impacted, was working for me
Please test and close if resolve, feedback otherwise

**Comment by xeroiv** [comment]
It appears to crash now.  First I tried to update using the Shell Update scanner.sh, but it only recieved a 40k file.  I readded the library and it did nothing.  I then went and downloaded the Absolute Series Scanner.py directly from github and placed it in my scanner folder.  I tried to add a new library again and nothing showed up.  I could see the toast messages at the bottom showing the various sub folders but at the end of the operation my library was blank.  I'll dig through the logs to see what I can find.

**Comment by xeroiv** [comment]
The SSL cert fails to verify on folders that have a tvdb2.id.  For folders that have a tvdb.id or no id file the scanner log shows all the videos, but the file list log is blank.
[Naruto Shippuuden.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2064302/Naruto.Shippuuden.filelist.log)
[Naruto Shippuuden.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2064303/Naruto.Shippuuden.scanner.log)
[Avatar The Last Airbender.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2064304/Avatar.The.Last.Airbender.filelist.log)
[Avatar The Last Airbender.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2064305/Avatar.The.Last.Airbender.scanner.log)

**Comment by ZeroQI** [comment]
Please test and feedback, and close if resolved
Library: 'no valid X-Plex-Token.id', root: 'C:\Users\benja\Videos\_temp2', path: 'Berserk (2016) [tvdb2-307111]', files: '1', dirs: '0', Plex scan date: 2018-06-02 01:12:33
=============================================================================================================================================================
Forced ID in series folder: 'tvdb2' with id '307111'
TVDB season mode (tvdb2) enabled
authorised, HEADERS: {'Content-type': 'application/json', 'Authorization': u'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1Mjc5ODQ3MjMsImlkIjoiSEFNQSIsIm9yaWdfaWF0IjoxNTI3ODk4MzIzfQ.Z28XPdCQvG9eJFtim4jVc0vKFbEAoTHmMfHEqBVnfwUPuO-crAiXmI66Xm6KqtC9Zo_URe4R3UMMvZkjfBdBfpT9ENGob6KGrzZq58lJzzeIdTm0vdb0CQCFIg1elVqNQenwbHmNU0YUvGSa0PgM5lrl_yNHp1CIjBADTcBi2F8qcb1xEgmZLY4uskVdaaoyu08Oj1IzchdcYQaKaYoCP8T-n5O3hqtDrXFNLjBMeA-bk6IR0IaXJybxF0uvjbiaRqn0hNNmme-y8aNgV5P3trsu4p68ZDuz7CXaYcOohpLQjxZn2XLL9zBNyXPfRi-Bx2s-lWj3qPzkqEaqsiZ8Cw'}
unknown_series_length: False, tvdb_mapping: {13: (2, 1), 14: (2, 2), 15: (2, 3), 16: (2, 4), 17: (2, 5), 18: (2, 6), 19: (2, 7), 20: (2, 8), 21: (2, 9), 22: (2, 10), 23: (2, 11), 24: (2, 12)} (showing changing seasons/episodes only)
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'15': 1, 'of': 1, 'flying': 1, 'sword': 1, 'the': 1, 'banner': 1, 'berserk': 1}
"Berserk (2016) [tvdb2-307111]" s02e003     (Orig: s01e015    ) "__" "Banner Of The Flying Sword" "Berserk (2016) - 15 - Banner of the Flying Sword.mkv"

**Comment by xeroiv** [comment]
I have it scanning my library right now, but it hasn't crashed yet and appears to have picked up the tvdb2.id seasons on the first major series in my folder (Bleach).  I believe we are fixed.
