### ISSUE TITLE
[Feature Request] Allow for GUID in filename

### ISSUE THREAD

**Issue by xrsxj** [ZeroQI/Absolute-Series-Scanner#161]
Would it be possible to allow for detection of the GUID in the filename, like having [anidb2-XXXX] at the end of the name?  It would allow for storing multiple different series in the same folder like series that have mulitple seasons.

**Comment by ZeroQI** [comment]
Series foldername support force id or anidb2.Id file in series folder.
You can move the series folder in a grouping folder. See grouping folder section in readme

ex:
- Code Geass/[01] Code Grass [anidb2-xxx]/Code Grass ep01.ext
- Code Geass/[02] Code Grass season 2 [anidb2-xxx]/Code Grass 2 - ep01.ext
