### ISSUE TITLE
Nura Rise of Yokai Clan Issue

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#162]
I'm having a really hard time getting this show to split correctly with the scanner.  I have it named with Absolute numbering in accordance with TVDB.  It's still splitting it up into three seasons, when there are only two.  It seems to be having issues following season 1 going into season 2.  

https://www.thetvdb.com/series/nura-rise-of-the-yokai-clan

<img width="522" alt="screen shot 2018-06-10 at 9 34 08 pm" src="https://user-images.githubusercontent.com/18091557/41208976-10d374fa-6cf6-11e8-97a7-cb18ec261309.png">

Logs: [Nura.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2088449/Nura.zip)

**Comment by ZeroQI** [comment]
"I have it named with Absolute numbering in accordance with TVDB"...
- Anidb has 24 eps only: https://anidb.net/perl-bin/animedb.pl?show=anime&aid=7404
- TheTVDB has 2x24 eps and you have absolute ep 50...

Numbering errors:
- ep 13 is actually s00e01 in AniDB AND TheTVDB
- ep 14-25 is actually ep 13-24 (offset -1)
- ep 27-50 is actually 25-48 (offset -2)

**Comment by sven-7** [comment]
So...why is absolute 49 and 50 (S2e23 and s2e24) being placed into a false season 3? TVDB has absolutes that are specials (13 and 26) hence why my absolute goes up to 50.

**Comment by sven-7** [comment]
In the below, absolute 24 should have been mapped to s01e23; 25 to s01e24 and 27 to s02e01.

```
"Nura Rise of the Yokai Clan [tvdb2-171731]" s01e024                         "__" "The Devil'S Hammer" "Nura Rise of the Yokai Clan - 24 - The Devil`s Hammer.mkv"
"Nura Rise of the Yokai Clan [tvdb2-171731]" s02e001     (Orig: s01e025    ) "__" "The Moon Is In The Sky" "Nura Rise of the Yokai Clan - 25 - The Moon is in the Sky.mkv"
"Nura Rise of the Yokai Clan [tvdb2-171731]" s02e003     (Orig: s01e027    ) "__" "Awakening Of The Nura Clan'S Third Heir" "Nura Rise of the Yokai Clan - 27 - Awakening of the Nura Clan's Third Heir.mkv"
```

**Comment by ZeroQI** [comment]
tvdb2 put seasons and eps as per TheTVDB, so season 1 of 24 eps + season 2 of 24 eps = 48 eps, and specials are s00e01 and s00e02. That is TheTVDB numbering.

the absolute index of these specials is 13 and 26 respectively which would create 50 eps for two seasons of 24 eps...
Yes they look good here these specials as this is where they fit chronologically, you still injected specials in the middle of the episodes not following anydb nor tvdb as they are not labelled s01e01...

You might get away with tvdb5 mode but no seasons...

TheTVDB absolute index is not the index in absolute numbering as int inject chronologically specials there.

**Comment by sven-7** [comment]
Even with having the special as S0E1, it will still parse season two up incorrectly.  It handles the special correctly whether it is set to S0E1 or '13'.  I've done this a lot with other shows too.  For some reason, this seems to be the only one that isn't splitting up as intended.  I think I'm just having trouble understanding why TVDB's S02E01 with Absolute 27 is not translating to S02E01. 

```
unknown_series_length: False, tvdb_mapping: {25: (2, 1), 26: (2, 2), 27: (2, 3), 28: (2, 4), 29: (2, 5), 30: (2, 6), 31: (2, 7), 32: (2, 8), 33: (2, 9), 34: (2, 10), 35: (2, 11), 36: (2, 12), 37: (2, 13), 38: (2, 14), 39: (2, 15), 40: (2, 16), 41: (2, 17), 42: (2, 18), 43: (2, 19), 44: (2, 20), 45: (2, 21), 46: (2, 22), 47: (2, 23), 48: (2, 24)} (showing changing seasons/episodes only)
```

Since you say this is working as intended, I just changed it to regular 'tvdb' mode with SXXEXX episode format to get it fixed.

**Comment by ZeroQI** [comment]
You would convert anidb numbering to tvdb but you don't use anidb numbering.
Tvdb2 use a made up by me absolute numbering not to have specials pop up.

You specials are NOT listed in tvdb season page. I an not using absolute index fom tvdb since it inject things not in the season.

**Comment by sven-7** [comment]
Okay, cool.  Thanks.

I think TVDB might have some messed up metadata in there, but it's locked and not easily viewable with all the issues surrounding their new website.
