### ISSUE TITLE
"March Comes in Like a Lion" detection error

### ISSUE THREAD

**Issue by NextFire** [ZeroQI/Absolute-Series-Scanner#167]
Hello, I have two seasons of 3-gatsu no Lion sorted like that: 

├── March Comes in Like a Lion
│   ├── S01 - March Comes in Like a Lion
│   │   ├── March Comes in Like a Lion - S00E02 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E01 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E02 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E03 (1920x1080 8-bit AVC AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E04 (1920x1080 8-bit AVC AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E05 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E06 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E07 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E08 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E09 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E10 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E11 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E12 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E13 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E14 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E15 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E16 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E17 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E18 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E19 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E20 (1920x1080 8-bit x264 AAC).mp4
│   │   ├── March Comes in Like a Lion - S01E21 (1920x1080 8-bit x264 AAC).mp4
│   │   └── March Comes in Like a Lion - S01E22 (1920x1080 8-bit x264 AAC).mp4
│   └── S02 - March Comes in Like a Lion
│       ├── March Comes in Like a Lion - S02E01 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E02 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E03 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E04 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E05 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E06 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E07 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E08 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E09 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E10 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E11 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E12 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E13 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E14 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E15 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E16 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E17 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E18 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E19 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E20 (1920x1080 8-bit x264 AAC).mp4
│       ├── March Comes in Like a Lion - S02E21 (1920x1080 8-bit x264 AAC).mp4
│       └── March Comes in Like a Lion - S02E22 (1920x1080 8-bit x264 AAC).mp4

These two seasons doesn't want to show up in plex and it seems that ASS got an error when processing them resulting in this:
<img width="1267" alt="powershell_2018-07-19_11-53-19" src="https://user-images.githubusercontent.com/20094890/42935626-63cdeb14-8b4a-11e8-8763-c6fd3a0128d5.png">

I'm running plex and the latest ASS on a Raspberry Pi 3 model B debian up to date.
Thanks for your work! I'm here if needing other information.

**Comment by NextFire** [comment]
The Raspberry can only do Direct Play without any problems, 1080p and 720p, 10-bit and 8-bit, x264 and HEVC. Transcoding will result in everlasting buffering.
When adding lot of files (like 1To of anime lol) metadata fetching takes 2-3 hours to complete (maybe it's normal). Sometimes it can take time to show up the library (maybe it's also normal when you have more than 200 shows I don't know).
Otherwise it's all OK I didn't have any problems excepting I had to purchase a micro-USB powered USB hub to mount all my 3 external disk drives to the Raspberry Pi because its 4 integrated USB ports can only deliver 1.2A.

**Comment by sven-7** [comment]
@NextFire - with the current HAMA the 2-3 hour range for metadata sounds about right for 200 shows. I have about 480 and just doing a full library refresh takes 3 hours by itself. Depends on the shows and how much metadata is coming back too.

**Comment by ZeroQI** [comment]
Forgot break in loop, tried to remove same variable from list multiple times
Only triggered if using naming convention for season folders passed the first regex so unusual patterns
