### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#17]
I'm guessing most people who use this don't follow along with the issues, but I'm guessing we should probably update the readme files to incorporate some of the major updates that have been made in the last few weeks and how to use them.  I think most features added are automatic, but I know these would be worthy of a mention.  Any others?

Right now my list would include:

- tvdb2:  The ability to map a long running series to TVDB, but have each season restart at 1.  See Sword Art Online as a good example.  Where AniDB treats it as two separate series, TVDB treats it as one series with two seasons.  

-tvdb3:  Ability to have a long running series automatically divided into seasons according to TVDB's definition of the series.  One Piece is a good example.

**Comment by ZeroQI** [comment]
That is a very fair point. I prefer to focus on hte code than the readme, but we need a proper readme, that is a very fair point. Updated it now, let me know what you think. Any productive criticism welcome

**Comment by sven-7** [comment]
I think that's good.  Should we have an example of how the files are numbered?

tvdb2:  SAO can be numbered 1-50, but will automatically be split into Season 1 (1-25) and Season 2 (1-25).

tvdb3:  One Piece can be numbered 1-700+ and will be automatically split into seasons. There is no need to separate the files into folders. 

I'm not seeing anything else, looking back at the last few issues that we should add -- I think these are the major two.

**Comment by ZeroQI** [comment]
updated. thks for the documented feedback
Didn't had too much for the scanner..
