### ISSUE TITLE
Single movie files in folder picked up as special 501

### ISSUE THREAD

**Issue by yauncle** [ZeroQI/Absolute-Series-Scanner#171]
It seems like "single file inside a folder for movies" isn't working for me.
I know it used to work, but I recently migrated some stuff around, which included moving Plex to Linux and updating the plugins I use.
But now, all the movies I have are getting picked up as Special episode 501.
Simply adding "- Complete Movie" or even "Movie" to the filename seems to fix it too, but I'm a kind of person who prefers to keep filenames intact where possible (I know, wishful thinking with Plex, but still).

A log excerpt
```
2018-08-01 09:19:27,811 (7fe87bfff700) :  INFO (common:121) - common.PlexLog(file="", movie=False)
2018-08-01 09:19:27,811 (7fe87bfff700) :  INFO (common:123) - [!] file:       "/mnt/media/Anime/Demon City Shinjuku [anidb-1023]/[A-FanRips]_Demon_City_Shinjuku_-_Remastered_[H264_DTS.5.1_AC3.2.0]_[CABAA94B].mkv"
2018-08-01 09:19:27,812 (7fe87bfff700) :  INFO (common:82) - [!] Library access denied
```

this should be the full log for this scan attempt: 
[shinjuku.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2248876/shinjuku.txt)

**Comment by ZeroQI** [comment]
This is the HAMA agent log, not the scanner log which is is hama agent data folder, along with per series agent logs and filelists...

> /mnt/media/Anime/Demon City Shinjuku [anidb-1023]/[A-FanRips]_Demon_City_Shinjuku_-_Remastered_[H264_DTS.5.1_AC3.2.0]_[CABAA94B].mkv

If you were to call your movie the same as the folder apart from the square brackets groups, it will see it as s01e01: "Demon City Shinjuku [H264_DTS.5.1_AC3.2.0]_[CABAA94B].mkv"

If you forward the right logs will make single file without ep number in folders s01e01

**Comment by yauncle** [comment]
Apologies on the wrong logs, I hope this is better?
[shinjuku2.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2249506/shinjuku2.zip)

For what it's worth, the same happens if I include an anidb.id file instead of putting it in the folder name.
Alternatively, if I tag something as, for example, [tvdb-74908-s0e1], the same happens as well

**Comment by yauncle** [comment]
In the meanwhile I've done some more testing following your suggestion.
I now have this folder structure:
Demon City Shinjuku [anidb-1023]/Demon City Shinjuku [H264_DTS.5.1_AC3.2.0]_[CABAA94B].mkv
And it still shows up as Special 501.

Here's more logs...
[shinjuku3.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2249565/shinjuku3.zip)

**Comment by ZeroQI** [comment]
Please try and confirm if resolved as expected

**Comment by yauncle** [comment]
Works perfectly. Tried a few different movies to make sure.

Thanks!

**Comment by EndOfLine369** [comment]
@ZeroQI, this has broken the scanner. If there is one file but that file is for an episode other than 01, its true episode number no (matter the numbering format used) will be ignored.

**Comment by EndOfLine369** [comment]
This test was originally in that piece of code:
  `not re.search("\d+(\.\d+)?", clean_string(filename, True))`
but you removed it in 2017.
As is a single episode movie/ova, there would be no episode number in the filename.
https://github.com/ZeroQI/Absolute-Series-Scanner/commit/caeb327456bd2d0cae57a4a0323b61a781ca89d1#diff-edf9a02ffa5a0496c5247e048b83f667L476

**Comment by yauncle** [comment]
That changes behavior rather drastically as well. 
Example:
`[RUELL-Raws] Inuyasha Movie 4 - Fire on the Mystic Island (BD 1280x688 AAC 4.1ch(JP)+AAC 5.1ch(EN) ENSub) [6830E6CE].mkv`
With tvdbid set to 71361-s0e4 ([tvdb link](https://www.thetvdb.com/series/inuyasha/seasons/0))
The result is the movie ends up in Plex as Specials -> Episode 7 (because "4" in filename plus the offset of "4-1" in the id file = 7).
Scanner log shows this as well:
`Library: 'no valid X-Plex-Token.id', root: '/mnt/media/Anime', path: 'InuYasha/InuYasha The Movie 4 - Fire on the Mystic Island (BD)', files: '1', dirs: '0', Manual scan date: 2018-08-03 06:39:01
=============================================================================================================================================================
Forced Series folder ID file: 'tvdb2.id' with id '71361-s0e4'
offset_season = -1, offset_episode = 3
TVDB season mode (tvdb2) enabled
[omitted]
misc_count: {'on': 1, 'Inuyasha': 1, 'Fire': 1, 'Movie': 1, 'Island': 1, '4': 1, 'Mystic': 1, 'the': 1}
"InuYasha The Movie 4 - Fire on the Mystic Island [tvdb2-71361]" s00e007     (Orig: s01e004    ) "9" "Fire on the Mystic Island ( 4.1ch (JP) +ch (EN) ENSub )" "[RUELL-Raws] Inuyasha Movie 4 - Fire on the Mystic Island (BD 1280x688 AAC 4$
root level manual call to Grouping folders`

**Comment by yauncle** [comment]
I can work with that, I just need to modify some id overrides in the library.
Just let me know if this is the way forward from now on, so I don't go changing stuff just to change it back afterwards.

**Comment by ZeroQI** [comment]
As designed

if the folder is called 'Inuyasha Movie 4' the 4 isn't picked up since series folder name is removed from filename. The following would be best practice
- Inuyasha Movie 4 [tvdb-71361]/ Inuyasha Movie 4 -  s00e04 - Fire on the Mystic Island .mkv
- Inuyasha Movie 4 [anidb2-2321]/ Inuyasha Movie 4 - Fire on the Mystic Island .mkv

single files for single season with no ep number will be ep 1
movies still need to be named the same as the folder to remove titles with numbers in them...
