### ISSUE TITLE
Scanner does not properly handle episodes split into two parts

### ISSUE THREAD

**Issue by localh0st-** [ZeroQI/Absolute-Series-Scanner#18]
Example: 
Re:Zero kara Hajimeru Isekai Seikatsu Episode 01

HorribleSubs release split episode 01 into 01A and 01B, each 24 minutes long. TVDB and AniDB show episode 01 as being 49 minutes long.

even when renamed to end with part1 and part2, the scanner loads both files as different versions of episode 01 and does not recognize them as parts

**Comment by sven-7** [comment]
I also had this problem.  Ultimately, I ended up getting a separate version that combined both 01A and 01B into a single episode to work around this problem. 

At the same time, I also have issues where multiple episodes are combined, but not registering.  A Detective Conan episode I have is unfortunately a 4 part episode (702-703-704-705), but it only shows up as 702.

**Comment by ZeroQI** [comment]
@Sven-7: it should show the same ep duplicated into the 4 with proper metadata. Please attach the scanner custom log so i can reproduce 

@Localh0st, i did this for opening and it works as separate eps, give me the custom scanner logs so i have your filenames. plex convention dictates -part1 at the end before the ext.

**Comment by localh0st-** [comment]
@ZeroQI Which logs do you want?

**Comment by localh0st-** [comment]
@ZeroQI: 
D:\Downloaded Anime\[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 01 - part1.mkv
D:\Downloaded Anime\[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 01 - part2.mkv

**Comment by localh0st-** [comment]
@ZeroQI 
D:\Downloaded Anime\[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 01 - part1.mkv
D:\Downloaded Anime\[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - 01 - part2.mkv

**Comment by ZeroQI** [comment]
https://support.plex.tv/hc/en-us/articles/200265006-Naming-Stacked-TV-Show-Episodes says this is acceptable. will edit the scanner
Seem like it's missing     Stack.Scan(path, files, mediaList, subdirs) at the end of "def add_episode_into_plex(mediaList, file, root, path, show, season=1, ep=1, title="", year=None, ep2="", rx="", tvdb_mapping={}):" function

**Comment by sven-7** [comment]
@ZeroQI here is how it's showing up:

`2016-04-20 15:38:04 "Detective Conan [tvdb3-72454]" s0022e700 "Detective Conan - 700 - The Shadow Approaching Haibara's Secret (Part 2).mkv" "The Shadow Approaching Haibara's Secret (Part 2)" 
2016-04-20 15:38:04 "Detective Conan [tvdb3-72454]" s0022e701-702 "Detective Conan - 701-702-703-704 - The Raven Mystery Train.mkv" "11" "703-704 - The Raven Mystery Train" 
2016-04-20 15:38:05 "Detective Conan [tvdb3-72454]" s0022e705 "Detective Conan - 705 - Conan Inside the Locked Room.mkv" "Conan Inside the Locked Room" `

**Comment by ZeroQI** [comment]
Plex default scanner doesn't support more than 2 episodes in that fashion, nor doe Dabs to my knowledge. 
It however currently supports 2 ep numbers, so 701-704 it will work since a loop is used


To solve i could try maybe adding   (([ _\.\-]|(e|ep)|[ _\.\-](e|ep))([0-9]{1,3}))* in between the two ep fields below but i am unsure it wouldn't skip the end episode then:
series_rx => '(^|(?P<show>.*?)[ _\.\-]+)s(?P<season>[0-9]{1,2})(e| e|ep| ep|-)(?P<ep>[0-9]{1,3})(([ _\.\-]|(e|ep)|[ _\.\-](e|ep))(?P<ep2>[0-9]{1,3}))?($|( | - |)(?P<title>.*?)$)'

**Comment by EndOfLine369** [comment]
By adding more than two clear start & end numbers, you add the possible issue of people having an issue with "100-101-103" as one of the numbers is missed. Best to probably either leave it at "xxx-xxx" only OR in the code (maybe the clean function?) to have it chop out the middle numbers before regex parsing. (EX: "100-101-103" => "100-103")

**Comment by localh0st-** [comment]
Could we possibly split this into two issue reports, seeing as sven-7 is describing a different issue than this was created for?

**Comment by sven-7** [comment]
This is interesting... I changed it to 701-704.  Now Plex shows it as four separate episodes. So, that's pretty cool.  Clicking into each one, it's the same file, but nice that's it's split out.  Would consider my side of this closed, so no need to start a separate one. 

Here's the log:  "2016-04-30 11:35:59 "Detective Conan [tvdb3-72454]" s0022e701-704 "Detective Conan - 701-704 - The Raven Mystery Train.mkv" "11" "The Raven Mystery Train" "


<img width="1677" alt="screen shot 2016-04-30 at 11 48 09 am" src="https://cloud.githubusercontent.com/assets/18091557/14937045/72353e8c-0ec9-11e6-8971-5dc1518b2415.png">

**Comment by ZeroQI** [comment]
@localh0st-; Please test and see if part if ... > Info list both parts in right order.

**Comment by localh0st-** [comment]
Affirmative, part1 and part2 are listed in the proper order. Thanks!
