### ISSUE TITLE
SAO S3 Issue

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#184]
There seems to be a disconnect somewhere between TVDB / ScudLee / ASS.  Inputting "Sword Art Online - 51 - Underworld", which should be S3E1, is getting mapped to S3E2.  TVDB has Absolute 50 as S0E22, so there is a gap in absolute numbering between S2 and S3.  Not sure where that messes things up, but here are my logs.  The scanner is recognizing it as S3E2.

[Sword Art Online.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2453568/Sword.Art.Online.zip)

**Comment by ZeroQI** [comment]
tvdb_mapping: {26: (2, 1), 27: (2, 2), 28: (2, 3), 29: (2, 4), 30: (2, 5), 31: (2, 6), 32: (2, 7), 33: (2, 8), 34: (2, 9), 35: (2, 10), 36: (2, 11), 37: (2, 12), 38: (2, 13), 39: (2, 14), 40: (2, 15), 41: (2, 16), 42: (2, 17), 43: (2, 18), 44: (2, 19), 45: (2, 20), 46: (2, 21), 47: (2, 22), 48: (2, 23), 49: (2, 24), 50: (3, 1), 51: (3, 2), 52: (3, 3), 53: (3, 4), 54: (3, 5), 55: (3, 6), 56: (3, 7), 57: (3, 8), 58: (3, 9), 59: (3, 10), 60: (3, 11), 61: (3, 12)}
Ep 50 is s03e01 according to scanner code
Sword Art Online: Alicization (a13493)
  <anime anidbid="13493" tvdbid="" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="">
    <name>Sword Art Online: Alicization</name>
  </anime>

Please edit AnimeLists mapping for anidbid 13493

**Comment by sven-7** [comment]
Thanks, @ZeroQI . Committed the change per your request. 

I submitted a request on ScudLee to have it updated there as well.

**Comment by ZeroQI** [comment]
Thanks for that. not sure they will take the movie tvdb mapping but the season will help many
