### ISSUE TITLE
Absolute Series Scanner marks Optimized Versions as deleted

### ISSUE THREAD

**Issue by miracle152004** [ZeroQI/Absolute-Series-Scanner#186]
Hi,
I have the problem that ASS marks Optimized Versions, which are created into its own directory, as deleted even though the files are still there.

Situation:
- Anime are positionied in one directory, i.e. F:\Anime
- Optimized Versions are created into a different root directory, i.e. F:\PlexOptimized\Anime
- Plex creates specific files with the naming S{SeasonNumber}E{EpisodeNumber} in a subdirectory, i.e. F:\PlexOptimized\Anime\Plex Versions\Optimized for TV\{AnimeName}
- Optimzation is done by following Settings: Only unwatched, 1 file, into F:\PlexOptimized\Anime

Tested it with different szenarios (Ass with hama, Ass with tvdb, Plex scanner with hama, plex scanner with tvdb) only the ASS configurations mark the files as deleted.

I did not have this problem with older versions of plex and ASS, it seems to be something which happened quiet recently.

Could you please take a look.
Thanks.

Best regards
miracle152004

**Comment by ZeroQI** [comment]
Do you have the latest version of ASS that doesn't give the issue ?
I have no clue what caused it but the notepad++ compare plugin could help

**Comment by miracle152004** [comment]
I have done a little more testing and found a little more information:

Since I only optimize for tv my structure is somthing like this:
Rootfolder
 - Plex Versions
       - Optimized for TV
            - Anime Folder
           -  Another Anime Folder

After adding some other folder on the same level as "Optimized for TV" it works without issue.
Could these lines of code be responsible:
`    #### Grouping folders skip , unless single series folder ###
    if not kwargs and len(reverse_path)>1 and not season_folder_first:  
      parent_dir = os.path.dirname(os.path.join(root, path))
      parent_dir_nb= len([file for dir in os.listdir(parent_dir) if os.path.isdir(os.path.join(parent_dir, dir))])
      if parent_dir_nb>1:  return  #Grouping folders Plex call, but mess after one season folder is ok`

Should be starting at line 534 of the current master branch.

Could you verify if my suspicions are correct. Python is not my main programming language.

**Comment by ZeroQI** [comment]
Very good point actually...
From the root folder call i call subfolders unless they would be called naturally or represent a single serie
Here if called naturally and not the folder at root level and more than 1 subfolder, we skip as it would habe been called manually during root folder scan...
Can you spot in Hama agent data folder the logs folder and see if you can spot logs about skipping plex Optimised folders?

**Comment by miracle152004** [comment]
I do not see something about skipping, but I have created the log files for both configurations.

In the working configuration he says something about grouping folders.

**[no files detected]
root level manual call to Grouping folders
[Added] F:\Anime Test Optimized ASS Hama\Plex Versions\Bob
[Added] F:\Anime Test Optimized ASS Hama\Plex Versions\Optimized for TV
[Added] F:\Anime Test Optimized ASS Hama\Plex Versions\Optimized for TV\11 Eyes
[Plex Versions] Grouping folder (contain 2 dirs)
Plex Versions\Optimized for TV\11 Eyes                      , subdir_files:   2, reverse_path: ['Optimized for TV', 'Plex Versions']**   

The not working configuration logs the operations like this:
**root level manual call to Grouping folders
[Added] F:\Anime Test Optimized ASS Hama\Plex Versions\Optimized for TV
[Added] F:\Anime Test Optimized ASS Hama\Plex Versions\Optimized for TV\11 Eyes**

The not working configuration does not create a scanner.log for the "Plex Versions" directory or any logs for subdirectories.
The working configuration creates one for "Plex Versions" and lists the scanned files.

**Comment by ZeroQI** [comment]
Sorry for delay, will be working on it
it's not as much as it is removed that never added. need to spot the folderis not in root folders (and/or contain"Optimized")

**Comment by ZeroQI** [comment]
I removed the return if it is an optimized folder: "if parent_dir_nb>1 and "Plex Versions" not in parent_dir and "Optimized for " not in parent_dir:  return"
Please test this fix, and report.
Since it was previously skipped, it will not re-run unless the folder changes.
Either add an episode or remove, rescan, add the folder back, rescan

**Comment by miracle152004** [comment]
Hi,
I tested it but it is still happening on my end.

**Comment by ZeroQI** [comment]
Please try again on latest version

**Comment by ZeroQI** [comment]
Is it working on the latest version?

**Comment by miracle152004** [comment]
Hi,
I have to test it again on my larger library, but on my small test library it works now.

**Comment by ZeroQI** [comment]
Excellent news. Looks good so far

**Comment by miracle152004** [comment]
Seems to be working now.
Checked with the larger library and could not detect any problems.
Thanks.
