### ISSUE TITLE
[TVBD5 - Numbering] Star Wars - The Clone Wars [tvdb5-83268]

### ISSUE THREAD

**Issue by DJScias** [ZeroQI/Absolute-Series-Scanner#187]
Hello there,

Since I've recently got interested back in the Clone Wars series, I wanted to push this in my Plex and try out the example used in the README about TVDB5.. However I don't think it turned out how it should:
![image](https://user-images.githubusercontent.com/439655/47272132-4599b980-d581-11e8-996e-9895b734eb62.png)

It's using the normal numbering, even though I was under the impression that TVDB5 would go with a different chronological (absolute) one? It's that or the README is wrongly written. The folder's called `Star Wars - The Clone Wars [tvdb5-83268]` (As windows doesn't accept `:`).

Attached logs:
[Star Wars - The Clone Wars [tvdb5-83268].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2499580/Star.Wars.-.The.Clone.Wars.tvdb5-83268.filelist.log)
[Star Wars - The Clone Wars [tvdb5-83268].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2499581/Star.Wars.-.The.Clone.Wars.tvdb5-83268.scanner.log)

If there's anything else needed, do let me know.

**Comment by ZeroQI** [comment]
tvdb5 goes using the absolute numbering indeed.
The scanner has remapped original s02e016 into s01e001 as it should.

`"Star Wars - The Clone Wars [tvdb5-83268]" s01e001     (Orig: s02e016    ) "SERIES_RX-0" "Cat And Mouse" "Star Wars The Clone Wars 02x16 Cat And Mouse.mkv"`

Do you mean the agent is using the non-remapped metadata?
Would need the agent logs to fix

**Comment by DJScias** [comment]
Hello there,

I've got three log files of HAMA that have traces of Star Wars into it:
[com.plexapp.agents.hama.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2499614/com.plexapp.agents.hama.zip)
[com.plexapp.agents.hama.log.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2499616/com.plexapp.agents.hama.log.zip)
[com.plexapp.agents.hama.log (2).zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2499617/com.plexapp.agents.hama.log.2.zip)


If you'd like, I can close it here and re-open it on the HAMA github?

**Comment by ZeroQI** [comment]
A recent update reverted

**Comment by ZeroQI** [comment]
Please test and report

**Comment by DJScias** [comment]
Hello there,

Refreshed the metadata after updating Hama.bundle and it's looking fine now.
![image](https://user-images.githubusercontent.com/439655/47382965-df896f80-d703-11e8-8ccc-34c20a67abbd.png)

If you need any sort of logs, do let me know. 👍

**Comment by ZeroQI** [comment]
Just donations :D
