### ISSUE TITLE
Reverse YouTube Numbering?

### ISSUE THREAD

**Issue by semicolonsnet** [ZeroQI/Absolute-Series-Scanner#193]
I'm working with a YT channel that has a lot of videos (https://www.youtube.com/channel/UCsQBsZJltmLzlsJNG7HevBg). I'm using the channel ID in the series folder name to designate them. However, episodes are numbered with the newest video first. I'd like an option to reverse that and number them starting with the oldest video.

**Comment by ZeroQI** [comment]
Do you use my scanner?
Could you attach the agent logs?

Doesn't youtube2 mode manages that albeit with one season per year or is it also reversed?

**Comment by semicolonsnet** [comment]
I am using ASS, with the YouTube agent prioritized. Attached are logs with verbose on and the series identifier renamed as youtube2 as you suggested. The same issue appears - episodes from the series' beginning are numbered 870+ when I'd like episodes numbered from oldest to most recent.

[Plex Media Server Logs_2018-11-04_08-45-18.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2546029/Plex.Media.Server.Logs_2018-11-04_08-45-18.zip)

Thanks for your help on this!

**Comment by ZeroQI** [comment]
The logs were missing YouTube agent logs...
scanner line 777-779
```
    if id.startswith('UC') or id.startswith('HC'):
      files_per_date = sorted(os.listdir(os.path.join(root, path)), key=getmtime, reverse=True)
      Log.info('files_per_date: {}'.format(files_per_date))
```
The main point of the scanner is not to renumber all episodes each time there is a release so reverse was wrong. i have amended that, so please try the latest version, and report

The folder will probably be cached by Pex so either add an episode or remove, re-scan, add back if it doesn't detect changes.

**Comment by semicolonsnet** [comment]
New version resolves the issue - closing the thread. Thanks!
