### ISSUE TITLE
Tvdb4 mapping Issue One piece

### ISSUE THREAD

**Issue by TrafalgaT** [ZeroQI/Absolute-Series-Scanner#194]
every episode metadata is offset by 1 starting from episode 590 - current i.e 590 is displayed as _"Chopper Enraged  Master's Tyrannical Experiments"_ instead of "_Histories Strongest Collaboration! The Glutton of the Abyss_" through to episode 862 titled _"Break Through - The Straw Hat's Mighty Sea Battle!"_ instead of "_Sulong - Carrot's Big Mystic Transformation"_. 

I don't know what is causing this and it is the first time i've encountered this issue

**Comment by ZeroQI** [comment]
Use either tvdb or anidb numbering but if the mode is alleed tvdb 4, follow tvdb
What you consider absolute ep 590 is TheTVDB season 0 episode 25 collaboration SPECIAL, not TheTVDB season 16 ep 12...
- rename your ep 590 to s00e25 + renumber all
- alternatively tvdb 5 would use absolute index in tvdb to transform tvdb absolute numbering display (no season) to insert specials using the tvdb absolute index, would display as you want, still needs proper TheTVDB numbering.
- could split in separate folder and use offset maybe: One Piece [tvdb4-81797-sxxeyy]

**Comment by TrafalgaT** [comment]
ok so id extract it and add it to specials (btw in fear of paying double the RTFM tax) is there a reason specials folder keeps getting removed ? specials folder follows the tvdb numbering syyexx and all the other season follow ae#

**Comment by ZeroQI** [comment]
I do not understand "specials folders keeps getting removed".
You can name specials
- s00exx
- Specials/01 title.ext
- Season 0/

**Comment by TrafalgaT** [comment]
What i Meant was i am following the "costum" seasons of the tvdb4 mapping file for seasons 1-23 as Absolute numbering (EXXX) and for specials i have the TVDB numbering meaning S00eXX, is there a way i can "combine them" or should i extract the folder containing the specials (movies, episodes etc) and have them seperately to the anime episodes or can i leave them inside of one folder containing both:

One Piece
          Specials
           - S00E01
           - S00E02 and so on
           S01
            - E001
            - E002 and so on

**Comment by TrafalgaT** [comment]
or is there a way to maybe just exclude E590 inside of tvdb4.mapping.xml 

20|575|589|Punk Hazard
20|591|628|Punk Hazard

would that be possible ?

**Comment by sven-7** [comment]
I just went thru this as well. It’s a bit of a pain when TVDB considers specials with absolute numbering, but it happens a lot. Episodes that air after the season ends, DVD episodes, specials that air during the season that the producer gives an absolute number (i.e. One Piece 590). Ideally, if you had 590 in your file directory, it would map to season 0 and the season in Plex would go from 589 to 591. 

See this:  https://github.com/ZeroQI/Hama.bundle/issues/264

The scanner used to have no problems with those, but there were some changes made that are tough to workaround.  It doesn’t read the absolute number index in TVDB anymore. SAO has this problem too now with Ordinal Scale counting as an absolute number (which it shouldn’t, but they have decided that’s the policy). 

I went ahead and did the two folder solution, which makes all the absolute numbers off by one after 590. It’s a little frustrating, but at least you get the right titles and metadata. You just have to know if you’re looking for episode 861, that it’s probably now listed as 860. Just as an example. 

I had a little success removing episodes with the mapping, like you suggested, but the metadata still didn’t map right. If you come up with any ideas, I’ll try some out too.

**Comment by TrafalgaT** [comment]
Thank you for your reply, Like i said im open for any kind of ideas to smoothly solve this issue, but as you mentioned it looks like ill have to live with the +1 offset (archive and organising wise extremly annoying and tedious but alright)

**Comment by ZeroQI** [comment]
@TrafalgaT scanner choose season and episode number, agent choose metadata. Your specials have the season 0 in numbering so you can put all in the series folder

TVDB5 reads the absolute index but in a single season
We had to change it as for example some movies (or OAVs) were being inserted with an absolute index number in tvdb and would have forced to renumber half of the episodes, which make no sense. Generally this absoule index change happened after the episode were numbered which make it clearly unfair to ask to renumber episodes when the series didn't change itself, just a timeline inserted special after the fact...

To solve i would have to
-  create a new tvdb6 mode which would be tvdb4 with absolute indexes
i could make the translation in the scanner and rename the mode to tvdb4 so no change in the agent
- manage a new token file presence to indicate to remove the ep and offset everything

that is troublesome for a numbering NOT following tvdb nor AniDB numbering, i can understand why you want it but it should be a normal ep, not a special per say, but that it for TheTVDB to decide.

**Comment by TrafalgaT** [comment]
It is alright and im not forcing this addition or "update" per se, ive renamed the eps following 591 onwards now which is tedious but hey it works !
