### ISSUE TITLE
Multiple Episodes Identified As A Single Episode (Duplicates)

### ISSUE THREAD

**Issue by orrorri** [ZeroQI/Absolute-Series-Scanner#195]
This is similar to #126 "Duplicate episodes for TV"

Multiple files are being identified as the same episode. Almost all of the files effected end in "x5" episode number. 
S01E01 and S01E15 = E01
S01E02 and S01E25 = E02
(etc)

Library Name in Plex: Anime      #yes, i know it is the most creative library name you have ever seen
Series Name: Cardcaptor Sakura      #anidb-102   
Folder Name in storage: ./Cardcaptor Sakura (1998) [main(x-jat)] [anidb-102]/Season 01   
File Name structure in storage: Cardcaptor.Sakura.S01Exx.1080p.x264-AAC.mkv

I have not noticed this error occurring in any other series. 
I have attempted to rename some effected files to see if alternate naming styles would fix the issue.
Other filenames that were attempted:
Cardcaptor.Sakura.Exx.1080p.x264-AAC.mkv
Cardcaptor.Sakura.S01E0xx.1080p.x264-AAC.mkv
Having the files in the "Season 01" folder, or in the base folder had no difference either.

I am using a fresh install of HAMA and ASS. 

I have shortened the log filenames for my personal ease of uploading from bash terminal.
Original log location is ./Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs

A file that is having problems, show in filelist.log

> [file] Cardcaptor Sakura (1998) [main(x-jat)] [anidb-102]/Season 01/Cardcaptor.Sakura.S01E15.1080p.x264.AAC.mkv

and in scanner.log

> "Cardcaptor Sakura (1998) [main(x-jat)] [anidb-102]" 
> s01e001                         
> "Word Search" 
> "080P" 
> "Cardcaptor.Sakura.S01E15.1080p.x264.AAC.mkv"

[scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2674830/scanner.log)
[filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2674859/filelist.log)

Let me know if you need any other log files.

**Comment by ZeroQI** [comment]
Sorry for the delay. File naming (dots replacing spaces) is atrocious
- "Cardcaptor.Sakura.S01E05.1080p.x264.AAC.mkv"
- "Cardcaptor.Sakura.S01E15.1080p.x264.AAC.mkv"
- "Cardcaptor.Sakura.S01E25.1080p.x264.AAC.mkv"

There need to be a cleaning of "1080p" BEFORE "5.1" in WHACK_PRE_CLEAN_RAW.
Submitted new code but scanner might not refresh if no changes detected in folder
