### ISSUE TITLE
anidb2/3/4 not working

### ISSUE THREAD

**Issue by Feredzhanov** [ZeroQI/Absolute-Series-Scanner#196]
I can't make the [anidb2-xxxx] work with my library. Updated to the latest ASS and HAMA, it worked once for "Highshcool of the dead" once, I manually renamed the 2 folders for test and it worked, then I renamed all my other folders that way (WebAOM helps a lot) and nothing. My folders structure is (that's Anime Test folder, with only 2 shows):

> Black Lagoon Roberta's Blood Trail [anidb3=6645]
Black Lagoon The Second Barrage [anidb3=4597]
Black Lagoon [anidb3=3395]
High School DxD Born Yomigaeranai Fushichou [anidb2=11844]
High School DxD Born [anidb2=10691]
High School DxD Hero
High School DxD Hero [anidb2=12498]
High School DxD New Gekkou Koutei no Excalibur [anidb2=9409]
High School DxD New Teishi Kyoushitsu no Vampire [anidb2=11184]
High School DxD OAD [anidb2=8925]
High School DxD [anidb2=8660]

And that's how it looks in Plex
![image](https://user-images.githubusercontent.com/27891431/50052812-bf3dc600-0132-11e9-8e5b-a346e51b4208.png)
Looking for ideas on what the issue may be.

**Comment by EndOfLine369** [comment]
hi,
Going only on your posted of folder names as no logs were provided, your using an equals '=' sign instead of a dash '-'.
```
BAD:
Black Lagoon Roberta's Blood Trail [anidb3=6645]
Black Lagoon The Second Barrage [anidb3=4597]
Black Lagoon [anidb3=3395]

CORRECT:
Black Lagoon Roberta's Blood Trail [anidb3-6645]
Black Lagoon The Second Barrage [anidb3-4597]
Black Lagoon [anidb3-3395]
```

**Comment by ZeroQI** [comment]
Only '-' is recognised as a separator, no scanner logs attached so didn't follow readme troubleshooting steps. Closing
