### ISSUE TITLE
File forcing

### ISSUE THREAD

**Issue by Feredzhanov** [ZeroQI/Absolute-Series-Scanner#197]
Sorry for publishing in issues. Is there a way to force the file recognition. I mean, if I add the id of the file, will it work the same way it does as with folders, like "<file> [anidb-xxxxx].mkv" or something like that, and if not, is it possible to be implemented (I guess it wouldn't be really hard). Thanks in advance.

**Comment by ZeroQI** [comment]
Plex match a series so matching files make no sense to me.
I could check for movie libraries, but you gave no example or practical use.

**Comment by Feredzhanov** [comment]
The use is, that if you use [anidb2-xxxx] to match series, often the files aren't matched right. And here's a direct example that is happening to me at the moment. Fafner has 3 seasons, 2 movies and 2 "specials". The two specials are actually replacing the original Ep. 25 from the 1st season with 2 slightly different episodes: "Arcadian Memory 1" and "Arcadian Memory 2". When I use [anidb2-xxxx] tag it matches the seasons properly, however, the movie "Heaven and Earth" is matched as "Arcadian Memory 1", the special "Arcadian Memory 1" is matched as "Arcadian Memory 2" and "Arcadian Memory 2" is matched as "Heaven and Earth". And that's just one of the problems that I currently have.

**Comment by ZeroQI** [comment]
Anidb2 mode translate from anidb numbering to tvdb numbering according to ScudLee's XML mapping files.
You can always use [tvdb-xxxx-s00e02] to insert at the right place. 
The movie is AniDB s01e01 and TheTVDB s00e02 according mapping file.

<anime anidbid="7304" tvdbid="81110" defaulttvdbseason="0" episodeoffset="" tmdbid="137502" imdbid="">
    <name>Soukyuu no Fafner: Dead Aggressor - Heaven and Earth</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-2;</mapping>
    </mapping-list>
  </anime>

According TheTVDB it should be s00e04
https://www.thetvdb.com/series/fafner/seasons/0

Please update Scudlee's mapping file.

The logs even indicate the mapping in a readable manner.

**Comment by Feredzhanov** [comment]
Yes, the problem is, it didn't recognize the files right, the 2 episodes are anidb-1806, S00E03 and S00E04 in AniDB and are tvdb-81110 S00E05 and S00E06, but, Plex/ASS/HAMA doesn't match them right, it matches 
`Soukyuu no Fafner Dead Aggressor - Heaven and Earth [anidb2-7304]\Soukyuu no Fafner Dead Aggressor - Heaven and Earth - 1 - Complete Movie [ACX](DF081233).mkv` as `anidb-1806 S00E01`

`Soukyuu no Fafner Dead Aggressor [anidb2-1806]\Soukyuu no Fafner Dead Aggressor - S03 - Episode 25 Symbiosis (The Final Battle) [ACX](F2029906).mkv` as `anidb-1806 S00E02`

and `Soukyuu no Fafner Dead Aggressor [anidb2-1806]\Soukyuu no Fafner Dead Aggressor - S04 - Episode 26 The Sky (Azure) [ACX](E6DCFEA7).mkv` as `anidb-7304 S01E01`

If you can explain how can I make Plex/ASS/HAMA match the files correctly I'll be very happy.

**Comment by ZeroQI** [comment]
Soukyuu no Fafner Dead Aggressor - Heaven and Earth
- anidb "7304" s01e01 Soukyuu no Fafner: Dead Aggressor - Heaven and Earth
- TVDB "81110" s00e04  Heaven and Earth 
- MAPPING FILE s01e01=>s00e02 Arcadian Memory 1, mapping is wrong, should be s00e04 Heaven and Earth so use [tvdb-127502-s00e04] OR [anidb2-7304] & FIX MAPPING FOR EVERYBODY (RECOMMENDED)

Soukyuu no Fafner Dead Aggressor
- Anidb "1806" s00e03 Episode 25 Symbiosis (The Final Battle) 
- Anidb "1806" s00e04 Episode 26 The Sky (Azure)
- tvdb "81110" no ep
- no specials mapping

Notes
- You cannot match these 2 eps using TheTVDB since it is not in TheTVDB. Add them?
- You have to follow either anidb or thetvdb and while i accommodate conversions with anidb2 mode, you cannot have it both ways if eps are missing in TheTVDB.
- Why not use anidb mode [anidb-1806] since it handles both specials and make a collection with the movie?

**Comment by Feredzhanov** [comment]
>     * MAPPING FILE s01e01=>s00e02 Arcadian Memory 1, mapping is wrong, should be s00e04 Heaven and Earth so use [tvdb-127502-s00e04] OR [anidb2-7304] & FIX MAPPING FOR EVERYBODY (RECOMMENDED)

If you can pls explain how to do that, I will. Thanks in advance.

**Comment by EndOfLine369** [comment]
Looks like you opened up a ticket for ScudLee-159 😄

**Comment by Feredzhanov** [comment]
Yeah, I did, tried to contribute....it ain't working. But if you know other way, I'm in ;)

**Comment by ZeroQI** [comment]
Once they correct it, it will work for the movie. I added a comment as you did not remap the 2 first specials in the request. The last 2 specials on tvdb cannot be added to thetvdb as they never aired, so TheTVDB will not add them and remove them if added...

**Comment by Feredzhanov** [comment]
They are DVD only, it's basically the last episode (that is 50 min) split in 2.

**Comment by ZeroQI** [comment]
i know, so all 4 specials in thetvdb are accurate (not possible to add these 2) and with my edit the 2 specials get mapped ok and your edit map the movie correctly. TheTVDB probably inserted the special and shifted 2 place down the movie after the mapping was done and never updated...

**Comment by Feredzhanov** [comment]
It's possible, I just don't know what the 2 nameless specials are...

**Comment by ZeroQI** [comment]
i missed hese 2, probably somebody that added the dvd specials and they removed them and locked the series.

**Comment by ZeroQI** [comment]
So we are clear, the mapping file is incorrect (pending being updated) in this example, but agent and scanner behave as expected considering that?
- You should only use anidb2 if the mapping file translate to thetvdb correctly and there is thetvdb entries for the files. 
- If using AniDB numbering + Plex collection could also be easier

Can we close this ticket or do you have a meaningful example?

**Comment by Feredzhanov** [comment]
Yeah, thanks for the help. I've made a pull request on ScudLee's list, waiting for merge, and I'm adding tons of mapping fixes to it while waiting :D
