### ISSUE TITLE
How to  match longrunning numbering to anidb id's

### ISSUE THREAD

**Issue by Cezus** [ZeroQI/Absolute-Series-Scanner#200]
Hello,

I have this anime, Boku no Hero Academia, and I want it to match anidb id. As for now I have the folders structured referenced to Anidb. The second season is called Boku no Hero Academia (2017) but the files I have do not start from episode number 1, but number 14 (as s01 ended with number 13).

folder structure:
- Boku no Hero Academia
 -- files from 1 - 13
- Boku no Hero Academia (2017)
 -- files from 14 to 38

I have spend a couple of hours to understand the matching (anidb, anidb2, tvdb, etc) but I cannot find out what would be applicable to my situation.

With kind regards

**Comment by ZeroQI** [comment]
Renumber the file to match anidb numbering would be most logical, (and would take less than 2 hours) any other media agent software than plex would give you no latitude there...

However, there is with my scanner these solutions without renumbering:

Anidb offset for the second series:
Boku no Hero Academia\eps 1-13.ext 
Boku no Hero Academia (2017) [anidb-12233-s01e-13]\eps14-38.ext

TVDB seasons keeping absolute numbering:
Boku no Hero Academia [tvdb3-305074]
- Season 1 Boku no Hero Academia\eps 1-13.ext
- Season 2 Boku no Hero Academia (2017)\eps14-38.ext

TVDB all eps in absolute numbering mode
Boku no Hero Academia [tvdb4-305074]\eps 1-13.ext
Boku no Hero Academia (2017) [tvdb4-305074]\eps 14-38.ext

Please consider donating if happy with the scanner and/or agent

**Comment by Cezus** [comment]
Thnx! This is something I can work with.

> Please consider donating if happy with the scanner and/or agent

You got yourself a coffee =]

**Comment by Cezus** [comment]
Okey, for now I am trying the "Anidb offset for the second series" way. If this fails I think that i will go for changing filenames.

How does dat work for the third season? I tried: 
"Boku no Hero Academia (2018) [anidb-13485-s01e-38]" and "Boku no Hero Academia (2018) [anidb-13485-s02e-25]"

The third season is not showing in Plex. This is in the log "Missing Episodes.html" I see:

`TVDBid: 305074 | Title: 'My Hero Academia' | Missing Episodes: ['s1e1-13', 's2e1', 's2e2', 's2e3', 's2e4', 's2e5', 's2e6', 's2e7', 's2e8', 's2e9', 's2e10', 's2e11', 's2e12', 's2e13', 's3e1-25']`

**Comment by ZeroQI** [comment]
"[anidb-13485-s01e-38]" seem fine
if you do not have duplicate files for this series episodes, remove the folder, re-scan, put ir back and re-scan.

**Comment by EndOfLine369** [comment]
@Cezus, note the 'Missing Episodes.html' entry you posted is from one of your tvdb/anidb2 tries. It will only go away if you delete it or actually complete the tvdb entry in plex.

**Comment by ZeroQI** [comment]
Any progress?
Please paste scanner logs and problem statement if issues are remaining

**Comment by Cezus** [comment]
> Any progress?
> Please paste scanner logs and problem statement if issues are remaining

Sorry for the late response and holding on =]
Your solution for removing the folder, re-scan, put it back did the trick!! Thank you 👍 

> @Cezus, note the 'Missing Episodes.html' entry you posted is from one of your tvdb/anidb2 tries. It will only go away if you delete it or actually complete the tvdb entry in plex.

Thnx for explaining!

**Comment by ZeroQI** [comment]
I have that so much un scanner devlopment.. It was a pain to develop but i am surprised suite few people use my scanner...
