### ISSUE TITLE
Illformed example command in README

### ISSUE THREAD

**Issue by Zennoe** [ZeroQI/Absolute-Series-Scanner#201]
In the section "Install / Update" https://github.com/ZeroQI/Absolute-Series-Scanner#install--update
The last line of the "Linux install script example" code block contains an invalid command.

Simply change `chmod 775 -R '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scanners'` to
 `chmod -R 775 '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scanners'`.

This is how the chmod command is descriped in the man pages as well. Otherwise you receive an error message stating that `-R` is not a directory.

**Comment by ZeroQI** [comment]
Thanks, updated the readme
