### ISSUE TITLE
Help with long running series with multiple Anidb entries

### ISSUE THREAD

**Issue by jbowwow02** [ZeroQI/Absolute-Series-Scanner#203]
Ok so I have all episodes of Gintama in one folder named in absolute ordering. I was trying to use the scanner to seperate new anidb entry as a season in plex (using anidb3) but I don't know how to go about doing that because when I did it the first time it only got metadata for the first 201 episodes (i.e. the first season of gintama.) I'd really appreciate some guidance here because I don't really know what I'm doing.

**Comment by ZeroQI** [comment]
Scanner logs needed as per readme troubleshooting steps.

**Comment by jbowwow02** [comment]
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2875707/Plex.Media.Scanner.log)
[Gintama.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2875719/Gintama.scanner.log)
[Gintama.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2875720/Gintama.filelist.log)

I couldn't find the library folder in DataItems (doesn't exist) so those logs are missing.

**Comment by ZeroQI** [comment]
I can see both your season numbering and your absolute numbering in the same folder 30 minutes apart
However the absolute numbering wasn't instructed to convert into seasons with tvdb2/tvdb3 or any absolute arrangement with tvdb4 mode...
"No forced id found in series folder name nor id file"

It therefore use the anidbid by default and metadata won't gather for other seasons as the folder doesn't follow anidb numbering nor does it follow tvdb numbering neither and since there is a single season, the agent doesn't know it is in tvdb absolute numbering mode...

Why didn't you name the absolute folder:
- "Gintama [tvdb3-79895]" for absolute numbering put automatically in tvdb seasons keeping the abs episode number
- "Gintama [tvdb2-79895]" for absolute numbering put automatically in tvdb seasons reseting at 1 the ep number each season
- "Gintama [tvdb4-79895]" for absolute numbering in any season arrangement (beware use the tvdb4 online saga season list by default)
- You could have created a tvdb3.id with "79895" inside but none were present when the scanner ran
- since the content of the folder didn't change, Plex will not register the change, you have to remove, rescan, put back, rescan. This is a limitation of Plex caching for scanners, only rescanning when a folder actually changed and renaming the folder doesn't change the content

**Comment by sven-7** [comment]
If you don't like how TVDB has the seasons, which splits the first series of Gintama (201 episodes) into roughly 50 episode seasons, then you'll need to use an anidb mode or a custom tvdb4 file of your own.

**Comment by jbowwow02** [comment]
I originally had the folder structured using tvdb's season structure but because of how irregular the naming is compared to the actual show it was a tad bit confusing (just like @sven-7 said) and decided to change it last night. At first I tried using the tvdb2 but then realised that wasn't how I actually wanted it to do. I tried the anidb modes and then got confused. 

So from what I understand so far I can use anidb3 or anidb4 modes like I want with the episodes in absolute order but each new season will have to be in a new folder with the anidb season id tagged into the folder name (e.g. Gintama. (2018) [anidb3-13917]), or alternatively use custom mapping using the tvdb4 file. Is that correct?

**Comment by ZeroQI** [comment]
tvdb2 and tvdb3 create the season for you from the absolute numbering, but will use them as well if already created.
tvdb4  take any arrangement but eps must stay with absolute numbering, but it will use the online tvdb4 mapping file that is meant to use seasons as sagas for long-running series
anidb3 and 4 are recent additions putting anidb sereis (seasons) as seasons instead or relying on thetvdb.

I believe you are correct
You can always follow strictly anidb numering and put all anidb sereis (seasons) in the same Plex colleciton...

**Comment by sven-7** [comment]
Exactly. I have Gintama on tvdb3, but here is an anidb4 example with Durarara!!

[Durarara!!.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2876127/Durarara.scanner.log)
[Durarara!!.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2876128/Durarara.filelist.log)


For Gintama you would want to do something like:

```
/Gintama/Gintama[anidb4-3468]
/Gintama/Gintama'[anidb4-8126]
```
etc....

**Comment by jbowwow02** [comment]
I still can't seem to get it to work right.
![image](https://user-images.githubusercontent.com/4137235/52969305-e08e8d00-33d5-11e9-8d4f-8aad8d57a91d.png)

I also tried anidb3 but that seemed to be worse. Season 1 seems to be missing episodes 151-201 in either case.

[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2876916/Plex.Media.Scanner.log)
[Gintama.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2876920/Gintama.filelist.log)
[Gintama.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/2876921/Gintama.scanner.log)

**Comment by ZeroQI** [comment]
You use anidb3 on Non-anidb numbered series... The files 151+ are converted to season 4 as explicitly indicated in scanner logs.

**Comment by jbowwow02** [comment]
As far as I can tell I don't think I'm doing anything wrong? All my files are named in absolute order using anidb and filebot and even in the filelist log all the episodes are labelled the same so I don't think the issue is with the naming but I will try renaming all files to tvdb absolute and try again if that is what you mean. I think with the previous attempt I did achieve what I was hoping for but I'm not too sure because of the "season 4" issue. 

Adding just the first season of Gintama to plex again using anidb4:
![image](https://user-images.githubusercontent.com/4137235/52970816-3154b480-33db-11e9-97bd-427012e86c28.png)

Regular anidb:
![image](https://user-images.githubusercontent.com/4137235/52971700-6dd5df80-33de-11e9-8e52-e7ae1c718d7b.png)

I didn't try anidb3 but anidb2 did return the same results as anidb4. Both tests were done after removing the folders from root, scanning, emptying trash, and then rescanning.

Another thing I did notice is despite having the [anidb2-3468] and [anidb4-3468] in the folder title it did scan into plex as [tvdb-79895].

**Comment by sven-7** [comment]
For each season/anidb ID in anidb3 mode, you need to follow the anidb numbering.  Each season will restart with 1 as the first episode. 

If you want to maintain the absolute numbering that tvdb uses 1-350+, I'd suggest converting everything to tvdb4 and make yourself a custom mapping file to do the seasons how you want.

```
Gintama - 1-201
Gintama' - 1-51
Gintama` (2012) - 1-13
Etc.
```

**Comment by jbowwow02** [comment]
Yeah I might do that but most likely I'll just go back to the original tvdb mode. I'm still not sure why Gintama season 1 randomly breaks the last 51 episodes as season 4 on any anidbX modes except for anidb mode itself.

**Comment by sven-7** [comment]
That's a TVDB thing. For long-running shows they'll break them up into arcs or seasons sometimes.  Because 201 episodes is a really long season, they opted to break it up by airing year for the first Gintama series.  All of the subsequent ones didn't require that, thus, the first one gets split up into four seasons.  

You need to do one of a few things:

Mode:  TVDB3
- Episode Numbering:  TVDB Absolute (1-367)
- Result 10 seasons
- Episodes will be continuously numbered (will not restart at one each season)

Mode:  TVDB4 (added in 3d51773)
- Episode Numbering:  TVDB Absolute (1-367)
- Result 7 seasons
- Episodes will be continuously numbered (will not restart at one each season)

Mode:  AniDB3
- Episode Numbering:  AniDB for each series of Gintama
```
Example:
Gintama - 1-201
Gintama' - 1-51
Gintama` (2012) - 1-13
```
- Result 7 seasons
- Episode numbering will restart from 1 at the beginning of each season

**Comment by jbowwow02** [comment]
Thank you @sven-7 and @ZeroQI for the support. I still can't seem to figure out what I'm doing wrong so I resorted to using custom tvdb4 mappings:

```
  <anime tvdbid="79895" name="Gintama">
    01|001|201|Gintama
    02|202|252|Gintama`
    03|253|265|Gintama` (2012)
    04|266|316|Gintama (2015)
    05|317|328|Gintama.
    06|342|353|Gintama. (2017)
    07|354|367|Gintama. (2018)
  </anime>
```

But after seeing the updated online mapping I think I'll remove mine and use that since it does the same job (thanks you for that btw). 

I'll close the issue since it seems to be something I'm doing wrong but I just want to ask what exactly is it that I've done wrong in the naming that makes the series get named and act that way? (Just so future additions I do to my library do not result in the same behaviour.) 
Do you get the same behaviour with your gintama episodes when 1-201 are named in absolute order and scanned using anidb3 modes?

**Comment by sven-7** [comment]
I'll see if I can replicate in a test library and let you know.

**Comment by jbowwow02** [comment]
Actually I think there might be wrong with my setup. I had just updated the saekano files on my system and readded them to my plex and noticed this:

![image](https://user-images.githubusercontent.com/4137235/53045660-333e7680-34b4-11e9-9c98-8db47a5dad1c.png)

Couple things off here. Firstly this is using regular tvdb mode, nothing special the files are labelled with season numbers tagged onto them but the show autocorrects the name to flat for whatever reason.
![image](https://user-images.githubusercontent.com/4137235/53046002-05a5fd00-34b5-11e9-8279-e4f7bc06f1cb.png)

Secondly it pulls the date as 2017 which was the year flat was released, but season 1 came out in 2015. I'm assuming the scanner is weirdly mapping stuff right now. Will do a clean install of plex tomorrow and update as it is quite late right now.

**Comment by ZeroQI** [comment]
The metadata agent choose the metadata like year and title, not the scanner.

**Comment by sven-7** [comment]
Note - your mapping is missing 329-341. Correct below:

```
  <anime tvdbid="79895" name="Gintama">
    01|001|201|Gintama
    02|202|252|Gintama (2011)
    03|253|265|Gintama (2012)
    04|266|316|Gintama (2015)
    05|317|328|Gintama. (2017)
    06|329|353|Gintama. (2017-2018)
    07|354-367|Gintama (2018)
  </anime>
```

Also - yes, for me anidb3 mode seems to be wrong/broken with Gintama. It's definitely chopping off the first 51 episodes.  I'm very certain I set mine up correctly and it's all over the place.  It could be the relational graph complexity of Gintama that is causing this.  It's not as straightforward as other shows, so I think it may just be impossible given it's structure on AniDB.  I think your best option is to stick with TVDB3 (and what TVDB says) or TVDB4.

**Comment by jbowwow02** [comment]
Not sure why I used 342 instead of 329 lol. Thanks for checking I really appreciate it. @ZeroQI right I don't know why I posted that here lol. Thanks for the help @ZeroQI and @sven-7, I really appreciate it.
