### ISSUE TITLE
Scanner is broken with Latest Plex pass updates

### ISSUE THREAD

**Issue by Hiren-Z** [ZeroQI/Absolute-Series-Scanner#204]
After updating to Plexpass versions 15.x the scanner would not function giving errors:

Feb 10, 2019 02:36:25.584 [0x14e598e7c740] DEBUG - Directory had 13 files, database had 0 files, can't skip.
Feb 10, 2019 02:36:25.597 [0x14e598e7c740] ERROR - No module in Absolute Series Scanner
Feb 10, 2019 02:36:25.597 [0x14e598e7c740] ERROR - Error in Python: Looking up module: Traceback (most recent call last): File "/config/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 20, in <module> from lxml import etree # fromstring ImportError: libexslt.so.0: cannot open shared object file: No such file or directory

I am running in the binhex/plexpass docker (https://hub.docker.com/r/binhex/arch-plexpass) 

Last tested broken build is plex1.15.1.707-1-01.  Reverting to 1.14.1.5488-1-01 fixs the scanner.

**Comment by ZeroQI** [comment]
binhex/plexpass docker changed something in last version, and i am unsure i can fix it scanner side but can collaborate to fix the issue, raised https://github.com/binhex/arch-plexpass/issues/11

import line 20 "from lxml import etree" fail so there is some dependency issues within Python so the following should mitigate the issue if not using forced id mode or it will fail to recognise lxml.etree function...
```
try:                 from lxml import etree
except ImportError:  pass
```
You may need to adjust your plex install location accordingly to get around the distribution version specific issue (hence likelly not scanner dependent):
`sys.path.append("/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Scanners/Series")
`

**Comment by Hiren-Z** [comment]
Was checking log files and saw these.  Not sure if they are related though.

2019-02-26 15:54:54,639 DEBG 'plexmediaserver' stderr output:
AniDB:307: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.

2019-02-26 15:54:55,068 DEBG 'plexmediaserver' stderr output:
AnimeLists:41: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.

**Comment by ZeroQI** [comment]
Unrelated. try refreshing in 24h when the ban is revoked

**Comment by ZeroQI** [comment]
Please check when new Plex version released, update it and report

**Comment by Hiren-Z** [comment]
Seems to work on a fresh Windows plexpass installation. However doesn't work inside the docker.

Ill spin up several vms later tonight/tomorrow and test in different environments to see what I can figure out.

**Comment by Hiren-Z** [comment]
Using the latest binhex plexpass docker returns:

Error in Python: Looking up module:
Traceback (most recent call last):
File "/config/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 20, in <module>
from lxml import etree # fromstring
ImportError: libexslt.so.0: cannot open shared object file: No such file or directory

Using the latest binhex plexstandard docker returns:

Error in Python: Looking up module:
Traceback (most recent call last):
File "/config/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 20, in <module>
from lxml import etree # fromstring
ImportError: libexslt.so.0: cannot open shared object file: No such file or directory

Using the linuxserver docker (unraid default) returns:
expected results. 


Issue appears to be in the binhex repositories.  All repos are pulling plex 1.15.* .

**Comment by Hiren-Z** [comment]
https://github.com/binhex/arch-plexpass/issues/11#issuecomment-474943732

Opening the dockers terminal and running "pacman -S libxslt --noconfirm" then rebooting the docker fixs the issue.
