### ISSUE TITLE
how to install ASS on Synology?

### ISSUE THREAD

**Issue by sosbxx0928** [ZeroQI/Absolute-Series-Scanner#209]
Soory im a newbie but how can i install  ASS on Synology? I know Synology is Lunix based system but I haven't used Linux before. So any advice? Many thanks.

**Comment by ZeroQI** [comment]
Plex folder for synology is given in the readme
Save into [...]/Plex Media Server/Scanners/Series/Absolute Series Scanner.py Note:
"Scanners" and "Series" folder are not created by default and will need to be created.
"Scanners" folder will be at the same level as "Plug-in Support" folder (in other words the same parent directory)
