### ISSUE TITLE
Some Episodes fail to import

### ISSUE THREAD

**Issue by xrsxj** [ZeroQI/Absolute-Series-Scanner#210]
Some episodes fail to import since the most recent commit 2735cff2ab0e612fab0d7edb609cb16b46fc4d9b, here is the error when scanning:

`Apr 10 11:09:48 plex bash[23139]: Error in Python: Running scanner:
Apr 10 11:09:48 plex bash[23139]: Traceback (most recent call last):
Apr 10 11:09:48 plex bash[23139]:   File "/config/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 981, in Scan
Apr 10 11:09:48 plex bash[23139]:     for entry in standard_holding + unknown_holding:  add_episode_into_plex(media, *entry)
Apr 10 11:09:48 plex bash[23139]:   File "/config/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 378, in add_episode_into_plex
Apr 10 11:09:48 plex bash[23139]:     if 'episodeoffset'     in mappingList and is_integer(mappingList['episodeoffset'    ]):  ep, ep2 = ep+int(mappingList['episodeoffset']), ep2+int(mappingList['episodeoffset']) if ep2 else None
Apr 10 11:09:48 plex bash[23139]:   File "/config/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 147, in is_integer
Apr 10 11:09:48 plex bash[23139]:     def is_integer(string):  return isdigit(string) or len(string)>1 and string.startswith("-") and string[1:].isdigit()
Apr 10 11:09:48 plex bash[23139]: NameError: global name 'isdigit' is not defined`

I pushed the scanner back before that commit and all is working again.

For reference:

This was successfully imported after commit:
/mnt/user/Anime/Bakumatsu։ Ren'ai Bakumatsu Kareshi Gaiden - Crisis [anidb2-14548]/(HorribleSubs)Bakumatsu_Renai_Bakumatsu_Kareshi_Gaiden_-_Crisis_-_03_[anidb2-14548]_(1080p).mkv

This was not:
/mnt/user/Anime/Tate no Yuusha no Nariagari [anidb2-13246]/(HorribleSubs)Tate_no_Yuusha_no_Nariagari_-_14_[anidb2-13246]_(1080p).mkv

**Comment by ZeroQI** [comment]
Perfect report, indeed a bug, the error message given allowed to pinpoint the issue, included test filenames.
note: [anidb2-13246] in the filename is not processed in any way

**Comment by xrsxj** [comment]
Thanks, glad it helped.  I use ShokoServer to do the import and sorting of new files it doesn't allow me to specify folder names, but i can customize the file names.  So i use the file names in a script that sorts through whats been processed by Shoko and moves it to another set of folders that include the anidb2 id in the folder name.  Thanks!
