### ISSUE TITLE
unable to grab any metadata from MyAnimeList

### ISSUE THREAD

**Issue by hexx1001** [ZeroQI/Absolute-Series-Scanner#211]
I am able to get metadata from AniDB and TheTVDB. However, MyAnimeList choosing does not get any data. Specifically looking for using rating and content rating from MyAnimeList. Any suggestions? Thank you.

**Comment by ZeroQI** [comment]
Metadata is the agent responsability, as explained first in the readme..
MyAnimeList api i used to gather data hasn't been working for months.
