### ISSUE TITLE
Mobile Suit Gundam: Iron Blooded Orphans not showing

### ISSUE THREAD

**Issue by snoopy82481** [ZeroQI/Absolute-Series-Scanner#213]
I have attempted multiple variations of getting this series to show up with Season 1 and Season 2 nested folders.  Scanner finds the folder, but doesn't add them to PLEX. I'm not sure what I am doing wrong with it. Below is my folder structure, and I'll include all the logs I have found. Let me know if I'm missing something
[Anime.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3158753/Anime.zip)
[_Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3158758/_Logs.zip)

Mobile Suit Gundam Iron-Blooded Orphans
- Season 1
- Season 2

**Comment by ZeroQI** [comment]
I can see in agent logs s01e01-25 were detected without season folders but with season folders it adds both seasons episodes as season 0 at the right episode number. That does not qualify as "doesn't add them to PLEX.". If really tthey are not added, that's a plex issue, do the plex dance...

The naming of the files is atrocious. Two episodes numbers separated by a dot... why????

tried to search "Mobile.Suit.Gundam.Iron-Blooded.Orphans.S02E01.026.HDTV-1080p-AnimeRG.mkv" but no match... Shouldn't the nump have these naming convention:
- /Season 01/[AnimeRG] MSG - Iron-Blooded Orphans - 01 [720p] [x265] [pseudo].mkv

Please link to the dump that released the filenames like that.

**Comment by snoopy82481** [comment]
I added it through Sonarr and it renamed them to that. I don't have the original anymore, as it was taking space on my SSD, since Sonarr downloads to downloads folder, then copies them over to the next destination.

**Comment by snoopy82481** [comment]
I appologize, the above statement is false. I find the original source I got it from. Then had Sonarr rename it.  I'm going to grab it again, see if it will found by PLEX and the scanner and let you know.

**Comment by ZeroQI** [comment]
it renamed using dot as spacer ? If you put spaces instead it should work BUT since the folder content hasn't changed, plex might not re-scan the folder... You might have to remove, re-scan, put back, re-scan...

**Comment by snoopy82481** [comment]
You sir are a genius. I'm sorry I wasted your time, I ended up just renaming them, putting spaces and removing the absolute number.

**Comment by ZeroQI** [comment]
the issue is dots between the two numbers. replace dots with spaces and you are good
You can keep the abs number in brackets and it won't mess up anything "title s01e24 [24] ...".
both in clear might trigger weird side effects as i count each numbers to figure out ep numbers so double numbers could give bugs but in brackets no issue
