### ISSUE TITLE
Dots in season folder name

### ISSUE THREAD

**Issue by icemouton** [ZeroQI/Absolute-Series-Scanner#215]
So I just noticed a major Issue I was having without realising it.
Most of my automated content is in folders as follows:
SHOW\
Season.00
Season.01
Season.0...

But for the content I manage manually I didn't respect that (which is most of my anime).. but I juste figured out that ASS does not consider the name "Season.XX" to be valid and considers every episode to be in season 1. .. 
Is there any way to have ASS support it instead of me having to rename all my media ?
The solution I used was to change from Season.01 to "Season - 01" and that worked immediatly.

**Comment by ZeroQI** [comment]
Yes there is, but:
- you have to indicate which program use this atrociously bad naming convention so i can shame you personally
- try to insert '\.' in regex line 49 and report if it work: cic(r'^(Season|Series|Book|Saison|Livre|S)[ _\-\.]*(?P<season>\d{1,2})'),                                                                                      # Season / Series / Book / Saison / Livre / S
- you might have to change the folder content to re-scan the folder, as plex doesn't rescan folders that didn't change, making Plex scanner development a PITA
- Are you saying as a web developer, my code was obscure to figure out?

**Comment by ZeroQI** [comment]
Please try to insert '.' in regex line 49 and report if it work: 
`cic(r'^(Season|Series|Book|Saison|Livre|S)[ _-.]*(?P\d{1,2})'), # Season / Series / Book / Saison / Livre / S`

**Comment by icemouton** [comment]
Well I'm to blame here, I had my folders named like that before and gave that pattern to sickbeard... I had some issues with dataloss linked to spaces in filenames in the past (think early 2000s) and have adopted a policy to avoid spaces and replace them with dots.. which I no longer really do as most modern filesystems allow spaces in filenames. 

Then I didn't open the source code to go check the regex, which I should have lol.. I was just excited to have finally found the source, that I didn't think of looking into ways to fix it myself. 

Will try it tonight and let you know if that fixed it.

**Comment by ZeroQI** [comment]
So... did it work?

**Comment by ZeroQI** [comment]
So... did it work?

**Comment by ZeroQI** [comment]
support dots (regex '\.').
Closing. update if doesn't fix update this bug report
