### ISSUE TITLE
Incompatibility with new Plex version

### ISSUE THREAD

**Issue by konigprinz** [ZeroQI/Absolute-Series-Scanner#217]
I had some issuis installing it on the new version.
I just downgraded to version 1.6.1.3722-4955e31cf and it all seems to work perfect again.
The download link can be found here:

https://downloads.plex.tv/plex-media-server/1.6.1.3722-4955e31cf/Plex-Media-Server-1.6.1.3722-4955e31cf.exe

**Comment by ZeroQI** [comment]
Please paste error message
libxslt issue under windows with latest Plex version, dunno how to vix under latest version, hopefully will be fixed with next version

**Comment by konigprinz** [comment]
I didn't got any message back, when i was trying to install the plug-in it wouldn't show as an available option in plex.
I was using windows 10.

**Comment by EndOfLine369** [comment]
Version 1.15.6.1079 running just fine on my Windows 10.

**Comment by GlassedSilver** [comment]
> I didn't got any message back, when i was trying to install the plug-in it wouldn't show as an available option in plex.
> I was using windows 10.

Make sure you unzipped Hama.bundle-master.zip.
Then you'll have a folder named Hama.bundle-master.
Rename that folder to Hama.bundle.

I once messed up by renaming the folder on my Mac, renaming through bash in Linux did work much better. In case any Mac users are reading this and who want to deploy on a Linux-based system like unRAID.

**Comment by ZeroQI** [comment]
@konigprinz You didn't confirm faulty version number so we don't know when new version comes out if it has the issue or not. please document. Confirm if it was Version 1.15.6.1079

**Comment by konigprinz** [comment]
Okay, to give everyone a clear picture of the situation:

At first I didnt know how to install the library libxslt and i didnt install the scanner in the first place.
After mailing with @ZeroQI, he told me to downgrade and try it. And that just works.
Now I just installed all updates (now its Version 1.15.6.1079) and it works fine as well.

So my initial problem was just not knowing how to install that library thingy, but aparently you dont have to install that on a Windows OS.

**Comment by ZeroQI** [comment]
Correct, Plex does that.
If latest version of Plex works, then the scanner is working.
If that is not the version you tried Plex fixed it
If it was, you had a local issue on your PC.
