### ISSUE TITLE
Grouping folders skip , unless single series folder ### [return]

### ISSUE THREAD

**Issue by clowncracker** [ZeroQI/Absolute-Series-Scanner#221]
[Per @ZeroQI](https://forums.plex.tv/t/rel-http-anidb-metadata-agent-hama/40470/1923?u=clowncracker) 

>Now it exit but should let single folder in grouping folder pass so your folder structure trigger a bug
**Grouping folders skip , unless single series folder ### [return]**

`No forced id found in series folder name nor id file`
`-------------------------------------------------------------------------------------------------------------------------------------------------------------`
`misc_count: {'': 1}`
`misc_words: []`
`-------------------------------------------------------------------------------------------------------------------------------------------------------------`
`[no files detected] #1`
`=============================================================================================================================================================`
`Plex scan end: 2019-06-24 19:52:43,389421`
`grouping folder? dirs: ['/anime/Darker Than Black/Darker Than Black [tvdb-80042]/Season 2', '/anime/Darker Than Black/Darker Than Black [tvdb-80042]/Season 1', '/anime/Darker Than Black/Darker Than Black [tvdb-80042]/Specials'], reverse_path: ['Darker Than Black [tvdb-80042]', 'Darker Than Black'] [return]`
`=============================================================================================================================================================`
`Library: 'no valid X-Plex-Token.id', root: '/anime', path: 'Darker Than Black/Darker Than Black [tvdb-80042]/Season 1', files: '26', dirs: '0'`
`Plex scan start: 2019-06-24 19:52:43,403819`
`=============================================================================================================================================================`
`### Grouping folders skip , unless single series folder ### [return]`
`=============================================================================================================================================================`
`Library: 'no valid X-Plex-Token.id', root: '/anime', path: 'Darker Than Black/Darker Than Black [tvdb-80042]/Season 2', files: '12', dirs: '0'`
`Plex scan start: 2019-06-24 19:52:43,411119`
`=============================================================================================================================================================`
`### Grouping folders skip , unless single series folder ### [return]`
`=============================================================================================================================================================`
`Library: 'no valid X-Plex-Token.id', root: '/anime', path: 'Darker Than Black/Darker Than Black [tvdb-80042]/Specials', files: '4', dirs: '0'`
`Plex scan start: 2019-06-24 19:52:43,417023`
`=============================================================================================================================================================`
`### Grouping folders skip , unless single series folder ### [return]`
`=============================================================================================================================================================`
`Library: 'no valid X-Plex-Token.id', root: '/anime', path: 'Darker Than Black', files: '0', dirs: '1'`

[Darker Than Black.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3327286/Darker.Than.Black.scanner.log)

**Comment by ZeroQI** [comment]
Uploaded new version, worked for me
Please update scanner, do plex dance then report and close if resolved
