### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by Salvora** [ZeroQI/Absolute-Series-Scanner#222]
I am trying to build a naming convention that will not fail with ASS. I am using HAMA with ASS. Could you please give some advice? My current convention is below. How can I further improve this? 

-	Clannad Series
   o	Clannad 01-22 + Bonus 2 Eps + Extras (2007) [Blu-Ray 1920x1080 h264 AAC] [MII] [SS-Eclipse] [THORA]
                  	Clannad - 01 [Blu-Ray 1920x1080 h264 AAC] [520B584E] [MII] [SS-Eclipse] [THORA].mkv
                  	….
                  	…
                  	Clannad - 24 [Blu-Ray 1920x1080 h264 AAC] [7F919814] [MII] [SS-Eclipse] [THORA].mkv
                  	Clannad - ED [Blu-Ray 1920x1080 h264 AAC] [B90E3F82] [MII] [SS-Eclipse] [THORA].mkv
                  	Clannad - OP [Blu-Ray 1920x1080 h264 AAC] [DAAF6555] [MII] [SS-Eclipse] [THORA].mkv
   o	Clannad After Story 01-22 + Bonus EP + Recap + Extras (2008) [Blu-Ray 1920x1080 Hi-10P h264 FLAC] [Doki]
                  	Clannad After Story - 01 [Blu-Ray 1920x1080 Hi-10P h264 FLAC] [1AA8D908] [Doki].mkv
                  	…
                  	..
                  	.
   o	Gekijouban Clannad Movie (2007) [DVD 720x480 h264 Vorbis] [SS-Eclipse]
                  	Gekijouban Clannad - 01 [DVD 720x480 h264 Vorbis] [FDB42A85] [SS-Eclipse].mkv

**Comment by ZeroQI** [comment]
File naming is ok mostly
- Gekijouban Clannad Movie (2007) [DVD 720x480 h264 Vorbis] [SS-Eclipse]/Gekijouban Clannad Movie (2007) [DVD 720x480 h264 Vorbis] [FDB42A85] [SS-Eclipse.mkv

series naming need all not part of series name in square braquets as it will disturb search algorythm and not reach 80% match and be unmatched
- Clannad [01-22 + Bonus 2 Eps + Extras (2007)] [Blu-Ray 1920x1080 h264 AAC] [MII] [SS-Eclipse] [THORA]

**Comment by purposelycryptic** [comment]
I've bee using a similar naming convention to yours, minus the _Collection_ folder at the root (Since paths get too long as is), video codec, the Sub/Raw source in remuxes (like [MII]'s), and, well, stuff like this: `01-22 + Bonus 2 Eps + Extras (2007)`, which will confuse any scanner unless it's scan-blocked (which, for ASS, involves placing it in Square Brackets, as ZeroQI already mentioned), and it has worked very well for me with ASS and HAMA for well over 2.000 series.

It is also easy to use with auto-renaming tools like Filebot and AniAdd (Although _Collection_ folders require some manual moving). I'm not sure if you're using an OS with a hard path limit, but the win32 256-character limit can be a real pain for organizing anime (Like this season's "Uchi no Ko no Tame Naraba, Ore wa Moshikashitara Maou mo Taoseru Kamo Shirenai." - that's 80 characters right there, just in the title!).

Anyway...

This is what my Clannad folders look like (Don't have the movie anymore, since the different art and protagonist VA really disagreed with me):
```
Clannad [Doki] [BD, 1080p, FLAC]\
	Clannad - 01 [Doki] [BD, 1080p, FLAC] [4A6B18D8].mkv
	Clannad - 02 [Doki] [BD, 1080p, FLAC] [89B3DC80].mkv
	Clannad - 03 [Doki] [BD, 1080p, FLAC] [8B5D01CE].mkv
	Clannad - 04 [Doki] [BD, 1080p, FLAC] [84FA1A8D].mkv
	Clannad - 05 [Doki] [BD, 1080p, FLAC] [B74A12D6].mkv
	Clannad - 06 [Doki] [BD, 1080p, FLAC] [48ADAF35].mkv
	Clannad - 07 [Doki] [BD, 1080p, FLAC] [B54F54EE].mkv
	Clannad - 08 [Doki] [BD, 1080p, FLAC] [8EB55453].mkv
	Clannad - 09 [Doki] [BD, 1080p, FLAC] [AD88AD7D].mkv
	Clannad - 10 [Doki] [BD, 1080p, FLAC] [6F295AF2].mkv
	Clannad - 11 [Doki] [BD, 1080p, FLAC] [27BB5485].mkv
	Clannad - 12 [Doki] [BD, 1080p, FLAC] [D159F1FE].mkv
	Clannad - 13 [Doki] [BD, 1080p, FLAC] [F9293611].mkv
	Clannad - 14 [Doki] [BD, 1080p, FLAC] [65BE7F0B].mkv
	Clannad - 15 [Doki] [BD, 1080p, FLAC] [F814B93D].mkv
	Clannad - 16 [Doki] [BD, 1080p, FLAC] [E23AD666].mkv
	Clannad - 17 [Doki] [BD, 1080p, FLAC] [01721131].mkv
	Clannad - 18 [Doki] [BD, 1080p, FLAC] [A76F6C09].mkv
	Clannad - 19 [Doki] [BD, 1080p, FLAC] [F37818B6].mkv
	Clannad - 20 [Doki] [BD, 1080p, FLAC] [21A432B0].mkv
	Clannad - 21 [Doki] [BD, 1080p, FLAC] [F31830F4].mkv
	Clannad - 22 [Doki] [BD, 1080p, FLAC] [84EC5DF4].mkv
	Clannad - ED1 [Doki] [BD, 1080p, FLAC] [6D115AD8].mkv
	Clannad - OP1 [Doki] [BD, 1080p, FLAC] [F8915248].mkv
	Clannad - SP1 [Doki] [BD, 1080p, FLAC] [86EFA80C].mkv
	Clannad - SP2 [Doki] [BD, 1080p, FLAC] [9BE3B851].mkv
	Clannad - T1 [Doki] [BD, 1080p, FLAC] [014DAE13].mkv
	Clannad - T2 [Doki] [BD, 1080p, FLAC] [6A223458].mkv
	Clannad - T8 [Doki] [BD, 1080p, FLAC] [B3C8B955].mkv

Clannad - After Story [Doki] [BD, 1080p, FLAC]\
	Clannad - After Story - 01 [Doki] [BD, 1080p, FLAC] [1AA8D908].mkv
	Clannad - After Story - 02v2 [Doki] [BD, 1080p, FLAC] [72E85145].mkv
	Clannad - After Story - 03 [Doki] [BD, 1080p, FLAC] [A8381124].mkv
	Clannad - After Story - 04 [Doki] [BD, 1080p, FLAC] [366134EF].mkv
	Clannad - After Story - 05 [Doki] [BD, 1080p, FLAC] [CCFA914E].mkv
	Clannad - After Story - 06 [Doki] [BD, 1080p, FLAC] [AC7C8353].mkv
	Clannad - After Story - 07 [Doki] [BD, 1080p, FLAC] [83AE908A].mkv
	Clannad - After Story - 08 [Doki] [BD, 1080p, FLAC] [5CE1A998].mkv
	Clannad - After Story - 09 [Doki] [BD, 1080p, FLAC] [32BF2A64].mkv
	Clannad - After Story - 10 [Doki] [BD, 1080p, FLAC] [228CD257].mkv
	Clannad - After Story - 11 [Doki] [BD, 1080p, FLAC] [7606618F].mkv
	Clannad - After Story - 12 [Doki] [BD, 1080p, FLAC] [0FF3DFBC].mkv
	Clannad - After Story - 13 [Doki] [BD, 1080p, FLAC] [246D2FD2].mkv
	Clannad - After Story - 14 [Doki] [BD, 1080p, FLAC] [B9B46085].mkv
	Clannad - After Story - 15 [Doki] [BD, 1080p, FLAC] [F1DCBDF7].mkv
	Clannad - After Story - 16 [Doki] [BD, 1080p, FLAC] [5EA74032].mkv
	Clannad - After Story - 17 [Doki] [BD, 1080p, FLAC] [3C326FA9].mkv
	Clannad - After Story - 18 [Doki] [BD, 1080p, FLAC] [E79B5E57].mkv
	Clannad - After Story - 19 [Doki] [BD, 1080p, FLAC] [F10A608D].mkv
	Clannad - After Story - 20 [Doki] [BD, 1080p, FLAC] [BF61AC00].mkv
	Clannad - After Story - 21 [Doki] [BD, 1080p, FLAC] [5E153762].mkv
	Clannad - After Story - 22 [Doki] [BD, 1080p, FLAC] [C5180E53].mkv
	Clannad - After Story - ED1a [Doki] [BD, 1080p, FLAC] [DB4AE844].mkv
	Clannad - After Story - ED1b [Doki] [BD, 1080p, FLAC] [A279C28D].mkv
	Clannad - After Story - ED1c [Doki] [BD, 1080p, FLAC] [350B84E7].mkv
	Clannad - After Story - ED1d [Doki] [BD, 1080p, FLAC] [A06D04E0].mkv
	Clannad - After Story - OP1 [Doki] [BD, 1080p, FLAC] [189FFBE1].mkv
	Clannad - After Story - SP1 [Doki] [BD, 1080p, FLAC] [BE34D782].mkv
	Clannad - After Story - SP2 [Doki] [BD, 1080p, FLAC] [C7E3C7B0].mkv
	Clannad - After Story - SP3 [Doki] [BD, 1080p, FLAC] [5F96064C].mkv
```

And movies like this:
```
Gekijouban Cardcaptor Sakura [Coalgirls] [BD, 1080p, FLAC]\
	Gekijouban Cardcaptor Sakura - 01 - Complete Movie [Coalgirls] [BD, 1080p, FLAC] [CDF7F555].mkv
```

Not sure if that ended up being of any help, just saw your issue in my feed, and figured I'd offer my $0.02.

**Comment by Salvora** [comment]
Thanks for the help. It worked for some. I had to move so I have re-organized all my archive.
- Clean Install Plex, HAMA, ASS
- Rename all the files as below:
```
Archive Folder/
        Anime Title [1st ep - Last ep] (Year) [Source Res Codec] [Group] [anidb-xxxxx]
                Anime Title - Ep number [Source Res Codec] [CRC] [Group].mkv
                Anime Title - Ep number [Source Res Codec] [CRC] [Group].mkv
                ....
                ....

```
I tried to force ASS by using [anidb-xxxxx] but it doesnt seem to work.
It found some matches, skipped lots of files, created duplicates under the same ep no etc...
The weird thing is I cannot find some files. ASS didnt detect them at all.
Where have I gone wrong?
Below is the some examples for the folder and file names
```
Aoi Sekai no Chuushin de [01-03] (2012) [Web 1920x1080 h264] [HorribleSubs] [anidb-9091]
   Aoi Sekai no Chuushin de - 01 [Web 1920x1080 h264] [D5378B0A] [HorribleSubs].mkv
   ....
   ....
Aquarion Logos [01-26] (2015) [Web 1920x1080 h264] [HorribleSubs] [anidb-11150]
   Aquarion Logos - 01 [Web 1920x1080 h264] [962D972E] [HorribleSubs].mkv
   ....
   ....
Capeta [01-52] (2005) [DVD 640x480 h264] [A-E&Saizen] [anidb-3463]
   Capeta - 01 [DTV 640x480 XviD] [7AFBCA50] [A-E].mkv
   ....
   ....
```

**Comment by ZeroQI** [comment]
Filename look ok
The scanner use cache. if you rename the folder but the content doesn't change it will not run again... Do the Plex Dance to fix...

**Comment by Salvora** [comment]
> 
> 
> Filename look ok
> The scanner use cache. if you rename the folder but the content doesn't change it will not run again... Do the Plex Dance to fix...

Plex dance didn't fix it.
Instead deleted the library and readded it.

The main folder has total 145 subfolders all with different titles. So, Plex library should also list 145 different series.
After adding the new library, it started scanning and successfully scanned the 145 titles, however, after that it started deleting or merging the files. Now, the scan has finished and it lists 52 series in the library page.

**Comment by ZeroQI** [comment]
it should list all 145 unless they have the same unique id, in this case Plex will merge them
You need to pick a merged serie, check scanner log and agent search logs in hama agent data folder > logs

**Comment by Salvora** [comment]
Allright, he is what I did.
- uninstall plex to clean up the folders
- delete everything in the Plex volume in my NAS
- clean install plex Version 1.16.3.1402
- Install ASS and HAMA
- Break down the Anime folder so it is easy to track logs. Now there are only 9 folders in the folder. The rest I will add them later after figuring this out.
- Create library and point to folder

Out of these 9 folders with unique anidb ids. It only detected 6. It didn't download any thumbnails or anything.
When I check the logs at \Plex\Library\Application Support\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs,
I see all 9 folders are detected with every folder their own .filelist and .scanner logs.

However, it also produced "_unknown_folder.agent-search" and "_unknown_folder.agent-update" logs. I believe the problem is there.
There are some lines there mostly:
root not found
path:    _unknown_folder
Library access denied

Should I post the whole text?

**Comment by ZeroQI** [comment]
If you create a Plex token I'd file it will be able to put a log per series in a subfolder with the library name and make things easier...

**Comment by Salvora** [comment]
Sent the plex token to your mail.

**Comment by ZeroQI** [comment]
Don't... the plex token allow to access your plex server... do not give it to anybody
The readme indicates to put it 
`X-Plex-Token.id file in 'Plex Media Server' folder with your token inside to have logs saved per library. See this link to find your token value: https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token`

**Comment by Salvora** [comment]
ehh, no problem I can generate new token later.

- I have put this X-Plex-Token.id file in my "Plex Media Server" with my token inside.
- Restarted Plex
- deleted the library with a different name
- re-added the library with these 9 files and with a new name
- when it was scanning, it created a log subfolder with the lib name in Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\
-  I see no problem with the logs. It detects all nine titles in the logs. But library shows only 6 titles so it merged some files.
- It didnt create this log in the [...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Library_name/Logs/root_folder_name.scanner.log

Here are the logs

[_unknown_folder.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469397/_unknown_folder.agent-update.log)
[_unknown_folder.agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469398/_unknown_folder.agent-search.log)
[_root_-volume1-Video-Anime-Archive.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469404/_root_-volume1-Video-Anime-Archive.scanner.log)
[_root_-volume1-Video-Anime-Archive.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469405/_root_-volume1-Video-Anime-Archive.filelist.log)
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469384/Plex.Media.Scanner.log)

**Comment by ZeroQI** [comment]
That means the scanner did the job and the unique id given by search function is the same for some series and Plex group them together. You need to check which series have the wrong I'd and give me these series #.search.logs...

**Comment by Salvora** [comment]
here are the series logs of all 9 of them.
It is all jumbled for me in the library. For example, there is no title with "Aoi Sekai no Chuushin de".  It merged with the eps of "Air Gear Kuro no Hane to Nemuri no Mori - Break on the Sky". All eps have double files like below. Let me know if you need anything else. I believe there is something wrong with the forced id function.

Files

    Delete Files
    /volume1/Video/Anime/Archive/Aoi Sekai no Chuushin de [01-03] (2012) [Web 1920x1080 h264] [HorribleSubs] [anidb-9091]/Aoi Sekai no Chuushin de - 03 [Web 1920x1080 h264] [7510C2EB] [HorribleSubs].mkv

    Delete Files
    /volume1/Video/Anime/Archive/Air Gear Kuro no Hane to Nemuri no Mori - Break on the Sky [01-03] (2010) [DVD 848x480 h264] [Tasty] [anidb-7669]/Air Gear Kuro no Hane to Nemuri no Mori - Break on the Sky - 03 [DVD 848x480 h264] [C26D17D7] [.mkv


[Aoki Hagane no Arpeggio Ars Nova [01-12] (2013) [Blu-ray 1920x1080 h264] [MD] [anidb-9905].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469880/Aoki.Hagane.no.Arpeggio.Ars.Nova.01-12.2013.Blu-ray.1920x1080.h264.MD.anidb-9905.scanner.log)
[Aoki Hagane no Arpeggio Ars Nova [01-12] (2013) [Blu-ray 1920x1080 h264] [MD] [anidb-9905].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469881/Aoki.Hagane.no.Arpeggio.Ars.Nova.01-12.2013.Blu-ray.1920x1080.h264.MD.anidb-9905.filelist.log)
[Aoi Sekai no Chuushin de [01-03] (2012) [Web 1920x1080 h264] [HorribleSubs] [anidb-9091].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469882/Aoi.Sekai.no.Chuushin.de.01-03.2012.Web.1920x1080.h264.HorribleSubs.anidb-9091.scanner.log)
[Aoi Sekai no Chuushin de [01-03] (2012) [Web 1920x1080 h264] [HorribleSubs] [anidb-9091].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469883/Aoi.Sekai.no.Chuushin.de.01-03.2012.Web.1920x1080.h264.HorribleSubs.anidb-9091.filelist.log)
[Angel Densetsu [01-02] (1996) [DVD 700x480 h264] [Rising Sun] [anidb-3611].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469884/Angel.Densetsu.01-02.1996.DVD.700x480.h264.Rising.Sun.anidb-3611.scanner.log)
[Angel Densetsu [01-02] (1996) [DVD 700x480 h264] [Rising Sun] [anidb-3611].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469885/Angel.Densetsu.01-02.1996.DVD.700x480.h264.Rising.Sun.anidb-3611.filelist.log)
[Amagi Brilliant Park [01-13] (2014) [Blu-ray 1920x1080 h264] [BlurayDesuYo] [anidb-10399].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469886/Amagi.Brilliant.Park.01-13.2014.Blu-ray.1920x1080.h264.BlurayDesuYo.anidb-10399.scanner.log)
[Amagi Brilliant Park [01-13] (2014) [Blu-ray 1920x1080 h264] [BlurayDesuYo] [anidb-10399].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469887/Amagi.Brilliant.Park.01-13.2014.Blu-ray.1920x1080.h264.BlurayDesuYo.anidb-10399.filelist.log)
[Allison to Lillia [01-26] (2008) [DVD 720x480 h264] [E-D] [anidb-5569].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469888/Allison.to.Lillia.01-26.2008.DVD.720x480.h264.E-D.anidb-5569.scanner.log)
[Allison to Lillia [01-26] (2008) [DVD 720x480 h264] [E-D] [anidb-5569].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469889/Allison.to.Lillia.01-26.2008.DVD.720x480.h264.E-D.anidb-5569.filelist.log)
[Aldnoah.Zero [01-12] (2015) [Blu-ray 1920x1080 h264] [FFF] [anidb-10846].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469890/Aldnoah.Zero.01-12.2015.Blu-ray.1920x1080.h264.FFF.anidb-10846.scanner.log)
[Aldnoah.Zero [01-12] (2015) [Blu-ray 1920x1080 h264] [FFF] [anidb-10846].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469891/Aldnoah.Zero.01-12.2015.Blu-ray.1920x1080.h264.FFF.anidb-10846.filelist.log)
[Aldnoah.Zero [01-12] (2014) [Blu-ray 1920x1080 h264] [FFF] [anidb-10445].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469892/Aldnoah.Zero.01-12.2014.Blu-ray.1920x1080.h264.FFF.anidb-10445.scanner.log)
[Aldnoah.Zero [01-12] (2014) [Blu-ray 1920x1080 h264] [FFF] [anidb-10445].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469893/Aldnoah.Zero.01-12.2014.Blu-ray.1920x1080.h264.FFF.anidb-10445.filelist.log)
[Air Gear [01-25] (2006) [DVD 640x480 h264] [E-D] [anidb-4196].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469894/Air.Gear.01-25.2006.DVD.640x480.h264.E-D.anidb-4196.scanner.log)
[Air Gear [01-25] (2006) [DVD 640x480 h264] [E-D] [anidb-4196].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469895/Air.Gear.01-25.2006.DVD.640x480.h264.E-D.anidb-4196.filelist.log)
[Air Gear Kuro no Hane to Nemuri no Mori - Break on the Sky [01-03] (2010) [DVD 848x480 h264] [Tasty] [anidb-7669].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469896/Air.Gear.Kuro.no.Hane.to.Nemuri.no.Mori.-.Break.on.the.Sky.01-03.2010.DVD.848x480.h264.Tasty.anidb-7669.scanner.log)
[Air Gear Kuro no Hane to Nemuri no Mori - Break on the Sky [01-03] (2010) [DVD 848x480 h264] [Tasty] [anidb-7669].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/3469897/Air.Gear.Kuro.no.Hane.to.Nemuri.no.Mori.-.Break.on.the.Sky.01-03.2010.DVD.848x480.h264.Tasty.anidb-7669.filelist.log)

**Comment by ZeroQI** [comment]
Hama nodoesn't like [01-03] as it thinks it's the forced id

**Comment by EndOfLine369** [comment]
@ZeroQI,
Any reason HAMA should not be updated to be closer to ASS to remove the overly loose force id match?
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py#L91
```python
FROM:
match = re.search(r"(?P<show>.*?) ?\[(?P<source>([a-z0-9]*))-(tt)?(?P<guid>[0-9]{1,7})\]", orig_title, re.IGNORECASE) if ' [' in orig_title else None
TO:
match = re.search(r"(?P<show>.*?) ?\[(?P<source>(anidb(|[2-9])|tvdb(|[2-9])|tmdb|tsdb|imdb))-(tt)?(?P<guid>[^\[\]]*)\]", orig_title, re.IGNORECASE) if ' [' in orig_title else None
```

**Comment by ZeroQI** [comment]
@EndOfLine369 Thanks for the fix, applied to source
@Salvora please test and report, and close if resolved. you will need to re-match all and i think no metadata was picked up as a result. Your numbering although not clean should have been accepted with no issue, thanks for spotting

**Comment by Salvora** [comment]
I will upadte and test it. What would be the clean numbering?

**Comment by ZeroQI** [comment]
Without the bracket tags but this fix should make it supported without any changes which would be the easiest

**Comment by Salvora** [comment]
Tested
now it detects all with no problem. Thanks for the help.
