### ISSUE TITLE
Replacement for : (colon) in paths

### ISSUE THREAD

**Issue by TieSKey** [ZeroQI/Absolute-Series-Scanner#223]
Windows doesn't allow : (colon) as part of a file or folder name (not sure about linux FSs) so, what is the recommended replacement that won't interfere with the agent matching?

**Comment by ZeroQI** [comment]
space or hyphen, will try exact match then cleaned match, so should just work will replace with space then reduce multiple spaces to one
- os_filename_clean_string() line 214
- FILTER_CHARS line 45: "\\/:*?<>|~;"

https://forums.plex.tv/t/plex-get-confused-when-the-actual-movie-name-inludes-colon-character/59139/5

**Comment by TieSKey** [comment]
Perfect, thx.
