### ISSUE TITLE
anime list xml doesn't work correctly unless episodeoffset is specified

### ISSUE THREAD

**Issue by deusxanime** [ZeroQI/Absolute-Series-Scanner#227]
I believe this is a fairly new bug since I use tons of anime-list-custom.xml files and only have recently started running into this...

```
<?xml version="1.0" encoding="utf-8"?>
<anime-list>
  <anime anidbid="1091" tvdbid="82971" defaulttvdbseason="1">
    <name>Space Cobra</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-2;</mapping>
    </mapping-list>
  </anime>
</anime-list>
```

I used the above custom xml for a series since there was not a mapping for the special in ScudLee's list. Inside the series folder "Space Adventure Cobra [anidb2-1091]" I have all the regular Ep 01-31, the anime-list-custom.xml file, and then inside the folder I have another "specials" folder with the Special 01. When scanning into Plex, the only thing that showed up was the Special season with the single episode (properly mapped to TheTVDB Special 2). After fiddling around I figured out the only way to get the regular episodes to show up was to add in the "episodeoffset" parameter into the custom xml file.

```
<?xml version="1.0" encoding="utf-8"?>
<anime-list>
  <anime anidbid="1091" tvdbid="82971" defaulttvdbseason="1" episodeoffset="0">
    <name>Space Cobra</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-2;</mapping>
    </mapping-list>
  </anime>
</anime-list>
```

After adding that parameter and doing Plex Dance on the series everything showed up. I've run into that before, but this reminded me and so I thought I should open an issue so you were aware. 

The "episodeoffset" parameter used to be optional and would just default to 0 if unspecified. For the dozens (maybe 100s) of custom xml files I have done in the past I've never bothered to specify it and they have worked fine. But I've noticed now if it is not included it is causing some kind of issue which causes ASS/HAMA to not pick up the episodes. I believe the only reason the special was scanned properly is because a specific mapping was included for it so it overrode the defaults.

I don't have a series handy to check if the same thing happens if no custom xml is used, so it uses ScudLee's list instead, and if that episodeoffset parameter is missing from the ScudLee list xml. But for sure it affects using custom xmls inside the series folder.

**Comment by EndOfLine369** [comment]
My initial guess would be the change as "anidbTvdbMapping()" has not recently changed.
```python
FROM:
    if 'episodeoffset'     in mappingList and mappingList['episodeoffset'    ].isdigit():  ep, ep2 = ep+int(mappingList['episodeoffset']), ep2+int(mappingList['episodeoffset']) if ep2 else None 

TO:
    if 'episodeoffset'     in mappingList and is_integer(mappingList['episodeoffset'    ]):  ep, ep2 = ep+int(mappingList['episodeoffset']), ep2+int(mappingList['episodeoffset']) if ep2 else None 

WHICH USES:
def is_integer(string):  return string.isdigit() or len(string)>1 and string.startswith("-") and string[1:].isdigit()
```

**Comment by ZeroQI** [comment]
Line 384 should only update the ep with offset if offset exists, and already uses is_integer
`    if 'episodeoffset'     in mappingList and is_integer(mappingList['episodeoffset'    ]):  ep, ep2 = ep+int(mappingList['episodeoffset']), ep2+int(mappingList['episodeoffset']) if ep2 else None `

Doesn't explain an issue if empty, unless i missed something...
Need to check when i can

**Comment by ZeroQI** [comment]
@deusxanime Please test and report

**Comment by deusxanime** [comment]
Updated HAMA and ASS to the latest, then restarted Plex to be sure they are picked up. Did the Plex Dance on the series (the main series along with the movie that is a special, just to be sure the entire series is completely removed from Plex) and now it doesn't seem to be matching properly.

The series is blank (no match/metadata) in Plex with just the title "Space Adventure Cobra - The Movie [tvdb-82971]". It does show 33 episodes for the series (31 episodes in Season 1 and 2 episodes in Specials), so it does seem to be picking up all the episodes/files, just not matching now for some reason.

Here's a list of my folders and files that I'm doing the testing with:

```
V:\_tmp>dir /b
Space Adventure Cobra - The Movie [anidb2-1384]
Space Adventure Cobra [anidb2-1091]

V:\_tmp>dir /b "Space Adventure Cobra - The Movie [anidb2-1384]"
Space Adventure Cobra - The Movie 01 (DVD 1280x720, AC-3 6ch) [animepacks007] [2B9C3773].mp4

V:\_tmp>dir /b "Space Adventure Cobra [anidb2-1091]"
anime-list-custom.xml
Space Adventure Cobra - Ep 01 (DVD 960x720) [animepacks007] [38C9698F].mp4
Space Adventure Cobra - Ep 02 (DVD 960x720) [animepacks007] [F9F65FBB].mp4
Space Adventure Cobra - Ep 03 (DVD 960x720) [animepacks007] [2174D2B7].mp4
Space Adventure Cobra - Ep 04 (DVD 960x720) [animepacks007] [21214ABA].mp4
Space Adventure Cobra - Ep 05 (DVD 960x720) [animepacks007] [3A332B82].mp4
Space Adventure Cobra - Ep 06 (DVD 960x720) [animepacks007] [02E57D09].mp4
Space Adventure Cobra - Ep 07 (DVD 960x720) [animepacks007] [D6C07966].mp4
Space Adventure Cobra - Ep 08 (DVD 960x720) [animepacks007] [726D0B86].mp4
Space Adventure Cobra - Ep 09 (DVD 960x720) [animepacks007] [0EBA6BF0].mp4
Space Adventure Cobra - Ep 10 (DVD 960x720) [animepacks007] [B267D4D6].mp4
Space Adventure Cobra - Ep 11 (DVD 960x720) [animepacks007] [DB0E895D].mp4
Space Adventure Cobra - Ep 12 (DVD 960x720) [animepacks007] [4D3192B8].mp4
Space Adventure Cobra - Ep 13 (DVD 960x720) [animepacks007] [B39F47A3].mp4
Space Adventure Cobra - Ep 14 (DVD 960x720) [animepacks007] [B570DD51].mp4
Space Adventure Cobra - Ep 15 (DVD 960x720) [animepacks007] [3B575C2B].mp4
Space Adventure Cobra - Ep 16 (DVD 960x720) [animepacks007] [9A2D5DFD].mp4
Space Adventure Cobra - Ep 17 (DVD 960x720) [animepacks007] [84560410].mp4
Space Adventure Cobra - Ep 18 (DVD 960x720) [animepacks007] [EAA948D1].mp4
Space Adventure Cobra - Ep 19 (DVD 960x720) [animepacks007] [EA65F304].mp4
Space Adventure Cobra - Ep 20 (DVD 960x720) [animepacks007] [97EBC1B2].mp4
Space Adventure Cobra - Ep 21 (DVD 960x720) [animepacks007] [5253CA01].mp4
Space Adventure Cobra - Ep 22 (DVD 960x720) [animepacks007] [4075A4C8].mp4
Space Adventure Cobra - Ep 23 (DVD 960x720) [animepacks007] [94030295].mp4
Space Adventure Cobra - Ep 24 (DVD 960x720) [animepacks007] [21E05168].mp4
Space Adventure Cobra - Ep 25 (DVD 960x720) [animepacks007] [00523DE6].mp4
Space Adventure Cobra - Ep 26 (DVD 960x720) [animepacks007] [071F86AF].mp4
Space Adventure Cobra - Ep 27 (DVD 960x720) [animepacks007] [11943F45].mp4
Space Adventure Cobra - Ep 28 (DVD 960x720) [animepacks007] [AFFC9DBA].mp4
Space Adventure Cobra - Ep 29 (DVD 960x720) [animepacks007] [AE46AB75].mp4
Space Adventure Cobra - Ep 30 (DVD 960x720) [animepacks007] [BEF478E7].mp4
Space Adventure Cobra - Ep 31 (DVD 960x720) [animepacks007] [6F6051AB].mp4
specials

V:\_tmp>dir /b "Space Adventure Cobra [anidb2-1091]\specials"
Space Adventure Cobra - Special 01 - Pilot (DVD 960x720) [03E63D87].mp4

```

**Comment by deusxanime** [comment]
Ran another library scan/update while adding unrelated movies and it seems to have fetched the metadata now. TheTVDB was having problems earlier today, might have just not been able to communicate at the time.

**Comment by ZeroQI** [comment]
if not adding new materials, the scanner doesn't re-run for the folder, making scanner development really annoying as you need to change folder content at every check...

Metadata is an agent issue, seem like the scanner part works so closing
