### ISSUE TITLE
naming scheme causes files to be merged into a single one

### ISSUE THREAD

**Issue by Luro02** [ZeroQI/Absolute-Series-Scanner#229]
Naming your files like this
```
One_Piece_S01xE001.mkv
One_Piece_S01xE002.mkv
One_Piece_S01xE003.mkv
One_Piece_S01xE004.mkv
```
will merge all files into one episode.

**Comment by ZeroQI** [comment]
Logs?

Line 54 the regex doesn't seem to support xxXExxx...
I searched Google for the exact filename and got 0 match...

Can you give me the link or info to a release group using this naming convention?
Not adding the format for a single person unless a release group use this naming convention.
