### ISSUE TITLE
ASS + YouTube: chaotic episode numbering

### ISSUE THREAD

**Issue by disrupted** [ZeroQI/Absolute-Series-Scanner#235]
I am using this Scanner in conjunction with the YouTube-Agent metadata provider and while it does work I noticed that the episode numbers on some shows are all over the place so I am looking to possibly set it up from scratch. What's the preferred way of naming the files? Currently I am using this scheme:
```
/webvideos/
  Sara Dietschy [UC3fg6pL63upkXCc0T203wVg]/
    421 - 20181001 - Why he left ... [1920x1080][hCQ_a-FWib4].annotations.xml
    421 - 20181001 - Why he left ... [1920x1080][hCQ_a-FWib4].jpg
    421 - 20181001 - Why he left ... [1920x1080][hCQ_a-FWib4].mp4
    422 - 20181002 - Starting a Daily Vlog Again ! [1920x1080][Z4hMlOIhjJ4].annotations.xml
    422 - 20181002 - Starting a Daily Vlog Again ! [1920x1080][Z4hMlOIhjJ4].jpg
    422 - 20181002 - Starting a Daily Vlog Again ! [1920x1080][Z4hMlOIhjJ4].mp4
    479 - 20190716 - 5 Survival Tips for Visiting NEW YORK CITY [1920x1080][Z9JJI3rLBic].annotations.xml
    479 - 20190716 - 5 Survival Tips for Visiting NEW YORK CITY [1920x1080][Z9JJI3rLBic].jpg
    479 - 20190716 - 5 Survival Tips for Visiting NEW YORK CITY [1920x1080][Z9JJI3rLBic].mp4
    479 - 20190717 - Switching to ALL Google Apps [1920x1080][FNndBCeY8R4].annotations.xml
    479 - 20190717 - Switching to ALL Google Apps [1920x1080][FNndBCeY8R4].jpg
    479 - 20190717 - Switching to ALL Google Apps [1920x1080][FNndBCeY8R4].mkv
    480 - 20190718 - Testing LEICA Lenses on my Sony Camera [1920x1080][oaEiJgmffTA].annotations.xml
    480 - 20190718 - Testing LEICA Lenses on my Sony Camera [1920x1080][oaEiJgmffTA].jpg
    480 - 20190718 - Testing LEICA Lenses on my Sony Camera [1920x1080][oaEiJgmffTA].mkv
    481 - 20190731 - 3 Things Every Story NEEDS [1920x1080][RVznTAxqthU].annotations.xml
    481 - 20190731 - 3 Things Every Story NEEDS [1920x1080][RVznTAxqthU].jpg
    481 - 20190731 - 3 Things Every Story NEEDS [1920x1080][RVznTAxqthU].mp4
```

probably because I have thumbnails and annotations alongside the main video files I noticed that usually episode numbers would always increase by 3 (for instance 50,53,56,59,...). I deleted all the companion files for testing purposes however I noticed that they sometimes go completely out of order as can be seen in this screenshot:

<img width="971" alt="weird episode numbers" src="https://user-images.githubusercontent.com/4771462/66668924-ab7dc600-ec56-11e9-9f83-d0a12b22a117.png">

am I doing something fundamentally wrong?

**Comment by ZeroQI** [comment]
I need logs which are saved here (really needs to move them to Logs folder):
-  [...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Logs/...

Channels have no order so labelled as per the file year for the season which is production year if using youtubedl as instructed. Did you try the recommendation here: https://github.com/ZeroQI/YouTube-Agent.bundle ?

Lines 882-888:
```
      ### YouTube Channel numbering ###
      if source.startswith('youtube') and id.startswith('UC'):
        filename = os.path.basename(file)
        folder_season = time.gmtime(os.path.getmtime(os.path.join(root, path, filename)) )[0]
        ep            = files_per_date.index(filename)+1 if filename in files_per_date else 0
        standard_holding.append([os.path.join(root, path, filename), root, path, folder_show if id in folder_show else folder_show+'['+id+']', int(folder_season if folder_season is not None else 1), ep, filename, folder_season, ep, 'YouTube', tvdb_mapping, unknown_series_length, offset_season, offset_episode, mappingList])
        continue
```

**Comment by ZeroQI** [comment]
If showing order is wrong, that's a Plex issue. The scanner decides the season and ep number

**Comment by disrupted** [comment]
Yes, I located the logs, and ran the next scan on a smaller number of videos from this channel.

here are the results:
**[_Logs.zip](https://disrupted.cloud/s/j72BAMTFrtzsbEE)**
<img width="977" alt="frontend sorting" src="https://user-images.githubusercontent.com/4771462/66704166-f876a080-ed19-11e9-8a44-944e6bf4b9ba.png">

**Comment by ZeroQI** [comment]
```
"Sara Dietschy [UC3fg6pL63upkXCc0T203wVg]" s2019e007                         "YouTube" "486 - 20190903 - Switching to Davinci Resolve for 30 DAYS [1920x1080][qkISp2hkh9w].mp4" "486 - 20190903 - Switching to Davinci Resolve for 30 DAYS [1920x1080][qkISp2hkh9w].mp4"
"Sara Dietschy [UC3fg6pL63upkXCc0T203wVg]" s2019e010                         "YouTube" "487 - 20190910 - iPhone 11 & 11 Pro _ Apple Event Recap 2019 [1920x1080][a1T4I2dmO6A].mp4" "487 - 20190910 - iPhone 11 & 11 Pro _ Apple Event Recap 2019 [1920x1080][a1T4I2dmO6A].mp4"
"Sara Dietschy [UC3fg6pL63upkXCc0T203wVg]" s2019e013                         "YouTube" "488 - 20190916 - I bought the BMPCC6K (NEW CAMERA) [1920x1080][MJJYNvnNqko].mp4" "488 - 20190916 - I bought the BMPCC6K (NEW CAMERA) [1920x1080][MJJYNvnNqko].mp4"
"Sara Dietschy [UC3fg6pL63upkXCc0T203wVg]" s2019e016                         "YouTube" "489 - 20190925 - iPhone 11 Pro Camera - No More Complaints [1920x1080][AIxjvzZRaQ0].mp4" "489 - 20190925 - iPhone 11 Pro Camera - No More Complaints [1920x1080][AIxjvzZRaQ0].mp4"
"Sara Dietschy [UC3fg6pL63upkXCc0T203wVg]" s2019e019                         "YouTube" "490 - 20190929 - My $4,485 Cinema Setup [1920x1080][0hEBtLCoJ2o].mp4" "490 - 20190929 - My $4,485 Cinema Setup [1920x1080][0hEBtLCoJ2o].mp4"
"Sara Dietschy [UC3fg6pL63upkXCc0T203wVg]" s2019e022                         "YouTube" "491 - 20191002 - the new Surface Laptop 3 ...Beautiful but Weird [1920x1080][eQrob2iArlg].mp4" "491 - 20191002 - the new Surface Laptop 3 ...Beautiful but Weird [1920x1080][eQrob2iArlg].mp4"
"Sara Dietschy [UC3fg6pL63upkXCc0T203wVg]" s2019e003                         "YouTube" "492 - 20191008 - How I Organize Footage - NAS vs Local Raid Storage [1920x1080][iEbD9QZpNH8].mp4" "492 - 20191008 - How I Organize Footage - NAS vs Local Raid Storage [1920x1080][iEbD9QZpNH8].mp4"
```
Seem like the index include non video files, list need to be scrubbed with video ext. 
Will take some time

**Comment by disrupted** [comment]
does that mean I should wait a bit and check back? Or is there anything else I can do?

**Comment by ZeroQI** [comment]
In the meantime you can remove extra files, add a fideo file to the folder to generate a change or the dcan result would be cached and re:scan

**Comment by disrupted** [comment]
ok, did that. while it has certainly improved the episode numbers and sorting still aren't correct.
<img width="955" alt="screenshot" src="https://user-images.githubusercontent.com/4771462/66822553-bc735380-ef44-11e9-95b2-220cc9da959d.png">

Can't it just use the index from the filename as episode numbers (in this case 485-492)?

**Comment by ZeroQI** [comment]
Still the order listed is Plex which has a big... Can't help with that...

**Comment by disrupted** [comment]
> Still the order listed is Plex which has a big... Can't help with that...

what I am saying is that not just the displayed order is wrong but also the episode numbers

**Comment by ZeroQI** [comment]
Lines 816-818 fix for ep 3 apart, replace `os.listdir(os.path.join(root, path))` with `files`, full code section:
```
    if id.startswith('UC') or id.startswith('HC'):
      files_per_date = sorted(files, key=getmtime) #to have latest ep first, add: ", reverse=True"
      Log.info('files_per_date: {}'.format(files_per_date))
```
Please try the fix and a Plex dance (r)

While YouTube playlists are numbered and thus the episode number logical, random videos of a channel pose a problem, and the scanner responsability is to decide the season and episode number.
- xml list per channel does NOT contain all videos for a very full channel so a compromise convention was needed
- Using year as season does split into seasons nicely per year...
- The scanner sort the episodes for channels per folder file date in sequence, so new episodes do not renumber previously present episodes and no holes between episodes. 
- If the scanner were to read the ep from the filename, some title with number will mess things up...

The very point of this scanner is to rename the folder at best, not the filenames.
I fail to see why episodes 421, 422, 479, 480, 481 have these numbers, but they will be in the chronological order of file date which, if you downloaded with youtubedl, will be the release date and no need to renumber the files when downloading...

**Comment by ZeroQI** [comment]
Any feedback on the above?
Did you try the change suggested ? It should handle other files in the folder without jumping the ep number...

**Comment by disrupted** [comment]
sorry, I only saw your reply now, haven't had a chance of testing the suggested code change yet.
if you're saying that the scanner decides episode numbers based on the filedate (and not on the filename) then there we have it. I don't like to archive all videos of a channel from the very beginning but rather start somewhere and then later on I might decide to pick additional (earlier) videos later when I am done watching the latest ones. that's probably why they would show up as newer (according to their filedate) even though they're older episodes.

**Comment by ZeroQI** [comment]
However youtube dl make the creation date of the file the one of the video upload... Now if you use another method that youtubedl i recommended in the readme, you could have issues...

**Comment by disrupted** [comment]
oh really? I am indeed using ytdl of course, then let me check my local filedates to confirm it's working

**Comment by disrupted** [comment]
> Lines 816-818 fix for ep 3 apart, replace `os.listdir(os.path.join(root, path))` with `files`, full code section:
> 
> ```
>     if id.startswith('UC') or id.startswith('HC'):
>       files_per_date = sorted(files, key=getmtime) #to have latest ep first, add: ", reverse=True"
>       Log.info('files_per_date: {}'.format(files_per_date))
> ```
> 
> Please try the fix and a Plex dance (r)
> 
> While YouTube playlists are numbered and thus the episode number logical, random videos of a channel pose a problem, and the scanner responsability is to decide the season and episode number.
> 
> * xml list per channel does NOT contain all videos for a very full channel so a compromise convention was needed
> * Using year as season does split into seasons nicely per year...
> * The scanner sort the episodes for channels per folder file date in sequence, so new episodes do not renumber previously present episodes and no holes between episodes.
> * If the scanner were to read the ep from the filename, some title with number will mess things up...
> * if you downloaded with youtubedl, will be the release date and no need to renumber the files when downloading, and they will be in sequence with no holes in between... The very point of this scanner is to rename the folder at best, not the filenames. As such, I fail to see why episodes 421, 422, 479, 480, 481 have these numbers, but they will be in the chronological order of file date, which i fail to see any negative point about,

just applied the patch, episodes are now all indexed as Episode 1 (show up as different versions in plex). I can supply the log tomorrow

**Comment by ZeroQI** [comment]
Channels episodes are numbered according to file date (as in my tests under win10 with playlists the creation date was kept and not replaced by download date)
Playlist episodes are numbered as per the playlist rank

Reproduced and fixed and moved logs location.
You have two number 479 btw:
- 479 - 20190716 - 5 Survival Tips for Visiting NEW YORK CITY [1920x1080][Z9JJI3rLBic].jpg
- 479 - 20190717 - Switching to ALL Google Apps [1920x1080][FNndBCeY8R4].mkv
