### ISSUE TITLE
Naming Support 

### ISSUE THREAD

**Issue by typkrft** [ZeroQI/Absolute-Series-Scanner#241]
Is it possible to group playlist_id as series > channel_id as season > video_id as file?

If I have a playlist that is all about video games for instance it would be nice to see the topic, then pick the channel then watch the video. 

eg:
#!/bin/zsh

/usr/local/bin/youtube-dl --download-archive '/Volumes/Media V/Youtube/archive.txt' -i -f best -o '/Volumes/Media V/Youtube/%(playlist)s - [%(playlist_id)s]/%(uploader)s - [%(channel_id)s]/%(title)s - [%(id)s].%(ext)s' -a '/Users/media/Documents/playlists.txt' -c

**Comment by typkrft** [comment]
I just saw there is no season numbering available. Could I maybe suggest this then as a feature request?

**Comment by ZeroQI** [comment]
You can do
- Channel as series > year as season automatically > title [videoid].ext
- Series > seasons '[youtube-playlist_id]' > title [videoid].ext
- Test if "Series > Season xx [youtune-channel-id] > title [videoid].ext" works

**Comment by typkrft** [comment]
If I do something like 

> Series > Season 02 [youtune-channel-id] > title [videoid].ext (to be tested)

implemented as

`'/Volumes/Media V/Youtube/%(playlist)s/%(uploader)s [youtube-%(channel_id)s]/%(title)s - [%(id)s].%(ext)s'`

I get the videos organized by channel and season, which I what I think most people want. 

However, in my case I have several playlists, which are topics of interest on Youtube such as Videogames, Javascript, Music, etc. What I was hoping to do is to organize them together by thePlaylist (Series) > theChannel (Season) > theVideo. 

With 

`/Volumes/Media V/Youtube/%(playlist)s - [%(playlist_id)s]/%(uploader)s - [%(channel_id)s]/%(title)s - [%(id)s].%(ext)s`

I get 2 levels of organization thePlaylist(Series) > theVideo, but no season, which is good enough if it doesn't make sense to implement something like this.  

Thanks again for your response and work on this. I've been looking for a youtube solution off and on for a while.

**Comment by ZeroQI** [comment]
The scanner need to decide the season and ep number... To do what you want it would need to
- download metadata to figure the channel
- decide which season it is and not change regardless of the other files added
It is not doable practically to have the scanner do that nor can i find a logical way to do this to figure out the episode number...
