### ISSUE TITLE
Wrong episode number after updating agent

### ISSUE THREAD

**Issue by avluis** [ZeroQI/Absolute-Series-Scanner#242]
After downloading the latest bundle (from the 29th), noticed that the following gets recognized as the wrong episode:
`Pocket Monsters Sun & Moon [anidb3-12407]/054 - 10,000,000 Reasons to Fight! [Some-Stuffs][Blu-ray](0a362e5a).mkv`

![Capture](https://user-images.githubusercontent.com/875593/67926908-a5ac3e00-fb8d-11e9-8312-51236c9145ec.PNG)

Attached are the relevant files, but the change in behavior can be seen in the `scanner.log` file around the time the bundle was updated; here is an excerpt.

Line 838:
`"Pocket Monsters Sun & Moon [tvdb-]" s01e054                         "Word Search" "10,000,000 Reasons To Fight!" "054 - 10,000,000 Reasons to Fight! [Some-Stuffs][www](b76437ee).mkv"`

Line 998:
`"Pocket Monsters Sun & Moon [tvdb-]" s01e010                         "SERIES_RX-2" ",000,000 Reasons To Fight!" "054 - 10,000,000 Reasons to Fight! [Some-Stuffs][www](b76437ee).mkv"`

[Pocket Monsters Sun & Moon [anidb3-12407].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3792561/Pocket.Monsters.Sun.Moon.anidb3-12407.agent-search.log)
[Pocket Monsters Sun & Moon [anidb3-12407].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3792562/Pocket.Monsters.Sun.Moon.anidb3-12407.agent-update.log)
[Pocket Monsters Sun & Moon [anidb3-12407].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3792563/Pocket.Monsters.Sun.Moon.anidb3-12407.filelist.log)
[Pocket Monsters Sun & Moon [anidb3-12407].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3792564/Pocket.Monsters.Sun.Moon.anidb3-12407.scanner.log)

**Comment by ZeroQI** [comment]
The scanner decides the season and ep number, not the agent, First line in the agent readme "If all video files are showing in plex at the right season and episode number, the scanner did its job" so moved the bug report to the scanner side...

Anidb3 "Uses ScudLee mapping to map the AniDB series to TVDB entries" according readme...
there is no tvdb id in scudlee's xml so "[anidb3-12407]" is pointless in this case

You have two video files per season/episode, thic could lead to valid episode number in the word search being thrown out by the failsafe... 

If you remove "10,000,000" from the title it will work...

**Comment by avluis** [comment]
My apologies on getting the repo wrong yet again! I need to not create issues when tired.

`anidb3` being set as is due to my scripts, but it is being overridden with `Fix Match` on Plex.

I had the web version and now the Blu-ray version; which was when the issue started happening so definitely ruling out the agent.

I'm guessing the parse logic can't have more than one continuous word search so it goes into failsafe?
Any way this can be improved for the future?

Anyways, this is low priority as I'll be removing the web version of the file which should get us out of that failsafe.
Thank you for your time.
