### ISSUE TITLE
Bananya Season 1 and 2 are mapping individually using [anidb2]

### ISSUE THREAD

**Issue by EarthBoundGiygas** [ZeroQI/Absolute-Series-Scanner#246]
Hey, I hope I'm not clogging this up too terribly. I use anidb2 for the most part for all of my series I can't get to stick together, but Banananya Season 2 refuses to group to season 1. I have all of the correct anidb entries and file structure and episode naming scheme is correct. Season 2 shares the same Title as season 1, even though they should have different titles, and the descriptions are identical.

![image](https://user-images.githubusercontent.com/6926502/69570983-fd707600-0f8e-11ea-8ab7-883c3f03c415.png)

I hope this is just me being bad at the software and not just a glitch.

**Comment by ZeroQI** [comment]
From the readme:
`If you post anything on the scanner github or thread for any issue like poster missing/wrong, episode thumbnail/screenshot/title/summary missing/wrong, then you clearly haven't read this and need to pay the RTFM tax by donating (or you just find this the best anime scanner and/or agent, much appreciated average is 5 euros). Also applies if you want assistance but didn't follow troubleshooting steps or include logs...`

Series search logs missing... 
Series folder naming missing
Scanner logs missing

Please tell me you used the forced id as such and if not please donate:
- Bananya [anidb2-11910]
- Bananya Fushigi na Nakama-tachi [anidb2-15036]

**Comment by ZeroQI** [comment]
No answer for 6 days, no logs attached, no folder name given, closing
