### ISSUE TITLE
AniDB Arc Mode

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#252]
Can ASS do custom season mappings for AniDB shows like we do for TVDB4? It would be virtually the same, except use AniDB's numbering for the seasons.  Because AniDB doesn't split into seasons like TVDB, this would require a local mapping file.

**Comment by ZeroQI** [comment]
Anidb2 and anidb3 already does that...
Closing.

**Comment by sven-7** [comment]
I can map One Piece to custom seasons with those modes?

**Comment by ZeroQI** [comment]
If those seasons are anidb entries.
What do you week that tvdb4 doesn't do?

**Comment by sven-7** [comment]
I just wanted to get the same functionality. Because TVDB is changing how they do absolute numbers soon when it comes to Absolute and Official Numbering, AniDB might become more accurate with their numbering.

**Comment by ZeroQI** [comment]
TheTVDB will still have the information in the API. We will adapt the code when we get to that point.
