### ISSUE TITLE
Regarding "Other" episodes

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Absolute-Series-Scanner#253]
Related to https://github.com/ZeroQI/Hama.bundle/issues/379

I'm creating this ticket here since it's regarding a scanner issue after all.

> You put the letter 'O' in front of the episode number 'O1' instead of '01', you can compare with the size of the '0' in the '1080p' part of the filename

According to your own read me in ASS Scanner, it says the following:

Type | Internal letter | Episode number
-- | -- | --
Specials | S | Episodes 001-100
OPs | C | Episodes 101-150
EDs | C | Episodes 151-200
Trailers | T | Episodes 201-300
OPs/EDs | P | Episodes 301-400
Others | O | Episodes 401-500
unmapped |   | Episodes 501-600

So episodes marked as other in AniDB should be started with the letter "O" and then following by the number. I'm not understanding your comment since it's not compatible with what you wrote in the read me.

AniDB Link: https://anidb.net/anime/13473

As you can see, episodes are marked as "other" in AniDB. According to the table above, using the "OXX" where XX is the number, the episodes should be mapped to Episodes 401-500.

As you can see below they are marked in the 500-600 range, making them clearly not marked as Others episodes by the ASS Scanner, instead they are being marked as "unmapped"

https://user-images.githubusercontent.com/14930057/72209297-b2f67a80-34a4-11ea-9a9a-10da021833f1.png

**Comment by ZeroQI** [comment]
Did you try a capital 'O'?
So you want the files to be numbered 401-xxx... They will still get no metadata, I don't see the point of this bug report...

**Comment by KurtzPT** [comment]
> Did you try a capital 'O'?
They are currently with capital O. 

> They will still get no metadata, I don't see the point of this bug report...

I thought everything that is matched on the table above would get metadata (except the unmapped files 501+)

I know that special files (S01, S02) get populated with metadata, why the same doesn't happen to other files?

So for example with the AniDB title I have above:

O1 or O01 would get the title "Amritsar" from AniDB

**Comment by purposelycryptic** [comment]
Are you sure everything is named/mapped correctly? I have quite a few series with O-maps, including Die Neue These (2019), and they work properly, i.e.:

![ginga eiyuu densetsu](https://user-images.githubusercontent.com/9452779/72304702-5a0f1980-363f-11ea-910c-2e6d77f18971.JPG)

 i have mine organized like this:

Ginga Eiyuu Densetsu - Die Neue These (2019) [anidb-13473] [HorribleSubs] [www, 1080p]\
 - Ginga Eiyuu Densetsu - Die Neue These (2019) - O1 - Amritsar [HorribleSubs] [www, 1080p, AAC] [6F4A897B].mkv
 - Ginga Eiyuu Densetsu - Die Neue These (2019) - O2 - Demise of the Emperor [HorribleSubs] [www, 1080p, AAC] [AB027CB2].mkv
...

And everything just worked without any manual file manipulation required

**Comment by EndOfLine369** [comment]
There is indeed something off here. I can replicate and manual re test against the "other" regex returns match.
```python
>>> filename = "[HorribleSubs] Legend of the Galactic Heroes - Die Neue These - O1 [1080p].mkv"
>>> rex = r'(^|(?P<show>.*?)[ _\.\-]+)(O|OTHERS?)(?P<ep>\d{1,2})[ _\.]?(V\d)?[ _\.\-]+(?P<title>.*)$'
>>> re.search(rex, filename, re.IGNORECASE).groupdict() 
{'ep': '1', 'show': '[HorribleSubs] Legend of the Galactic Heroes - Die Neue These', 'title': '[1080p].mkv'}
```

**Comment by EndOfLine369** [comment]
Issue is string post clean where there is nothing after the "O#". The regex expects it.
```
First go:
"ep:           -       - o1"
Second go:
"Legend of the Galactic Heroes - Die Neue These - O1"
```
If you had the episode title after it like @purposelycryptic it would work. Will see what should be done to the regex to handle this.

**Comment by EndOfLine369** [comment]
Fixed

**Comment by KurtzPT** [comment]
Well that was really an unique case, usually I don't rename my files except to making sure the identifiers are correctly like stated in the table.

Thanks for the fix @EndOfLine369
