### ISSUE TITLE
Trying to modify the script

### ISSUE THREAD

**Issue by dmagyar** [ZeroQI/Absolute-Series-Scanner#255]
Hi! I'm trying to alter the script so it better fits for my use-case but I don't know how can I manually execute it from shell? The plex container does not come with python it looks like plex has an embedded libpython to run these. 

How do you test your code/functionality?

Thanks!

**Comment by ZeroQI** [comment]
Not a scanner issue per say but a custom (or default) Plex Scanner command line usage query

The part at the end allows it to be called from the console so the code is right on my end
```
### Command line scanner call ###
if __name__ == '__main__':  #command line
  print("Absolute Series Scanner by ZeroQI")
  path  = sys.argv[1]
  files = [os.path.join(path, file) for file in os.listdir(path)]
  media = []
  Scan(path[1:], files, media, [])
  print("Files detected: ", media)
```

You mean something like that:
- https://support.plex.tv/articles/201242707-plex-media-scanner-via-command-line/
- https://forums.plex.tv/t/need-help-starting-scanner-from-python-script-ubuntu/13033/2
- https://nubcakes.net/index.php/2018/11/21/how-to-scan-plex-media-from-command-line/

Closing as
- the code is right to allow to be launched from the command line
- documented in the forum and google and not a standard user case for my scanner, nor is the method generic to my scanner neither.
- To test, when i do, I refresh the scan from the library menu
