### ISSUE TITLE
Large number handling

### ISSUE THREAD

**Issue by Remnence** [ZeroQI/Absolute-Series-Scanner#256]
With Crayon Shin-chan hitting 1000 episodes recently the episodes now have 3 leading zeros causing them to be picked up by HAMA/ASS as specials instead of numbered episodes.

**Comment by Remnence** [comment]
Looks like no impact at all including Crayon Shin-chan. Still detects as season 00.

**Comment by ZeroQI** [comment]
You edited the code manually, modified the folder content(otherwise won't re-scan the folde) re-scanned,  and Plex scanner code show it ran ok ?

**Comment by Remnence** [comment]
Yes. I even removed the folder and re-scanned, cleaned bundles, then re-added and scanned. Other new episodes detected correctly. The Crayon Shin-chan with three leading zeros (Crayon Shin-chan - 0001) detected as S00. I edited the .py script on my server directly, I even double checked after it failed to correctly detect the show.

**Comment by ZeroQI** [comment]
Can you please attach as files the scanner logs and your edited scanner code?
I changed all references to 3 digit ep numbers so dunno where it failed..

**Comment by Remnence** [comment]
[Absolute Series Scanner.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4127764/Absolute.Series.Scanner.txt)
[Crayon Shin-chan.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4127794/Crayon.Shin-chan.filelist.log)
[Crayon Shin-chan.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4127795/Crayon.Shin-chan.scanner.log)

**Comment by ZeroQI** [comment]
> s00e029                         "Word Search" "Episode 29" "Crayon Shin-chan - 0029 - Episode 29.mkv"
> "Crayon Shin-chan" s00e030                         "Word Search" "Episode 30" "Crayon Shin-chan - 0030 - Episode 30.mkv"

you have the episode number twice in the filename, i wouldn't do that...
Need to find in word search where is assignes to s00e29...

Lines 75, 149, 392, 391 have {1,3} still..
lines 995-996:
```
          if   ep.isdigit() and len(ep)==4 and (int(ep)< 1900 or folder_season and int(ep[0:2])==folder_season):   season, ep = int(ep[0:2]), ep[2:4]                 # 1206 could be season 12 episode 06  #Get assigned from left ot right
          elif ep.isdigit() and len(ep)==4:  filename = clean_string( " ".join(words).replace(ep, "(%s)" % ep));   continue                                           # take everything after supposed episode number
```
That's the culprit. commenting these 2 lines will solve the issue but tv series with s10e15 labelled with ep number "1015" will no longer be supported...

Can you test by commenting these 2 lines with "#" just before "if" and "elif"?

**Comment by Remnence** [comment]
> you have the episode number twice in the filename, i wouldn't do that...

That is how any of the anime renamers output an unknown title from anidb. I try not to have it but anidb is only so complete.

> That's the culprit. commenting these 2 lines will solve the issue but tv series with s10e15 labelled with ep number "1015" will no longer be supported...

Shouldn't be an issue as I use absolute numbering for anime hence why Crayon is an issue and One Piece will become one shortly. There was an issue with a few shows like the last season of Gintama that had numbers in the episode. I had to switch the names to the words instead of numbers to fix it.

The changes seem to have worked and no adverse effects that I can find yet.

**Comment by ZeroQI** [comment]
Inserted into master branch
Closing issue. Reworked the second  line to put years into parenthesis.
