### ISSUE TITLE
Evolve to simple AMS

### ISSUE THREAD

**Issue by Akior** [ZeroQI/Absolute-Series-Scanner#260]
Its possible to create "Movie Scanner" ?
Let's example

My formatted path with file is:
/mnt/Аниме HD/5 сантиметров в секунду/5 сантиметров в секунду [5 Centimeters per Second] (2007) [1080p] [10bit]
If I add - Complete Movie. ABS will find 5 Centimeters per Second as 1 season episode, without metadata.
Other plex scanner for movies will see to basic part of filename "5 сантиметров в секунду" and ignore ENG name inside brackets and year. Matching ~70% good
I know that basic solution is revert eng and other name, but impossible for dlna search.

So, is possible to create scanner that will look to [TEXT] and (YEAR) and pass to agent filename and year ?
Aprox there are 99.9% match

**Comment by ZeroQI** [comment]
I will not do it, but it is possible to create a movie scanner and use ASS or other code as base.
You could even search Google for an already made movie scanner and modify it:
https://github.com/filebot/plex-agents/blob/master/Scanners/Movies/FileBot%20Xattr%20Movie%20Scanner.py
