### ISSUE TITLE
Episodes within Seasons 2>= aren't getting named properly.

### ISSUE THREAD

**Issue by BambaSamba** [ZeroQI/Absolute-Series-Scanner#269]
For some reason my Plex only names episodes within Season 1 of a series while episodes within Season 2+ are only getting named "Episode x".

C:\Anime\One Piece\Season1\ -> Titles show up fine
C:\Anime\One Piece\Season2\ -> Titles show "Episode x"

**Comment by ZeroQI** [comment]
Titles are the responsibilities of the metadata agent line 7 of the readme:
> Episode title (not filled by plex default series scanner, but ASS fills it, but this will be overwritten by the metadata agent)

Looked over https://www.thetvdb.com/series/one-piece and no english titles for season 2 so...

For some reason you included no logs, no examples, didn't follow any of the troubleshooting steps of the readme and the ticket closed itself...issue seem to be metadata agent related so closing that ticket, not agent related as the eps get added to Plex fine
