### ISSUE TITLE
[Question] PLEX python libraries on Windows

### ISSUE THREAD

**Issue by localh0st-** [ZeroQI/Absolute-Series-Scanner#27]
I've been trying to start playing around with the scanner in Jetbrains PyCharm IDE, but I have been unable to locate several  modules (Utils, Media, etree, and Stack). Where can I find these?

**Comment by ZeroQI** [comment]
Search plex included default acanner. Common files folder within contain
them.
I use notepad++ to edit...

**Comment by localh0st-** [comment]
where is the default scanner located?

**Comment by ZeroQI** [comment]
https://github.com/plexinc-plugins/Scanners.bundle/blob/master/Contents/Resources/Series/Plex%20Series%20Scanner.py
Please search for this file on your pms folders
Should be somewhere like /Users/XXX/Library/Application Support/Plex/Plex Media Server.app/Contents/Resources/Plug-ins/Scanners.bundle
