### ISSUE TITLE
Episodes are being identified as duplicate for some shows

### ISSUE THREAD

**Issue by ArabCoders** [ZeroQI/Absolute-Series-Scanner#271]
Isekai Quartet S2 - 01 to 12 are all being identified as duplicates so is (Major 2nd S2 - 01 to 03)

if i rename them to S01E(episode number), then it fixes the issue. is there anyway to fix it without having to manually go thru renaming those episodes weekly?

i have updated both Hama.bundle and the scanner and rerun the scanner and moved the episodes to another folder just to be sure, and when i moved them back they are identified as duplicates of E01.

i think the issue is that these shows have "S2" in title.

**Comment by ZeroQI** [comment]
Please review [...]/Plex Media Server/Logs/ASS Scanner Logs/root_folder_name.scanner.log and attach if needed/unsure...
- You didn't specify the series folder name. If you had it set to "Isekai Quartet S2" then it is removed from the filename and would cause no issues so i guess you named the folder differently from the filenames
- S2 = Anidb Special 2 = s00e02

**Comment by ArabCoders** [comment]
Indeed, the folder name was exactly like what was in AniDB "Major 2nd (2020)" so the path was

/anime/Major 2nd (2020)/[HH] Major 2nd S2 - 01 [1080p].mkv

renaming it to just "Major 2nd S2" fixed it.

Thank you.

**Comment by Hamuko** [comment]
>If you had it set to "Isekai Quartet S2" then it is removed from the filename and would cause no issues so i guess you named the folder differently from the filenames

This doesn't seem to work for `Kaguya-sama ~Love is War~ S2`. `[GJM] Kaguya-sama ~Love is War~ S2 - 01 [338CFE1E].mkv` and `[GJM] Kaguya-sama ~Love is War~ S2 - 02 [EC4E69CD].mkv` are both identified as duplicates despite the directory name being exactly the same as the filename.

**Comment by ZeroQI** [comment]
Encoding foulsd be different than ven if it appears identical. Missing logs to reply precisely. In any case S2 = s00e02 following AniDB specials numbering if the folder name wasn't substracted correctly.... Series specific scanner logs in logs/ASS scanner/*.scanner.log needed....

**Comment by Hamuko** [comment]
```
=============================================================================================================================================================
Library: 'no valid X-Plex-Token.id', root: '/Volumes/Elements/Anime', path: 'Kaguya-sama ~Love is War~ S2', files: '2', dirs: '0'
Plex scan start: 2020-04-26 10:06:50,614231
=============================================================================================================================================================
Forced ID (source file) - source: "anidb", id: "15207"
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'02': 1, '01': 1, 'Love': 2, 'S2': 2, 'sama': 2, 'Kaguya': 2, 'War': 2, 'is': 2}
misc_words: []
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"Kaguya-sama Love is War S2 [anidb-15207]" s01e002                         "Word Search" "01" "[GJM] Kaguya-sama ~Love is War~ S2 - 01 [338CFE1E].mkv"
"Kaguya-sama Love is War S2 [anidb-15207]" s01e002                         "Word Search" "02" "[GJM] Kaguya-sama ~Love is War~ S2 - 02 [EC4E69CD].mkv"
=============================================================================================================================================================
Plex scan end: 2020-04-26 10:06:50,624282
```

**Comment by EndOfLine369** [comment]
Guess is from the `~` in https://github.com/ZeroQI/Absolute-Series-Scanner/blob/e88ad19445f0ddfc09e6a3b48e29dd8ea4e123e9/Scanners/Series/Absolute%20Series%20Scanner.py#L63

**Comment by ZeroQI** [comment]
https://anidb.net/anime/15207
title is not supported, but others are that have a tilde in the title.
We should try to remove line 63 '~' from FILTER_CHARS
@ArabCoders Can you test and report please?

**Comment by ArabCoders** [comment]
@ZeroQI can confirm, after pulling last changes on both scanner and hama.bundle the scanner does semes to link to correct aid.

![plex](https://user-images.githubusercontent.com/1621552/81515495-0686b100-933d-11ea-8ecc-697b5eea66ed.png)
