### ISSUE TITLE
Scan seasons like "Se1E1"

### ISSUE THREAD

**Issue by IvanShift** [ZeroQI/Absolute-Series-Scanner#272]
Hello!
Is it possible to add ability to scan series with names like that "SeXEx"?

[Sherlock.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4550905/Sherlock.filelist.log)
[Sherlock.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4550906/Sherlock.scanner.log)

**Comment by ZeroQI** [comment]
'Se' seem very wrong, as S stands for seasons, e for episodes but could find this naming on that release on the web...

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py line 72 to replace

`  cic(r'(^|(?P<show>.*?)[ _\.\-]+)S(?P<season>\d{1,4})[ _\.\-]?EP?(?P<ep>\d{1,3})(([ _\.\-]|EP?|[ _\.\-]EP?)(?P<ep2>\d{1,3}))?[ _\.]*(?P<title>.*?)$'),                          #  1 # s01e01-02 | ep01-ep02 | e01-02 | s01-e01 | s01 e01'(^|(?P<show>.*?)[ _\.\-]+)(?P<ep>\d{1,3})[ _\.\-]?of[ _\.\-]?\d{1,3}([ _\.\-]+(?P<title>.*?))?$',                                                              #  2 # 01 of 08 (no stacking for this one ?)
`
with:
`  cic(r'(^|(?P<show>.*?)[ _\.\-]+)S([Ee])?(?P<season>\d{1,4})[ _\.\-]?EP?(?P<ep>\d{1,3})(([ _\.\-]|EP?|[ _\.\-]EP?)(?P<ep2>\d{1,3}))?[ _\.]*(?P<title>.*?)$'),                          #  1 # s01e01-02 | ep01-ep02 | e01-02 | s01-e01 | s01 e01'(^|(?P<show>.*?)[ _\.\-]+)(?P<ep>\d{1,3})[ _\.\-]?of[ _\.\-]?\d{1,3}([ _\.\-]+(?P<title>.*?))?$',                                                              #  2 # 01 of 08 (no stacking for this one ?)
`
Please test and report (folder content need changing like removing 1 file to be able to scan again)

**Comment by IvanShift** [comment]
Thanks! Now everything is fine!
[Sherlock.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4551719/Sherlock.filelist.log)
[Sherlock.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4551720/Sherlock.scanner.log)
