### ISSUE TITLE
Support directories starting with . (dot) in them that also contain files starting with . (dot)

### ISSUE THREAD

**Issue by runecalico** [ZeroQI/Absolute-Series-Scanner#275]
**Is your feature request related to a problem? Please describe.**
I assumed when it listed support for files that start with . (dot), like .hack SIGN - 01v2 - Role Play [KAA][DVD][704x480][h264][10234CD2].mkv that it would also parse the parent directory of .hack sign.

However that does not seem to be the case. I have an anime folder /data/Anime for example, that has the folder .hack sign and in that folder is the file .hack SIGN - 01v2 - Role Play [KAA][DVD][704x480][h264][10234CD2].mkv.

The Scanner does not seem to notice the directory at all, this is on Linux.

There are ZERO entries in any log file in the ../logs/ASS Scanner Logs directory that mention this folder. I believe it is not listing it all.

**Describe the solution you'd like**
Parse directories that start with a , and alphanumeric text after them.  In Unix you have to ignore just a . and .. as they are special references to current working directory and parent directory.

**Describe alternatives you've considered**
Renaming the folder to dot hack sign, which should then allow the scanner to notice the directory and scan the files.

**Additional context**

**Comment by ZeroQI** [comment]
Plex Media scanner.log missing. It would allow to see if the scanner code crashed or not.

**Comment by ZeroQI** [comment]
Seem to be a plex limitation, as i do not restrict it
This is normal for Plex to not scan a folder that starts with a '.' according:
- https://forums.plex.tv/t/media-is-not-added-when-a-folder-starts-with/74690/5
- https://forums.plex.tv/t/plex-does-not-recognize-folders-that-start-with-dot/239077
- https://forums.plex.tv/t/plex-media-center-not-picking-up-hack-sign/223153
