### ISSUE TITLE
Scanner cannot recognize some episodes names

### ISSUE THREAD

**Issue by IvanShift** [ZeroQI/Absolute-Series-Scanner#277]
Hello!
Is it possible to add ability scan episodes with names like this:
StrawberryAndWalrusS01E01.mp4
StrawberryAndWalrusS02E10.mp4
КитStupidShowS08E15.mp4
КитStupidShowS03E13.mp4

Unfortunately  scanner cannot recognize those names (

[2x2.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4622320/2x2.filelist.log)
[2x2.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4622321/2x2.scanner.log)

**Comment by ZeroQI** [comment]
Thatissinglehanddlelythemoststupidnamingconventionihaveeverseendoyouknowwhatimean?

**Comment by ZeroQI** [comment]
This naming convention is without separators, so no other scanner would support that, which is why i thought that would be good to add. Still think it is a stupid naming convention, but the release group is that fault. Please test and i will include in the master if it works

**Comment by IvanShift** [comment]
Thank you! First variant is working!

[2x2.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4622937/2x2.filelist.log)
[2x2.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4622936/2x2.scanner.log)

**Comment by EndOfLine369** [comment]
@ZeroQI, please advise why `([Ee])?` was added. Looking at the filenames above, the only issue was that there was no space/separator before the SxEx piece? That should have been handled when you changed `+` (1+ in `[ _\.\-]+`) to `*`(any amount in `[ _\.\-]*`). By adding that 'E', you allow for some reason a filename format of `<show>SE01E01` allowing 'SE' for season.

**Comment by ZeroQI** [comment]
Good point. I suck at regex.

**Comment by EndOfLine369** [comment]
Looks like you updated your comment after I updated. I reupdated. all we need is `E?`. The string is case insensitive so not need for '[Ee]' and is a single char so '()' is redundant.

**Comment by EndOfLine369** [comment]
FYI, https://github.com/ZeroQI/Hama.bundle/commit/bd3683330ae6a69548523d52591d4520f37f95ec
