### ISSUE TITLE
Updated scanner, messed up library

### ISSUE THREAD

**Issue by whinette** [ZeroQI/Absolute-Series-Scanner#281]
Hello,

I've just updated the scanner to the latest version (latest version I used was updated on 20/04/2020) and a whole lot of previously recognized media were rediscovered (appear as new import in plex), and some of them aren't recognized and stacked together:
![image](https://user-images.githubusercontent.com/6152660/83187469-7fa04980-a12e-11ea-92f9-fadf508ca445.png)

The xxx are stacked media that should be properly recognized, example:
![image](https://user-images.githubusercontent.com/6152660/83187551-a199cc00-a12e-11ea-960c-b990cd10f8db.png)

On a sidenote, I have no media tagued with `tvdb-01` no idea where it come from:
![image](https://user-images.githubusercontent.com/6152660/83187985-4a482b80-a12f-11ea-8b54-c26b2d6015e5.png)

If I take as example the first item of the stack in the screenshot (FLCL), it appears to be correctly scanned in the logs:
```
=============================================================================================================================================================
Library: 'Anime', root: '\\shou\plex\Anime Collections', path: 'FLCL\FLCL Alternative [anidb-13258]', files: '1', dirs: '0'
Manual scan start: 2020-05-28 22:07:20,006000
=============================================================================================================================================================
Forced ID (series folder) - source: "anidb", id: "13258"
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'Movie': 1, 'Alternative': 1, 'FLCL': 1, '01': 1, 'Complete': 1}
misc_words: []
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"01" s01e001                         "Word Search" "" "FLCL Alternative - 01 - Complete Movie.mkv"
=============================================================================================================================================================
Manual scan end: 2020-05-28 22:07:20,458000
=============================================================================================================================================================
```

```
=============================================================================================================================================================
Library: 'Anime', root: '\\shou\plex\Anime Collections', path: 'FLCL\FLCL Alternative [anidb-13258]', files: '1', dirs: '0'
Manual scan start: 2020-05-28 22:07:20,005000
plexignore_files: '[]', plexignore_dirs: '[]'
=============================================================================================================================================================
[file] FLCL\FLCL Alternative [anidb-13258]\FLCL Alternative - 01 - Complete Movie.mkv
=============================================================================================================================================================
```

Kindly find attached the whole logs for this run only:
[Anime.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4698040/Anime.zip)

**Comment by whinette** [comment]
I've rollbacked to the old script linked bellow to confirm and no more issues
[Absolute Series Scanner.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4698195/Absolute.Series.Scanner.zip)

**Comment by whinette** [comment]
Confirming, the filebot plex-agent were at fault.

**Comment by ZeroQI** [comment]
"01" s01e001 => indicates the series name detected is "01", therefore considered tvdbid, therefore translated to xxx [tvdb-01]

How can an agent mess up the scanner???
That is weird...
