### ISSUE TITLE
Deleted or replaced files are not cleaned up

### ISSUE THREAD

**Issue by Gumbyohson** [ZeroQI/Absolute-Series-Scanner#282]
I am unsure if this is a HAMA or ASS issue.
I have this issue only on libraries that are covered by these.
Deleted or replaced files are still showing up as (unavailable) in the plex library list. I have tried to do an "empty trash" which completes instantly. Monogatari is an example.
[Monogatari.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4721123/Monogatari.filelist.log) 
[Monogatari.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4721124/Monogatari.scanner.log)
[Plex Media Scanner.1.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4721121/Plex.Media.Scanner.1.log)
[_root_.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4721122/_root_.scanner.log)

**Comment by ZeroQI** [comment]
https://support.plex.tv/articles/200289326-emptying-library-trash/

The file was added to Plex so the scanner did its job
It is not metadata related so not agent related
It is Plex responsibility.

Did you try a library using Plex scanner and agents doing the same to prove the point?
That's the first thing I would have done...

Seem like you have a corrupted database to me:
https://support.plex.tv/articles/201100678-repair-a-corrupt-database/#:~:text=Repair%20a%20Corrupt%20Database,attempt%20to%20repair%20the%20database.

**Comment by Gumbyohson** [comment]
Hey, thanks for confirming. It's weird cause its not effecting the databases plex media scanner is managing. I'll try the database refresh/repair. Thanks.
