### ISSUE TITLE
Single Folder -> Multiple shows

### ISSUE THREAD

**Issue by 19wolf** [ZeroQI/Absolute-Series-Scanner#283]
**Is your feature request related to a problem? Please describe.**
Sonarr uses exclusively TVDB for downloading and organizing media. This is a problem with anime, as some shows are intended to be listed separately, not as "seasons". Ex. the Monogatari series.

**Describe the solution you'd like**
My anime is automatically downloaded and sorted (by sonarr) as such-
```
/data/Media/Anime/Monogatari (2009) [tvdb3-102261]
├── Monogatari - 27 - Tsubasa Tiger - Part 1 [HorribleSubs - HDTV-720p - x264 AAC].mkv
├── Monogatari - 28 - Tsubasa Tiger - Part 2 [HorribleSubs - HDTV-720p - x264 AAC[JA]].mkv
├── Monogatari - 29 - Tsubasa Tiger - Part 3 [HorribleSubs - HDTV-720p - x264 AAC].mkv
├── Monogatari - 30 - Tsubasa Tiger - Part 4 [HorribleSubs - HDTV-720p - x264 AAC [EN]].mkv
├── Monogatari - 31 - Tsubasa Tiger - Part 5 [HorribleSubs - HDTV-720p - x264 AAC].mkv
etc.
```
These particular episodes end up shown in "Season 3" when they are actually the "Nekomonogatari" series. I would like them to be matched with and appear as a separate show within the "Monogatari" collection, rather than a Season within a show.

Edit: In this case, the scanner correctly identifies that the files belong in another show (anidb-id), and then is able to present it as a season. But instead, I'd like it to be presented as the other show.

**Describe alternatives you've considered**
I could manually rename and track all my anime, but with over 200 shows, this is not feasible nor automated via sonarr.

**Additional context**
(Comparing to wikipedia, it seems my absolute episode numbers don't quite match up correctly, but this is unrelated.) I have other examples if necessary.

**Comment by ZeroQI** [comment]
Monogatari Series are the worst anime to rename so you will need to make choices, generally rename the series that are special manually. 
After all if it's worth downloading and watching, it is worth renaming...

" [tvdb3-102261]" means you forced TheTVDB numbering and tvdb3 mode so **creation of season folder and keeping absolute numbering for the episode number**
- TheTVDB series 102261 is Monogatari [https://thetvdb.com/series/monogatari]
- abs number ep 27 => s03e01 will be showing as s03e27, exactly as tvdb3 dictates https://thetvdb.com/series/monogatari/episodes/4318918
- Nekomonogatari is tvdb season 3
- Nekomonogatari only exist standalone in anidb under Monogatari Series: Second Season [https://anidb.net/anime/9183] 
- it will cross reference AniDB 

You FORCED the series TVDB ID asking it to put eps in season folders, and it work as designed.
You should have renamed the folder [anidb-9183-s1-26] to remove the offset and assign to AniDB numbering so you don't have to rename files... (manual anidb forced id + Manual season and offset numbering)

**Comment by 19wolf** [comment]
Another example is Clannad and Clannad After Story

Sonarr will download all episodes with an absolute numbering. What do I need to do to make it show up as two separate entries, per anidb? I can automate naming as tvdb with seasons or absolute numbering (per tvdb).

**Comment by ZeroQI** [comment]
It can't be done if I am correct as all files inside a series folder at root level will belong to the same series, even if the scanner gives it a different title, so in short you cannot have one folder show up as 2 entities under the scanner currently.

Sonarr was asked for AniDB support 
- https://forums.sonarr.tv/t/use-anidb-for-anime/11340/3
- https://www.reddit.com/r/sonarr/comments/3zqofj/anime_watchers_is_sonarr_your_primary_tool_to/

Only this scanner re-number season and episodes but i cannot implement that, sorry.
