### ISSUE TITLE
Forcing Anidb series ID leads to wrong date

### ISSUE THREAD

**Issue by Columbo199X** [ZeroQI/Absolute-Series-Scanner#287]
I recently switched from adding each series separately to Plex to only having one directory to add it automaticly.
However this lead to a problem after readding the series.
This is the main directory set in the Plex Libary: 
A:\Anime
This is how the directory on my hdd looks like:
Anime/Dirty Pair/Dirty Pair [anidb-401]
Anime/Dirty Pair/Dirty Pair - Project EDEN [anidb-1032]
Both entrys get added properly but they both show up with the same release date. So even though Project Eden released in 1987 it shows 15. July 1985 which is the release date of the original Dirty Pair series. 
This only happens when there are multiple entries in one folder.

**Comment by ZeroQI** [comment]
The unique ID given by the agent changes so it makes no sense.i need HAMA custom series logs for Project Eden

**Comment by Columbo199X** [comment]
Are these the logs you need?
![235184384](https://user-images.githubusercontent.com/67553546/85955277-b52e9180-b97d-11ea-8bb7-2eb6c12e3903.png)

**Comment by ZeroQI** [comment]
Yes

**Comment by Columbo199X** [comment]
[[1987] Dirty Pair - Project Eden [anidb-1032].agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4842870/1987.Dirty.Pair.-.Project.Eden.anidb-1032.agent-update.log)
[[1987] Dirty Pair - Project Eden [anidb-1032].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4842874/1987.Dirty.Pair.-.Project.Eden.anidb-1032.agent-search.log)

**Comment by Columbo199X** [comment]
[[1987] Dirty Pair - Project Eden.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4842876/1987.Dirty.Pair.-.Project.Eden.filelist.log)
[[1987] Dirty Pair - Project Eden.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4842877/1987.Dirty.Pair.-.Project.Eden.scanner.log)

**Comment by Columbo199X** [comment]
After a complete reinstallation of Plex Server and HAMA/ASS it seems to work again.
![452313241](https://user-images.githubusercontent.com/67553546/85962209-cdb79f80-b9af-11ea-8d25-4cde91161f2f.png)

**Comment by ZeroQI** [comment]
Agent logs (now removed) showed date came from TheTVDB which would have the show as special or season of the original.
Being banned on AniDB would provide no meta from AniDB...
