### ISSUE TITLE
Absolute Series Scanner recognizes S2 anime wrong 

### ISSUE THREAD

**Issue by eslamsidereel** [ZeroQI/Absolute-Series-Scanner#293]
Hi,
I am an anime lover and Absolute Series Scanner is essential for me, but I noticed that it recognizes episodes named like this `Enen no Shouboutai S2 - 01 [480]` or ` Kaguya-sama wa Kokurasetai S2 - 05 [480]` as the second episodes. Therefore plex puts it all in the same episode (2).
In order to fix the issue I have to rename the anime to something like `Season 2` or removing S2 all together.
Any way to fix this?

Sorry for my bad english

**Comment by ZeroQI** [comment]
S2 are for specials 2
If I consider grouping folders and a series folder with the name in S2, we cannot drop it and cannot consider it season 2 neither...

You have to match the series name as it will be subtracted from the filename:
Enen no Shouboutai S2/ Enen no Shouboutai S2 ep01 title.ext

**Comment by eslamsidereel** [comment]
OK I get it now thanks for replying. I have to rename the files after downloading.

**Comment by ZeroQI** [comment]
Or the series folder title more simply ...

**Comment by eslamsidereel** [comment]
> Or the series folder title more simply ...

I always name the series folder like `Enen no Shouboutai Season 2` or `Enen no Shouboutai Second season`, so I guess it should recognize episode numbering correctly. I use automated downloads so it is a bit tedious to rename all downloaded episodes named `S2`.

**Comment by ZeroQI** [comment]
"I always name the series folder like Enen no Shouboutai Season 2 or Enen no Shouboutai Second season, so I guess it should recognize episode numbering correctly" -> Not is you leave the series name in the episodes filename as "xxx S2"
- Enen no Shouboutai S2/ Enen no Shouboutai S2 ep01 title.ext => no issue but may require manual matching
- Enen no Shouboutai Second season/ Enen no Shouboutai S2 ep01 title.ext => issue
- Enen no Shouboutai Second season/ Enen no Shouboutai Second season ep01 title.ext => no issue

if you just rename the folder name with the same series name as the episodes then all works
if you name them differently the episode name with series name ending is S2 will be taken for Season 0 episode 2 as per Anidb numbering
