### ISSUE TITLE
Error when running on linuxserver/plex docker

### ISSUE THREAD

**Issue by isyangban** [ZeroQI/Absolute-Series-Scanner#296]
Hi. Thanks for the great program.
I tried your scanner on plex docker (https://hub.docker.com/r/linuxserver/plex) with additional python dependencies installed. (python3-lxml libxslt-dev libxml2-dev)

Same error occurs on  554 line and 614 lines. They are the same code. If I comment out those lines, it works well.

```bash
plex    | Error in Python: Running scanner:
plex    | Traceback (most recent call last):
plex    |   File "/config/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 614, in Scan
plex    |     Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id"), root, path, len(files or []), len(dirs or [])))
plex    | UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

```

**Comment by ZeroQI** [comment]
I do not have issues reported when ran from Plex
When run manually you get an error  indicating a conversion when no conversion is taking place seemingly...
Note sure the reported line is at fault, but if it is, there are steps to mitigate in link below
https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

**Comment by isyangban** [comment]
I didn't run the python code manually, it's just the stdout from the docker.

**Comment by ZeroQI** [comment]
It seem to be an issue with that docker image

Please check https://forums.unraid.net/topic/40463-support-linuxserverio-plex-media-server/page/97/
"interestingly enough, I had switched back to the plex official docker, which worked fine"

Did you try the plex official docker ?

**Comment by isyangban** [comment]
I'll check out the official plex docker and check if the problem persists.

**Comment by ZeroQI** [comment]
Any update ?

**Comment by disrupted** [comment]
I was actually thinking of switching from the official Docker image to linuxserver but this makes me hesitant. Thanks for the heads up.

**Comment by ZeroQI** [comment]
To my knowledge, no issue with official Docker image, might have dependencies issues for Python on other docker images.
If the agent (which is OS agnostic) doesn't work on one docker image, then that image is wrong...

**Comment by isyangban** [comment]
I've tested on the official Plex docker image and it works without any problems. I guess linuxserver's Plex image have some problems (I'm too lazy to investigate why). I don't think it's a dependency problem because I built a custom docker image on top on linuxserver and just included any missing dependencies.

Thanks for the interest btw.
