### ISSUE TITLE
Issue with Accel World Specials

### ISSUE THREAD

**Issue by meisnate12** [ZeroQI/Absolute-Series-Scanner#297]
So I have the Accel World [anidb4-8691] folder in my library shown as below
![Image 1](https://user-images.githubusercontent.com/1631064/88126554-c85d0780-cb9f-11ea-9907-0c069334390c.png)

which comes up in plex as 
![Image 2](https://user-images.githubusercontent.com/1631064/88126575-d3b03300-cb9f-11ea-8ffd-fc9abbbbaaa1.png)

the S00E01 is being scanned in as S00E02 is this an issue or do I have something wrong

[Accel World [anidb4-8691].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4957468/Accel.World.anidb4-8691.agent-search.log)
[Accel World [anidb4-8691].agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4957469/Accel.World.anidb4-8691.agent-update.log)
[Accel World [anidb4-8691].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4957470/Accel.World.anidb4-8691.filelist.log)
[Accel World [anidb4-8691].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/4957471/Accel.World.anidb4-8691.scanner.log)

**Comment by EndOfLine369** [comment]
This is as designed as your using "anidb4" that maps to TVDB episode listings. If you don't want it changed or potentially combined with other Accel World series (point of anidb2/3/4) just use standard `[anidb-8691]`.

Mapping of AniDB S0E1 -> TVDB S0E2 
`'s0e1': 's0e2'`
From below via ScudLee mapping:
`anidb: '8691', tvbdid: '257516', name: 'Accel World', mappingList: {'s0e5': 's0e6', 's0e8': 's0e9', 's0e6': 's0e7', 's0e7': 's0e8', 's0e4': 's0e5', 'defaulttvdbseason_a': False, 's0e2': 's0e3', 's0e3': 's0e4', 's0e1': 's0e2', 'defaulttvdbseason': '1', 'episodeoffset': '0'}`

There are no specials for https://anidb.net/anime/8691 after S0E8 so your S0E10 is not remapped.
Your S0E10 is actually S1E2 from https://anidb.net/anime/9187

**Comment by ZeroQI** [comment]
Ditto
