### ISSUE TITLE
Episodes with season number (S5) reported as season 1 episodes

### ISSUE THREAD

**Issue by Ariane-B** [ZeroQI/Absolute-Series-Scanner#301]
Whenever episodes are named with a season-centric numbering (I can't really help it... sometimes they release them numbered absolutely, and other times they restart the numbering on a per-season basis), the scanner attributes them to season 1. Currently, I can see this happening with Shokugeki no Soma S5 and Enen no Shouboutai S2.

I'm not sure if this counts as a bug or a feature request, but I wish the scanner could manage both absolute and per-season numbering if the file name contains an indication to it. (For example, "S<number>")

## Platform

Operating system and version: Windows 10 Pro, version 2004
Plex version: 4.34.4 (Media server 1.20.1.3252)

## Expected Behavior

Shokugeki no Soma S5, episode 11 should be Shokugeki no Souma - Gou no Sara, episode 11 (The Taste of Failure)

## Current Behavior

Instead, it's reported as season 1, episode 11.

Log: [Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5212891/Plex.Media.Scanner.log)

## Steps to Reproduce

1. Add to your library a file called [HorribleSubs] Shokugeki no Soma S5 - 11 [1080p].mkv
2. Refresh library.
3. See that your library will refer to it as Episode 11 from season 1 (The Magician that came from the East).

**Comment by Ariane-B** [comment]
Just realized https://github.com/ZeroQI/Absolute-Series-Scanner/issues/293 is exactly what I was talking about. You said we should rename things, but I really wish I didn't have to do that every time.

Is it possible (in a simple way) for me to add a special rule to my library that would say "when there's an S in the file name, prioritize considering that a season number"? Because I've seen a lot of file names with S for season, but specials are by definition a rare thing, and I don't think I've ever had to deal with an S in their file names.

**Comment by ZeroQI** [comment]
Don't you have an absolute series scanner folder in logs folder with the series scanner logs?
I would need the *.filelist.log and *.scanner.log

**Comment by Ariane-B** [comment]
[Absolute-Series-Scanner-master.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5213151/Absolute-Series-Scanner-master.filelist.log)
[Absolute-Series-Scanner-master.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5213152/Absolute-Series-Scanner-master.scanner.log)

I'm not 100 % sure. Is this what you want?

**Comment by Ariane-B** [comment]
[Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5213155/Logs.zip)
Just in case, here's my whole logs folder.

**Comment by ZeroQI** [comment]
_root_.scanner.log show the library

id:  7, type: show  , agent: com.plexapp.agents.thetvdb    , scanner: Absolute Series Scanner       , library: Anime Test              , path: C:\Users\azma\Downloads
Cannot see any logs for impacted series for some reason...

Supported namings otherwise, it will be taken as season 1 indeed
- Shokugeki no Soma/Season 05/[HorribleSubs] Shokugeki no Soma S5 - 11 [1080p].mkv
- Shokugeki no Soma S5 [tvdb-*****-s5]/[HorribleSubs] Shokugeki no Soma S5 - 11 [1080p].mkv

**Comment by EndOfLine369** [comment]
Those logs are irrelevant and not for the library "Anime" you appear to be using. You would have to provide the ones for your library from your HAMA logs location as you are using ASS against a HAMA managed library and thus with all your other HAMA logs for that library.

Logs aside, there is no issue here. We can not have ASS see any 'SX' in a filename, outside of a recognized regex pattern, to be seen as any anything other than a special entry.

If you want to see them as anything outside of Season 1 without fixing the filenames, your only option is to use modes "anidb2/3/4" via https://github.com/ZeroQI/Absolute-Series-Scanner#forcing-the-movieseries-id if "anidb->tvdb" mapping is present to get AniDB entries remapped to TVDB entry placements.

As you basically want an AniDB numbered entry in a TVDB numbering format.
