### ISSUE TITLE
Movies in a series library and anidb2 force id mode assign series "xxx [tvdb-1]"

### ISSUE THREAD

**Issue by OmegaToken** [ZeroQI/Absolute-Series-Scanner#302]
I tried to order my collection
For that I renamed all movies and episodes so that the containing folder holds the [anidb2-????] Tag.

Most of the files are working but some files got placed in the  xxx [tvdb-1] folder.
The folder look like a collection of errors. There are different Movies and Episodes mixed into one entry as versions. (See Image)
![Screenshot 2020-09-21 170957](https://user-images.githubusercontent.com/70204881/93784594-7c752000-fc2d-11ea-968f-faa41aeac4a7.png)

The log files do give me no hint, or at least I do not know what I am looking for.

I use the actual ASS and HAMA Plugins

**Comment by ZeroQI** [comment]
Please use anidb OR tvdb mode only, as 3 of the anidb2 mode you chose are devoid of any logic
You cannot map a single movie to a non-existant series. What is wrong with [anidb-xxx] force id?

**Comment by OmegaToken** [comment]
>>What is wrong with [anidb-xxx] force id?
Based on the description I got the impression that if using anidb-xxx Episodes of Series will not combined into one entry.

**Comment by ZeroQI** [comment]
It needs the tvdbid in mapping file and mapping matching tvdb numbering exactly 

With what were you trying to group little nemo?

**Comment by OmegaToken** [comment]
I just downloaded ASS and Hama and created the library after scanning the description for important settings.
I did not make any modification to mapping files or whatsoever. The only thing I tried is to add AniDB in the Settings for Posters.

**Comment by OmegaToken** [comment]
I checked the mapping and did a minimalistic test run and there seems to be some problems.
I droped the old one did make a cleanup and then added a new mediatek. As you can see on the images
![AnimeFolder](https://user-images.githubusercontent.com/70204881/93867166-f3132b80-fcc8-11ea-8586-bf81aad9ce85.png)
![Plex](https://user-images.githubusercontent.com/70204881/93867272-1938cb80-fcc9-11ea-9476-d4d877d7b4e8.png)
.hack is not recognised at all. Whitch is I suspect because of the leading . whitch on linux systems would mean hidden.

1000-nen Joou is not recogliced at all and can not be found in the mediatek.
Ookami Kodoo no Ame to Yuki did show up in the xxx folder.

All Series/Movies listed have an valid ScudLee tvdbid mapping. The only exception is
Ookami Kodoo where the mapping has no id but the entry movie.
  <anime anidbid="8832" tvdbid="movie" defaulttvdbseason="1" imdbid="tt2140203">
    <name>Ookami Kodomo no Ame to Yuki</name>
  </anime>

So I reopen this Issue because the documentation clearly states that as long as the mediatek is if type series movies are also supported.
Copy From ASS description
- Movies in series libraries support (names same as folder or contain " - Complete Movie")

**Comment by ZeroQI** [comment]
The scanner run once, then never again as long as the folder content is not modified, so if you just rename the folder name, nothing changes at Plex level, hence why i advised the plex dance [https://forums.plex.tv/t/the-plex-dance/197064]

You can do a Naruto Collection to group series and can select to hide items in collections in the library settings

1000-nen Joou is not recognized at all and can not be found in the Sereis library => need scanner logs for the folder

xxx [tvdb1] is indead a cache of the title in Plex database. Did you remove the items, re-scanned, clean bundles, than added back and re-scanned as per the plex dance advised ?

**Comment by OmegaToken** [comment]
@ZeroQI 
Since I suspect some plex database corruption I deleted the database an will rebuild it with my normal movies and series.
After that I will delete all the logfiles start plex and create the mediatek Anime with some Testfiles again and send you all created Logfiles, if my problem still remains?

Should I try anidb2-xxx again or anidb-xxx?

As for Ookami Kodomo no Ame to Yuki
I did copy the exact entry into my comment, It only seems that github did hide the xml since I did not encapsulate it in an code tag. Sorry my bad.

**Comment by OmegaToken** [comment]
So ok Fresh from the start.... after creating andloading my test files.
My test environment
![AnimeFolder](https://user-images.githubusercontent.com/70204881/93887308-d38afb80-fce6-11ea-8abe-c300f0f6b0eb.png)
The resulting logs

[_root_.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5261637/_root_.scanner.log)
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5261640/Plex.Media.Scanner.log)
[Plex Media Server.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5261641/Plex.Media.Server.log)

Current Status
.hack is not shown at all
1000-nen Joou is not shown at all but it is mixed up as version in the xxx [tvdb-1] folder.
Naruto looks ok.
Naruto Narutimate Hero 3 looks ok
Naruto Shippuden looks ok
Ookami Kodomo moved to xxx [tvdb-1] folder
Nauto The Cross Roads only japanese Title is shown. -> This is new, an hour ago this was working. It is realy hard to track anything down if the result is different every time I run the test. Even with same starting parameters.

As for tvdb Ookami has is the only title in this test that has no tvdbid. The entry in the ScrudLee xml is posted above.

**Comment by OmegaToken** [comment]
Just to be clear the .hack is not an issue since I simply can rename it to dothack and it is working. The other things are...

**Comment by ZeroQI** [comment]
Issues mentioned
- [ASS] .hack is not shown at all due to leading dot. That is a bug. ASS scanner logs missing
- [ASS] Series showing under "xxx [tvdb-1]" ("1000-nen Joou" and "Ookami Kodomo"). ASS scanner logs missing
- [HAMA] "Naruto The Cross Roads" only japanese Title is shown. The answer is in the Hama series specific logs. You may be AiDB banned temporarily
- [HAMA] same poster on multiple series. The answer is in the Hama series specific logs. Since the poster is from TheTVDB, and they all point to the same series, if there is not enough posters it is possible, or you didn't "clear bundles" and Plex remembers the database information as it was the same files, even if you deleted the libraries...

There is no series specific agent or scanner logs attached...
What other logs did you have alongside the file "root.scanner.log" in the same folder ?

**Comment by OmegaToken** [comment]
There are none.
Do I have to activate them somewhere?

**Comment by OmegaToken** [comment]
Ok I think I found something.
1.) The Logs for the Plugins are not located in the Logs folder instead they can be found in the Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs folder
2.) There is an bug in the agent where the anidb hint is ignored.
For Example:
[1000-nen Joou (1982) [anidb-764].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5269776/1000-nen.Joou.1982.anidb-764.agent-search.log)
As you can see the anidb hint is ignored instead an tvdb hint with id 1 is enforced, this is compleatly wrong.
Well the scanner log for the folder gives away an hint
```
=============================================================================================================================================================
Forced ID (series folder) - source: "anidb", id: "764"
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'nen': 2, 'Complete': 1, 'Movie': 1, 'T1': 1, '1': 1, '1000': 2, 'Trailer': 1, 'Joou': 2}
misc_words: []
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"1" s01e001                         "Word Search" "" "1000-nen Joou - 1 - Complete Movie [Henshin-BOX](41AC7FC1).mkv"
"1000-nen Joou (1982) [anidb-764]" s00e201                         "ANIDB_RX-3" "Trailer" "1000-nen Joou - T1 - Trailer [Henshin](CAC4AA38).mkv"
=============================================================================================================================================================
```
The "1" did give me an idea and I changed the Filename
Now the scanner.log shows
```
=============================================================================================================================================================
Forced ID (series folder) - source: "anidb", id: "764"
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'nen': 2, 'Complete': 1, 'Movie': 1, 'T1': 1, '1000': 2, 'Trailer': 1, 'Joou': 2}
misc_words: []
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"1000-nen Joou (1982) [anidb-764]" s00e201                         "ANIDB_RX-3" "Trailer" "1000-nen Joou - T1 - Trailer [Henshin](CAC4AA38)[anidb-764].mkv"
"1000-nen Joou (1982) [anidb-764]" s00e501                         "__" "Complete Movie" "1000-nen Joou - Complete Movie [Henshin-BOX](41AC7FC1)[anidb-764].mkv"
=============================================================================================================================================================
```
And the agent search log changed to 
[1000-nen Joou (1982) [anidb-764].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5269839/1000-nen.Joou.1982.anidb-764.agent-search.log)

As you can see now Title changed from "1" to "1000-nen Joou (1982) [anidb-764]" and name changed from "None" to "Complete Movie" and most important the Forced ID log now shows source: anidb and id 764 what was expected in the first place.
The fact that a simple number in the title throw the forced id of balance is troublesome since that should never be the case as soon a  force id is present.

After that I tried to rename the file to "1000-nen Joou - 2 - Complete Movie [Henshin-BOX](41AC7FC1).mkv" and guess what now the message reads
````
Forced ID - source: tvdb, id: 2, title: 'xxx'
````
So there is a bug where a number in the title overrides the forced id and the source with tvbd and whatever number is found.

**Comment by ZeroQI** [comment]
"D:\Anime\1000-nen Joou (1982) [anidb-764]\1000-nen Joou - 1 - Complete Movie [Henshin-BOX](41AC7FC1).mkv" indeed should keep the forced id, but "- Complete movie" was meant to be single file if a folder created by WebAOM, and all before " - Complete Movie" is the series title, which should have been "1000-nen Joou - 1"...
The title is wrongly changed to "1" (erasing forced id), and because the title has been changed to a number, the agent considers it a tvdb id...

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py line 954
`if " - Complete Movie" in ep:  ep, title, show = "01", ep.split(" - Complete Movie")[0], ep.split(" - Complete Movie")[0]   ### Movies ### If using WebAOM (anidb rename)
`
To test if it resolves:
`if " - Complete Movie" in ep:  ep = "01"   ### Movies ### If using WebAOM (anidb rename)`

**Comment by OmegaToken** [comment]
@ZeroQI Thanks for the help. I think I'm getting better at understandig Plex and scripts at all. Damn I would kill if there was a posibility to debug the python scripts.

> "D:\Anime\1000-nen Joou (1982) [anidb-764]\1000-nen Joou - 1 - Complete Movie [Henshin-BOX](41AC7FC1).mkv" indeed should keep the forced id, but "- Complete movie" was meant to be single file if a folder created by WebAOM, and all before " - Complete Movie" is the series title, which should have been "1000-nen Joou - 1"...
> The title is wrongly changed to "1" (erasing forced id), and because the title has been changed to a number, the agent considers it a tvdb id...

I do see the point, the problem is that many Movies in AniDB are called "Complete Movie". Especially if there are "Part 1 of x" Versions of the movie too, in that case the name would be "Part 1 of x"

> https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py line 954
> `if " - Complete Movie" in ep: ep, title, show = "01", ep.split(" - Complete Movie")[0], ep.split(" - Complete Movie")[0] ### Movies ### If using WebAOM (anidb rename) `
> To test if it resolves:
> `if " - Complete Movie" in ep: ep = "01" ### Movies ### If using WebAOM (anidb rename)`

The change does work at least as far as I have tested it. I will start to scan my whole library and the see what the out come is. If the change does do more harm than could I could change the naming template for all files in the type movie. The only problem with that is that AniDB nows some types (Others, Web, ...) that can hold movieish or serieish named files, in that case it would be an case to case naming which I would like to avoid.

Conclusion:
> [ASS] .hack is not shown at all due to leading dot. That is a bug. ASS scanner logs missing
They did not show up in any log so I assume Plex is ignoring them and there is nothing agents or scanners can do about it
> [ASS] Series showing under "xxx [tvdb-1]" ("1000-nen Joou" and "Ookami Kodomo"). ASS scanner logs missing
The suggested change seems to solve this particular problem
> [HAMA] "Naruto The Cross Roads" only japanese Title is shown. The answer is in the Hama series specific logs. You may be AiDB banned temporarily
This was my fault I messed up the language priority and this particular  movie did only have a few languages inserted. After fixing it the english Title was shown as expected.
> [HAMA] same poster on multiple series. The answer is in the Hama series specific logs. Since the poster is from TheTVDB, and they all point to the same series, if there is not enough posters it is possible, or you didn't "clear bundles" and Plex remembers the database information as it was the same files, even if you deleted the libraries...
HArd to tell if it is a bug or just work as designed. You are right that they all point to the same Series, however I changed posters to be taken from anidb only. My expectation was that then the one Poster that is visible on the anidb page for that series/movie is used. That does not seem to be the case since even after recreating the library more that one poster was available even when AniDB only should deliver one. I can rule out caching since I deleted all caches and even used a new sourcefolder and a new library to test this.

Suggestion:
Since taking the information from the Filename seems quite fragile. Wouldn't it be better if on folders decorated with [anidb-xxx] all information regarding the servies/movie is only taken from anidb. And thinking ahead would'nt it be better to let files be decorated with [anidb-yyy] where yyy is the episodeid from anidb and regardles of file name every data is taken from anidb too.
And if that hints are given Filenames and directory names are ignored compleatly. That way regardles of file/directory name the entries get always the expected Entry.

For completition I use AniAdd to rename and organize my Anime Library
The actual script is posted below. I take suggestions on that site too
``` 
Trunc(str, len):= $repl(%str%, ".{" $len($repl(%str%, "(.?){" %len% "}$", "")) "}$", "")
TruncEllipse(str, len):= { $len(%str%) = $len($Trunc(%str%, %len%)) ? %str% : $Trunc(%str%, %len%) "..." }
TooLong(path):= { $max($len(%path%), "256") = "256" ? "0" : "1" }

AT:=[%ATr%,%ATe%,%ATk%]
AT:= $repl(%AT%,'^\.',"dot")
AT:= $repl(%AT%,'[\\\":/*|<>?]',"")
AT:= $repl(%AT%,' \([0-9][0-9][0-9][0-9]\)$',"")
ET:=[%ETe%,%ETr%,%ETk%]
GT:=" [" [%GTs%,%GTl%] "]"
GT:=$repl(%GT%," \[raw\]","")
GT:=$repl(%GT%," \[\]", "")
CRC:="("$uc(%FCrc%)")"
NaN:= $repl(%EpNo%, "[0-9]", "_")

EpNoPad:= { $substr(%NaN%, "0", "1") = "_" ? $pad(%EpNo%,$max($len(%EpHiNo%),$len(%EpCount%)),"0") : %EpNo% }

Ver:={%Ver%="1"?"":"v"%Ver%} 

FileNameLong:=%AT%" - "%EpNoPad% %Ver%" - "%ET%%GT%%CRC%
FileNameMedium:=$TruncEllipse(%AT%,"79")" - "%EpNoPad% %Ver%" - "$TruncEllipse(%ET%, "17")%GT%%CRC%
FileNameShort:=$TruncEllipse(%AT%,"97")" - "%EpNoPad% %Ver%%GT%%CRC%
PathNameLong:="D:\Anime\" %AT%" ("%AYearBegin%") [anidb-"%AId%"]"
PathNameShort:="D:\Anime\" $TruncEllipse(%AT%,"76")" ("%AYearBegin%") [anidb-"%AId%"]"

FullPathLong:=%PathNameLong% "\" %FileNameLong%
FullPathMedium:=%PathNameLong% "\" %FileNameMedium%
FullPathShort:=%PathNameLong% "\" %FileNameShort%
FullPathShort2:=%PathNameShort% "\" %FileNameMedium%

FileName:={$TooLong(%FullPathLong%)="1" ? {$TooLong(%FullPathMedium%)="1" ? {$TooLong(%FullPathShort%)="1" ? {$TooLong(%FullPathShort2%)="1" ? %FileNameShort% : %FileNameMedium%} : %FileNameShort%} : %FileNameMedium%} : %FileNameLong%}
PathName:={$TooLong(%FullPathLong%)="1" ? {$TooLong(%FullPathMedium%)="1" ? {$TooLong(%FullPathShort%)="1" ? %PathNameShort% : %PathNameLong%} : %PathNameLong%} : %PathNameLong%}
```

**Comment by ZeroQI** [comment]
> Wouldn't it be better if on folders decorated with [anidb-xxx] all information regarding the servies/movie is only taken from anidb
- Translation: movies in series libraries cause a scanner issue, let's change the agent???
- It will use specials numbering from the source given but cross reference anidb eps to TheTVDB. TheTVDB has better episode title languages also.
- you would get crap quality posters, no episode titles nor episode summaries...
- We cannot make a distinction between assigned an id and forced assigned the same id

"Hard to tell if it is a bug or just work as designed. "
- not hard, it's in the logs, which for the *.update.log are very well documented
- priority for posters however cannot be changed after the fact so if you change settings, the previously active poster will stay active, needing a plex dance

You have to understand the difference between scanner and agent. 
- the scanner will give a series title (used by agent search, updated by agent update), choose season and ep number. it is not meant to download meta but i had it download info to rename season/episode numbers
- the agent search will assign a fixed ID
- the agent update take the ID and update the metadata

Please confirm if the code update works for you and i will include in master code

**Comment by OmegaToken** [comment]
I can confirm that the problem with the xxx folder is gone.
