### ISSUE TITLE
Grouping folders recognise error at windows when folder name has special character like "☆", "／"

### ISSUE THREAD

**Issue by littleneko** [ZeroQI/Absolute-Series-Scanner#305]
## Platform
Operating system and version: Windows Server 2016  (zh_cn)
Plex version: 1.20.2.3402

## Expected Behavior
my test folder and file like this:
```
D:\TEST_PLEX
├─Date A Live [BD 1080p AVC Hi10pHEVC Ma10p FLAC MKV] - VCB-Studio
│  ├─[Makino House&VCB-S&philosophy-raws] Date A Live Mayuri Judgement [Ma10p_1080p]
│  │      1.mkv
│  │
│  ├─[VCB-Studio&philosophy-raws] Date A Live [Hi10p_1080p]
│  │      1.mkv
│  │
│  └─[VCB-Studio&TUcaptions] Date A Live II [Hi10p_1080p]
│          1.mkv
│
└─Fate／Kaleid Liner Prisma Illya S1-S4 [BD 1920x1080 Ma10p FLAC] - VCB-Studio
    ├─[VCB-Studio] Fate／Kaleid Liner Prisma Illya 2wei Herz! [Ma10p_1080p]
    │      1.mkv
    │
    ├─[VCB-Studio] Fate／Kaleid Liner Prisma Illya 2wei! [Ma10p_1080p]
    │      1.mkv
    │
    ├─[VCB-Studio] Fate／Kaleid Liner Prisma Illya 3rei!! [Ma10p_1080p]
    │      1.mkv
    │
    └─[VCB-Studio] Fate／Kaleid Liner Prisma Illya [Ma10p_1080p]
            1.mkv
            2.mkv
```
I expected all the "Date A Live [BD 1080p AVC Hi10pHEVC Ma10p FLAC MKV] - VCB-Studio" and "Fate／Kaleid Liner Prisma Illya S1-S4 [BD 1920x1080 Ma10p FLAC] - VCB-Studio" are `Grouping folders`.

## Current Behavior
But it only treat the "Date A Live ..." as a Grouping folder, and "Fate／Kaleid Liner Prisma Illya ..." not a `Grouping folder`.

(i modified the .py file add some log and re pattern for me)
[_root_D -TEST_PLEX.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5332474/_root_D.-TEST_PLEX.scanner.log)
[_root_D -TEST_PLEX.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5332475/_root_D.-TEST_PLEX.filelist.log)
[Date A Live [BD 1080p AVC Hi10pHEVC Ma10p FLAC MKV] - VCB-Studio.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5332479/Date.A.Live.BD.1080p.AVC.Hi10pHEVC.Ma10p.FLAC.MKV.-.VCB-Studio.filelist.log)
[Date A Live [BD 1080p AVC Hi10pHEVC Ma10p FLAC MKV] - VCB-Studio.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5332480/Date.A.Live.BD.1080p.AVC.Hi10pHEVC.Ma10p.FLAC.MKV.-.VCB-Studio.scanner.log)
[Fate／Kaleid Liner Prisma Illya S1-S4 [BD 1920x1080 Ma10p FLAC] - VCB-Studio.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5332482/Fate.Kaleid.Liner.Prisma.Illya.S1-S4.BD.1920x1080.Ma10p.FLAC.-.VCB-Studio.filelist.log)
[Fate／Kaleid Liner Prisma Illya S1-S4 [BD 1920x1080 Ma10p FLAC] - VCB-Studio.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5332483/Fate.Kaleid.Liner.Prisma.Illya.S1-S4.BD.1920x1080.Ma10p.FLAC.-.VCB-Studio.scanner.log)

## Additional information
1. It's work well at Linux.

2. It debug the code, and found `os.path.isdir(path_item)` is not work as expected at windows when the folder has some special character.

e.g.
```
# env py2
# -*- coding: utf-8 -*-

print os.path.isdir("A／B").   # notify "／" is not "/"
# False
print os.path.isdir(u"A／B")
# True
print os.path.isdir("A／B".decode('utf-8'))
# True
```

```
        ### Process subfolders ###
        subdir_dirs, subdir_files = [], []
        folder_count[path]        = 0
        for file in os.listdir(full_path):
          path_item = os.path.join(full_path, file) 
          if os.path.isdir(path_item):                 subdir_dirs.append(path_item);  folder_count[path] +=1  #Fullpath
          elif extension(file) in VIDEO_EXTS+['zip']:  subdir_files.append(path_item)                          #Fullpath
        if not subdir_files and subdir_dirs:  # Only add in subfolders if no valid video files in the folder
          Log.info(''.ljust(157, '-'))
          for x in subdir_dirs:  Log.info("[Added] " + x);  subfolders.append(x)
```

**Comment by ZeroQI** [comment]
Notes
- You have two grouping folders indeed with series folder inside 
- Your char (UTF8  0xEF 0xBC 0x8F or efbc8f) gets translated to the forbidden char "/"which is not a supported character in windows for files or folders name, as it is a folder separator (source http://www.fileformat.info/info/unicode/char/ff0f/index.htm)

I can add to translation table but should i replace it by a space or do you have anything else in mind ?

**Comment by littleneko** [comment]
Oh，I found out that not only the character "／" result in the error，*all the no ASCII character* are working wrong at windows, the chinese, japanese and other no ascii character.
So may be i should rename my all grouping folders to ascii character name.

**Comment by ZeroQI** [comment]
All the 3 bytes per character languages need the right packages loaded in the OSi believe or there may be issues, yes.
ASCII is the way to go to be fair. a bad copy/paste with different file format could rename hazardously, but i have users using japanese folder names and it work...

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py line 139 you could try to add to CHARACTERS_MAP:  `15711375:' ',`

**Comment by littleneko** [comment]
Thank you, I have changed my "grouping folders" to ascii character, and now it work well.
The no ascii folder name is only not work when used as grouping folders, single series folder and file name no problem.

**Comment by ZeroQI** [comment]
Really tricky one to solve for me
If it worked before, the link to the update breaking it would make it easier to fix
Have similar issue with a special character in library name, a recent update caused a bug to appear but dunno which version

**Comment by littleneko** [comment]
i fix it by use `decode('utf-8')` at windows, but i don't test at linux.

```
-      parent_dir_nb = len([file for dir in os.listdir(parent_dir) if os.path.isdir(os.path.join(parent_dir, dir))]) #How many folders in folder at root
+      parent_dir_nb = len([file for dir in os.listdir(parent_dir) if os.path.isdir(os.path.join(parent_dir, dir).decode('utf-8'))]) #How many folders in folder at root
```

```
-          if os.path.isdir(path_item):                 subdir_dirs.append(path_item);  folder_count[path] +=1  #Fullpath
+          path_item_unicode = path_item.decode('utf-8')
+          if os.path.isdir(path_item_unicode):                 subdir_dirs.append(path_item);  folder_count[path] +=1  #Fullpath
```
