### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-9: ordinal not in range(128)

### ISSUE THREAD

**Issue by mihidumh** [ZeroQI/Absolute-Series-Scanner#306]
## Platform

Operating system and version: Windows Server 2019 (17763.1457)
Plex version: 1.20.3.3421

## Expected Behavior

Scanner should detect new files.

## Current Behavior

Log file attached.

[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5362384/Plex.Media.Scanner.log)

## Steps to Reproduce

1. Scan for new files.

## Additional information

I've tried updating to the latest ASS version (e83efdc).
I've already tried updating to the latest Python 2.7.18 and Python 3.9.0 as it seems to be related to Python and Unicode.
I've tried restarting afterwards.
It was working until about a week or 2 ago.

**Comment by mihidumh** [comment]
So it would seem to be something to with my library name, Anime 🇯🇵 (https://emojipedia.org/flag-japan/). 
Removing the emoji fixed the issue, although it had been working fine for a while and worked on a new library with the emoji in it.

**Comment by ZeroQI** [comment]
```
Oct 12, 2020 11:18:22.425 [14168] ERROR - We got an error scanning in P:\Anime
Oct 12, 2020 11:18:22.454 [14168] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 554, in Scan
    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id"), root, path, len(files or []), len(dirs or [])))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-9: ordinal not in range(128)
```

Would need to identify which version broke it to see the code change and fix it easily hopefully now that you indicated the character is another codepage seemingly cause the issue to appear

**Comment by ZeroQI** [comment]
Error seem linked to implied str() when using format, which doesn't mean the code can't cope otherwise...
@mihidumh try line 554:
`Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id").encode('utf-8'), root.encode('utf-8'), path.encode('utf-8'), len(files or []), len(dirs or [])))
`

**Comment by ZeroQI** [comment]
@mihidumh can you test and report please?

**Comment by ZeroQI** [comment]
@mihidumh can you test and report please?
