### ISSUE TITLE
Item under Specials vanishes after first scan

### ISSUE THREAD

**Issue by BrutuZ** [ZeroQI/Absolute-Series-Scanner#309]
## Platform

Operating system and version: Windows 10 v2004
Plex version: 1.20.3.3437

## Expected Behavior

Scan the file to library, keep it there unless something changes (file deleted, renamed, etc...)
## Current Behavior

The file will be scanned to library once, not be recognized and therefore removed from library on subsequent scans.
## Steps to Reproduce

1. Modify something inside the folder to trigger a Plex automatic scan
2. Item appears under Specials
3. Trigger manual scan for the Library \ Section
4. Item vanishes from Specials

[Logs](https://1drv.ms/u/s!AgdMVATtnoD9g7J8-7lSckfOKwEVOA?e=KBsKIE)
## Additional information

Folder Structure:
```
anime\
|- InuYasha\
  |- Eps. 001 - 033\
    |- Inuyasha - 01.mkv
    |- (...)
    |- anidb2.id
  |- Eps. 034 - 066\
    |- Inuyasha - 34.mkv
    |- (...)
    |- anidb2.id
  |- (...)\
  |- Season 00\ *
    |- InuYasha - s00e01 - Movie 1.mkv *
    |- thetvdb.id
```
Also tried naming the `*` marked items `Specials` and removing `s00e01` respectively to try variants from the readme, the behavior is the same in every instance.

**Comment by ZeroQI** [comment]
The naming convention looks very clean at first glance until I spotted the file IDs..
Grouping folder 'Inuyasha'
Series 'Eps. 001 - 033' anidb2
Series 'Eps. 034 - 066' anidb2
Series 'Season 00' tvdb

Using a season folder naming to backend force it as a series folder while in a grouping folder could bring unforeseen issues... 
Does it behave the same without thetvdb.id file?

You may want to clean up things using 'transparent' folder

Inuyasha [anidb2-xxxxx]
- Arc 001-033
- Arc 034-066
Inuyasha movie [anidb2-xxxxx]

Or using directly TheTVDB numbering...
Inuyasha [tvdb4-xxxxx]
- season 1 [001-033]
- season2 [034-066]
- specials/ inuyasha movie s00e01.ext

**Comment by BrutuZ** [comment]
> Using a season folder naming to backend force it as a series folder while in a grouping folder could bring unforeseen issues...

Nailed it, renaming the `Season 00` folder to `Movies` which is not reserved seems to have done the trick. A couple section scans later and everything is still where it's supposed to on the Plex library 🙂 

Guess now we know what the "unforeseen issue" was xD
