### ISSUE TITLE
`.plexignore` in subfolder will ignore full entry in root

### ISSUE THREAD

**Issue by christopher2007** [ZeroQI/Absolute-Series-Scanner#311]
I have the following folder structure (example entries generated, tested with them as if):

```
- rootMedia/
    - Deadman Wonderland [tvdb4-247997]/
        - Images/
            - cover1.jpg
            - cover2.jpg
        - s00/
            - 01.mkv
            - 02.mkv
            - 03.mkv
        - s01/
            - 01.mkv
            - 02.mkv
            - 03.mkv
        - `show.jpg`
    - High School D×D [tvdb4-254653]/
        - Images/
            - cover1.jpg
        - s01/
            - 01.mkv
            - 02.mkv
            - 03.mkv
        - s02/
            - 01.mkv
            - 02.mkv
            - 03.mkv
        - _BadBonus/
            - .plexignore
            - 01.mkv
        - `show.jpg`
```

And the content of `rootMedia/High School D×D [tvdb4-254653]/_BadBonus/.plexignore` is:

```
*
```

The media folder is a TV series with HamaTV. The priority is: First `Local Media Assets (TV)` at the top and then `HamaTV` at the bottom.

With the above setup only `Deadman Wonderland [tvdb4-247997]` will be displayed in the Plex Web Interface after scanning the media (as `Deadman Wonderland` with a `Deadman Wonderland Collection`).  
But the `High School D×D [tvdb4-254653]` is not displayed at all with this folder sctructure.

With this, the `High School D×D [tvdb4-254653].filelist.log` has following content:

```
=============================================================================================================================================================
Library: 'rootMedia', root: '/mnt/disk/rootMedia', path: 'High School D×D [tvdb4-254653]/_BadBonus', files: '1', dirs: '0'
Manual scan start: 2020-11-14 10:24:09,746017
plexignore_files: '['.*\\Z(?ms)']', plexignore_dirs: '[]'
=============================================================================================================================================================
# /mnt/disk/rootMedia/High School D×D [tvdb4-254653]/_BadBonus/.plexignore
--------------------------------------------------------------------------------------------------------------------------------------
# - *
-------------------------------------------------------------------------------------------------------------------------------------------------------------
# File: 'High School D×D [tvdb4-254653]/_BadBonus/01.mkv' match '.plexignore' pattern: '<_sre.SRE_Pattern object at 0x1484f3215730>'
[no files detected] Grouping folder skip as >1 folder [return]
```

There are no other log files in the same folder starting with `High School D×D [tvdb4-254653]`.

When I remove the `_BadBonus` subfolder and rescan the media, all of a sudden the `High School D×D` media appears.

What is wrong with my `.plexignore` file? Why is it ignoring folders from the directory above? (Folders `s01` and `s02`.)  
From the [ASS doc](https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md#plexignore-files) and the [Plex .plexignore doc](https://support.plex.tv/articles/201381883-special-keyword-file-folder-exclusion/) the file should only be appended to subfolders, not parent folders.

I also tested the following `.plexignore` content, same result (completely missing media in Plex):

```
01.mkv
```

(I posted it here in HAMA because I was not sure if it is a HAMA or a ASS problem and only found HAMA logs because in the `ASS Scanner Logs` there is no file containing information for `High School D×D`.)

**Comment by ZeroQI** [comment]
Files adding or not is the scanner responsibility...
Plex and ASS both read the file...
Plex is wrong seemingly as my scanner logs indicate the file skipped and it would have listed other files skipped and didn't..

# File: 'High School D×D [tvdb4-254653]/_BadBonus/01.mkv' match '.plexignore' pattern: '<_sre.SRE_Pattern object at 0x1484f3215730>'
[no files detected] Grouping folder skip as >1

**Comment by christopher2007** [comment]
So I tested a little bit.  

Main setup:  
One library with ASS as Scanner and HAMA as Agend. Then folders with the `anidb` and the `tvdb4` naming scheme.  
A `.plexignore` inside a subfolder in order to ignore Movies inside this subfolder. All `tvdb4` folders disappear, all `anidb` folders stay.

It is nor important to have `Local Media Assets (TV)` in front of HAMA or not. The bug will occur on both scenarios.  
Also it is not important what is in the `.plexignore` file (`*` and concrete filenames both have the same result).

This bug will not occure when using `Plex Series Scanner` instead of `ASS`, so I am sure this must be a bug in ASS.

**Comment by christopher2007** [comment]
So I tested a little bit.  

Main setup:  
One library with ASS as Scanner and HAMA as Agend. Then folders with the `anidb` and the `tvdb4` naming scheme.  
A `.plexignore` inside a subfolder in order to ignore Movies inside this subfolder. All `tvdb4` folders disappear, all `anidb` folders stay.

It is nor important to have `Local Media Assets (TV)` in front of HAMA or not. The bug will occur on both scenarios.  
Also it is not important what is in the `.plexignore` file (`*` and concrete filenames both have the same result).

This bug will not occure when using `Plex Series Scanner` instead of `ASS`. So I guess this is a bug in ASS.

**Comment by ZeroQI** [comment]
> This bug will not occure when using Plex Series Scanner instead of ASS. So I guess this is a bug in ASS.

I concur. Need to look at the code

**Comment by ZeroQI** [comment]
High School D×D [tvdb4-254653]
- s01/01.mkv
- s02/01.mkv 
- _BadBonus/01.mkv
- _BadBonus/.plexignore

It acts as if the '_BadBonus/.plexignore' file was at root level.
However, the fact the folder is not a season , 'Extras', or 'Specials' folder trick the system into believing it is a grouping folder, messing things up, should be seen as s01e01 so duplicate eps i would have expected

Did you have the following output at the end of scanner logs?
```
  Log.info("".ljust(157, '='))
  Log.info("{} scan end: {}".format("Manual" if kwargs else "Plex", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S,%f")))
```
If not, is there a crash in plex media scanner.log?
What is the behaviour if the folder is renamed to "Extras"?

scanner output came from lines 519, 524, 576, 606
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py lines 503-527

**Comment by ZeroQI** [comment]
Did you have the following output at the end of scanner logs?

```
  Log.info("".ljust(157, '='))
  Log.info("{} scan end: {}".format("Manual" if kwargs else "Plex", datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S,%f")))
```
If not, is there a crash in plex media scanner.log?

**Comment by ZeroQI** [comment]
@christopher2007 

> What is wrong with my .plexignore file? Why is it ignoring folders from the directory above?

It didn't say in the logs that it skipped the files in s1 and s2 like it did for 'High School D×D [tvdb4-254653]/_BadBonus/01.mkv', therefore it crashed, and i need the logs from the issue happening:
- Plex Media Scanner.log
- High School D×D [tvdb4-254653].filelist.log full file as it may contain "scan end" output...

**Comment by ZeroQI** [comment]
@christopher2007 You there?

**Comment by ZeroQI** [comment]
Folder is neither series folder nor season nor transparent folders so guidelines not followed
- These files should have been in an "Extras" folder to be skipped, negating the need for .plexignore
- line 607 the return could explain, commenting could allow to test theory to code fix
Closing for these reasons and no reply in 12 days
