### ISSUE TITLE
tvdb5 and The clone wars wrong mapping : ep3 in absolute order should be S00E01 in DVD order

### ISSUE THREAD

**Issue by StudioEtrange** [ZeroQI/Absolute-Series-Scanner#312]
## Platform

Operating system and version: Linux 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Plex version: plex1.20.4.3517

## Expected Behavior
With TVDB5 mode
The Clone wars S00E01 should be mapped to S01E03 (absolute order) as specified in tvdb 

## Current Behavior
With TVDB5 mode
The Clone wars S00E01 create a special folder and is identified as S00E01
All others episodes mapping to absolute order are ok 

## Additional information
My folder tree : 

The Clone Wars\
    \The Clone Wars (2008) S0 [tvdb5-83268]\The clone wars S00E01.mkv
    \The Clone Wars (2008) S1 [tvdb5-83268]\The clone wars S01E0x.mkv
    \The Clone Wars (2008) S2 [tvdb5-83268]\The clone wars S02E0x.mkv
    \The Clone Wars (2008) S3 [tvdb5-83268]\The clone wars S03E0x.mkv
    \The Clone Wars (2008) S4 [tvdb5-83268]\The clone wars S04E0x.mkv
    \The Clone Wars (2008) S5 [tvdb5-83268]\The clone wars S05E0x.mkv
    \The Clone Wars (2008) S6 [tvdb5-83268]\The clone wars S06E0x.mkv
    \The Clone Wars (2008) S7 [tvdb5-83268]\The clone wars S07E0x.mkv

I have tried to put The clone wars S00E01.mkv in the same folder with all the other files, or at the root of the show, nothing change
S00E01 is not mapped with its absolue order (EP3) 
I think it is because it is identifed as special episode before doing any special matching with TVDB5 mode

NOTE : i think the absolute order have changed in tvdb, before S00E01 was maybe not mapped as E03 in absolute order

**Comment by ZeroQI** [comment]
Could i have the scanner logs attached with the mapping that the scanner did please ?
the absolute numbering mapping should include specials with absolute number indeed...

**Comment by StudioEtrange** [comment]
The problem is on this special episode https://thetvdb.com/series/star-wars-the-clone-wars/episodes/402119

[The Clone Wars (2008).scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5557036/The.Clone.Wars.2008.scanner.log)

**Comment by ZeroQI** [comment]
```
=============================================================================================================================================================
Library: 'no valid X-Plex-Token.id', root: '/media/SERIE_ANIMATION', path: 'The Clone Wars (2008)/The Clone Wars (2008) S0 [tvdb5-83268]', files: '1', dirs: '0'
Manual scan start: 2020-11-17 22:13:34,412385
=============================================================================================================================================================
Forced ID (series folder) - source: "tvdb5", id: "83268"
-------------------------------------------------------------------------------------------------------------------------------------------------------------
TVDB season mode (tvdb5) enabled, tvdb serie rl: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/83268/all/en.xml'
URL: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/83268/all/en.xml', Using cached file: '/tmp/ASS-tvdb-83268.xml'
mappingList: {'s5e20': 's1e109', 's3e5': 's1e46', 's3e4': 's1e50', 's3e7': 's1e48', 's3e6': 's1e47', 's3e1': 's1e4', 's3e3': 's1e5', 's3e2': 's1e49', 's3e9': 's1e53', 's3e8': 's1e51', 's5e13': 's1e101', 's5e12': 's1e100', 's5e11': 's1e99', 's5e10': 's1e98', 's5e17': 's1e106', 's5e16': 's1e105', 's5e15': 's1e104', 's5e14': 's1e103', 's5e19': 's1e108', 's5e18': 's1e107', 's3e15': 's1e60', 's3e14': 's1e59', 's3e17': 's1e62', 's3e16': 's1e61', 's3e11': 's1e55', 's3e10': 's1e54', 's3e13': 's1e58', 's3e12': 's1e57', 's3e19': 's1e64', 's3e18': 's1e63', 's4e10': 's1e77', 's4e11': 's1e78', 's4e12': 's1e79', 's4e13': 's1e80', 's4e14': 's1e81', 's4e15': 's1e82', 's4e16': 's1e83', 's4e17': 's1e84', 's4e18': 's1e85', 's4e19': 's1e86', 's1e22': 's1e52', 's1e20': 's1e24', 's1e21': 's1e25', 's7e9': 's1e131', 's7e8': 's1e130', 's7e1': 's1e123', 's7e3': 's1e125', 's7e2': 's1e124', 's7e5': 's1e127', 's7e4': 's1e126', 's7e7': 's1e129', 's7e6': 's1e128', 's1e17': 's1e21', 's1e16': 's1e2', 's1e15': 's1e20', 's1e14': 's1e19', 's1e13': 's1e18', 's1e12': 's1e17', 's1e11': 's1e16', 's1e10': 's1e15', 's1e19': 's1e23', 's1e18': 's1e22', 's4e2': 's1e69', 's4e3': 's1e70', 's4e1': 's1e68', 's4e6': 's1e73', 's4e7': 's1e74', 's4e4': 's1e71', 's4e5': 's1e72', 's4e8': 's1e75', 's4e9': 's1e76', 's2e12': 's1e40', 's2e13': 's1e41', 's2e10': 's1e38', 's2e11': 's1e39', 's2e16': 's1e1', 's2e17': 's1e29', 's2e14': 's1e42', 's2e15': 's1e56', 's2e18': 's1e30', 's2e19': 's1e31', 's7e11': 's1e133', 's7e10': 's1e132', 's7e12': 's1e134', 's3e20': 's1e65', 's3e21': 's1e66', 's3e22': 's1e67', 's1e3': 's1e8', 's1e2': 's1e7', 's1e1': 's1e6', 's1e7': 's1e12', 's1e6': 's1e11', 's1e5': 's1e10', 's1e4': 's1e9', 's1e9': 's1e14', 's1e8': 's1e13', 's2e22': 's1e45', 's2e21': 's1e44', 's2e20': 's1e43', 's4e21': 's1e88', 's4e20': 's1e87', 's4e22': 's1e89', 's5e7': 's1e95', 's5e6': 's1e94', 's5e5': 's1e93', 's5e4': 's1e92', 's5e3': 's1e91', 's5e2': 's1e90', 's5e1': 's1e102', 's5e9': 's1e97', 's5e8': 's1e96', 's6e12': 's1e121', 's6e13': 's1e122', 's6e10': 's1e119', 's6e11': 's1e120', 's6e8': 's1e117', 's6e9': 's1e118', 's6e4': 's1e113', 's6e5': 's1e114', 's6e6': 's1e115', 's6e7': 's1e116', 's6e1': 's1e110', 's6e2': 's1e111', 's6e3': 's1e112', 's2e8': 's1e36', 's2e9': 's1e37', 's2e1': 's1e26', 's2e2': 's1e27', 's2e3': 's1e28', 's2e4': 's1e32', 's2e5': 's1e33', 's2e6': 's1e34', 's2e7': 's1e35'}
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc_count: {'s00e01': 1, 'star': 1, 'deal': 1, 'movie': 1, 'clone': 1, 'wars': 2, '2008': 1, 'the': 1}
misc_words: []
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"The Clone Wars (2008) S0 [tvdb5-83268]" s00e001                         "SERIES_RX-1" "Movie. . . -Deal" "Star.Wars.The.Clone.Wars.2008.S00E01.Movie.MULTi.1080p.BluRay.x264-DEAL.mkv"
=============================================================================================================================================================
Manual scan end: 2020-11-17 22:13:34,939132
```
Here is the relevant part.
'mappingList' doesn't have s0exx mappings at all

https://github.com/ZeroQI/Absolute-Series-Scanner/edit/master/Scanners/Series/Absolute%20Series%20Scanner.py lines 719-729 (tvdb5)
```
      #tvdb5 - TheTVDB to absolute index order
      elif source=='tvdb5':
        tvdb_guid_url = TVDB_API1_URL % id
        Log.info("TVDB season mode (%s) enabled, tvdb serie url: '%s'" % (source, tvdb_guid_url))
        try:
          tvdbanime = etree.fromstring(read_cached_url(tvdb_guid_url, foldername=os.path.join('TheTVDB','json',id), filename="series_en.xml"))
          for episode in tvdbanime.xpath('Episode'):
            if episode.xpath('absolute_number')[0].text:
              mappingList['s%se%s'%(episode.xpath('SeasonNumber')[0].text, episode.xpath('EpisodeNumber')[0].text)] = "s1e%s" % episode.xpath('absolute_number')[0].text
          Log.info("mappingList: %s" % str(mappingList))
        except Exception as e:  Log.error("xml loading issue, Exception: '%s''" % e)
```

it does add all absolute numbering into the mapping list so please check cache file  '/tmp/ASS-tvdb-83268.xml' 
Can you check if it has '<absolute_number>3</absolute_number>' somewhere and which episode? i see it in current s00e01, and abs number 3 but seem like your cache is old or it changed recently

In doubt, delete the cache and re-scan (will need folder change so add a dummydifferent  ep number in same folder that you delete afterwards)

**Comment by ZeroQI** [comment]
s0e1 should be mapped to s1e3 as both air order and absolute order are defined: [https://thetvdb.com/series/star-wars-the-clone-wars/episodes/402119]
- Home / Series / Star Wars: The Clone Wars / Aired Order / Season 0 / Episode 1 
- Home / Series / Star Wars: The Clone Wars / Absolute Order / Season 1 / Episode 3  

The code does add **ALL** absolute numbering into the mapping list so **please check cache file '/tmp/ASS-tvdb-83268.xml'**
Can you check if it has '<absolute_number>3</absolute_number>' somewhere and which episode? i see it in current s00e01, and abs number 3 but seem like your cache is old or it changed recently

In doubt, delete the cache and re-scan (will need folder change so add a dummy different ep number in same folder that you delete afterwards)

**Comment by ZeroQI** [comment]
@StudioEtrange your cached file is outdated. No answer since 18th of November. Closing
