### ISSUE TITLE
ScudLee Replacement

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#315]
Hi @ZeroQI 

ScudLee as virtually disappeared and many of the committers too. In speaking with another user, https://github.com/ScudLee/anime-lists/issues/360, the idea to start a fork popped up that can be a little more widely maintained. I was wondering if you would be open to utilizing this with ASS and HAMA? 

Thoughts?

**Comment by ZeroQI** [comment]
Try to be promoted as maintainer first, as I would rather have a single point for updates...
If it cannot be done, fork it, and will support IF it is moreqintained of course.

I have given maintainer rights myself to couple people in case something happens so the project can live on...

**Comment by sven-7** [comment]
Sadly, I’ve tried that. I cannot get anyone to give me access as none of the people respond. I’ve been asking for a few months now and have gotten nothing back in return. There is an overwhelming amount of backlog at this point. 

-Stephen

**Comment by purposelycryptic** [comment]
> Sadly, I’ve tried that. I cannot get anyone to give me access as none of the people respond. I’ve been asking for a few months now and have gotten nothing back in return. There is an overwhelming amount of backlog at this point.


Just wanted to echo that, ScudLee has been absent for years now without responding even once, and even a year or two ago, only a small handful of people with commit access existed, and it often took weeks to get anything committed, and only after much prodding.

**Comment by sven-7** [comment]
My thought would be to start an org versus a personal one (which I’ve started already). So that multiple admins can be added and allows it to passed down a lot better.

**Comment by sven-7** [comment]
I more or less started on this. Even if it doesn't take, a single merger should take care of the open issues. 

https://github.com/Anime-Lists/anime-lists

**Comment by ZeroQI** [comment]
The most precise link I found was https://softwareengineering.stackexchange.com/questions/273156/how-should-i-contribute-to-a-mostly-abandoned-github-project

The easiest would be to be added as maintainer for the project but unless the owner can be found and located, then this seem the right approach.

Did anybody contact scudlee on https://forum.kodi.tv/showthread.php?tid=142835?
We need community contact to try to ask for peacefully addition of maintainers.

XBMC mod was the main tool using the mappings but I believe XBMC/Kodi use is going down as streaming is picking up and Hama might have changed the répartition dynamics of AniDB mod agent for XBMC using the XML anime list mainly ...

I will support the new repository of maintained as HAMA is heavily relying on correct mappings and will assist actively if I can as this project and ASS is a proud achievement of mine despite the occasionnal bugs...

I will not let HAMA project go derrelict and thank you sven7 for your continuing efforts

**Comment by sven-7** [comment]
I can try to - it looks like his last post was in February/March 2020 range. I sent @scudlee a message there.

Seeing how great HAMA and ASS run for Plex, I think it's vital for an anime-lists repository to be maintained.

**Comment by sven-7** [comment]
Here is the org that I made and forked: https://github.com/Anime-Lists/anime-lists

It's different than my personal fork.
