### ISSUE TITLE
Clean up the source code

### ISSUE THREAD

**Issue by baseballlover723** [ZeroQI/Absolute-Series-Scanner#317]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I look at the source code

**Describe the solution you'd like**
Can I / you clean up the source code? Notable things I would want to do is 

- [ ] Break up the code into more functions
- [ ] Apply a consistent formatting (including enforcing line length)
- [ ] Make the source code more self documenting

**Describe alternatives you've considered**
Trying to understand the source code. Moving off of plex. Giving up and using windows file explorer instead.

**Additional context**
Please, the source code is the ugliest thing I've ever seen in my life. Will you let me make it readable?

**Comment by ZeroQI** [comment]
There are 11 bug reports yet you create another one for cosmetics, without giving one example of why the code needs editing.

If your files are named like you want the code to be, there should be no need to edit the code in the first place...

You can always use another scanner like BABS or fork this project without applying to the master... I would have a look but If I can't edit it on the phone I will stop editing most likely, so would the project be better off with you or me if opinion can't be reconciled?
- If you make 5 lines into 12 I can no longer follow the flow...
- if it's creating a function that get called once it will add to the length

Questions
- Why do you need to edit the scanner?
- what function are you thinking of that would be called more than once in the code?
- what part give you problem understanding?
- I see no python project only java, javascript, typescript on your github page so honestly don't think you will contribute as much 
- Had a look at https://github.com/swagluke/Team-Murica/blob/master/src/generictree/GenericTree.java a d while it is considered proper coding I do hate it as making like longer make patterns appears and code easier to read for me so do NOT edit the master, but you can fork it and edit on the your own if you so wish.

**Comment by baseballlover723** [comment]
I apologize if I was rude, but I was a little frustrated since the scanner was misbehaving with my own files (with their own naming scheme) yesterday. I think the best solution is just for me to create my own scanner the way I want to make it (with a more flexible and configurable file handling), and then use your scanner as a reference. Thanks for implementing this, it is sure to help me as I implement my own.

**Comment by ZeroQI** [comment]
You can always give your naming scheme, can add support if it make sense
Be careful when testing scanners, if the content of the folder doesn't change it will not rescan the folder's you have to add or remove files for it to not use the cached results
