### ISSUE TITLE
Does updating the scanner require restarting plex?

### ISSUE THREAD

**Issue by ksurl** [ZeroQI/Absolute-Series-Scanner#319]
I usually replace the file and restart to be safe, but just wondering if it's necessary. It shouldn't be actively loaded in plex except when it does the periodic library scanning right? So it should pick up the new version on next scan

**Comment by ZeroQI** [comment]
True, reboot shouldn't be necessary.
Beware however of scan result being cached and not refreshed if the folder content didn't change, even if the folder name was.
