### ISSUE TITLE
Crash if multiple YouTube playlist in Grouping folder

### ISSUE THREAD

**Issue by ecto1a2003** [ZeroQI/Absolute-Series-Scanner#324]
## Platform

Operating system and version: qnap 4.5.1.1540
Plex version: 1.21.1.3876

newest version of ASS

## Expected Behavior

I have a youtubve channel containd in a single grouping folder in a library. this is the only folder in the library, naming connventionis as follows:

"v:/youtube/%(uploader)s/%(playlist_title)s [%(playlist_id)s]/%(title)s [%(id)s].%(ext)s"

## Current Behavior

I scan the library and no content is added
[Plex Media Server.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5805381/Plex.Media.Server.log)
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5805389/Plex.Media.Scanner.log)
[_root_.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5805390/_root_.scanner.log)
[Pat Stares At.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5805393/Pat.Stares.At.filelist.log)
[Pat Stares At.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5805394/Pat.Stares.At.scanner.log)
[_root_-share-CACHEDEV1_DATA-Videos-youtube.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5805395/_root_-share-CACHEDEV1_DATA-Videos-youtube.scanner.log)
[_root_-share-CACHEDEV1_DATA-Videos-youtube.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5805396/_root_-share-CACHEDEV1_DATA-Videos-youtube.filelist.log)

## Steps to Reproduce

1. 
2.
3.
4.

**Comment by ZeroQI** [comment]
Plex Media Scanner.log shows that the Scanner crashes so there is a bug, and nothing will be added to Plex
```
Jan 12, 2021 15:15:20.483 [0x7f21bfa83780] DEBUG - Performing a scan with 'Absolute Series Scanner' (language: xn virtual: 0).
Jan 12, 2021 15:15:20.483 [0x7f21bfa83780] DEBUG -   * Scanning /share/CACHEDEV1_DATA/Videos/youtube
Jan 12, 2021 15:15:20.483 [0x7f21bfa83780] DEBUG - Scanner: Processing directory /share/CACHEDEV1_DATA/Videos/youtube (parent: no)
Jan 12, 2021 15:15:20.487 [0x7f21bfa83780] DEBUG - Skipping over directory '', as nothing has changed; removing 0 media items from map.
Jan 12, 2021 15:15:23.811 [0x7f21bfa83780] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 1141, in Scan
    Scan(path, sorted(subdir_files), media, sorted(subdir_dirs), language=language, root=root, kwargs_trigger=True)  #relative path for dir or it will show only grouping folder series
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 884, in Scan
    Log.info('---- count: {}'.format(len(json_full['items'])))
KeyError: ('items',)
```
root-share-CACHEDEV1_DATA-Videos-youtube.scanner.log shows nothing obvious

The playlist json wasn't downloaded for some reason, applied a fix to master branch to avoid crashing, but the json still isn't loaded...

**Comment by ecto1a2003** [comment]
with some more testing it seems to only bomb out when there is more than one playlist in a grouping folder. ill try out the new version and report back.

**Comment by ZeroQI** [comment]
workaround also: 'Pat Stares At - SuperGiant [PLPXYESFhUD6TFGImn7cKZ3sF8lvCmy3Uq]' series folder and put it in a 'Pat Stares At' collection

**Comment by ecto1a2003** [comment]
I cant add it to a collection if it never shows up? or is there another way

**Comment by ZeroQI** [comment]
without grouping folder it may not crash, then can be put in a collection

**Comment by ecto1a2003** [comment]
Ah, that makes sense. Everything seems to work when grouping folders aren't used. That's a little more messy than I'd like, plus the manual collection creation is more work than I'd like to do.

**Comment by ecto1a2003** [comment]
currently waiting for more space to fully test the change. ill update once i get it setup

**Comment by ZeroQI** [comment]
Issue seem present if more than one playlist in a grouping folder
- crash in 'Plex Media Scanner.log' corrected in https://github.com/ZeroQI/Absolute-Series-Scanner/commit/6cf53c9561f8c50b923aad37652ed3a7251ed558. If crash is still present, i need new 'Plex Media Scanner.log' log
- workaround:  'Pat Stares At - SuperGiant [PLPXYESFhUD6TFGImn7cKZ3sF8lvCmy3Uq]' for each playlist as series folder and put it in a 'Pat Stares At' collection

Closing for now as code was pushed to master to correct. If not solved update the ticket
