### ISSUE TITLE
YouTube - Playlists as Seasons

### ISSUE THREAD

**Issue by undaunt** [ZeroQI/Absolute-Series-Scanner#325]
**Is your feature request related to a problem? Please describe.**
I'm not currently able to figure out how to do this, so I apologize if it is already possible. My goal is to download a given YouTube channel's playlists into individual season folders. I'm currently causing all my files to either show up as one large season, or by year seasons inadvertently.

**Describe the solution you'd like**
Here is how I'm currently trying to organize the data.

**Playlists**
%(uploader)s - [%(uploader_id)s]/Playlist - [%(playlist_id)s]/%(playlist_index)s - %(title)s [%(id)s].%(ext)s

**Non-Playlist Videos** (to be downloaded after all playlist videos, skipping them by using youtube-dl's archive file)
%(uploader)s - [%(uploader_id)s]/No Playlist/%(upload_date)s - %(title)s [%(id)s].%(ext)s

Please let me know if the prior could be improved upon. I'm currently using the Absolute Series Scanner and the Youtube bundle, both latest versions as of today.

**Describe alternatives you've considered**
An alternative could be each playlist being a series instead of a season, and using a collection to view all playlists and videos belonging to a channel. I'm not sure how to accomplish that either.

**Comment by ZeroQI** [comment]
Make a series folder with playlist Id per playlist
- group them all in a collection by putting the same collection string manually in each series
- change Library settings to hide series in collections and hide single season folders for seamless browsing

Please consider donating

**Comment by undaunt** [comment]
I donated! Thanks for all your hard work.

I replied to https://github.com/ZeroQI/YouTube-Agent.bundle/issues/59 regarding this line of thinking.

**Comment by ZeroQI** [comment]
2021-01-26 16:55:30,615 (7faa757fa700) : INFO (init:489) - Grouping folder not found or single folder, root: /data/youtube/Dead Suns Character Intros - [PLz3Be--ot61Mvmms68yBEhX6KrzPrqxsW], path: , Grouping folder: , subdirs: 0, reverse_path: ['']
2021-01-26 16:55:30,616 (7faa757fa700) : INFO (init:575) - No GUID so random folder

It seem like the Playlist ID is not recognized despite being correct (tested it)

https://github.com/ZeroQI/YouTube-Agent.bundle/blob/master/Contents/Code/__init__.py line 697
YOUTUBE_REGEX_PLAYLIST = Regex('\[(?:youtube\-)?(?P<id>PL[^\[\]]{16}|PL[^\[\]]{32}|UU[^\[\]]{22}|FL[^\[\]]{22}|LP[^\[\]]{22}|RD[^\[\]]{22}|UC[^\[\]]{22}|HC[^\[\]]{22})\]', Regex.IGNORECASE) # https://regex101.com/r/37x8wI/2

Please replace it with the below, update metadata for this series, and report, and will add i to the master
YOUTUBE_REGEX_PLAYLIST = Regex('\[(?:youtube\-)?(?P<id>PL[a-zA-Z0-9\-_]{16}|PL[a-zA-Z0-9\-_]{32}|UU[a-zA-Z0-9\-_]{22}|FL[a-zA-Z0-9\-_]{22}|LP[a-zA-Z0-9\-_]{22}|RD[a-zA-Z0-9\-_]{22}|UC[a-zA-Z0-9\-_]{22}|HC[a-zA-Z0-9\-_]{22})\]', Regex.IGNORECASE) # https://regex101.com/r/37x8wI/2
