### ISSUE TITLE
Plex server stopped scanning after updating the script

### ISSUE THREAD

**Issue by BDiamond** [ZeroQI/Absolute-Series-Scanner#329]
[Plex Media Scanner.1.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/5986328/Plex.Media.Scanner.1.log)
## Platform
Operating system and version: FreeBSD 12.2-RELEASE-p3 (FreeNAS/TrueNAS jail)
Plex version: 1.21.3.4021-5a0a3e4b2

## Expected Behavior
Automatic scan or manual scan of library add new series episodes

## Current Behavior
Automatic scan or manual scan of library fails

## Steps to Reproduce
1. Select "Scan library files" from the library menu

## Additional information
The scan fails with the following error in the logs:

Feb 16, 2021 00:01:39.753 [0x8035d6000] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 1141, in Scan
    Scan(path, sorted(subdir_files), media, sorted(subdir_dirs), language=language, root=root, kwargs_trigger=True)  #relative path for dir or it will show only grouping folder series
  File "/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 1077, in Scan
    standard_holding.append([file, root, path, show, int(season), int(ep), title, year, int(ep2) if ep2 and ep2.isdigit() else int(ep), rx, tvdb_mapping, unknown_series_length, offset_season, offset_episode, mappingList])
ValueError: invalid literal for int() with base 10: '2a'
Feb 16, 2021 00:01:39.753 [0x8035d6000] ERROR - We got an error scanning in /media/Videos/Animation/JP

After several tests, I confirmed that commit f57c3770b41f43451d4e099f0d216900c26bee41 (the last one at the moment of writing) is the culprit of this bug. After reversing the change locally, scanning works again.

**Comment by BDiamond** [comment]
I suspect it's because I have some openings/endings "numbered" as OP1a, OP1b, OP2a, ED1a, ED1b, etc... (same numbering as anidb)

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py
line 1077 it expects an int string and get "2a" for `int(ep) ` and/or `int(ep2) if ep2 and ep2.isdigit() else int(ep)`
lines 1068-1076 actually do this type op ep translation to an int

All files may not give the error, need to have the output just before the error, that could help knowing the impacted filename, if it downloaded the AniDB series XML file, ...

can you uncoment line 1076 then rescan and attach the Plex media scanner.log as a file please?

**Comment by ZeroQI** [comment]
reverted code so closing this bug report
