### ISSUE TITLE
Trailer recognized as regular episode

### ISSUE THREAD

**Issue by krbrs** [ZeroQI/Absolute-Series-Scanner#330]
## Platform

Operating system and version: Windows 10 current version
Plex version: 1.21.4.4054

## Expected Behavior

Scanner should distinguish between regular episode and trailer

## Current Behavior

Trailer is recognized as regular episode

## Steps to Reproduce

1. Add folder to library and scan for new files
2. See trailer matched as regular episode

![image](https://user-images.githubusercontent.com/57227244/108518724-2b935180-72c9-11eb-9f00-418876e0f937.png)

## Additional information

I put the anidb-id in the folder name because of trouble with recognitions in some cases

Logfiles:

[Memories Off #5 Togireta Film [anidb-4139].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6010702/Memories.Off.5.Togireta.Film.anidb-4139.filelist.log)
[Memories Off #5 Togireta Film [anidb-4139].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6010703/Memories.Off.5.Togireta.Film.anidb-4139.scanner.log)

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py
ANIDB-RX3 is the regex used so the 4th item in the list line 82
` cic(r'(^|(?P<show>.*?)[ _\.\-]+)(TRAILER|PROMO|PV|T)[ _\.]?(?P<ep>\d{1,2})[ _\.]?(V\d)?([ _\.\-]+(?P<title>.*))?$')`

Look like line 1045 i messed up, replace with the below and test
`          if rx in ANIDB_RX[:-2]:                                                                                                                       ### AniDB Specials ################################################################
`

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/328
i fixed it but broke this. reverting solves it, but need to solve  bug 328 again

**Comment by krbrs** [comment]
> Look like line 1045 i messed up, replace with the below and test
> ` if rx in ANIDB_RX[:-2]: ### AniDB Specials ################################################################`

This line replaced fixes #330 but breaks #328 as you said. Logfiles below for both in a new Test-Library:

[Idolmaster Cinderella Girls Gekijou (2017) [anidb-13274].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6011556/Idolmaster.Cinderella.Girls.Gekijou.2017.anidb-13274.filelist.log)
[Idolmaster Cinderella Girls Gekijou (2017) [anidb-13274].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6011557/Idolmaster.Cinderella.Girls.Gekijou.2017.anidb-13274.scanner.log)

[Memories Off #5 Togireta Film [anidb-4139].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6011558/Memories.Off.5.Togireta.Film.anidb-4139.filelist.log)
[Memories Off #5 Togireta Film [anidb-4139].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6011559/Memories.Off.5.Togireta.Film.anidb-4139.scanner.log)

**Comment by ZeroQI** [comment]
Reverted code, closing that one, need to really fix #329 now
