### ISSUE TITLE
episode recognized as special

### ISSUE THREAD

**Issue by littleneko** [ZeroQI/Absolute-Series-Scanner#331]
## Platform
Operating system and version: windows server 2016
Plex version: 1.21.3.4046-3c1c83ba4

## Expected Behavior
![Xnip2021-02-21_14-48-19](https://user-images.githubusercontent.com/6368915/108617777-fbc48500-7453-11eb-801e-d4b74197e7cf.jpg)

episode 1 -4
and 4 special

## Current Behavior
![Xnip2021-02-21_14-48-50](https://user-images.githubusercontent.com/6368915/108617780-fe26df00-7453-11eb-9319-79c8fceaa036.jpg)
![Xnip2021-02-21_14-48-36](https://user-images.githubusercontent.com/6368915/108617781-febf7580-7453-11eb-945b-51d3aac75a77.jpg)

[[CASO][Rozen_Maiden][BDRIP].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6017285/CASO.Rozen_Maiden.BDRIP.scanner.log)
[[CASO][Rozen_Maiden][BDRIP].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6017286/CASO.Rozen_Maiden.BDRIP.filelist.log)

I try to add word "menu" to `WS_SPECIALS` and `ANIDB_RX`, but it seems don't work

**Comment by littleneko** [comment]
But, when I delete the files:
`[CASO][Rozen_Maiden][Menu][01][BDRIP][1920x1080][x264_FLAC][14AB3E46].mkv`
`[CASO][Rozen_Maiden][Menu][02][BDRIP][1920x1080][x264_FLAC][6C872629].mkv`
it recognized all the episode and special correctly.

**Comment by ZeroQI** [comment]
Files are at root level.
Content is brackets is meant to be scrubbed
Title found composed of brackets

This naming convention is an unsupported aberration and the fact the scanner log use word for some eps search means you can't just add a reged entry...

If you remove brackets around series name and ep number it will work

**Comment by littleneko** [comment]
i try to revert this commit https://github.com/ZeroQI/Absolute-Series-Scanner/commit/f57c3770b41f43451d4e099f0d216900c26bee41 , now it work, but the "[Menu][01]" and "[Menu][02]" recognized as episode.

**Comment by ZeroQI** [comment]
"Menu" is not a term for specials so as expected it duplicates in the episode number, working as expected
It should be in an "Extras" subfolder to be skipped entirely or manually set to s00e501-502 to not gather any metadata...

Reverted main code, will close that ticket as a result
