### ISSUE TITLE
error: unbalanced parenthesis

### ISSUE THREAD

**Issue by Farrah4Life** [ZeroQI/Absolute-Series-Scanner#334]
Hey all, hoping someone has some insight to my problem.

Been trying to get Absolute Series scanner up and running to take advantage of the TVDB4 organization.

As mentioned in the title, the non-legacy version of the scanner shows up in Plex but will not complete a scan or locate any media. The legacy version of the scanner will actually find files on the disk but it will not organize them in any way, just lumping them into one giant season. I'll attach log files for both, however the issue at hand seems to be this section of the log from the non-legacy scanner.

Scanners are located at "AppData\Local\Plex Media Server\Scanners\Series"

```
Feb 24, 2021 16:27:03.244 [2096] DEBUG - Performing a scan with 'Absolute Series Scanner' (language: en virtual: 0).

Feb 24, 2021 16:27:03.244 [2096] DEBUG -   * Scanning P:\Anime

Feb 24, 2021 16:27:03.244 [2096] DEBUG - Scanner: Processing directory P:\Anime (parent: no)

Feb 24, 2021 16:27:03.264 [2096] ERROR - No module in Absolute Series Scanner

Feb 24, 2021 16:27:03.265 [2096] ERROR - Error in Python: Looking up module:

Traceback (most recent call last):

 File "C:\Users\sling\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 75, in <module>

    MOVIE_RX        = cic(r'(^|(?P<show>.*) (?P<year>\d{4})$')

  File "C:\Users\sling\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 31, in cic

    def cic(string):  return re.compile(string, re.IGNORECASE)  #RE Compile Ignore Case

  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\re.py", line 194, in compile

    return _compile(pattern, flags)

  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\re.py", line 251, in _compile

    raise error, v # invalid expression

error: unbalanced parenthesis

Feb 24, 2021 16:27:03.265 [2096] ERROR - We got an error scanning in P:\Anime
```

I found an error kind of but not exactly similar to this in the ReadMe which recommended reinstalling Visual C++ 2015 which I did to no avail. 

Other attempted solutions: Reinstall PMS(most recent version), downgrade PMS(to 1.21.1.3795), redownloaded master.zip incase of corruption, ran the Poweshell updater in master.zip

----------------------

System information: 
Win 10 19042.746
PMS Version: 1.21.1.3795 and 1.21.4.4079 

File Structure: 

P:\Anime\Naruto [tvdb4-78857]\Naruto EP001 - Enter Naruto Uzumaki!
...
P:\Anime\Naruto [tvdb4-78857]\Naruto EP220 - Going on a Journey

P:\Anime\Dragon Ball [tvdb4-76666]\Dragon Ball EP001 - Secret of the Dragon Balls
...
P:\Anime\Dragon Ball [tvdb4-76666]\Dragon Ball EP153 - The End, The Beginning

And so forth. Originally I was using EXXX instead of EPXXX but changed after seeing an example from a few years ago on reddit about getting this all set up that was using EP. Neither has worked so far. All episodes are in the same parent folder. As I understand this is an acceptable structure. 

I also attempted to add tvdb4.id and tvdb4.mapping files to the folders for use with the legacy scanner, however those did not do anything either. 

Most likely this is something very simple and I am just extremely stupid, but after a few hours of messing around with this, looking over help threads and the troubleshooting section, figured I would post here. More than happy to pay a RTFM tax. 

Thanks for any help or insight. 

Logs below.

Ethan

[Plex Media Scanner (ASS NON LEGACY SCAN ATTEMPT).log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6039789/Plex.Media.Scanner.ASS.NON.LEGACY.SCAN.ATTEMPT.log)
[Plex Media Scanner (LEGACY SCAN).log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6039790/Plex.Media.Scanner.LEGACY.SCAN.log)

**Comment by ZeroQI** [comment]
Same name as my youngest nephew!
Nop, you read the readme (SS event!), tried two versions of the scanner, all good!

Issue was introduced in https://github.com/ZeroQI/Absolute-Series-Scanner/commit/9f4e152e02627044b644bcb386107fb979d836a4 yesterday, did few commits in a row

"error: unbalanced parenthesis" means the code has a parenthesis or more missing or in excess
If we remove the file calls not from my code we get 3 opening ones, 2 closing ones...

File "C:\Users\sling\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 75, in <module>
    MOVIE_RX        = cic(r'(^|(?P<show>.*) (?P<year>\d{4})$')
[...]

I pasted the code in Notepad++, set language to Python, goes at the end, and both outer parenthesis are red so it did look good at first glance, but one is missing indeed

Please try latest release and report

**Comment by ZeroQI** [comment]
tested and working now
