### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by Aetf** [ZeroQI/Absolute-Series-Scanner#335]
Seems the fix added for #306 is causing a different error.

## Platform

Operating system and version: Windows 10
Plex version: 1.21.4.4079

## Expected Behavior

ASS detects new files

## Current Behavior

Nothing shows up in the library.

Errors in log:
```
Feb 25, 2021 20:33:18.043 [6164] DEBUG - Performing a scan with 'Absolute Series Scanner' (language: zh virtual: 0).
Feb 25, 2021 20:33:18.043 [6164] DEBUG -   * Scanning I:\动漫
Feb 25, 2021 20:33:18.043 [6164] DEBUG - Scanner: Processing directory I:\动漫 (parent: no)
Feb 25, 2021 20:33:18.128 [6164] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "F:\Plex\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 559, in Scan
    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id").encode('utf-8'), root.encode('utf-8'), path.encode('utf-8'), len(files or []), len(dirs or [])))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 3: ordinal not in range(128)
Feb 25, 2021 20:33:18.132 [6164] ERROR - We got an error scanning in I:\动漫
```

Full log: [Plex Media Scanner.log.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6046938/Plex.Media.Scanner.log.zip)

## Steps to Reproduce

1. Create a new library with non ascii character in path
2. Set ASS as the scanner

## Additional information

The reported error byte `0xe5` is the first byte of utf-8 encoded "动漫", so it must be the dir path `I:\动漫` causing the problem.

```python
>>> '动漫'.encode('utf-8')
b'\xe5\x8a\xa8\xe6\xbc\xab'
>>>
```

**Comment by Aetf** [comment]
After removing `encode('utf-8')` from the line, the scanner can continue normally. However, the produced `filelist.log` file contains a mix of utf-8 and unknown encoding characters.

Logs for the successful scan:

[Plex Media Scanner.log.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6047000/Plex.Media.Scanner.log.zip)

[_root_I -动漫.filelist.log.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6046999/_root_I.-.filelist.log.zip)

[腹黑妹妹控兄记 Onii-chan no Koto Nanka Zenzen Suki Janain Dakara ne!![BDRIP][1920x1080][(TV12+1)+pv9+NCoped][x264_m4a][10bit]加刘景长压制.filelist.log.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6047001/Onii-chan.no.Koto.Nanka.Zenzen.Suki.Janain.Dakara.ne.BDRIP.1920x1080.TV12%2B1.%2Bpv9%2BNCoped.x264_m4a.10bit.filelist.log.zip)

**Comment by ZeroQI** [comment]
Will use this bug report to summarize all known issues:

Directory "I:\动漫" - https://github.com/ZeroQI/Absolute-Series-Scanner/issues/335
```
File "F:\Plex\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 559, in Scan
    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id").encode('utf-8'), root.encode('utf-8'), path.encode('utf-8'), len(files or []), len(dirs or [])))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 3: ordinal not in range(128)
```

Library name "Anime 🇯🇵"- https://github.com/ZeroQI/Absolute-Series-Scanner/issues/306
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 554, in Scan
    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id"), root, path, len(files or []), len(dirs or [])))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-9: ordinal not in range(128)

path '/volume4/Video/sorted/HD Cartoon Series/2x2/Кит Stupid Show/Season01/КитStupidShowS01E01.mp4' - https://github.com/ZeroQI/Absolute-Series-Scanner/issues/276
```
File "/volume3/Plex/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 559, in Scan
    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id").encode('utf-8'), root.encode('utf-8'), path.encode('utf-8'), len(files or []), len(dirs or [])))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 15: ordinal not in range(128)
```

Source: https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte
- Unicode strings do not contain any encoding but Unicode point codes, can be encoded to strings
- Strings contain encoded text (UTF-8, UTF-16, ISO-8895-1, GBK, Big5 etc...), can be decoded to Unicode, Files and text data are always transferred in encoded strings.

**Since the scanner crashed, i would have to move the folder out, rescan, move it back, rescan at each attempt (the pain of scanner development)**

path.encode('utf-8'): UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
path.decode('utf-8'): UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 3: ordinal not in range(128)
path.decode('ascii', 'replace'): UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

OK let's catch errors and revert to working for this path "动漫" line 559-560
```
  try:                    Log.info("Library: '{}', root: '{}', path: '{}', files: '{}', dirs: '{}'".format(Dict(PLEX_LIBRARY, root, 'title', default="no valid X-Plex-Token.id"), root, path, len(files or []), len(dirs or [])))
  except Exception as e:  Log.info('exception: {}'.format(e))
```

That work back, good. Need to test the others without breaking this one
- 'Кит Stupid Show/Season01/КитStupidShowS01E01.mp4' work back after ".decode('utf-8')" on filename
- "Anime 🇯🇵" works after putting log in try-except but root logs catch exception, ok after ".encode('utf-8')"
- weirdly enough the library name is correct in one series, in the other one it shows as Library: 'Anime 馃嚡馃嚨'...

**Comment by ZeroQI** [comment]
Please test (after removing folder, rescan, putting back folder) but should be resolved

**Comment by IvanShift** [comment]
Hello!
I tested, no errors in "Plex Media Scanner.log", but "Solar Opposites" is still empty:
[Solar Opposites.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6051686/Solar.Opposites.filelist.log)
[Solar Opposites.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6051687/Solar.Opposites.scanner.log)

**Comment by IvanShift** [comment]
and "South Part" has only 13 episodes again(
[South Park.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6051712/South.Park.filelist.log)
[South Park.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6051713/South.Park.scanner.log)

**Comment by Aetf** [comment]
I feel this is an issue with the `path` being in OS native encoding, because it's passed in as command line arguments. Most likely it's not encoded in 'utf-8' or 'ascii', but as 'mbcs' . So the `Scan` function should try decode the path using filesystem default encoding: `path = path.decode(sys.getfilesystemencoding())`

**Comment by Aetf** [comment]
Ok, now I get the root cause of all of these. There are several things going on.

### String formatting with mixed `str` and `unicode`
`%` format can handle mixed `str` and `unicode` to a certain degree.

If the format string is `str`, the result will be `unicode` if there are `unicode` arguments, otherwise `str`. `unicode` arguments will be encoded using system's default encoding.

If the format string is `unicode`, the result will always be `unicode`. `str` arguments will first be decoded using 'ascii'. This may cause `UncodeDecodeError` if the argument contains unicode characters.
```python
>>> 'abc %s' % '动漫'
'abc \xe5\x8a\xa8\xe6\xbc\xab'
>>> 'abc %s' % u'动漫'
u'abc \u52a8\u6f2b'
>>> u'abc %s' % u'动漫'
u'abc \u52a8\u6f2b'
>>> u'abc %s' % '动漫'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

`str.format` can not  handle mixed types, and will raise `UnicodeEncodeError` or `UnicodeDecodeError` depend on which one is `unicode`.

If the format string is `unicode`, it tries to decode the `str` argument `'动漫'` using 'ascii', which will be in OS native encoding and definitely not 'ascii', thus `UnicodeDecodeError`.

If the format string is `str`, it tries to encode the `unicode` argument using 'ascii', which isn't possible since the character isn't reprentable as ASCII, thus `UnicodeEncodeError`.
```python
>>> 'abc {}'.format('动漫')
'abc \xe5\x8a\xa8\xe6\xbc\xab'
>>> 'abc {}'.format(u'动漫')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
>>> u'abc {}'.format('动漫')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
>>> u'abc {}'.format(u'动漫')
u'abc \u52a8\u6f2b'
```

### Logging handling
Python 2's logging does the following when processing a call like
```python
Log.info(arg1, arg2, arg3)
```

1. If there are multiple arguments, do a `%` formatting internally, and thus subject to the `str`/`unicode` business discussed above.
2. If the result is `unicode`, encode it to `str` using FileHandler's encoding, or system default encoding if the former not set.
3. Now the result must be `str`, write it unchanged to file

### The problem in the current code
The logging call is done using `str.format`, but the path arguments may or may not be `unicode`. Also, the log output file format is not set, thus file log file content encoding is dependent on the OS.

To fix:

* When setup logging, force the file encoding to be utf-8
* When calling `Log.info`, force the format string to be `unicode`
* At the beginning of `Scan`, sanitize all input arguments related to file path, and decode them to `unicode`, to ensure consistency

In the long run, probably should add `from __future__ import unicode_literal` at the beginning of the file, so all string literals become `unicode`. But that has larger implications and should be done carefully.

**Comment by ZeroQI** [comment]
Thank you very much, I passed all day (and previous day with various botched fixes) trying to fix this, and it is done so seemingly easily...
Tested with IvanShift's library and all working!

**Comment by Aetf** [comment]
Thanks for adding me as a contributor! I just started using ASS for my animation library, and so far ASS mostly works as expected except for this issue so I just took the liberty of fixing it :)

If all tests passing, let's close this issue. We can reopen in the future if it breaks again.

Btw, I do have a question:
Most file names in my library are bracketed names like `[CASO&SumiSora][The_irregular_at_magic_high_school][GB][720p]/[CASO&SumiSora][The_irregular_at_magic_high_school][13][GB][720p].mp4`, and ASS seems to not be able to extract the series name properly.

I understand the naming conversion is different, but all these are torrent files that can't be easily renamed or reorganized. So far I've been using force id files (mostly `anidb.id`/`anidb3.id`)  which works well, but it requires creating one for each series, and forcing rescan the library is tedious. Is there a better way I can map my series to anidb id?

**Comment by ZeroQI** [comment]
re-scan is tedious if using grouping folders (series folder not in the library root folder) for which it has to rescan all involved folders every time, otherwise folders that haven't changed are cached (including when the scanner crash, which is a pain)

Brackets have empirically been used for tags to scrub, and no release group was using such naming convention
Adding a regex to SERIES_RX will support it IF you change the folder name when downloading manually
```
SERIES_RX       = [                                                                                                                                                              ######### Series regex - "serie - xxx - title" ###
  cic(r'(^|(?P<show>.*?)[ _\.\-]+)(?P<season>\d{1,2})XE?(?P<ep>\d{1,3})(([_\-X]|[_\-]\d{1,2}X)(?P<ep2>\d{1,3}))?([ _\.\-]+(?P<title>.*))?$'),                                    #  0 # 1x01
  cic(r'(^|(?P<show>.*?)[ _\.\-]*)SE?(?P<season>\d{1,4})[ _\.\-]?EP?(?P<ep>\d{1,3})(([ _\.\-]|EP?|[ _\.\-]EP?)(?P<ep2>\d{1,3}))?[ _\.]*(?P<title>.*?)$'),                        #  1 # s01e01-02 | ep01-ep02 | e01-02 | s01-e01 | s01 e01'(^|(?P<show>.*?)[ _\.\-]+)(?P<ep>\d{1,3})[ _\.\-]?of[ _\.\-]?\d{1,3}([ _\.\-]+(?P<title>.*?))?$',                                                              #  2 # 01 of 08 (no stacking for this one ?)
  cic(r'^(?P<show>.*?)[ _\.]-[ _\.](EP?)?(?P<ep>\d{1,3})(-(?P<ep2>\d{1,3}))?(V\d)?[ _\.]*?(?P<title>.*)$'),                                                                      #  2 # Serie - xx - title.ext | ep01-ep02 | e01-02
  cic(r'^(?P<show>.*?)[ _\.]\[(?P<season>\d{1,2})\][ _\.]\[(?P<ep>\d{1,3})\][ _\.](?P<title>.*)$'),
  cic(r'^\[.*\]\[(?P<show>.*)\]\[(?P<ep>\d{1,3})\].*$')]
```
