### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 56: ordinal not in range(128)

### ISSUE THREAD

**Issue by ziggie216** [ZeroQI/Absolute-Series-Scanner#337]
## Platform

Operating system and version: UnRAID 6.9
Plex version: 1.21.4.4079-1b7748a7b

## Current Behavior
There are no items in Library
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6064221/Plex.Media.Scanner.log)

Character u2013 is a (dash), I cant figure out what's wrong with the files name.

**Comment by ziggie216** [comment]
I think I got it fixed... apparently some of my files had a longer dash. I couldn't see the length difference using linux command line until I was looking the files using Windows Explorer. Once I had the dash rename to a different dash, scanner was able to process the files.

Is this a normal behavior of accepting only a certain.. not even sure how to descriptive this, a long dash vs shorter dash?

**Comment by ZeroQI** [comment]
File "/config/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 943, in Scan
    Log.info('Youtube folder season gmtime,  season: {}, file: {}'.format(folder_season, filename))
The output doesn't use unicode, This should solve your issue, please update the scanner code and do the plex dance, and report please
