### ISSUE TITLE
Anidb auto-matches do not appear anymore and scan fails to properly separate seasoned animes as separate (anidb like)

### ISSUE THREAD

**Issue by BDiamond** [ZeroQI/Absolute-Series-Scanner#342]
## Platform
Operating system and version: TrueNAS 12.0
Plex version: 1.22.0.4163

## Expected Behavior
Anidb matches should appear when selecting Match... or Fix Match...
After manual matching, subsequent season should be detected as separate (different anidb ID)

## Current Behavior
Failure to match anidb series despite the [anidb-xxxx] tag at the end of each folder.
Only TheTVDB matches are displayed when selecting Match... or Fix Match...
After manual matching, subsequent seasons are added to the last successful manual match despite the different [anidb-xxxx] tags on each folders.

## Steps to Reproduce
1. Scan library (auto or manually)
2. Observe that previously perfectly matched/separated per anidb ID series get regrouped into one starting from season 2 onward.
3. Try to fix the issue by keeping only season 2, to match with anidb
4. Match window only shows TheTVDB tag, manually enforce anidb by appending [anidb-xxxx] to the series name
5. Add the next season and rescan
6. See that the next seasons episodes were added to the previously fixed anidb match.

## Additional information
Reverting to https://github.com/ZeroQI/Absolute-Series-Scanner/commit/b467d410b332066491ecefc6c931d4a4559fb7bc fixes the issue.
I couldn't rely try subsequent versions because of the UnicodeEncodeError bug.

**Comment by ZeroQI** [comment]
`Anidb matches should appear when selecting Match... or Fix Match...`
Not if the series have episodes from a season 2 or more, in which case only TheTVDB matches should appear for HAMA agent search() function, which seem to be the case.
- Why do you match a series with a season 2+ to AniDB? you need to pick AniDB for single season and The TVDB for multiple season content when forcing the ID.
- Why do you create an agent Search() function matching issue against the scanner?
- Which UnicodeEncodeError bug? If latest version have errors, i need logs (custom series scanner and filelist logs and Plex Media Scanner.log)

There have been 22 updates since the version you reference.
You need to include custom series scanner logs (even if created by the version referenced, ) so i can assess if the season folders are detected properly, and if all is passed correctly to the agent.

**Comment by BDiamond** [comment]
While I was setting up a test library on a secondary server to provide logs, I found out wat the issue was. If the name of a folder contains (or end with ?) "Season xx", it has precedence over the [xxxx-xxxx]  tags.
I removed "Season xx" from the folder names and everything worked properly with the current version of the script.

This happened because I have the folders named after the official (Japanese) name of the series like this:
進撃の巨人 attack on titan [anidb-9541]
進撃の巨人 attack on titan Season 2 [anidb-10944]
進撃の巨人 attack on titan Season 3 [anidb-13241]

Since there's an easy workaround, I guess you can close this issue if you think it is not worth fixing.

**Comment by ZeroQI** [comment]
I did make season folders way more permissive, so that makes sense
I believe we need to be permissive with season folders BUT need to implement season folder bypass:
- if a forced id is present
- if it's on a folder inside library root

**Comment by ZeroQI** [comment]
Already excluding the folder in the library root (last one in reverse_folder list), so i guess you put all in a grouping folder:
- Attack on Titan/進撃の巨人 attack on titan Season 3 [anidb-13241], and i just need to exclude forced ids from season folders line 501, could you try this fix `if SOURCE_IDS.search(folder):  break` in you setting with "season x" please?
```
  for folder in reverse_path[:-1]:                  # remove root folder from test, [:-1] Doesn't thow errors but gives an empty list if items don't exist, might not be what you want in other cases
    if SOURCE_IDS.search(folder):  break         #if it has a forced id, not a season folder
    for rx in SEASON_RX:                            # in anime, more specials folders than season folders, so doing it first
```

**Comment by BDiamond** [comment]
Exactly. I put them all in a grouping folder so that they all get in the same collection automatically after the first scan.

Unfortunately this change doesn't work. The folder content are skipped entirely.

[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6138528/Plex.Media.Scanner.log)

**Comment by ZeroQI** [comment]
Reproduces, that should fix it.

**Comment by BDiamond** [comment]
Tested. The issue is fixed, thanks.
