### ISSUE TITLE
UnboundLocalError when grouping folder and series anidb tag used together

### ISSUE THREAD

**Issue by Barker404** [ZeroQI/Absolute-Series-Scanner#346]
## Platform
Operating system and version: WIndows 10
Plex version: Plex Media Server Version 1.22.1.4275

## Expected Behavior
Absolute Series Scanner should be able to scan series that are within a grouping folder and have `[anidb-XXXXX]` tags in the folder name

## Current Behavior
When scanning a series within a grouping folder and with an anidb tag, the logs show the following error:
```
Apr 04, 2021 16:53:13.186 [18016] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 1155, in Scan
    if SOURCE_IDS.search(dir):  Log.info(u'Source id detected: {}'.format(match.group('yt') if match.group('yt') else match.group('id'))); continue        #if it has a forced id, not a season folder
UnboundLocalError: local variable 'match' referenced before assignment
```

## Steps to Reproduce
1. Create a grouping folder at top level of library, e.g. `Group`
2. Create a series folder within grouping folder, with anidb tag in its name, e.g. `Series1 [anidb-101]`
3. Add media file within the series. I think it can be any media file.
4. Scan the library
5. Check the logs in ...\Plex Media Server\Logs\Plex Media Scanner.log

In the example below, where the Test folder is the library root, Series1 causes this error but Series2 does not.
![image](https://user-images.githubusercontent.com/3380702/113514775-7b239900-9568-11eb-9ac4-be9f198930b0.png)

## Additional information
The relevant line is 1150 in Absolute Series Scanner.py:
```
if SOURCE_IDS.search(dir):  Log.info(u'Source id detected: {}'.format(match.group('yt') if match.group('yt') else match.group('id'))); continue
```
I'm not familiar with the code, but it looks like the bug is caused by the fact that the result of the regex search `SOURCE_IDS.search(dir)` on line 1150 is not saved to a variable. Later in the same line there's an attempt to use a `match` variable which I'm guessing is meant to be the result of that regex search.

I tried replacing line 1150 with:
```
match = SOURCE_IDS.search(dir)
if match:
  Log.info(u'Source id detected: {}'.format(match.group('yt') if match.group('yt') else match.group('id')))
  continue
```
and the error appears to have been resolved. I could create a pull request but I haven't properly tested the fix and I don't understand how it could interact with the surrounding code.

If I'm correct about this, it looks like the bug was introduced in commit 63a61315645d0861d1f2a49d3c499015fe7899e4.

**Comment by Barker404** [comment]
After a bit more poking around, it looks like this might occur even without the anidb tag, as long as a grouping folder is being used.

**Comment by ZeroQI** [comment]
Well spotted, leke the old saying says, Barker lewis can't lose :D
Submitted fix to Master code!

**Comment by Barker404** [comment]
Thanks! I can confirm that the error no long occurs in my test library.
