### ISSUE TITLE
Plex token read from wrong environment variable

### ISSUE THREAD

**Issue by ressu** [ZeroQI/Absolute-Series-Scanner#348]
## Platform
Operating system and version: docker image
Plex version: 1.22.2.4282

## Expected Behavior
Plex token should be picked up automatically by the new environment variable

## Current Behavior
Scanner tries to read token from X_PLEX_TOKEN environment variable, but Plex is actually providing PLEXTOKEN environment variable

The token is read here as X_PLEX_TOKEN:
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/620e3d0a6818c5157e94366388ca58ef22118ff8/Scanners/Series/Absolute%20Series%20Scanner.py#L171

After a quite a bit of debugging, I discovered that the correct variable is PLEXTOKEN. And in fact, Hama agent seems to use the correct environment variable:
https://github.com/ZeroQI/Hama.bundle/blob/9e268558c524fb1713661b0eb224a249b3925f6a/Contents/Code/common.py#L52

I can also see the readme referring to `X-Plex-Token.Id` file quite a bit which threw me off a bit on the path to getting plex tokens to work out of the box.

**Comment by ZeroQI** [comment]
Hi, apologies for the error, and well spotted
In the url it was referred to as "X-Plex-Token" so i kept that name for the local file
- dunno if bad coding or bad replacement...
- fix added to master code
