### ISSUE TITLE
[Offtopic] Show example folder structure and configuration

### ISSUE THREAD

**Issue by AbstractUmbra** [ZeroQI/Absolute-Series-Scanner#352]
Hi there.

I am personally having a little difficulty trying to find the correct config/naming scheme required to host movies alongside their anime.
I believe from what I read this is possible but I think the issue is that I am personally not doing it correctly. Could you perhaps show an example file structure that works nicely?

Maybe an example with Bleach and it's many movies, or Naruto?

I have made a few attempts at this and sadly each attempt has resulted in one failure, or another.

**Comment by ZeroQI** [comment]
Movies in series library
- Grouping Folder/Movie [anidb-123456]/Movie.ext
- Grouping Folder/Movie [anidb-123456]/Movie - complete movie.ext

**Comment by AbstractUmbra** [comment]
Thank you for the quick response! Sorry for my delay in replying.
I currently have the following path:
```
Y:\Bleach [anidb-2369]
```

Inside that folder I have
```
Movie Fade to Black (2008) [anidb-6041]\Fade to Black 2008 WEBDL-1080p.mkv
```

So given the example you kindly provided above, is this now acceptable?

**Comment by ZeroQI** [comment]
Pick either anidb or tvdb numbering and name accordingly, group series/movies into a bleach collection would be cleaner

For your current naming i would do as such:
- Bleach/Bleach [anidb-2369]
- Bleach/Movie Fade to Black (2008) [anidb-6041]\Fade to Black 2008 WEBDL-1080p.mkv is wrong
- put 'Local' in agent settings for collection field
- 
Knowing bleach is long, i would have used tvdb4 mode to put the absolutely numbered series into seasons representing Arcs already created, but you do what suits you
```
  <anime tvdbid="74796" name="Bleach">
    01|001|020|Agent of the Shinigami Arc
    02|021|041|Soul Society: The Sneak Entry Arc
    03|042|063|Soul Society: The Rescue Arc
    04|064|091|The Bount Arc
    05|092|109|Bount Assault on Soul Society Arc
    06|110|131|Arrancar: The Arrival Arc
    07|132|151|Arrancar: The Hueco Mundo Sneak Entry Arc
    08|152|167|Arrancar: The Fierce Fight 
    09|168|189|The New Captain Shūsuke Amagai arc
    10|190|205|Arrancar vs. Shinigami Arc
    11|206|212|The Past Arc
    12|213|229|Arrancar: Decisive Battle of Karakura Arc
    13|230|265|Zanpakutō: The Alternate Tale Arc
    14|266|316|Arrancar: Downfall Arc
    15|317|342|Gotei 13 Invading Army Arc
    16|343|366|Lost Agent Arc
  </anime>
```
That would allow to put some specials in a 'specials' folder...
https://www.thetvdb.com/series/bleach/seasons/official/0

Thgat being said, TheYVDB support may stop any day for the API HAMA uses...
