### ISSUE TITLE
Files with unicode characters in the name are throwing exceptions

### ISSUE THREAD

**Issue by drantor** [ZeroQI/Absolute-Series-Scanner#353]
## Platform

Operating system and version: NVIDIA Shield Android TV Version 8.2.2
Plex version: 1.23.0.4459

## Expected Behavior

Files with unicode characters are scanned and shown in Plex

## Current Behavior

A file with a unicode character in the name throws an exception and is not shown in Plex

## Steps to Reproduce

1. Create/Rename a File and put ä, ü or ö in the file name
2. Scan the Library

## Additional information

Tested with Names:
- Test/Fullmetal Panic! - 04 - Entführt.mkv
- Fumetsu no Anata e/Fumetsu no Anata e - 02 - Das unartige Mädchen.mkv
```
May 03, 2021 22:33:10.527 [12192] DEBUG - Scanner: Processing directory /storage/FLEXSTATION/Plex/Share/Anime/Test (parent: yes)
May 03, 2021 22:33:10.615 [12192] DEBUG - Directory had 1 files, database had 0 files, can't skip.
May 03, 2021 22:33:10.745 [12192] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 1117, in Scan
    for entry in standard_holding + unknown_holding:  add_episode_into_plex(media, *entry)
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Scanners/Series/Absolute Series Scanner.py", line 393, in add_episode_into_plex
    if not os.path.exists(file):  file = os.path.join(root, path, file)
  File "/data/user/0/com.plexapp.mediaserver.smb/Resources/Python/python27.zip/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 71: ordinal not in range(128)
```

**Comment by robdplatt** [comment]
Same

```
May 27, 2021 08:22:20.125 [16960] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "C:\Users\platt\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 928, in Scan
    Log.info('season: {}, episode: {}, filename: {},'.format(season, episode, filename))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd8' in position 92: ordinal not in range(128)
```

**Comment by ZeroQI** [comment]
Line 928, can you test with a Unicode string and report:
`Log.info(u'season: {}, episode: {}, filename: {},'.format(season, episode, filename))`

**Comment by ZeroQI** [comment]
@robdplatt please test this release to master code

**Comment by ZeroQI** [comment]
@drantor Do you still have the issue on latest fix ?
If so, am a bit stumped as the issue happen outside the agent on a plain looking line: `if not os.path.exists(file):  file = os.path.join(root, path, file)`, you could try to wrap the 'file =' part in a try: structure to catch the error...

**Comment by drantor** [comment]
@ZeroQI yeah still same issue :/
I will try out the `try` structure.
