### ISSUE TITLE
Enhancement: ANIDB(x)- equivalent mode to TVDB4- possible?

### ISSUE THREAD

**Issue by krbrs** [ZeroQI/Absolute-Series-Scanner#354]
**Is your feature request related to a problem? Please describe.**

Because of issues caused by me editing anime-lists-master and manually mapping seasons with absolute order as default, I took a closer look in the different tvdb-modes possible with ASS, since I'm using only anidb-modes now.

While reading and following the discussion about the absolute order/arc mapping with TVDB4, I found a liking to the concept of TVDB4 mode.

But using TVDB4 would break set up automations with my shoko server (that does the adding to mylist, moving and file renaming so new episodes show up in plex automatically), since this would need to be done by hand, as the TVDB-ID is not available during renaming with shoko.

**Describe the solution you'd like**

If I remember correctly, when adding anime to plex for the first time, the anidb2-id is "translated" to a tvdb-id by the scanner and later metadata is fetched using this id (You can see the "Anime Name tvdb-id" in plex showing up before metadata is available, so I thought this might be the case - correct me if I'm wrong).

If possible, I would like to keep the automations with the anidb(x)-id in the foldername but use the tvdb4 arc mappings along with a new anidb(x)-mode.

Example Folder Structure:

<img width="553" alt="Bildschirmfoto 2021-05-06 um 17 50 07" src="https://user-images.githubusercontent.com/57227244/117328150-a7964200-ae93-11eb-8adb-89efdb2de3b3.png">

**Describe alternatives you've considered**

A different approach could be:

Keeping the foldername with e.g. anidb2-id but adding a ".tvdb4"-file to the folder, so the initial scan is done with the anidb2-id to get the tvdb-id automatically - with this file present, the ".tvdb4"-file arc mappings are respected when adding the files to plex, but the anidb mode can be used.

Example Folder Structure:

<img width="554" alt="Bildschirmfoto 2021-05-06 um 17 50 37" src="https://user-images.githubusercontent.com/57227244/117328191-af55e680-ae93-11eb-93c1-cb0035e927f5.png">

**Additional context**

I know there is an uncertain future with TVDB, so I'm not sad if this feature request is declined because of that or if you think this would not be used by many users.

**Comment by ZeroQI** [comment]
tvdb4.id in the series folder with no id on the series folder name?

**Comment by krbrs** [comment]
I could script my way around in the shoko moving/renaming script if certain anidb-series IDs are hit so nothing is put at the end of the folder name and add a tvdb4.id file in it.

Since I only have to do this once, this would be ok for me, I just have to once decide on the folders I have/want to do that with. I don't have a problem with renaming the folders as I can script my way around so it's still kind of automatic :)

Maybe I can find a way to fetch the TVDB-ID automatically somehow and put a file with it into the folder - basically something like this was the idea behind my question: getting the tvdb-id from the anidb-id and mapping the absolute order to seasons as in tvdb4 without the need of putting a file with the ID into the folder or appending it.


For ANIDB3 being the equivalent to TVDB4: I used anidb3 a while ago and I just tried with One Piece again - everything stays in Season 1 this way. I think this is why I switched to anidb2 after trying a while ago (and started editing the anime-lists file which then worked for me before issues with tvdb4 occurred).

Is this the designed behaviour for anidb3?

TVDB4 does a fine job in splitting it into seasons though. If this was the case with anidb3 this would be my choice then.

**Comment by ZeroQI** [comment]
you can get the tvdb id from animelist xml using the anidb id
yes one piece would stay in one season with anidb3... it use a season per anidb series in relationship order 

I would like to avoid yet another mode. The code is multiple times more complex than another metadata agent and tvdb api change throws a spanner in the gears, and once the api stops users will scream bloody murder

**Comment by krbrs** [comment]
Yeah I totally understand this will be big trouble and yep, this is already a really complex scanner and agent here..
I absolutely appreciate the work you put into this all the time and I'm glad this is here!

I think I will have to go with a mixture of modes:

- anidb-2 will suit most of my needs, since I want Anime like the Slime one or Attack on Titan to be put into seasons under one series

- For series like One Piece, Dragon Ball, Naruto,... which have a tvdb4 mapping I will add an ID file inside of the folder and change the renaming script for the corresponding anidb-IDs

- For Detective Conan I will do the same but think a tvdb3 ID file will be best, since there is no mapping in the tvdb4 mapping xml (or does it have a fallback?)

Thanks a bunch, I think talking about this alone made things much clearer for me and helped me deciding which way to go!

**Comment by ZeroQI** [comment]
tvdb3 use absolute numbering files and keep the absolute episode number but put it in tvdb seasons...
You can create tvdb4 arcs for Detective Conan but it's not really an Arc based series...
