### ISSUE TITLE
4-digit episode number messes with scanner

### ISSUE THREAD

**Issue by krbrs** [ZeroQI/Absolute-Series-Scanner#355]
## Platform

Operating system and version:  Linuxserver-Plex Docker Container running on QNAP NAS
Plex version: 1.23.0.4482

## Expected Behavior

(Sorry for stumbling across stuff like that lately 😅 )

Meitantei Conan hit >1000 Episodes and they are named like this in my library for sorting/consistency:

````
[AConan]_Meitantei_Conan_-_0001v2_(640x480_DivX3)_[B58E4700].avi

up to

[SubsPlease]_Meitantei_Conan_-_1004_(1920x1080_H264_AVC)_[808B408F].mkv

````

Episodes should match their corresponding Season and Episode after scanning.

## Current Behavior

Episodes match the wrong season and episode after scanning.

Examples:

EP 0001 should match s01e01, but matches s00e01
EP 0017 should match s1e17 but matches s1e1 along with more files starting with 001x

It seems scanning messes up with 4 digit episode numbers with leading zeros because it "cuts" them off after 3 digits. Episodes 1000+ seem to show up fine again.

````
"Meitantei Conan [tvdb3-72454]" s00e         1     (Orig: s01e000    ) "SERIES_RX-2" "1v2_ (DivX3)" "[AConan]_Meitantei_Conan_-_0001v2_(640x480_DivX3)_[B58E4700].avi"
"Meitantei Conan [tvdb3-72454]" s00e         1     (Orig: s01e000    ) "SERIES_RX-2" "1_ (Avc)" "[Baaro]_Meitantei_Conan_-_0001_(640x480_H264_AVC)_[6CEBB5FF].mkv"
"Meitantei Conan [tvdb3-72454]" s01e         1                         "SERIES_RX-2" "0_ (DivX3)" "[AConan]_Meitantei_Conan_-_0010_(640x478_DivX3)_[495E2C38].avi"
"Meitantei Conan [tvdb3-72454]" s01e         1                         "SERIES_RX-2" "2_ (DVD_DivX3)" "[AConan]_Meitantei_Conan_-_0012_(640x480_DVD_DivX3)_[1CAD6E80].avi"
"Meitantei Conan [tvdb3-72454]" s01e         1                         "SERIES_RX-2" "7_ (DVD_DivX5_6)" "[AConan]_Meitantei_Conan_-_0017_(640x480_DVD_DivX5_6)_[C3D57183].avi"
"Meitantei Conan [tvdb3-72454]" s01e         1                         "SERIES_RX-2" "8_ (DVD_XviD)" "[AConan]_Meitantei_Conan_-_0018_(640x480_DVD_XviD)_[448DF412].avi"
etc.

````
## Steps to Reproduce

1. Have Series with >1000 Episodes (Conan) and with 4 digit episode number with leading zeros
2. Scan with ASS, the mode used does not seem to make a difference (I used tvdb3 but it's the same with anidb2)
3. Wait for the episodes to show up in plex
4. Find different episodes matched wrong

## Additional information

Logfiles:
[Meitantei Conan.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6439685/Meitantei.Conan.scanner.log)
[Meitantei Conan.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6439686/Meitantei.Conan.filelist.log)

Example Screenshots for S01E01 matched episodes:
<img width="920" alt="Bildschirmfoto 2021-05-07 um 09 12 23" src="https://user-images.githubusercontent.com/57227244/117411937-74e05e00-af14-11eb-8100-1a6875c23ffa.png">
<img width="935" alt="Bildschirmfoto 2021-05-07 um 09 12 51" src="https://user-images.githubusercontent.com/57227244/117411960-79a51200-af14-11eb-9bc2-05ed6fd93286.png">

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py
Series_RX index 2 (3rd one) lines 68-75
```
SERIES_RX       = [                                                                                                                                                              ######### Series regex - "serie - xxx - title" ###
  cic(r'(^|(?P<show>.*?)[ _\.\-]*)(?P<season>\d{1,2})XE?(?P<ep>\d{1,4})(([_\-X]|[_\-]\d{1,2}X)(?P<ep2>\d{1,4}))?([ _\.\-]+(?P<title>.*))?$'),                                    #  0 # 1x01
  cic(r'(^|(?P<show>.*?)[ _\.\-]*)SE?(?P<season>\d{1,4})[ _\.\-]?EP?(?P<ep>\d{1,4})(([ _\.\-]|EP?|[ _\.\-]EP?)(?P<ep2>\d{1,4}))?[ _\.]*(?P<title>.*?)$'),                        #  1 # s01e01-02 | ep01-ep02 | e01-02 | s01-e01 | s01 e01'(^|(?P<show>.*?)[ _\.\-]+)(?P<ep>\d{1,4})[ _\.\-]?of[ _\.\-]?\d{1,4}([ _\.\-]+(?P<title>.*?))?$',                                                              #  2 # 01 of 08 (no stacking for this one ?)
  cic(r'^(?P<show>.*?)[ _\.]-[ _\.](EP?)?(?P<ep>\d{1,4})(-(?P<ep2>\d{1,4}))?(V\d)?[ _\.]*?(?P<title>.*)$'),                                                                      #  2 # Serie - xx - title.ext | ep01-ep02 | e01-02
  cic(r'^(?P<show>.*?)[ _\.]\[(?P<season>\d{1,2})\][ _\.]\[(?P<ep>\d{1,4})\][ _\.](?P<title>.*)$'),
  cic(r'^\[.*\]\[(?P<show>.*)\]\[(?P<ep>\d{1,4})\].*$'),
  cic(r'(^|(?P<show>.*)[ _\.\-]+)(?P<season>\d{1,2})ACV(?P<ep>\d{1,2})([ _\.\-]+(?P<title>.*)|$)') #20th Television production format (Futurama)
  ]
```
I just changes from 1 to 3 digits for ep field to 1 to 4...

**Comment by krbrs** [comment]
This looks good now 👍 I am still missing a few episodes after a scan in my test-library and found that now a few "multi-episodes" are missing.

Example for missing episodes 302,306,317 since only the first part seems to be recognized:

````
Meitantei Conan [tvdb-72454]" s01e       301                         "Word Search" "302" "[DCTP]_Meitantei_Conan_-_0301-302_(640x480_XviD)_[3722E962].avi"
"Meitantei Conan [tvdb-72454]" s01e       305                         "Word Search" "306 (DVD XviD)" "[DCTP]_Meitantei_Conan_-_0305-306_(640x480_DVD_XviD)_[221A7174].avi"
"Meitantei Conan [tvdb-72454]" s01e       316                         "Word Search" "317 (DVD XviD)" "[DCTP]_Meitantei_Conan_-_0316-317_(640x480_DVD_XviD)_[2411959B].avi"
````

Example for correctly recognized episodes 176-178,286-288:

````
Meitantei Conan [tvdb-72454]" s01e       176-178 (Orig: s01e176-178) "SERIES_RX-2" "(AVC)" "[Puto]_Meitantei_Conan_-_0176-178_(960x720_H264_AVC)_[85957C28].mkv"
"Meitantei Conan [tvdb-72454]" s01e       286-288 (Orig: s01e286-288) "SERIES_RX-2" "(AVC)" "[Puto]_Meitantei_Conan_-_0286-288_(640x480_H264_AVC)_[52146EDD].mkv"
````

But this seems to be another cause, right? If so I can open another issue since this one is closed.

**Comment by ZeroQI** [comment]
Word search is before the regex so cannot fix easily...
The underscores in filename don't help

Use s01exxxx-xxxy numbering as workaround

**Comment by krbrs** [comment]
I have to ask the developer of the renamer if it's possible to also pad the count on the 2nd episode number and will change this then.

meanwhile I'll try out the workaround

**Comment by ZeroQI** [comment]
not sure if padding change something, probably not.
if i remove word search algorithm, it will trigger issues as i wrote it to
avoid duplicate number in titles, so tricky to remove for that reason, and
am short in time as i need to fix lambda, especially with tvdb free api end
looming, and need to fix HAMA so if you do create a ticket for that, it
will not be worked on to be honest

**Comment by krbrs** [comment]
Don't worry, I will try the workaround und understand this has no priority/will most likely not be fixed 👍
It's only a few series that have these multi-episodes so it's not a big deal if I switch to another naming convention for them 😊
