### ISSUE TITLE
ASS not working anymore

### ISSUE THREAD

**Issue by WoisWoi** [ZeroQI/Absolute-Series-Scanner#357]
## Platform

Operating system and version: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)
Plex version: Version 1.22.3.4392

## Expected Behavior
Media to be scanned (animes with hama)

## Current Behavior
From the plex logs : 
![image](https://user-images.githubusercontent.com/75491231/118044552-18979700-b377-11eb-9762-6af03dd3acf3.png)

**Comment by ZeroQI** [comment]
Permission error, scanner cannot write logs.
Check Plex use write permissions in logs folder

**Comment by WoisWoi** [comment]
> 
> 
> Permission error, scanner cannot write logs.
> Check Plex use write permissions in logs folder
> 
> https://forums.plex.tv/t/plex-media-scanner-cli-not-working/408322/7
> For the scanner to work:
> 
> Environment variables (APP_SUPP_DIR) must be set

Sorry, I'm not sure to understand how to do it.

> 
> Scanner must be invoked with the same UID PMS is running as.

![image](https://user-images.githubusercontent.com/75491231/118403177-7bd24380-b66d-11eb-9396-c36ec1af66ef.png)
(screenshot of the config.json)

I have to do something else ?

**Comment by ZeroQI** [comment]
It's a Plex issue more than a scanner issue I am afraid...
Make sure Plex user have write access in logs folder

**Comment by ZeroQI** [comment]
Since you have a clear OS permission denied error on a log file, it is an OS issue, therefore 3rd party, closing
