### ISSUE TITLE
Anidb4 not working - Fragments Series into several individual one

### ISSUE THREAD

**Issue by dwilson89** [ZeroQI/Absolute-Series-Scanner#358]
## Platform
Operating system and version: Windows 10 - Build 19041
Plex version: 1.23.1.4603

## Expected Behavior
Expected result should be 1 series, that contains all the entrees as seasons or specials that are flagged with anidb4. As seen in the screen shot below. 
![image](https://user-images.githubusercontent.com/24381372/120089771-aed20800-c140-11eb-88e1-6af994ea200a.png)
![image](https://user-images.githubusercontent.com/24381372/120089778-c27d6e80-c140-11eb-8972-d7baa401194c.png)

## Current Behavior

Fragments the Series into several. Looks to have this behavior for all anidb4 collections in my library. Example below.
![image](https://user-images.githubusercontent.com/24381372/120089871-9b736c80-c141-11eb-8647-3457c0500fdd.png)

Logs Below
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6565586/Plex.Media.Scanner.log)
[Sword Art Online.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6565589/Sword.Art.Online.agent-update.log)
[Sword Art Online.agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6565590/Sword.Art.Online.agent-search.log)
[Sword Art Online.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6565591/Sword.Art.Online.filelist.log)
[Sword Art Online.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6565592/Sword.Art.Online.scanner.log)

## Steps to Reproduce

1.Current Folder structure is as below:
![image](https://user-images.githubusercontent.com/24381372/120089497-441fcd00-c13e-11eb-8d8e-a7a461afd634.png)
2. Ran scanner.
3. Got outcome as shown above.
4. 4. Ive done the dance several times.

## Additional information
Issue look to have be introduced sometime after the 2nd of March 2021, though was unable to pinpoint the change that caused it.

**Comment by ZeroQI** [comment]
```
path: 'Sword Art Online\Sword Art Online (Specials)                         [anidb4- 8692]' => "Sword Art Online (Specials)                         [tvdb6-259640]"
path: 'Sword Art Online\[KH] Sword Art Online - Extra Edition               [anidb4-10022]' => "Sword Art Online - Extra Edition                    [tvdb6-259640]"
path: 'Sword Art Online\[KH] Sword Art Online - Ordinal Scale               [anidb4-11681]' => "Sword Art Online - Ordinal Scale                    [tvdb6-259640]"
path: 'Sword Art Online\[KH] Sword Art Online Alternative - Gun Gale Online [anidb -13494]' => "[KH] Sword Art Online Alternative - Gun Gale Online [anidb- 13494]"
path: 'Sword Art Online\[KH] Sword Art Online II                            [anidb4-10376]' => "Sword Art Online II                                 [tvdb6-259640]"
path: 'Sword Art Online\[KH] Sword Art Online                               [anidb4- 8692]' => "Sword Art Online                                    [tvdb6-259640]
```
I didn't code anidb4 but it assigns tvdb6 so the HAMA Search() should assign the same GUID and Plex see it as one series
There is only one series search and update in logs, and it does have tvdb, not tvdb4...
I would personally have used anidb2 to use Anidb convention on disk and TheTVDB numbering used in Plex...
Do you have more HAMA Search logs?

https://github.com/ZeroQI/Absolute-Series-Scanner/commit/8a2f17e4a4411200498cd05f70c94c73648ff342
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L861
tvdb6?

**Comment by dwilson89** [comment]
Fair Enough. I probably could get away with using anidb3, but i generally use anidb4 for when movies/OVAs are sequels, and I don't want them sitting in specials or by themselves.

To expand on the behavior, from inspection it treats it as follows:
Sword Art Online II as Season 3 in its own Series (Looks to be treating it as [TVDB-259640])
Sword Art Online as Season 1 in its own Series (Looks to be treating it as anidb-8692)
Sword Art Online - Extra Edition as Season 2 in its own Series (unmatched)
Sword Art Online Ordinal Scale as Season 4 in its own Series (unmatched)

Below are the only ones I found for this series.
[Sword Art Online.agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6609908/Sword.Art.Online.agent-search.log)
[Sword Art Online.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6609909/Sword.Art.Online.agent-update.log)

Were you after another example or a different bunch?

**Comment by dwilson89** [comment]
Here is the update logs, when using the version of the scanner from #337 
[Sword Art Online.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6610073/Sword.Art.Online.agent-update.log)
[Sword Art Online.agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6610074/Sword.Art.Online.agent-search.log)

**Comment by ZeroQI** [comment]
Look like matching in HAMA fails but scanner does add "[tvdb6-259640]" to all but one series
I don't think tvdb6 mode exist yet in the search 
One search work, one doesn't but different series folder and scanner versions...

**Comment by dwilson89** [comment]
Oh, the following can be ignored if thats what you mean, i accidentally left it within the Collection Folder. 
Sword Art Online\[KH] Sword Art Online Alternative - Gun Gale Online [anidb -13494]' => "[KH] Sword Art Online Alternative - Gun Gale Online [anidb- 13494]

**Comment by ZeroQI** [comment]
[ ] path:       "Sword Art Online\[KH] Sword Art Online - Ordinal Scale [anidb4-11681]" founf no tvdb6 match as it should

**Comment by dwilson89** [comment]
Ahk, thanks for clarifying, that's interesting behavior.

**Comment by dwilson89** [comment]
I managed to pin point the commit which looks to have introduced the behavior, its from March 19th.
 6eea5e7f456cd2c746e4240e07b178f43759cc90

**Comment by dwilson89** [comment]
It looks to be the line 354 on that commit, commenting this out looks to have resolved the problem. 

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L383?

**Comment by ZeroQI** [comment]
That is highly probable.  It scrubs so much stuff that it becomes difficult to track
Did you comment 354 and shifted former line 255 by 2 spaces left ?

**Comment by dwilson89** [comment]
I didn't end up changing anything else, just commented out that particular line.

**Comment by ZeroQI** [comment]
but... it is an "if loop", the two additional spaces on the line below will throw an error...

**Comment by dwilson89** [comment]
Hmm, i might be confused as to which line requires to be shifted. I am also still testing it with an older file.

![image](https://user-images.githubusercontent.com/24381372/122659295-0bfa3000-d1ba-11eb-8584-29f48a3736af.png)

Though its been awhile since I've played around with python, though was under the impression that particular line I commented out whilst testing wasn't apart of the conditionals surrounding it.

**Comment by dwilson89** [comment]
I believe the following fix for it though is on line 45:
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L45

Change the following:  tvdb(|[2-5]) to tvdb(|[2-6])
![image](https://user-images.githubusercontent.com/24381372/122662212-8637ae00-d1d4-11eb-87a5-1cfe99844d64.png)

**Comment by ZeroQI** [comment]
Do just moving tvdb5 to 6 solve the issue, or does it still need line 383 commented ?

**Comment by dwilson89** [comment]
That line was uncommented.
