### ISSUE TITLE
anidb2 makes scanner freeze when using UNC for library [anidb2-7307]

### ISSUE THREAD

**Issue by vyressi** [ZeroQI/Absolute-Series-Scanner#359]
## Platform

Operating system and version: Windows 10 19041.1023
Plex version:  1.23.2.4625

## Expected Behavior
Library scan scans as normal

## Current Behavior
Library scan hangs.  Process doesn't go 100%, it just ..stops trying to scan until you cancel it and start again.
"Scanning %library% status widget in plex UI states title prior to anidb2 title and just spins forever ( I let it sit 8 hours and no log entries were made )
The log doesn't have anything interesting except half an entry for the show, and once I resolved I can't find the entry anymore.

## Steps to Reproduce

1. have library just fine in mapped drive letter ( previously Q: )
2. change library from using mapped drive to UNC ( now \\repository\anime )
3. scan library
4. library freezes as described.
5. I changed anidb2 to anidb and the scan is working fine now with no hiccups.

## Additional information
The show is K-On!! so it's very possible the exclamation points have something to do with it, if I can hunt down where the freeze was in several MB of scanner logs I will be happy to show you.  once the scan is done I should be able to replicate it.

edit - i used the wrong slashes in my unc

**Comment by ZeroQI** [comment]
> used the wrong slashes in my unc

So a Plex issue... Can we close then ?

**Comment by vyressi** [comment]
> > used the wrong slashes in my unc
> 
> So a Plex issue... Can we close then ?

I meant I used incorrect slashes in my post.  I used the correct UNCs in my plex implementation, the library is scanning right now that I changed things from anidb2 to anidb.

**Comment by ZeroQI** [comment]
UNC sould be '\\server\share\folder'...
How does Plex scanner behave on the same share ?

**Comment by vyressi** [comment]
just made a dummy library to test plex scanner.  i'll let you know when i have results.  

will point out that ASS appears to be working just fine now on that UNC now that I removed the [anidb2-xxxx] tag from two shows.

**Comment by vyressi** [comment]
Plex scanner has finished the dummy library without any obvious issues.

**Comment by ZeroQI** [comment]
So it seem to impact only ASS scanner in anidb2 mode? Any Plex media scanner.log for the issue ?

**Comment by vyressi** [comment]
I also started experiencing the symptoms of hama issue 418 ( https://github.com/ZeroQI/Hama.bundle/issues/418 ) 

This may be related to the fact that my library is in the root of a share, as opposed to a subfolder of it.  Either way my library takes several hours to refresh for every change, I am going to go back to using drive letter share instead of a UNC, this problem still exists and when I am able to make a setup where I can thoroughly test it, I will be glad to put in the time to do so.

**Comment by ZeroQI** [comment]
Will need ASS scanner log or filelist to rule out bad naming conventions

**Comment by vyressi** [comment]
[find.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/6587771/find.txt)

There's the find for that resource.

As I said, the scanner works fine as long as I don't use [anidb2-xxxx]

On a related / unrelated issue, I also, after I corrected the scanner issue, started having a metadata issue, an issue I don't have with the same dataset when accessed as a mapped network drive.

The same dataset works fine when I change to a mapped drive as opposed to a UNC, all of this was to eliminate having to have a user logged in to map the drives.  I will just deal with it until I can transition the box to ubuntu.

**Comment by ZeroQI** [comment]
You use 'grouping folders' though, which is a **hack** and will never cache and it will rescan everything in grouping folder every single time, so if it takes hours... Put all your series folders in the root folder (you can use season folders though) and if will only rescan if the folder content changes and be super fast... If you looked at ASS scanner logs, it does list grouping folders:
```
/FATE/Fate Stay Night [anidb-3348]
/Jojo's Bizzare Adventure (Series)/JJBA - Battle Tendancy [anidb-9304]
...
```
I never said grouping folders was a good idea, it's practical and with huge drawbacks, and using it on super big libraries and UNC could have unforeseen circumstances... I never tested UNC to be honest... 

> UNC names must conform to the \\SERVERNAME\SHARENAME syntax, where SERVERNAME is the name of the Provisioning Server and SHARENAME is the name of the shared resource.
> 
> UNC names of directories or files can also include the directory path under the share name, with the following syntax:
> 
> \\SERVERNAME\SHARENAME\DIRECTORY\FILENAME

You keep talking about UNC but i could not once see a SERVERNAME or SHARENAME so cannot not if their naming is problematic. Impacted folders: 
```
/K-On!! Season 1 [anidb-6257]
/K-On!! Season 2 [anidb-7307]
```
They could be detected as season folders, which could give issues with depending the sharename or library root...
This would be in the scanner logs
It is possible it is detected as season folder and series folder point to library root causing freeze...

Series logs must be compared for both sources, the bottom part will show the metadata for each field and the source that provided it, you can compare that first. I doubt it is an agent issue, you are really meant to create a new library to avoid Plex database issues and not mix path as it will try to reuse media info on different protocols...  

Action plan
- create a new library
- add a root folder containing "K-On! [anidb-6257]" and "K-On!! [anidb-7307]" and without" season xx" in the folder name
- report

**Comment by Eagle1337** [comment]
Doesn't make a difference for me. Ends up with an entry of K-On! [anidb-6257]  with no metadata.

**Comment by ZeroQI** [comment]
Scanner logs?

**Comment by ZeroQI** [comment]
Scanner logs?

**Comment by ZeroQI** [comment]
Closing due to lack of scanner logs
