### ISSUE TITLE
anidb matching broken

### ISSUE THREAD

**Issue by BDiamond** [ZeroQI/Absolute-Series-Scanner#361]
## Platform
Operating system and version: TrueNAS Core 12.0
Plex version: 1.23.2.4656

## Expected Behavior
New episode added to the existing show

## Current Behavior
New episode creates a new show entry with a single episode.

## Steps to Reproduce
1. Add new episode
2. Scan library

## Additional information
Logs:
...
Jun 12, 2021 08:27:54.927 [0x8031d7000] DEBUG - Looking for path match for [/media/Videos/Animation/JP/Dragon Quest/Dragon Quest Dai no Daibouken (2020) [anidb-15321]/ドラゴンクエスト ダイの大冒険（２０２０） - 036 - 超魔生物対チウ.mkv]
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG - Skipping hash check, no size match for 273392456 bytes.
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG - No match for hash.
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG - Checking descendants of Dragon Quest
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG -  -> Searching down into Dragon Quest/Dragon Quest Dai no Daibouken (2020) [anidb-15321]
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG - Checking descendants of Dragon Quest/Dragon Quest Dai no Daibouken (2020) [anidb-15321]
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG -  -> Searching down into Dragon Quest/Dragon Quest [anidb-2091]
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG - Checking descendants of Dragon Quest/Dragon Quest [anidb-2091]
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG -  -> Searching down into Dragon Quest/Dragon Quest [anidb-2091]/Extras
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG - Checking descendants of Dragon Quest/Dragon Quest [anidb-2091]/Extras
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG -  -> Searching down into Dragon Quest/Dragon Quest [anidb-2091]/Extras/(Ep 38-42 Youtube rip with good subs)
Jun 12, 2021 08:27:54.928 [0x8031d7000] DEBUG - Checking descendants of Dragon Quest/Dragon Quest [anidb-2091]/Extras/(Ep 38-42 Youtube rip with good subs)
Jun 12, 2021 08:27:54.929 [0x8031d7000] DEBUG -  -> Searching down into Dragon Quest/Dai no Daibouken - Buchiyabure!! Shinsei 6 Daishougun [anidb-2094]
Jun 12, 2021 08:27:54.929 [0x8031d7000] DEBUG - Checking descendants of Dragon Quest/Dai no Daibouken - Buchiyabure!! Shinsei 6 Daishougun [anidb-2094]
Jun 12, 2021 08:27:54.929 [0x8031d7000] DEBUG -  -> Searching down into Dragon Quest/Dai no Daiboken [anidb-1105]
Jun 12, 2021 08:27:54.929 [0x8031d7000] DEBUG - Checking descendants of Dragon Quest/Dai no Daiboken [anidb-1105]
Jun 12, 2021 08:27:54.929 [0x8031d7000] DEBUG - Creating show 'Dragon Quest Dai no Daibouken (2020) [anidb-15321]'
...

**Comment by ZeroQI** [comment]
...

**Comment by BDiamond** [comment]
Sorry, I just found that for some unknown reason, my Plex server "lost" the HAMA agent...

**Comment by ZeroQI** [comment]
That explains / Forcement ca explique du coup ...
