### ISSUE TITLE
Possible scanner changes for multi-part movies

### ISSUE THREAD

**Issue by pathsny** [ZeroQI/Absolute-Series-Scanner#363]
Multipart movies when named with WebAOM are often named this way.
```Tenkuu no Shiro Laputa - Part 1 of 2.mkv```
```Tenkuu no Shiro Laputa - Part 2 of 2.mkv```

This gets identified by the scanner as episodes 1 and 2. This is actually incorrect and these are episodes 2 and 3. To match them correctly would require adding the episode number to the name. However, the default naming scheme is actually better since Plex Stacking works correctly so these actually show up as  a single file.

Is there any architectural change thats possible that would allow the episode number to be identified by identified by matching the episode name?

**Comment by ZeroQI** [comment]
https://anidb.net/anime/331
- The default scanner stacking would recognize that they are a single episode number as per the naming matching stacked episodes format, which does not correspond to AniDB showing them as ep 2 and 3
- It is a single movies theatrical release, which had been split into two and 3 parts release as well for TV on demand i guess, you opted to download a two episode version of it, which come with the issues you see
- The episode contains no numbering to match the files to ep 2 and 3, then they are numbered incorrectly

The point of the scanner is to deduce the episode numbering from the filename without additional file loading
- i do have forced modes that could change the numbering by loading xml info from either AniDB or TheTVDB

Even if i had made a fix you would have to force an anime id and mode by renaming the folder name , and therefore it makes more sense for you to change the bad numbering at episode level, as it is not even correct for Plex Series scanner, or add the episode number possibly as well through WebAOM

**Comment by pathsny** [comment]
What naming scheme would you suggest? I think one problem with calling it episode 2 and 3 would be that we dont get the default stacking? Im wondering how to get the best of both worlds. The stacking behavior and correct identification of episode numbers? (Or is the correct identification not useful in this case)

**Comment by ZeroQI** [comment]
Next time please download the single file version and there is no issue...
But you do have two files, which matched ep 2 and 3, but for some reason you want to use em stacking?
Then s01e01 and stack it but unsure ASS will stack them
