### ISSUE TITLE
Update Readme following addition of tvdb4

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#37]
Know #34  is still in development, but we should probably have a separate issue tracker to get the readme updated when we've fully solidified how it will work now that there are various options.

**Comment by ZeroQI** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/README.md
Better ?

**Comment by sven-7** [comment]
I think we just need to clarify what you need to do for each option.

Example:  Option1:  for option one you could put [tvdb4-xxxxxx] or a tvdb4.id file with xxxxxx inside of it.

I think it's option 2/3 that need more clarification.  I don't quite understand how to do that myself.

**Comment by ZeroQI** [comment]
anidb and tvdb just specify the guid and metadata source
tvdb 2 3 4 are virtual modes (they show seasons that are not there, apart if done manually in tvdb 4 mode only). the guid is received the same way.

For tvdb 4, some arbitrary seasons are selected with absolute numbering eps inside (like tvdb3)... 
It uses the seasons folders the user created. if he created none, it uses the local tvdb4.mapping file, and if not there, it pulls the xml from github.

**Comment by sven-7** [comment]
Sorry, I meant by option 3 tvdb4 (option 3: xml from github).  Understood -- the XML option worked perfectly for Seraph of the End both with user created seasons and by downloading the mapping from Github.

**Comment by ZeroQI** [comment]
Thanks for explaining. Didn't got what option 3 refered to....
