### ISSUE TITLE
TVDB Movid ID support?

### ISSUE THREAD

**Issue by Neipas09** [ZeroQI/Absolute-Series-Scanner#370]
Is there any way you can support TVDB's Movie ID's with TV Libraries?

For example, https://www.thetvdb.com/movies/the-witcher-nightmare-of-the-wolf
This has a THETVDB.COM MOVIE ID: 136400

But if i search for 136400 using HAMA + ASS it doesn't come up with anything in my Anime TV Library.

Of course, If i move the movie to a "Movie" library, then it finds it with no issues and pulls all the metadata just fine.
But this defeats the purpose of trying to have 1 Library for all my Anime. (movies + series)

**Comment by ZeroQI** [comment]
Your movie library is not using hama as agent so your statement is misleading

As per the readme ASS support movies in tv libraries with anidb or TMDb id and the file and containing folder need to be named appropriately

TheTVDB movies is not supported and support will be likely deprecated with the legacy TVDB API ending in november

**Comment by Neipas09** [comment]
You either don't read or don't comprehend what i asked, because your response above is 100% FALSE!

I am indeed using HamaTV as the Agent and ASS as the scanner. 
To claim i'm not is just about the most idiotic thing i've ever heard when you 
1) Don't know how my server is setup, and 
2) Have no fucking clue how my server is setup!
![image](https://user-images.githubusercontent.com/58871039/130644432-9b179a89-3bf2-4e88-b12f-1ea9feec07b2.png)


To help you better understand...
1) I have a TV LIBRARY, NOT A MOVIE LIBRARY! (as i stated in the first line of my original post)
2) There is no Anidb ID number
3) The TMDB ID number (666243) doesn't work when i add it to the end of the folder i have created for the movie. 
Exact setup: 
Folder Name = **The Witcher - Nightmare of the Wolf [tmdb-666243]**
File Name = **The Witcher - Nightmare of the Wolf (2021).mp4**
(https://www.themoviedb.org/movie/666243-the-witcher-nightmare-of-the-wolf)

**Comment by ZeroQI** [comment]
> Of course, If i move the movie to a "Movie" library, then it finds it with no issues 

Your movie library (in above statement) is not using hama as agent (since I never implemented TheTVDB movie ID) so your statement (above) is misleading.

If I am mistaken, please attach HAMA search logs from above test...
The TMDB search logs would have helped as well...

The TVDB part will stop working in October and HAMA will stop working... Tic... Toc...
