### ISSUE TITLE
ASS and new plex series scanner

### ISSUE THREAD

**Issue by lishan89uc** [ZeroQI/Absolute-Series-Scanner#371]
**Is your feature request related to a problem? Please describe.**
With plex moving toward their own plex tv series agent. is it possible to make ASS compatible with that? To be honest i am not sure what is happening. Since switching to the tv series agent cause the scanner to jump to plex is this a plex side issue or an ASS side issue?

**Describe the solution you'd like**
since plex scanner doesn't work very well, it would be nice to be able to use ASS instead of plex scanner but still use the plex agent

**Describe alternatives you've considered**
the only other alternative is go back and rename 5 years of anime. since plex tv scanner doesn't even pick those up.

**Additional context**

**Comment by ZeroQI** [comment]
Plex side issue. New scanner and agent no longer use python, look like agent use become deprecated for Plex, and we fear they will remove third party agent support anytime as its use is marginal compared to their overall market size

If it's worth keeping, it's worth renaming, as renaming time compared to the viewing time is marginal
You should label properly label your files regardless of the tool, ASS tried to make it more tolerant

ASS works with HAMA, you can't have both ASS and new agent, make your pick, knowing TheTVDB free API stop the 1st of October so you might have to pay a yearly subscription IF we code the TVDB v4 API...

**Comment by lishan89uc** [comment]
> Plex side issue. New scanner and agent no longer use python, look like agent use become deprecated for Plex, and we fear they will remove third party agent support anytime as its use is marginal compared to their overall market size
> 
> If it's worth keeping, it's worth renaming, as renaming time compared to the viewing time is marginal
> You should label properly label your files regardless of the tool, ASS tried to make it more tolerant
> 
> ASS works with HAMA, you can't have both ASS and new agent, make your pick, knowing TheTVDB free API stop the 1st of October so you might have to pay a yearly subscription IF we code the TVDB v4 API...

Wow, I didn't know... i feel bad for complaining to plex now... Hmmm, may i ask if other python base db's will still work? like anidb? if so i don't think it would cause me much disruption unless plex removes 3rd party scanners entirely. Thank you for enlightening me. I don't follow plex news much.

**Comment by ZeroQI** [comment]
Movies and anidb stay free, but depending on the amount of tvdb traffic that will be transfered to tmdb they might have issues as quite a few open source projects are switching....

Yeah the 3rd party agents Plex future is uncertain and new scanner/agent are very good but prevent 3rd party ones.

Is it because the title is not named as per anidb/tvs it won't be found?
