### ISSUE TITLE
Scanner fails

### ISSUE THREAD

**Issue by Erdk2** [ZeroQI/Absolute-Series-Scanner#372]
Hi there! Plex was recently updated and has a broken scanner. Did this happen to someone?. Thank you!

**Comment by ZeroQI** [comment]
Which version worked last?
Which version failed?
Which error do you have in logs?

**Comment by Speedmod88** [comment]
for animes no, only real series work at least lol

so you suggest to have a folder of the anime series names? 
ex: /ANiMES/Boruto/Boruto.Naruto.Next.Generations.E213.SUBFRENCH.720p.HDTV.x264

with that folder its supposed to work with ASS?

**Comment by ZeroQI** [comment]
Yes.

It is a mandatory setup for ANY series based metadata ecosystem, whereas it is XBMC/Kodi, Emby, Plex...

You are not meant to have episode in folders but might work
