### ISSUE TITLE
Plexignore file not working

### ISSUE THREAD

**Issue by Warsen** [ZeroQI/Absolute-Series-Scanner#374]
## Platform

Operating system and version: Windows 10
Plex version: 1.24.2.4973

## Expected Behavior

It is expected that .plexignore files define rules for files that should be ignored by scanners. If I listed something in the ignore file, it should not be added to my library when scanned.

## Current Behavior

.plexignore file doesn't seem to be working at all. I switched from using the standard scanner into using Absolute Series Scanner and found that everything I defined in an ignore file got added to my library. Here is my ignore file at my base content directory.

```
# Ignore directory "_Adult"
_Adult/*

# Ignore directory "_Movies"
_Movies/*

# Ignore directory "_Specials"
_Specials/*

# Ignore subdirectories "Extras"
*/Extras/*

# Ignore subdirectories "Modified"
*/Modified/*

# Ignore all files with "NCOP", "NCED", "Recap" in the name
*NCOP*
*NCED*
*Recap*
```

Even with this ignore file, all of my intentionally hidden movies, specials, and OPs/EDs got added to my library.

## Steps to Reproduce

1. Copy my .plexignore file into the main content scan directory. In my case it was F:\Anime\
2. Put some series video into _Specials, doesn't matter what it is. Just for the an example, F:\Anime\\_Specials\With Hinako\Sleeping With Hinako.mkv
3. Scan media using Absolute Series Scanner, you will have that special come up.
4. Alternatively you can also check if NCOP or NCED files show up. I wanted them ignored, but they did show up.

## Additional information

I already manually worked around it by finding and editing the IGNORE_DIRS_RX_RAW to just hardcode my desired ignore rules. On a side note, what is up with the rule r'^subs?$'? Why does that one have a ^ start of line and $ end of line when all the others do not? Also a suggestion, you should make the 's' in Extras optional just like the 's' in Samples is optional. It would also be nice to have all directories that start with an underscore be just be ignored, unless there is some series name I don't know about that starts with underscore, it sounds to me like a directory starting with an underscore implies the admin intended for it to be hidden. Thanks.

**Comment by Warsen** [comment]
I'm sorry I got this wrong, filename ignore in a plexignore file is working fine. It's only my attempt to ignore directories that was failing to work, as now that I think about it, I only saw files named OP and ED when I only excluded NCOP and NCED somehow I failed to notice this before I even switched to Absolute Series Scanner

**Comment by Warsen** [comment]
On further investigation, I think I see where it all went wrong. "The * character is a wildcard" rule doesn't apply at all because that's not a rule in any regular expression engine. The standard * for wildcard worked when I use the default built-in Plex Series Scanner, but it won't work for this scanner because * alone is 'zero or more' of the preceding character in the pattern. Nothing in my plexignore file worked because my plexignore is built to specifications that are not like regular expression patterns.

To fix this for files, patterns obtained from a plexignore file will need to add a period before *. Every line would also have to be cleaned so that it can not trigger any regex tokens, because they aren't supposed to be allowed. To fix this for directories, the code needs to be rewritten entirely. The current way the code is written, you could not possibly have any wildcards in directories you want to ignore. Honestly, it's better to just rewrite scan function so that regular expression matching isn't used anymore. There's no reason to use regex when a custom match function allowing * as a wildcard can be sufficient for all your needs.

I'd be glad to code and contribute fixes, but I don't at all know how to debug this python script. What does a typical function call to scan(path, files, media, dirs) look like? Does scan get called for the root directory and then once every sub-directory?

**Comment by ZeroQI** [comment]
I never used the command line but here it is:
https://support.plex.tv/articles/201242707-plex-media-scanner-via-command-line/

**Comment by Warsen** [comment]
@ZeroQI I finished writing those code changes. I am not sure if I have perfect 1:1 behavior replicated from the regular plex series scanner, but for the test cases I could think of, it works great. I'll clone the project and submit it as a pull request. I'd like you to work with me on this by examining my new set of hardcoded ignore patterns and verifying that they do what you want. I actually put in less file rules than what was previously there because I was thinking it really should be the end-user's task to add .plexignore rules for content they don't want getting matched. Since the new .plexignore code works so great, there is no need to rely on so many hardcoded file rules.

My lists are called IGNORE_DIRS and IGNORE_FILES. The old lists are called IGNORE_DIRS_RX_RAW and IGNORE_FILES_RX. My rules are strings, not regexes. The old lists will be left in the file for your immediate reference. You should convert additional rules from IGNORE_FILES_RX to IGNORE_FILES if you think they should still be hardcoded.

**I ran into this crazy anomaly where if I add a line `*/_*` into the .plexignore file, over 99% of all my series would not be scanned,** and it has nothing to do with any of our scanner code. It appears to be happening outside of our code even though no other rules from .plexignore do anything without our code.

So because of that anomoly, I'm currently deciding whether I should just place hardcoded rules to ignore directories and files that start with underscores, _taking it out of the hands of the end-user_. **What is your opinion?** I'll post that pull request after the decision.

**Comment by efalsken** [comment]
I'm going to say this is fixed now (at least on windows). Works great!
