### ISSUE TITLE
Don't create grouping collections if there's only one show

### ISSUE THREAD

**Issue by Pluckerpluck** [ZeroQI/Absolute-Series-Scanner#378]
I am new to trying to use both this and Hama.bundle, so this may exist, and I may just be an idiot, but there equally doesn't seem to be anywhere else to ask this as a question. So I'm putting it as a feature request on the off chance it's a thing.

Let's say I have the folder structure:

```
/media/anime/One Punch Man/[01] One Punch Man S1/One Punch Man S01E01.ext
/media/anime/One Punch Man/[01] One Punch Man S1/Specials/One Punch Man S00E01.ext
/media/anime/One Punch Man/[02] One Punch Man S2/One Punch Man S02E01.ext
/media/anime/One Punch Man/[02] One Punch Man S2/Specials/One Punch Man S00E11.ext
```

This effectively creates the following. A show (consisting of three seasons, including the specials), and a collection for the top level folder.

![image](https://user-images.githubusercontent.com/175488/136992337-288f44f0-4695-4a3c-9d06-ed243501bc87.png)

In general, I want this ability to create grouping collections. Who knows, perhaps they'll release a movie that I want in this collection. But right now, the collection only contains 1 show.

As a result, if I choose to hide shows that are in collections, you end up just getting an extra click that's not needed.
![image](https://user-images.githubusercontent.com/175488/136992616-8cb19003-ec88-4fbd-9f5d-34664be71bc9.png)

Is there any way to have the collection not auto generate if there is only one show beneath it? That way the show itself would appear top level in the library.

If not, can this be a feature (in the same way the newest Movie agent only adds collections automatically when you have X many movies that match)?

------------

Note: The obvious "solution" is to manually remove these from collections, but that's somewhat annoying. Being automated would be nicer.

**Comment by ZeroQI** [comment]
The new movie agent isn't written in Python to my knowledge and need new style libraries that don't support agents...

A collection is a field assigned to the movies or series.
If I don't assign it when there's not enough, it will never be assigned since updates are series/movies updated separately...

Could it be done at agent level?
Yes if doing a separate collection table with guids and counting them to create them but you couldn't rename or remove
