### ISSUE TITLE
Dragon Ball Z - tvdb4 not working

### ISSUE THREAD

**Issue by Tyestor** [ZeroQI/Absolute-Series-Scanner#381]
## Platform

Operating system and version: Unraid 6.9.2
Plex version: Version 1.24.4.5081

## Expected Behavior
Split DBZ into sagas based on the xml file

## Current Behavior
Does not split DBZ into sagas based on the xml file

## Extra Info

First I renamed `Dragon Ball Z (1989) [tvdb-81472]` to `Dragon Ball Z (1989) [tvdb4-81472]`. Then I told Sonarr to change the DBZ folder structure to absolute ordering (no season folders). So I just just had every episode in one folder named like `Dragon Ball Z (1989) - S01E01 - 001 - The New Threat [DVD][8bit][x264][Vorbis 1.0][JA+EN]-DBNL`. When I scanned for updates, only 39 episodes and no season/saga folders appeared in plex. Doing plex dance did not change this. 

![image](https://user-images.githubusercontent.com/4704145/139531617-f0a45ad1-e5c7-4cd7-b7d4-5a22821d61f1.png)

After that, I told Sonarr to go back to the season layout according to TheTVDB season structure, re-scanned, and all that did was make `tvdb4` behave the same as `tvdb` (all episodes show up in 9 season folders). Plex dance again did nothing.

## Logs:

[Dragon Ball Z (1989) [tvdb4-81472].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7446366/Dragon.Ball.Z.1989.tvdb4-81472.filelist.log)
[Dragon Ball Z (1989) [tvdb4-81472].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7446368/Dragon.Ball.Z.1989.tvdb4-81472.scanner.log)
[Dragon Ball Z (1989) [tvdb4-81472].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7446431/Dragon.Ball.Z.1989.tvdb4-81472.agent-search.log)
[Dragon Ball Z (1989) [tvdb4-81472].agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7446430/Dragon.Ball.Z.1989.tvdb4-81472.agent-update.log)

Files and folders are named exactly according to trash guides anime naming scheme for Sonarr. Folder structure is the recommended layout as well.

I've never used tvdb4 before, so I might be missing something here. I'd like to make use of it more from now on.

**Comment by Tyestor** [comment]
Well, after a bit more investigating it turns out the mapping in the XML file is identical to the TVDB season layout...I eated my own mapping

```
  <anime tvdbid="81472" name="Dragon Ball Z">
    01|001|006|Raditz Saga
    02|007|035|Vegeta Saga
    03|036|067|Namek Saga
    04|068|074|Captain Ginyu Saga
    05|075|107|Frieza Saga
    06|108|117|Garlic Jr. Saga
    07|118|125|Trunks Saga
    08|126|139|Androids Saga
    09|140|152|Imperfect Cell Saga
    10|153|165|Perfect Cell Saga
    11|166|194|Cell Games Saga
    12|195|199|Other World Saga
    13|200|209|Great Saiyaman Saga
    14|210|219|World Tournament Saga
    15|220|231|Babidi Saga
    16|232|253|Majin Buu Saga
    17|254|275|Fusion Saga
    18|276|287|Kid Buu Saga
    19|288|291|Peaceful World Saga
  </anime>
```

But I can't get DBZ in Plex to follow it. Am I supposed to have all the files named according to this as well? That is not going to play nice with Sonarr (and is going to be extremely tedious).

**Comment by Tyestor** [comment]
Swapping from `Dragon Ball Z (1989) - **S01E01 - 001** - The New Threat [DVD][8bit][x264][Vorbis 1.0][JA+EN]-DBNL` to `Dragon Ball Z (1989) - **001 - S01E01** - The New Threat [DVD][8bit][x264][Vorbis 1.0][JA+EN]-DBNL` fixed the issue of only 39 episodes showing up in Plex. This is probably some sort of parsing bug. I still don't know how to get my custom mapping to show up, however.

**Comment by ZeroQI** [comment]
You have two numbering present on a single file, which is not supported. This trigger both absolute numbering hence doesn't put in seasons due to bug.
If you remove

**Comment by Tyestor** [comment]
No, it does not work still.

What I did:

1. Renamed all the files to `Dragon Ball Z (1989) - 001 - The New Threat [DVD][8bit][x264][Vorbis 1.0][JA+EN]-DBNL` or similar
2. Moved Dragon Ball Z folder out of anime directory
3. Empty trash
4. Clean bundles
5. Optimise database
6. Moved Dragon Ball Z folder back to anime directory
7. Scanned library files

Still 9 seasons, the same nine seasons that are on tvdb, not my mapped sagas in the XML.

**Comment by ZeroQI** [comment]
tvdb4.mapping file in root folder with:
`    01|001|006|Raditz Saga
    02|007|035|Vegeta Saga
    03|036|067|Namek Saga
    04|068|074|Captain Ginyu Saga
    05|075|107|Frieza Saga
    06|108|117|Garlic Jr. Saga
    07|118|125|Trunks Saga
    08|126|139|Androids Saga
    09|140|152|Imperfect Cell Saga
    10|153|165|Perfect Cell Saga
    11|166|194|Cell Games Saga
    12|195|199|Other World Saga
    13|200|209|Great Saiyaman Saga
    14|210|219|World Tournament Saga
    15|220|231|Babidi Saga
    16|232|253|Majin Buu Saga
    17|254|275|Fusion Saga
    18|276|287|Kid Buu Saga
    19|288|291|Peaceful World Saga`

**Comment by Tyestor** [comment]
Okay, that worked. But I don't understand. In the README.md it says "Will take the arc definitions from tvdb4.mapping.xml and posters from tvdb4.posters.xml unless the absolute numbered episodes were placed in season folders already " - This didn't work for me. Why won't editing the XML in the Plex Media Server appdata folder work?

**Comment by ZeroQI** [comment]
Takes it from the online file, not locally
It put in season folders but you used SxxExx alongside absolute numbering. Sorry but double numbering isn't supported and trigger a bug

**Comment by Tyestor** [comment]
By online file do you mean the one in the github repository? If so, that makes more sense.

**Comment by ZeroQI** [comment]
Correct
