### ISSUE TITLE
Episodes >= 1000 detecting incorrectly

### ISSUE THREAD

**Issue by Winter** [ZeroQI/Absolute-Series-Scanner#383]
With episodes >= 1000 Plex seems to be detecting them incorrectly when using ASS.

## Platform
Operating system and version: Unraid (Docker)
Plex version: 1.24.5.5173

## Expected Behavior
ASS should detect "One Piece - 1000 [1080p WEB-DL].mkv" as episode 1000

## Current Behavior
ASS detects "One Piece - 1000 [1080p WEB-DL].mkv" as Season 0, Episode 0 (Specials).
"One Piece - 1001 [1080p WEB-DL].mkv" is detected as Season 10, Episode 1.

## Steps to Reproduce

1. Rename an episode absolute number to anything greater than 1000

## Additional information

Seems to be an issue with a lot of things, not entirely sure whether it's a Plex issue or an ASS issue.

**Comment by ZeroQI** [comment]
Any chance you could attach ASS log output in logs folder? Seem like a series Regex format to remove, depending the log output, but I am not in any position to reproduce sadly...

**Comment by Winter** [comment]
So, I'm not really sure how to explain this but when I opened Plex yesterday it had reverted from the whole Special season and season 10 to episode 1000 and episode 1001 respectively.. I haven't changed, restarted or updated anything. I would think myself mad if I didn't take a screenshot at the time.. sorry for wasting your time!

<img width="242" alt="Screen_Shot_2021-11-28_at_2 44 40_pm" src="https://user-images.githubusercontent.com/11798919/143935164-fffaf4f9-9cd9-469f-9c32-6ecb9d6fed68.png">
