### ISSUE TITLE
One Piece Episode 1000 being matched incorrectly using tvdb4

### ISSUE THREAD

**Issue by Kadenar** [ZeroQI/Absolute-Series-Scanner#384]
I am using tvdb4 to sort One Piece into individual story / arcs in Plex.

The episode is being incorrectly read as Special 501:
![image](https://user-images.githubusercontent.com/37740708/145638551-ca94cb84-bbe2-4e4e-81c2-753e6edb022b.png)

I am using a custom override for the standard tvdb4.mapping (uploaded below as a .txt file).

"One Piece 1999 [tvdb4-81797]" s51e       999     (Orig: s01e999    ) "Word Search" "" "[Judas] One Piece 999 [1080p] [x265].mkv"
"One Piece 1999 [tvdb4-81797]" s51e      1001     (Orig: s01e1001    ) "Word Search" "" "[Judas] One Piece 1001 [1080p] [x265].mkv"
"One Piece 1999 [tvdb4-81797]" s51e      1002     (Orig: s01e1002    ) "Word Search" "" "[Judas] One Piece 1002 [1080p] [x265].mkv"
"One Piece 1999 [tvdb4-81797]" s00e       501                         "__" "1000" "[Judas] One Piece 1000 [1080p] [x265].mkv"

My folder is named: One Piece 1999 [tvdb4-81797]
All episodes are in absolute order and not in subfolders.

I've also attached the filelist and scanner logs below:

[One Piece 1999 [tvdb4-81797].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/7695332/One.Piece.1999.tvdb4-81797.filelist.log)
[One Piece 1999 [tvdb4-81797].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/7695333/One.Piece.1999.tvdb4-81797.scanner.log)
[tvdb4 - Copy.txt](https://github.com/ZeroQI/Hama.bundle/files/7695337/tvdb4.-.Copy.txt)

Let me know if there is anything else you need to aid in debugging.

**Comment by Kadenar** [comment]
Thanks for transferring the issue here. I wasn't 100% certain on whether it was a matching issue with the agent, or if it was a scanner issue. In hindsight, when looking at the scanner logs, I probably should have realized.

As for reproduction steps, my setup is:

Folder structure:
/Anime/Shows/One Piece 1999 [tvdb4-81797]

Plex scanner -> Absolute Series Scanner
Agent -> HamaTV

I included the custom tvdb4.mapping which is placed in the above directory along with the episodes.

Expectation would be for Episode 1000 to be mapped similar to 1001 and 1002:
"One Piece 1999 [tvdb4-81797]" s51e 1000 (Orig: s01e1000 ) "Word Search" "" "[Judas] One Piece 1000 [1080p] [x265].mkv"

**Comment by ZeroQI** [comment]
All meta mentionnés are documented as per the very last 20 lines of the log...

**Comment by Kadenar** [comment]
Okay, I'll just edit this episode manually for the time being. It's at least in the right season now, thank you!
