### ISSUE TITLE
Unexpected Merging and Mixing of Anime Episodes with ASS - Detective Conan

### ISSUE THREAD

**Issue by EarthBoundX5** [ZeroQI/Absolute-Series-Scanner#391]
While the outcome issue is the same, opening a new Bug report from this one as the cause is different
https://github.com/ZeroQI/Absolute-Series-Scanner/issues/388

After creating a clean library, adding folders, and confirming ASS is set as the scanner and Hama as the Agent; I found similar issues to those reported in the ticket above...however, on the surface it at least looks contained to the correct series instead of mixing different series together.

![image](https://user-images.githubusercontent.com/2718666/150022164-5de62d59-fd0b-41ca-b686-c92836445ea4.png)

The issue I'm witnessing is mis-categorization of Season vs Special for the show Detective Conan / Case Closed.  I purely guess this may be do to the large episode count using 4 digits instead of the expected 1, 2, or 3.

![image](https://user-images.githubusercontent.com/2718666/150022218-c61cf9a8-75ba-4481-82af-ee25633ed633.png)

As seen, it looks like it starts off with episode 1 being marked as a Special episode 501.

![image](https://user-images.githubusercontent.com/2718666/150022291-165dead1-8db9-45f3-8501-42d8388b12c0.png)

And for some reason it's taking multiple versions and made it a separate episode, 502.

![image](https://user-images.githubusercontent.com/2718666/150022389-a3324891-0b10-4faa-8308-abb0671829cd.png)

The same is seen here with 676 and 677

![image](https://user-images.githubusercontent.com/2718666/150022467-4d9c4b8c-2a11-4f1d-ba7e-2ca63fbeeb9b.png)

Where this gets problematic is the episodes then marked as Season 1.  Where Episode 1 is filled with around 44 episodes (technically 22, as it's at least grabbing the double copies of the same episode).

![image](https://user-images.githubusercontent.com/2718666/150022576-86908bae-b5e2-4571-a914-a891543b5953.png)

Random spot checks imply that after the first (or first few) episodes, the remainder appear to be good.

![image](https://user-images.githubusercontent.com/2718666/150022862-9b3baff2-9f46-4a61-bf3d-cf1932e7cac6.png)

I'm thinking that this may be to do with the added "Part 1" distinction on some of the episodes, and maybe it's being imported as Episode 1 subsequently.  As episodes 2 and 3 seem to have Part 2 and Part 3 episodes (note Episode 3 doesn't have Episode 3 in it).
Ep2
![image](https://user-images.githubusercontent.com/2718666/150023057-d9bffad6-f015-430f-afcd-49b65c2afa86.png)
Ep3
![image](https://user-images.githubusercontent.com/2718666/150023118-f1f979c2-e25e-494c-a538-5902ec7bd47d.png)

I'm not really sure that there is a solution to be made with my naming, as I'm following pretty consistent standards and if any of this is to be blamed on Part 1/Part 2/Part 3, that'd be a bug I'd say, as it's episode titles pulled from anidb, not added.

Thanks for any time in resolving this!

==================================================================================

## Platform
Operating system and version: Windows Server 2019 (Version 1809, Build 17763.2366)
Plex version: 1.25.3.5409

## Expected Behavior
I would expect episodes to be matched to their correct episodes, double episodes to be grouped to the same episode as multiple versions, and incorrect episodes to not be grouped with a completely different episode.

## Current Behavior
See above description.
Log:
[Plex Media Server Logs_2022-01-18_15-44-42.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7892546/Plex.Media.Server.Logs_2022-01-18_15-44-42.zip)
Please note for the logs, Plex is still in progress detecting intros to my new anime library.

ASS Log for Case Closed:
[Case Closed (1996) [anidb-266].zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7892560/Case.Closed.1996.anidb-266.zip)
I can provide all ASS logs if needed.

## Steps to Reproduce
1. Create New Library.  Set to Absolute Series Scanner and Hama.Bundle.
2. Scan library, including show Case Closed / Detective Conan.  Filenames should be like this: Case Closed - 0286 - The Kudou Shinichi NY Case (Part 1 - The... [Kaizou][DTV](28AA5843).avi 
3. Observe reported issue.

## Additional information
See above.

**Comment by ZeroQI** [comment]
Is the issue fixed by the commit referenced?

**Comment by ZeroQI** [comment]
Is the issue fixed by the commit referenced?

**Comment by ZeroQI** [comment]
Closing due to fix pushed to master and no reply to 2 comments asking for feedback
