### ISSUE TITLE
some text on plexignore not working

### ISSUE THREAD

**Issue by artoargue** [ZeroQI/Absolute-Series-Scanner#392]
Thanks to scanner.

I use this scanner to japanese anime.

# Ignore all files with "trailer" in the name
*trailer*
*SPOT*
*CM*
*MENU*
*NCOP*
*NCED*
*特典*
*OP&ED*

# Ignore files with the extension ".cr2"
*.cr2
*.smi
# Ignore all ".tif" files in the "thumbnails" subdirectory
*thumbnails/*.tif

# Ignore directories called "Modified"
*/Modified/*
*/CDs/*
*/Extras/*
*/Scans/*
*/特典/*
*/menu/*
*/scan/*
*Extra/*
*Picture Drama/*
*/Credits/*
*/特典CD*/*

these .plexignore

but files text or directory name include 特典 not ignored by scanner.

**Comment by ZeroQI** [comment]
unicode encoding for the strings needed most likely

you can try the below (cannot test at the moment)

https://github.com/ZeroQI/Absolute-Series-Scanner/edit/master/Scanners/Series/Absolute%20Series%20Scanner.py
571:        pattern = u''+pattern.strip()
573:        cwd = u'/'.join(path_split2[1:index+1])

**Comment by artoargue** [comment]
> 

thanks to support. It work correctly!
