### ISSUE TITLE
Anidb4 not working and ASS not creating logs per new series

### ISSUE THREAD

**Issue by Roshri** [ZeroQI/Absolute-Series-Scanner#393]
I tried testing anidb4 with series I haven't yet added to my plex library, but those seem to be added as plain anidb.
Series in question is Highschool DxD and all subsequent seasons and OVAs

Deleted from the library, did a rescan, emptied trash, moved directories back, rescan, still picked up as anidb.

Tried looking for the per-series logs but those haven't been created at all. Double checked and updated Plex Token just in case. Still no logs for new series. Issue seems to have started around New Years, because I just noticed no series added in January have per-series logs in the folder

![image](https://user-images.githubusercontent.com/29184137/150397661-a734be32-907d-4227-9e88-737cc07908a3.png)

The folders have this structure

![image](https://user-images.githubusercontent.com/29184137/150397296-65684e92-dae1-4c0f-855a-cfcfaba8019d.png)

## Platform

Operating system and version: Win 10
Plex version: 1.25.3.5409

## Expected Behavior
Add a series with anidb4 keys and have them mapped into a single series with multiple seasons

## Current Behavior

Series fallback to anidb1

## Steps to Reproduce

1. Add Highschool DxD and its sequels to a plex library
2. Scan
3. Series show as anidb1

[_root_.agent.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7907614/_root_.agent.log)

[_root_.agent.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7907607/_root_.agent.log)

[_unknown_folder.agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7907612/_unknown_folder.agent-search.log)
[_unknown_folder.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7907613/_unknown_folder.agent-update.log)
[Plex Media Scanner (custom ASS) - filelist .log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7907619/Plex.Media.Scanner.custom.ASS.-.filelist.log)

**Comment by ZeroQI** [comment]
You need to look into Plex media scanner logs for crash errors

I didn't add code for anidb4 and to be honest don't understand the point of it, so will not answer that point.

You are showing on a bug report for the scanner:
- per series agent logs missing
- forced Id not taken into account by agent search function 

Are you 100% sure ASS in showing as scanner in your library currently?

**Comment by Roshri** [comment]
Yup, library shows ASS as the scanner
![image](https://user-images.githubusercontent.com/29184137/150432455-01fbb6c0-b503-4222-8511-7866b6854ca3.png)
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7908927/Plex.Media.Scanner.log)
[Plex Media Scanner.1.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/7908925/Plex.Media.Scanner.1.log)

I'm aware I'm missing per series logs but I'm also unable to generate or locate them at the moment, which is really worrisome as I don't know how to troubleshoot that part.


AFAIK to get the per series agent logs I only need to create the `X-Plex-Token.id` file at the root of my Plex data folder right?

**Comment by ZeroQI** [comment]
If no scanner logs, then it crashed and left logs in the Plex scanner logs:

  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
WindowsError: (3, 'The system cannot find the path specified', 'V:\\Anime\\Shin Kimagure Orange Road Soshite, Ano Natsu no Hajimari\\Shin Kimagure Orange Road (1996) (DVDRip 720x480p x265 HEVC AC3 2.0)[sxales]\\Shin Kimagure Orange Road Soshite, Ano Natsu no Hajimari (1996) - TV Spot Collection (DVDRip 720x480p x265 HEVC AC3 2.0)[sxales].mkv')

Why cannot your OS find that file? Maybe a rights issue...

**Comment by jaller200** [comment]
Bumping this because I think it's related to a similar or the same problem I'm having — `anidb4` doesn't produce any logs and the series are sorted like `anidb1`. 

During my research of a different issue here, I believe the problem lies in a silent crash / bug in the code for `anidb3` and `anidb4`. I'm currently looking over it to see if I can find anything...

**Comment by ZeroQI** [comment]
if it doesn't create logs, it probably crashed bad but do not know where to start, and further series will not be added
Logs show nothing actionnable/. The only way to proceed would be to comment all tvdb4 section of the code lines 790-807, and see if it works, then narrow down by replacing the except else part with "pass", then output somethign that doesn't crash...

```
      #tvdb4 - Absolute numbering in any season arrangements aka saga mode
      elif source=='tvdb4' and folder_season==None:  #1-folders nothing to do, 2-local, 3-online
        try:
          file_fullpath = os.path.join(root, path, "tvdb4.mapping")
          if os.path.isfile(file_fullpath):
            tvdb4_mapping_content = read_file(file_fullpath).strip()
            Log.info(u"TVDB season mode (%s) enabled, tvdb4 mapping file: '%s'" % (id, file_fullpath))
          else:
            tvdb4_mapping_content = etree.fromstring(read_cached_url(ASS_MAPPING_URL).strip()).xpath("/tvdb4entries/anime[@tvdbid='%s']" % id)[0].text.strip()
            Log.info(u"TVDB season mode (%s) enabled, tvdb4 mapping url: '%s'" % (id, ASS_MAPPING_URL))
          for line in filter(None, tvdb4_mapping_content.splitlines()):
            season = line.strip().split("|")
            for absolute_episode in range(int(season[1]), int(season[2])+1):  tvdb_mapping[absolute_episode] = (int(season[0]), int(absolute_episode))
            if "(unknown length)" in season[3].lower(): unknown_series_length = True
        except Exception as e:
          tvdb_mapping = {}
          if str(e) == "list index out of range":  Log.error("tvdbid: '%s' not found in online season mapping file" % id)
          else:                                    Log.error("Error opening tvdb4 mapping, Exception: '%s'" % e)
```

**Comment by ZeroQI** [comment]
Any update ?

**Comment by ZeroQI** [comment]
Any update ?

**Comment by ZeroQI** [comment]
Any update ?
\|This seem to crash on tvdb4 alone, so if you remove the tvdb4 part of the code and it doesn't crash, i know the issue is in there, but it is extremely difficult to resolve something not creating any logs...

**Comment by Roshri** [comment]
As mentioned in issue #476 it seems the problem was the really old agent taking precedence, just tried on a new library with anidb4

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/29184137/e65b4631-9ee6-43cf-ab40-ec96c6495510)
