### ISSUE TITLE
How do you use tvdb4 to make custom seasons

### ISSUE THREAD

**Issue by Ackerman69** [ZeroQI/Absolute-Series-Scanner#395]
Can someone explain please 
I am going crazy figuring it out

**Comment by ZeroQI** [comment]
Please use Plex forum for queries
No logs, no example... You do not even explain what you expect or Want to achieve...
- you do need to label the series folder appropriately BEFORE scanning (or the scan is cached and will not run again unless grouping folder or folder content is changed, Plex limitation): series title [tvdb4-12345] where 12345 is the tvdbid
- choice 1: You keep absolutely numbered episode in the season folder of your choice. 
- choice 2: You keep absolutely numbered episode in the series root folder and tvdbid is in the defined sagas list https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.mapping.xml

**Comment by Avyayy** [comment]
Is there a way to use absolutee seeies scanner only for specific shows?
I have over 300+ anime and about 100 custom series poster and i would not like to jumble that up?

**Comment by ZeroQI** [comment]
That is a Plex specific question. Forum is there for that...
Why creating a bug report for a usage specific question? 

The scanner is specific to the library and posters are a metadata entity so agent related. You can select an agent for a specific series but not a scanner.

If you named posters as per local media assets agents I do not see the issue.
If you are going to rescan the unique I'd might change and thus the metadata no longer be recognised
