### ISSUE TITLE
Scanner halts on any folder using ASS after updating to Plex 1.25.4.5487 on Synology DSM6

### ISSUE THREAD

**Issue by rasalomx** [ZeroQI/Absolute-Series-Scanner#396]
Ever since upgrading to Plex 1.25.4.5487 on my DSM6 Synology, ASS/Hama just doesn't work right. There are some Anime shows it will detect but not complete metadata on, and if you try to move the folder out and back in, or add new folders, it won’t detect the change unless you cancel the current scan and start it over.

I’ve wiped the logs, reinstalled ASS/Hama, and rebuilt the library multiple times. It scans about 90% of the stuff, spins its wheels on the last few, and won’t load the metadata.

I’ve noticed the scanner gets stuck on any library (Anime OVAs and Anime Movies, so movies and TV show types) using ASS. This stops Plex from detecting new content anywhere else.

Once I kill the scan on my anime library, Plex starts scanning other stuff again… Until it hits the anime libraries, then it halts again. It gets stuck on different files each time.

Did the Plex update break something? These folders all worked on the last version of Plex.

https://www.mediafire.com/folder/17129pox7pfxn/ASS+and+Plex+logs

Logs provided, if you need more just let me know which ones to get. I am very busy during the day so I don't have these ahead of time, sorry. Thank you for this product, I think it's wonderful and very helpful with organizing my data.

**Comment by ZeroQI** [comment]
Cannot see an error in Plex media scanner log
As such, if only Plex version changed, then Plex bug definitely.

**Comment by rasalomx** [comment]
If it was a Plex bug I would expect it to fail on Plex libraries, too, but it's not. So, is that a bug or ASS failing to accommodate changes to Plex?

**Comment by ZeroQI** [comment]
I need to know what they changed.
Grouping folder may stop working at any point since it's a hack... Presently I don't know if that is Plex version specific or for some os only... We need feedback from other users

**Comment by rasalomx** [comment]
OK, I understand. It's not killing me to restart it but I wanted to see what my options were. Thanks.

Here are the notes for the last 3 versions of Plex Media Server:

1.25.4.5468-989df2310
ITEMS ADDED:

(NOTE) Database changes may cause longer than normal start-up times after initial installation of this update, especially on larger libraries. Please be patient and do not interrupt this process.
(Library) Refresh movie metadata periodically during scheduled tasks (#13250)
(Metadata) Add Bulgarian language option for modern movie and TV agents (#13263)
(TLS) Server-side HTTPS connection support is now always enabled for signed-in users; plaintext connections will continue to be supported as well by default (#13257)
ITEMS FIXED:

(HttpClient) The server may quit unexpectedly if internal HTTP requests are made with certain timings (#13231)
(Library) Requesting the list of items starting with special characters could give unexpected results (#13251)
(Metadata) Some users could end up with massive amounts of duplicate extras (#13241)
(Optimized Versions) New versions shouldn't be encoded from existing optimized versions (#13254)
(Subtitles) On-demand subtitles would not work on optimized versions (#13218)
(Transcode) The transcoder process could fail to complete when encoding E-AC-3

---
1.25.4.5487-648a8f9f9

ITEMS ADDED:

(Library) Refresh movie metadata periodically during scheduled tasks (#13250)
(Metadata) Add Bulgarian language option for modern movie and TV agents (#13263)
(TLS) Server-side HTTPS connection support is now always enabled for signed-in users; plaintext connections will continue to be supported as well by default (#13257)
ITEMS FIXED:

(HttpClient) The server may quit unexpectedly if internal HTTP requests are made with certain timings (#13231)
(Library) Requesting the list of items starting with special characters could give unexpected results (#13251)
(Metadata) Some users could end up with massive amounts of duplicate extras (#13241)
(Optimized Versions) New versions shouldn't be encoded from existing optimized versions (#13254)
(Subtitles) On-demand subtitles would not work on optimized versions (#13218)
(Transcode) The transcoder process could fail to complete when encoding E-AC-3
(Windows) The relay executable would not launch.

---
1.25.5.5492-12f6b8c83

ITEMS ADDED:

None

ITEMS FIXED:

(Auto Update) Old update files were not cleaned up after a manual update. (#12693)
(Collections) Items added from TIDAL could not be added to collections (#13289)
(EPG) Guide could show wrong VCN if lineup has duplicate channel ids. (#13207)
(EPG) Lineup channels returned during DVR setup were not sorted. (#13188)
(Media Decision) The server could attempt to transcode files that use unsupported nonstandard colorspaces, even when other supported versions are available (#13183)
(Metadata) In rare instances some tv seasons could match to the incorrect episode ordering (#13312)
(Metadata) Local metadata for episode release dates would not get set correctly (#13189)
(Metadata) The SDH flag for subtitles would be ignored for TV episodes (#13307)
(Metadata) The embedded titleSort tag would be ignored when preferring local metadata for video files (#13266)
(Scanner) Files with certain name formatting could be matched with incorrect episode numbers (#13280)
(Scanner) Pick up 4 digit episode numbers when no season number exists (#13212)
(Scanner) Try to use a year hint from a movie filename if the parent path doesn't contain one (#13310)
(Search) Music collections were not being returned in search results (#13000)

**Comment by rasalomx** [comment]
As a test I have rolled back to PlexMediaServer-1.25.3.5409 from .5492. It's actually pretty painless on DSM6 to uninstall Plex, it doesn't touch your library or settings.

I will let you know if the behavior stops. If it stops I'll update to the next version that came out and see if it does it there. Then I'll keep going until it breaks again, if it does.

**Comment by ikari7789** [comment]
This is helpful. I'm facing the same issue but can't see anything in the logs that would indicate the reason. It just hangs indefinitely at random points in the library. I'll also try rolling back to 5409.

**Comment by rasalomx** [comment]
https://forums.plex.tv/t/library-updater-does-not-manually-update-library-media/772681/21

**Comment by rasalomx** [comment]
This appears to have been resolved in the latest release: 1.25.6.5577-c8bd13540

https://www.plex.tv/de/media-server-downloads/

You may close the thread.
