### ISSUE TITLE
Scanner Combining Openings / Endings with Alphabetical Characters (ED2a, OP2a, etc.) for forced AniDB ID (anidb-xxxx)

### ISSUE THREAD

**Issue by jaller200** [ZeroQI/Absolute-Series-Scanner#397]
## Platform
Operating system and version: Unraid 6.9.2 / Docker 20.10.5
Plex version: Version 4.69.1

## Expected Behavior
When appending `[anidb-xxxx]` to the end of a series' folder name, openings and endings should be picked up properly as Episode 101, 102, ... and 151, 152, ...

## Current Behavior
I'm currently using the file naming scheme `{Series Name} - {AniDB Episode Number (e.g. 01, 02, ED1...)} - {Episode Title} [Additional Metadata]`.

For this report, I have three opening files for the anime Nagi no Asukara (AniDB ID: 9387):

1. `Nagi no Asukara [anidb-9387]/Nagi no Asukara - OP1 - Lull - Soshite Bokura wa (1-13) [Bluray 1080p]`
2. `Nagi no Asukara [anidb-9387]/Nagi no Asukara - OP2a - Ebb and Flow (14-24) [Bluray 1080p]`
3. `Nagi no Asukara [anidb-9387]/Nagi no Asukara - OP2b - Ebb and Flow (14-24) [Bluray 1080p]`

If I scan this folder using the forced ID, it detected the first two files as a single Episode 102:

**Logs**
[Nagi no Asukara [anidb-9387].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8056817/Nagi.no.Asukara.anidb-9387.filelist.log)

[Nagi no Asukara [anidb-9387].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8056818/Nagi.no.Asukara.anidb-9387.scanner.log)

**Images**
<img width="1070" alt="Screenshot 2022-02-13 at 17 23 16" src="https://user-images.githubusercontent.com/7927236/153778231-9cd47bbe-68d9-4cbc-95e4-1d234308e1ba.png">

<img width="676" alt="Screenshot 2022-02-13 at 17 23 26" src="https://user-images.githubusercontent.com/7927236/153778234-f64d68a5-0434-428f-86be-8f4e7add49e2.png">

However, if I take away the forced ID and use the year instead, or even just the name, it renders correctly:

**Logs**
[Nagi no Asukara (2013).filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8056815/Nagi.no.Asukara.2013.filelist.log)

[Nagi no Asukara (2013).scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8056816/Nagi.no.Asukara.2013.scanner.log)

**Images**
<img width="1058" alt="Screenshot 2022-02-13 at 17 19 49" src="https://user-images.githubusercontent.com/7927236/153778244-9484d058-33c2-4362-bfe8-930ba492b679.png">

Trying as `C1`, `C2`, etc. just lists it as unmapped (Episode 501+).

## Steps to Reproduce
1. Create a folder (in this case, `Nagi no Asukara [anidb-9387]`)
2. Put the first opening and first second opening in the subfolder (e.g. `Nagi no Asukara - OP1 - Lull - Soshite Bokura wa (1-13) [Bluray 1080p].mkv`). It doesn't matter if anything after `OP1` or `ED2a` exists, or if it's the only two files
3. Scan / re-scan the library.

## Additional information
What's most interesting is that this issue seems to affect the anime if it has an alphabetical character across numbers. Another anime (Konohana Kitan, AniDB ID: 13030) has Openings 1a and 1b and they both seem to appear fine, even when using a forced AniDB ID.

<img width="708" alt="Screenshot 2022-02-13 at 17 41 15" src="https://user-images.githubusercontent.com/7927236/153778463-092a80c5-6e5f-4e35-990a-a64d4bcd0b1c.png">

I'm unsure what might be the root cause here, but I suspect it has to do with either the alphabetical characters themselves, or some weird issue with the numbers.

**Comment by ZeroQI** [comment]
Op1 should be s00e101 and not s00e102 and bug only when using forced ID? Weird, must be something bad in forced ID part somewhere

**Comment by jaller200** [comment]
I've finally got some time to sit down, and from my brief scan over the codebase, I believe the issue might have something to do with these lines of code:

```python
### OP/ED with letter version Example: op2a
if not ep.isdigit() and len(ep)>1 and ep[:-1].isdigit():  ep, offset = int(ep[:-1]), ord(ep[-1:])-ord('a')
else:                                                     offset = 0
if anidb_xml is None:
  if ANIDB_RX.index(rx) in AniDB_op:  AniDB_op[ANIDB_RX.index(rx)]   [ep] = offset # {101: 0 for op1a / 152: for ed2b} and the distance between a and the version we have hereep, offset                         = str( int( ep[:-1] ) ), offset + sum( AniDB_op.values() )                             # "if xxx isdigit() else 1" implied since OP1a for example... # get the offset (100, 150, 200, 300, 400) + the sum of all the mini offset caused by letter version (1b, 2b, 3c = 4 mini offset)
  else:                               AniDB_op[ANIDB_RX.index(rx)] = {ep:   offset}
cumulative_offset = sum( [ AniDB_op[ANIDB_RX.index(rx)][x] for x in Dict(AniDB_op, ANIDB_RX.index(rx), default={0:0}) if x<ep and ANIDB_RX.index(rx) in AniDB_op and x in AniDB_op[ANIDB_RX.index(rx)] ] )
ep = ANIDB_OFFSET[ANIDB_RX.index(rx)] + int(ep) + offset + cumulative_offset    # Sum of all prior offsets
```

Adding my own logs and uncommenting the one already there it prints this:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/7927236/153786990-aef99a36-3ed8-4f42-af58-ada3cb8950f5.png">

Doing a bit more digging — haven't worked on a Plex scanner much before, so I find it takes a few moments to regenerate the logs, but it's made me curious...

**Comment by jaller200** [comment]
Found it!

```python
### OP/ED with letter version Example: op2a
if not ep.isdigit() and len(ep)>1 and ep[:-1].isdigit():  ep, offset = int(ep[:-1]), ord(ep[-1:])-ord('a')
else:                                                     offset = 0
if anidb_xml is None:
  if ANIDB_RX.index(rx) in AniDB_op:  AniDB_op[ANIDB_RX.index(rx)]   [ep] = offset # {101: 0 for op1a / 152: for ed2b} and the distance between a and the version we have hereep, offset                         = str( int( ep[:-1] ) ), offset + sum( AniDB_op.values() )                             # "if xxx isdigit() else 1" implied since OP1a for example... # get the offset (100, 150, 200, 300, 400) + the sum of all the mini offset caused by letter version (1b, 2b, 3c = 4 mini offset)
  else:                               AniDB_op[ANIDB_RX.index(rx)] = {ep:   offset}
cumulative_offset = sum( [ AniDB_op[ANIDB_RX.index(rx)][x] for x in Dict(AniDB_op, ANIDB_RX.index(rx), default={0:0}) if x<ep and ANIDB_RX.index(rx) in AniDB_op and x in AniDB_op[ANIDB_RX.index(rx)] ] )
ep = ANIDB_OFFSET[ANIDB_RX.index(rx)] + int(ep) + offset + cumulative_offset    # Sum of all prior offsets
```

In these lines, `ep` comes in as type `str`. Inside the `sum(..)` function the script performs a comparison `x<ep`. If there is no offset at all (i.e. `AniDB_op = {}`), this never executes.

However, if there _is_ an offset, then things get thrown off. Because `ep` is a string and `x` is an integer, then it will perform a string/int comparison. 

In my case, the following variables were set:

```
ep = '1'
AniDB_op = {1: {2: 1}, 2: {2: 1}}
ANIDB_RX.index(rx) = 2
```

Thus the script evaluated `2 < '1'`, which in Python 2 returns true (this throws an error in Python 3 from what I tested):

<img width="86" alt="image" src="https://user-images.githubusercontent.com/7927236/153801415-fcba9f0e-b5f7-4a0f-a7e0-f5939fd8b074.png">

What I believe should change are these lines from this:

```
if not ep.isdigit() and len(ep)>1 and ep[:-1].isdigit():  ep, offset = int(ep[:-1]), ord(ep[-1:])-ord('a')
else:                                                     offset = 0
```
to this
```
if not ep.isdigit() and len(ep)>1 and ep[:-1].isdigit():  ep, offset = int(ep[:-1]), ord(ep[-1:])-ord('a')
else:                                                     ep, offset = int(ep), 0
```

Which properly converts `ep` to an integer value regardless, and thus causes this to work properly. I shall open a merge request as well.
