### ISSUE TITLE
Add season poster urls for tvdb4 online setup

### ISSUE THREAD

**Issue by EndOfLine369** [ZeroQI/Absolute-Series-Scanner#40]
Carried over from discussion from https://github.com/ZeroQI/Absolute-Series-Scanner/pull/36

@EndOfLine369
Hmmmm....On further thought, maybe we don't want to store these images at all. I could see people complain about image rights. We could just store the URLs to the images. And still need a way for HAMA to know when the xml is used for seasons.

As xml, we can easily just add in a separate entry to not interfere with the other entries as we are searching for anime tags `"/tvdb4entries/anime[@tvdbid='%s']"` in ASS.
EX:
```xml
  <anime tvdbid="88031" name="Dragon Ball Kai">
    01|001|016|Saiyan Saga
    02|017|054|Frieza Saga
    03|055|067|Androids Saga
    04|068|098|Cell Saga
    05|099|133|Majin Buu Saga
    06|134|159|Evil Buu Saga
  </anime>
  <posters tvdbid="88031" name="Dragon Ball Kai">
    01|[URL]
    02|[URL]
    03|[URL]
    04|[URL]
    05|[URL]
    06|[URL]
  </posters>
```
Would not recommend separating into separate files and that could be an issue when reconciling file entries.

@sven-7 
I think the URL solution is a good compromise from a storage/rights perspective.  Could we design it either way so there can be more than one per season?  For example:

```
 <anime tvdbid="88031" name="Dragon Ball Kai">
    01|001|016|Saiyan Saga
    02|017|054|Frieza Saga
    03|055|067|Androids Saga
    04|068|098|Cell Saga
    05|099|133|Majin Buu Saga
    06|134|159|Evil Buu Saga
  </anime>
  <posters tvdbid="88031" name="Dragon Ball Kai">
    01|[URL]
    01|[URL]
  </posters>
```

@EndOfLine369
I don't see an issue with that to allow people different pictures available. But would probably need to make a rule for the file of only X images max per season. 2 per season?

@sven-7 
Seems fair to me. 

@ZeroQI 
```
<anime tvdbid="88031" name="Dragon Ball Kai">
    01|001|016|[URL]|Saiyan Saga
    02|017|054|[URL]|Frieza Saga
    03|055|067|[URL]|Androids Saga
    04|068|098|[URL]|Cell Saga
    05|099|133|[URL]|Majin Buu Saga
    06|134|159|[URL]|Evil Buu Saga
  </anime>
```
I thought you did the posters yourself...
If thetvdb have them yes a link will be great

Would not recommend separating into separate files and that could be an
issue when reconciling file entries.

@EndOfLine369
"Would not recommend separating into separate files and that could be an issue when reconciling file entries." I had already mentioned that or are you meaning separate entries in the file?

If we combined the 'anime' & 'poster' tags, we could not have more than one poster available for a season. I would prefer not all to be in one entry as the url will make the line exceedingly long and would think is best to keep the 'anime' entry same as the local 'tvdb4.mapping' file's content.

@ZeroQI 
The poster is done by the agent so technically no need for a single file having both but it's simpler...

We could have a variable number of arguments, the format stays compatible and allows local file to specify poster link too...
```
<anime tvdbid="88031" name="Dragon Ball Kai">
    01|001|016|Saiyan Saga|[URL]|[URL]
    02|017|054|Frieza Saga|[URL]|[URL]|[URL]
    03|055|067|Androids Saga|[URL]
    04|068|098|Cell Saga|[URL]|[URL]
    05|099|133|Majin Buu Saga|[URL]|[URL]|[URL]
    06|134|159|Evil Buu Saga|[URL]|[URL]
  </anime>
```
The tvdb id would be unique so i don't think there will be issues reconciliating entries, like what we do with the xml mapping file from scudlee's... single file easier to maintain... 
```
tvdb4.posters.xml
 <posters tvdbid="88031" name="Dragon Ball Kai">
    01|[URL]
    01|[URL]
    02|[URL]
    02|[URL]
    03|[URL]
    04|[URL]
    05|[URL]
    06|[URL]
  </posters>
```
Opinions?

**Comment by EndOfLine369** [comment]
@ZeroQI "If thetvdb have them yes a link will be great"
Are you only thinking about allowing urls from thetvdb posters?

And on the files, if you disagree on putting separate 'anime' and 'poster' xml entries right next to each other in the same file, I would go with option 2 of a separate 'tvdb4.posters.xml' as it would just make a mess of long lines when trying to read season mappings on adding in urls to the end.

**Comment by ZeroQI** [comment]
any posters but tvdb ones have fixed high res and look nicer
The season posters you have in your screenshot, they come from thetvdb season posters ?
would prefer 2 files as they look nicer and the scanner doens't need the url but updating a single file is easier...

**Comment by EndOfLine369** [comment]
Just wanted to make sure you were not opposed to anything other then tvdb posters.
Those posters were from Trakt's seasons. Actually found some good ones on themoviedb just now.
```
<posters tvdbid="88031" name="Dragon Ball Kai">
  01|https://image.tmdb.org/t/p/original/6WtCy228qbkpW5Eo71akpI8XJKi.jpg
  01|https://image.tmdb.org/t/p/original/aBFXBZugTCfnIDQTYl4vAoP9jE4.jpg
  01|https://walter.trakt.us/images/seasons/000/024/495/posters/thumb/53d58090f9.jpg
  02|https://image.tmdb.org/t/p/original/2o9tF5qIXVIc6cKV2uSLhXQyVox.jpg
  02|https://image.tmdb.org/t/p/original/3wj0YJWY8B3pzfvfk3tGXs4OQdc.jpg
  02|https://walter.trakt.us/images/seasons/000/024/497/posters/thumb/6a6c3f82a6.jpg
  03|https://image.tmdb.org/t/p/original/lvMz2kyfZ9K08EyHa57T1rah900.jpg
  03|https://image.tmdb.org/t/p/original/56mZEizhYsTwmtEkGDwWZfadYXq.jpg
  03|https://walter.trakt.us/images/seasons/000/024/498/posters/thumb/cd8aea9289.jpg
  04|https://image.tmdb.org/t/p/original/25rCwuPit2QlgLJ31Jdu6eKOXit.jpg
  04|https://image.tmdb.org/t/p/original/cQWHSKlZjQgXbRwtm7x1o6esW7v.jpg
  04|https://walter.trakt.us/images/seasons/000/024/499/posters/thumb/c8fc2e5e36.jpg
  04|https://walter.trakt.us/images/seasons/000/024/500/posters/thumb/892d9a4b8f.jpg
  05|https://image.tmdb.org/t/p/original/jDcTbOo2SOL7GH6tC7rRYzr2A2B.jpg
  05|https://walter.trakt.us/images/seasons/000/024/502/posters/thumb/a28d0ef148.jpg
  06|https://image.tmdb.org/t/p/original/wTccnUmJPEJXQQqjFfWNHTDcm8W.jpg
  06|https://walter.trakt.us/images/seasons/000/024/503/posters/thumb/a11d4d9c36.jpg
</posters>
```

**Comment by ZeroQI** [comment]
The point is to have posters with the saga named. Your screencap was superb
in that regard
We can add all tvdb season posters with lower id as second choice

**Comment by EndOfLine369** [comment]
Created the new file and put in the example & DB Kai entry.

So the mystery that needs to be solved now is how ASS can signal HAMA that the tvdb4 mode **option** was the online xml option 3.

**Comment by EndOfLine369** [comment]
I guess we could update 'folder_show' with '[tvdb4-option3]'...

**Comment by ZeroQI** [comment]
You need the tvdbid so hama sets the right guid. Only the first time will
hama know if you pass info on the serie name as it will change it which is
ok only for the guid as it remains. We can load the tvdb4 season poster
file in all situations not only online file...

**Comment by ZeroQI** [comment]
But saga won't match got it now...
We need to test if season folders or online mapping then... or make guid
with more info...

**Comment by EndOfLine369** [comment]
@ZeroQI 
Re first reply: Yep, found that out while trying to code it as 'metadata.title' will only contain it as initial load only.

Re first reply: I'll actually be counting the existing seasons with the season count in 'tvdb4.mapping.xml' and load posters if the match.

**Comment by ZeroQI** [comment]
Clever, do not count season 0 though
Night be worth checking eps range but not mandatory.

Good thinking

**Comment by EndOfLine369** [comment]
Just going to look for max season in both.
Crap, just thought about what if they don't have the episodes available for all the seasons....

**Comment by EndOfLine369** [comment]
In their Plex.

**Comment by ZeroQI** [comment]
Well 2 solutions
Check tvdb4 if season folder not present and no local mapping file
Or
Check mapping file and check ep mapping range for season posters.

You could use loop for physical files to check if in range and set
tvdb4_season[season] to 1 if didn't exist and in range and 0 if not in
range regardleas if it didn't exist or not.
Once 0 cannot become 1 again...
Could then deal with seasons afterwards.
We could load normal tvdb season posters with highter priority id number to
lower the actual priority...

**Comment by EndOfLine369** [comment]
The understanding of the how in what you just said is escaping me at the moment. I think i've been up too long. It is not tested. Still roughing out the code and expected behavior.
Here is what I have so far:
"DefaultPrefs.json" https://gist.github.com/EndOfLine369/329a66439a5e20248c3bf8d0a46ce4bc
) Addition of 'GetASSPosters'
"\_\_init\_\_.py" https://gist.github.com/EndOfLine369/8ee08c812a5f3943e6cc
) Replacement of all the 'metadata.id...' with variables to stop the constant 'split', 'startswith', & 'id[x:]' calls.
) Addition of 'GetASSPosters'
) Addition of 'def getImagesFromASS'

**Comment by EndOfLine369** [comment]
Got a working version into Gist. It will load the ASS posters on any tvdb4 mode at this time.
"DefaultPrefs.json" https://gist.github.com/EndOfLine369/329a66439a5e20248c3bf8d0a46ce4bc
"\_\_init\_\_.py" https://gist.github.com/EndOfLine369/8ee08c812a5f3943e6cc

You will need to check the option for ASS posters if you want them to be loaded in. Default is False.

![image](https://cloud.githubusercontent.com/assets/16750699/16177379/777a95d8-35f0-11e6-9793-909077d52577.png)

![image](https://cloud.githubusercontent.com/assets/16750699/16177341/2b8e9b84-35ef-11e6-9b0b-fe7eb260753c.png)

![image](https://cloud.githubusercontent.com/assets/16750699/16177387/f613b8b6-35f0-11e6-9117-5f460b473186.png)

**Comment by EndOfLine369** [comment]
@ZeroQI No idea how to do your "2 solutions" as HAMA has no idea on the physical files. Only ASS knows that unless i'm unaware of some data available to HAMA.

**Comment by EndOfLine369** [comment]
@ZeroQI Any idea on why the `not cacheable in Agent plug-ins` is happening on both the xml and all the images it loads in?
```
2016-06-19 09:42:53,848 (-b675470) :  DEBUG (networking:166) - Requesting 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
2016-06-19 09:42:53,973 (-b675470) :  DEBUG (networking:198) - Not caching 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml' (content type 'text/plain; charset=utf-8' not cacheable in Agent plug-ins)
2016-06-19 09:42:53,974 (-b675470) :  DEBUG (__init__:697) - getImagesFromASS() - Loaded poster XML: 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
2016-06-19 09:42:54,029 (-b675470) :  DEBUG (networking:166) - Requesting 'http://vignette4.wikia.nocookie.net/hunterxhunter/images/8/89/Hunter_Exam_Arc.jpg'
2016-06-19 09:42:54,837 (-b675470) :  DEBUG (networking:198) - Not caching 'http://vignette4.wikia.nocookie.net/hunterxhunter/images/8/89/Hunter_Exam_Arc.jpg' (content type 'image/jpeg' not cacheable in Agent plug-ins)
2016-06-19 09:42:54,868 (-b675470) :  DEBUG (__init__:789) - metadata_download() - url: 'http://vignette4.wikia.nocookie.net/hunterxhunter/images/8/89/Hunter_Exam_Arc.jpg', num: '1', filename: 'TVDB/seasons/252322-1-Hunter_Exam_Arc.jpg'
```

**Comment by ZeroQI** [comment]
Pictures are never cacheable. Xml should. When you load the xml you give
the cache time period

**Comment by EndOfLine369** [comment]
Nvm on the images. Seems like it only posts that on the initial load probably as it has the file locally now. But xml is still no idea on the xml not caching...

```
2016-06-19 09:57:56,638 (-b675470) :  DEBUG (networking:166) - Requesting 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
2016-06-19 09:57:56,951 (-b675470) :  DEBUG (networking:198) - Not caching 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml' (content type 'text/plain; charset=utf-8' not cacheable in Agent plug-ins)
2016-06-19 09:57:56,952 (-b675470) :  DEBUG (__init__:697) - getImagesFromASS() - Loaded poster XML: 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
2016-06-19 09:57:56,953 (-b675470) :  DEBUG (__init__:790) - metadata_download() - url: 'http://vignette4.wikia.nocookie.net/hunterxhunter/images/8/89/Hunter_Exam_Arc.jpg', num: '1', filename: 'TVDB/seasons/252322-1-Hunter_Exam_Arc.jpg'*
2016-06-19 09:57:56,954 (-b675470) :  DEBUG (__init__:790) - metadata_download() - url: 'http://vignette3.wikia.nocookie.net/hunterxhunter/images/2/26/Zoldyck_Family_members.png', num: '2', filename: 'TVDB/seasons/252322-2-Zoldyck_Family_members.png'*
...
2016-06-19 09:57:56,957 (-b675470) :  DEBUG (__init__:790) - metadata_download() - url: 'http://vignette2.wikia.nocookie.net/hunterxhunter/images/f/f1/13th_Hunter_Chairman_Election_arc_2011.png', num: '7', filename: 'TVDB/seasons/252322-7-13th_Hunter_Chairman_Election_arc_2011.png'*
2016-06-19 09:57:56,971 (-b675470) :  DEBUG (networking:161) - Fetching 'http://thetvdb.com/api/A27AD9BE0DA63333/series/252322/banners.xml' from the HTTP cache
2016-06-19 09:57:56,984 (-b675470) :  DEBUG (__init__:713) - getImagesFromTVDB() - Loaded picture XML: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/252322/banners.xml'
2016-06-19 09:57:56,989 (-b675470) :  DEBUG (__init__:790) - metadata_download() - url: 'http://thetvdb.com/banners/fanart/original/252322-14.jpg', num: '2', filename: 'TVDB/fanart/original/252322-14.jpg'*
```

Its the same code as TVDB's 'banners.xml' pull.
```
    try:     postersXml = XML.ElementFromURL( ASS_POSTERS_URL, cacheTime=CACHE_1HOUR * 24) # don't bother with the full zip, all we need is the banners
    except:  Log.Debug("getImagesFromASS() - Loading poster XML failed: " + ASS_POSTERS_URL); return
    else:    Log.Debug("getImagesFromASS() - Loaded poster XML: '%s'" % ASS_POSTERS_URL)
...
    try:     bannersXml = XML.ElementFromURL( TVDB_BANNERS_URL % tvdbid, cacheTime=CACHE_1HOUR * 24) # don't bother with the full zip, all we need is the banners
    except:  Log.Debug("getImagesFromTVDB() - Loading picture XML failed: " + TVDB_BANNERS_URL % tvdbid);  return
    else:    Log.Debug("getImagesFromTVDB() - Loaded picture XML: '%s'" % (TVDB_BANNERS_URL % tvdbid))
```

**Comment by ZeroQI** [comment]
The message says content type 'text/plain; charset=utf-8' not cacheable in
Agent plug-ins)
Save the xml in something else than utf8 and try agai

**Comment by EndOfLine369** [comment]
@ZeroQI Looks like I had to change it to non-https and it loads and caches.
Please be aware of the below code issues when you look on the https ticket.

Works - http://rawgithub.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml
```
2016-06-19 10:32:34,819 (-ba70470) :  DEBUG (networking:161) - Fetching 'http://rawgithub.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml' from the HTTP cache
2016-06-19 10:32:34,832 (-ba70470) :  DEBUG (__init__:697) - getImagesFromASS() - Loaded poster XML: 'http://rawgithub.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
```

Failed to load - https://rawgithub.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml
```
2016-06-19 10:26:02,484 (-b5b7470) :  DEBUG (networking:166) - Requesting 'https://rawgithub.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
2016-06-19 10:26:02,610 (-b5b7470) :  DEBUG (__init__:696) - getImagesFromASS() - Loading poster XML failed: https://rawgithub.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml
```

Loads but would not cache : https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml
```
2016-06-19 09:57:56,638 (-b675470) :  DEBUG (networking:166) - Requesting 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml'
2016-06-19 09:57:56,951 (-b675470) :  DEBUG (networking:198) - Not caching 'https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/tvdb4.posters.xml' (content type 'text/plain; charset=utf-8' not cacheable in Agent plug-ins)
```

**Comment by ZeroQI** [comment]
There is variation in the header
"Loads but would not cache" adds the following: "<?xml version="1.0" encoding="utf-8"?>"
If you put explicitely this header in the file without utf-8 encoding it should cache

**Comment by EndOfLine369** [comment]
@ZeroQI any thoughts on how to tell if it used the web xml? Otherwise, I think it works fine and will load the posters if source is tvdb4 and users have enabled the GetASSPosters option.

**Comment by ZeroQI** [comment]
@EndOfLine369: We can check if there is a local mapping file or season folders, and if not, it had to be online. Local mapping file is easy to check i guess and counting the folder depth between an episode filepath and the root folders is also easy (remove the root path from the first file path, then explode the path in an list and count the numbers of items in it).

**Comment by EndOfLine369** [comment]
@ZeroQI As mentioned above, I do not know how to do this with data I understand available to the agent as HAMA has no idea on the physical files. Please enlighten me if it is. What i'm thinking about doing is making the scanner put the source to tvdb43 for mode 4 option 3.

**Comment by ZeroQI** [comment]
Hama does access files here:

for media_item in media.seasons[media_season].episodes[media_episode].items:
            for item_part in media_item.parts:  Log("File: '%s' '%s'" % (ep, item_part.file))

Local media assets agent
https://github.com/plexinc-agents/LocalMedia.bundle/blob/master/Contents/Code/__init__.py

path = os.path.dirname(media.items[0].parts[0].file)
for p in os.listdir(path):
          path_files[p.lower()] = p
Give path of first part of first media file...

**Comment by EndOfLine369** [comment]
Nice

**Comment by EndOfLine369** [comment]
Got it I believe.
```python
    try:
      s = media.seasons.keys()[0]
      e = media.seasons[s].episodes.keys()[0]
      dir_path = os.path.dirname(media.seasons[s].episodes[e].items[0].parts[0].file)
      dir_name = os.path.basename(dir_path)
      if    "[tvdb4-" not in dir_name and "tvdb4.id" not in os.listdir(dir_path): Log.Debug("getImagesFromASS() - Files are in a season folder (option 1)"); return
      elif  "tvdb4.mapping" in os.listdir(dir_path): Log.Debug("getImagesFromASS() - Files are in the series folder and has a mapping file (option 2)"); return
      else: Log.Debug("getImagesFromASS() - Files are in the series folder and has no mapping file (option 3)")
    except Exception as e:  
      Log.Error("getImagesFromASS() - Issues in finding setup info as directories have most likely changed post scan into Plex")
      Log.Error(e); return
```
Gist updated https://gist.github.com/EndOfLine369/8ee08c812a5f3943e6cc

**Comment by ZeroQI** [comment]
try:
      s, e = media.seasons.keys()[0], media.seasons[s].episodes.keys()[0]
      dir_path, dir_name, dir_list = os.path.dirname(media.seasons[s].episodes[e].items[0].parts[0].file), os.path.basename(dir_path), os.listdir(dir_path)
      if    "[tvdb4-" not in dir_name and "tvdb4.id" not in dir_list: Log.Debug("getImagesFromASS() - Files are in a season folder (option 1)"); return
      elif  "tvdb4.mapping" in dir_list: Log.Debug("getImagesFromASS() - Files are in the series folder and has a mapping file (option 2)"); return
      else: Log.Debug("getImagesFromASS() - Files are in the series folder and has no mapping file (option 3)")
    except Exception as e:  
      Log.Error("getImagesFromASS() - Issues in finding setup info as directories have most likely changed post scan into Plex"); Log.Error(e); return

Nice code :D

**Comment by EndOfLine369** [comment]
Can't do the variable reductions as all variables are evaluated at the same time so evaluation would throw an error as 's' & 'dir_path' are unknown at the time. EX:
```python
>>> s, e = "qwe", s+"asd"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 's' is not defined

AND:

>>> dir_path, dir_name, dir_list = "/tmp", os.path.basename(dir_path), os.listdir(dir_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dir_path' is not defined
```
So this could only be reduced too:
```python
    try:
      s = media.seasons.keys()[0]
      e = media.seasons[s].episodes.keys()[0]
      dir_path = os.path.dirname(media.seasons[s].episodes[e].items[0].parts[0].file)
      dir_name, dir_list = os.path.basename(dir_path), os.listdir(dir_path)
      if    "[tvdb4-" not in dir_name and "tvdb4.id" not in dir_list: Log.Debug("getImagesFromASS() - Files are in a season folder (option 1)"); return
      elif  "tvdb4.mapping" in dir_list:                              Log.Debug("getImagesFromASS() - Files are in the series folder and has a mapping file (option 2)"); return
      else:                                                           Log.Debug("getImagesFromASS() - Files are in the series folder and has no mapping file (option 3)")
    except Exception as e:  
      Log.Error("getImagesFromASS() - Issues in finding setup info as directories have most likely changed post scan into Plex"); Log.Error(e); return
```
I do not object the removal of checking the 'Extras' folder when looking for the id files in ASS.

**Comment by ZeroQI** [comment]
My bad, missed that one.  I am still am a fan of aligning the Log.debug, much clearer :D

I thought it was cleaner to hide files, but don't think anybody actually uses it and will make things cleaner

**Comment by EndOfLine369** [comment]
Just to confirm we are talking about the same thing.
I'm going to change ASS:
```python
FROM:
    for file in ("anidb.id", "Extras/anidb.id", "tvdb.id", "Extras/tvdb.id", "tvdb2.id", "Extras/tvdb2.id", "tvdb3.id", "Extras/tvdb3.id", "tvdb4.id", "Extras/tvdb4.id", "tmdb.id", "Extras/tmdb.id", "tsdb.id", "Extras/tsdb.id", "imdb.id", "Extras/imdb.id"):

TO:
    for file in ("anidb.id", "tvdb.id", "tvdb2.id", "tvdb3.id", "tvdb4.id", "tmdb.id", "tsdb.id", "imdb.id"):
```

**Comment by ZeroQI** [comment]
Yes exactly. Makes things simpler

**Comment by EndOfLine369** [comment]
ASS updated

**Comment by EndOfLine369** [comment]
Updated the readme as well
https://github.com/ZeroQI/Absolute-Series-Scanner/commit/095e4f8df8b1732e285aaeeace806139c22136d4

**Comment by EndOfLine369** [comment]
Also removed the checking of the related "Extras/tvdb4.mapping" file to get rid of all of the "Extras" dir checks.

**Comment by ZeroQI** [comment]
Thanks. code reduction release [407 lines]:
   . removed seasonsfromfolder file
   . removed zerofilesize file
   . abs_manual_placement_worked replaced by else
   . urrlib python 3 included

Please review and test
https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d

**Comment by EndOfLine369** [comment]
Code update from this issue ticket has been committed
"DefaultPrefs.json"
) Addition of 'GetASSPosters' 
https://github.com/ZeroQI/Hama.bundle/commit/e6150877ff4d350371fe6da701cc798e012bf0d7
"\_\_init\_\_.py"
) Replacement of all the 'metadata.id...' with variables to stop the constant 'split', 'startswith', & 'id[x:]' calls. 
https://github.com/ZeroQI/Hama.bundle/commit/605ffc7267219c71d3aa1c8a08d5d1b7924cab15
) Addition of 'GetASSPosters' & 'def getImagesFromASS' 
https://github.com/ZeroQI/Hama.bundle/commit/5a8e19a0553734d18029d2d2b7222287f1838d32 
https://github.com/ZeroQI/Hama.bundle/commit/3f9bbe592eafaca7906c2c52d16f3369fc83ad8c

**Comment by sven-7** [comment]
Sidebar -- @EndOfLine369 where did you get the last two seasons of DB Kai?  I noticed I only have through Cell, not the two Buu ones.

**Comment by EndOfLine369** [comment]
I don't have that just yet. Hi10 is the only one I have found to have been done. Been trying to find how to get it without creating an account on their site. [Anime: Dragon Ball Kai (2014)](http://anidb.net/perl-bin/animedb.pl?show=anime&aid=10452)

**Comment by sven-7** [comment]
I signed up.  Here's a magnet link:  magnet:?xt=urn:btih:eb0848de84375482e0bba2ea012370a2decc0908&dn=%5bHi10%5d_Dragon_Ball_-_Kai_%5b720p%5d&tr=http%3a%2f%2fanisaishuu.de%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%2fannounce&tr=udp%3a%2f%2fopen.demonii.com%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.publicbt.com%2fannounce&tr=udp%3a%2f%2ftracker.istole.it%3a80%2fannounce

**Comment by EndOfLine369** [comment]
tyvm :smiling_imp:

**Comment by EndOfLine369** [comment]
Everything has been pushed for this ticket.
@sven-7 have you had to test this piece? If so and good, will close this ticket.

**Comment by EndOfLine369** [comment]
make sure you update your json file and that you also enable the option in the edit library agent pref area.

**Comment by EndOfLine369** [comment]
Mwahaha. ty again. And also shows no missing episodes now.
![image](https://cloud.githubusercontent.com/assets/16750699/16360559/ac83762a-3b2f-11e6-8f67-824305b20646.png)

**Comment by EndOfLine369** [comment]
And note, i'm using exactly what is currently committed to the master.

**Comment by EndOfLine369** [comment]
@ZeroQI, please put your reduction into a pull request. That way I can easily make fixes/adjustments and can handle any commits that happen to the master while review/testing is in-progress. There are a couple of commits that will need to be adjusted in your gist.

For the other mentions, i'll mull over them.

**Comment by ZeroQI** [comment]
@EndOfLine369, https://github.com/ZeroQI/Absolute-Series-Scanner/pull/45 created.

**Comment by MagellanSails** [comment]
I've only tried with one series so far, HxH, but the mappings to the tvdb4 defined seasons are working and I am getting the correct metadata for each episode. I was going to mention that the poster _were not_ showing up correctly, but re-reading this whole thread I missed the "fetch posters" checkbox.

I will try again later tonight / tomorrow morning and report back, but it's looking good so far.

**Comment by EndOfLine369** [comment]
Cool. Yeah, as Plex would be downloading images from other sources people should opt the ok to do that.

![image](https://cloud.githubusercontent.com/assets/16750699/16472934/938a0240-3e2e-11e6-8401-5c33ac31903f.png)

**Comment by EndOfLine369** [comment]
@MagellanSails haven't heard back. Hope that means everything is working fine post enabling the agent option. Will be closing out this ticket in the next day or two.

**Comment by sven-7** [comment]
This is working well for me.

**Comment by MagellanSails** [comment]
@EndOfLine369 Sorry, I've been busy with a lot of other things and haven't been able to work on plex much lately... I'm still having issues with the posters but I'm thinking I've mixed up files from different commits, have permissions issues, or have done something similar.  Everything else is working for me though, and it sounds like it works for everyone else, so I would vote to close this. 

If I discover a real issue once I have some more time to take a good look at things I'll just report a bug.

**Comment by EndOfLine369** [comment]
Sounds good to me :grin:
