### ISSUE TITLE
Unable to get anidb4 running for DBZ OVAs, Series, Movies & TV Specials

### ISSUE THREAD

**Issue by fisher745** [ZeroQI/Absolute-Series-Scanner#400]
I have tried to use anidb3/4 for this Anime to set it in a chronological link this [link](https://www.radiotimes.com/tv/fantasy/dragonball-in-order-how-to-watch/) order which should contain all the above in a single plex library

Here's my folder structure, for the time being I have placed the movies in the movies folder but all in all i plan to remove the movies folder and keep all amines in a single folder later

Base Folders
![image](https://user-images.githubusercontent.com/81430462/155218472-77c42576-bf99-4ce0-9ef5-c308cbb2fc8f.png)

Sub-Folders (please note that upon trying anidb3/4 which did not work in my case i  moved to tvdb4 for the saga seasons but can i still use anidb3/4 and get the sagas as well?)
![image](https://user-images.githubusercontent.com/81430462/155218740-50c176cf-ade0-4ad1-b9a5-148e6dc8e59c.png)

Also in plex when i checked the files with its metadata produced it was wrong for example

![image](https://user-images.githubusercontent.com/81430462/155220180-a777d6f3-387b-47df-a19a-e7b69d89ebad.png)

![image](https://user-images.githubusercontent.com/81430462/155220242-1b5c963f-e689-4e3a-bbd7-48348abad9ad.png)

To reproduce this, make use of the following

1. ASS is being used as Series Scanner
2. DBZ movies (not the super ones)
2. Some DBZ Specials like OVAs and TV Specials
3. And one or two seasons if you can. (this isnt needed as ASS detects series but not the above mentioned types)

And also i believe in Scudlees xml master file entry for anidb-2643, there are actually 2 parts but in that xml its a single entry. [here](https://raw.githubusercontent.com/ScudLee/anime-lists/master/anime-list.xml)

**Comment by fisher745** [comment]
here are the logs
[Dragon Ball Z [tvdb4-81472].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120222/Dragon.Ball.Z.tvdb4-81472.scanner.log)
[Dragon Ball Z [tvdb4-81472].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120223/Dragon.Ball.Z.tvdb4-81472.filelist.log)
[Dragon Ball Z Summer Vacation Special (1992) [anidb4-1530].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120224/Dragon.Ball.Z.Summer.Vacation.Special.1992.anidb4-1530.scanner.log)
[Dragon Ball Z Plan to Destroy Saiyans Part 1 (1993) [anidb4-2643].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120225/Dragon.Ball.Z.Plan.to.Destroy.Saiyans.Part.1.1993.anidb4-2643.scanner.log)
[Dragon Ball Z Plan to Destroy Saiyans Part 2 (1993) [anidb4-2643].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120226/Dragon.Ball.Z.Plan.to.Destroy.Saiyans.Part.2.1993.anidb4-2643.filelist.log)
[Dragon Ball Z Plan to Destroy Saiyans Part 2 (1993) [anidb4-2643].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120227/Dragon.Ball.Z.Plan.to.Destroy.Saiyans.Part.2.1993.anidb4-2643.scanner.log)
[Dragon Ball Z Summer Vacation Special (1992) [anidb4-1530].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120228/Dragon.Ball.Z.Summer.Vacation.Special.1992.anidb4-1530.filelist.log)
[Dragon Ball Z Gather Together, Goku's World (1992)) - Complete Movie [anidb4-6540].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120229/Dragon.Ball.Z.Gather.Together.Goku.s.World.1992.-.Complete.Movie.anidb4-6540.filelist.log)
[Dragon Ball Z Gather Together, Goku's World (1992)) - Complete Movie [anidb4-6540].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120230/Dragon.Ball.Z.Gather.Together.Goku.s.World.1992.-.Complete.Movie.anidb4-6540.scanner.log)
[Dragon Ball Z Plan to Destroy Saiyans Part 1 (1993) [anidb4-2643].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8120231/Dragon.Ball.Z.Plan.to.Destroy.Saiyans.Part.1.1993.anidb4-2643.filelist.log)

**Comment by ZeroQI** [comment]
This is not a bug report, use forum for use case
- Meta wrong is an agent issue
- 'didn't work' is not a problem description
- never advertised different modes to work together
- We now use a fork of scudlee's xml and if this mapping is wrong submit a bug report to said project

You can use tvdb5 for chronological order of one series or and 4 for relationship order but you want chronological order of multiple series you want not in and. Relationship order (which would map in tvdb order mostly) but in arbitrary site chronological order?

Again, ask others HOW they sorted Dra
Gon Ball universe on the forum, as you failed to show an error in the way the scanner assign season and episode number
