### ISSUE TITLE
[feature request] .plexmatch files support

### ISSUE THREAD

**Issue by vidarrio** [ZeroQI/Absolute-Series-Scanner#412]
The new .plexmatch files would be a great if they worked with this agent as well!

**Comment by luckri13** [comment]
My personal use case would be less for series matching which is already easy with the anidb id as you said. It would be to correctly scan in episodes which have weird filenames that aren't getting scanned correctly. This isn't really necessary if you can rename the affected files, but in my case, I can't do that. Supporting .plexmatch files would allow full control of the file <-> episode matching separate from the files themselves, in turn making sure one can always manually fix any wrongly scanned files without changing them.

As a user, it's also quite easy to write scripts to generate .plexmatch files for various organisational use cases, so it's a nice tool to have.

**Comment by ZeroQI** [comment]
Instead of generating a .Plex match file, renaming the file would make more sense.
Now you will say you cannot change the filename but that's only the case if using torrent directly to your library without using a temporary folder... Am I wrong?

**Comment by luckri13** [comment]
Indeed, I am not using a temporary directory, the reason for this is that I keep everything (50+ TB) seeding at all times, and do not wish to keep duplicate files. There is of course the solution of using symlinks instead, but doing that for everything would be a huge pain in the ass, and the .plexmatch files would be a much more elegant solution in my opinion.

**Comment by ZeroQI** [comment]
Will close this for now
