### ISSUE TITLE
Can't setup arc order, idk why

### ISSUE THREAD

**Issue by Valhallle** [ZeroQI/Absolute-Series-Scanner#415]
Hello,

I think i'm an HUGE idiot, but I have issue with the option to order anime by arc.
I tried everything, but I think i've missed a step:

Let's take the One Piece example:

- Sonarr folder are named like this: {Series Title} [tvdb4-{TvdbId}] for One piece, it gives me => One Piece [tvdb4-81797]
- Inside the folder, Sonarr automatically place episode on season folder (Season 1, Season 2)
- The episode are named like this inside the folder:  One Piece - S01E01 - I'm Luffy! The Man Who's Gonna Be King of the Pirates! DVD.mkv
- I installed ASS and HAMA, they're both selected on my anime server. And it work. 
- I've put the whole tvdb4.mapping.xml file [https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.mapping.xml](url) on my anime server root folder
- I've put the same file on my one piece folder
- I've put the tvdb4.mapping file with this text on my one piece folder:
``001|030|East Blue - Gathering the Crew
02|031|044|Arlong Park
03|045|063|Entering into the Grand Line 
04|064|077|Whiskey Peak and Little Garden
05|078|091|Drum Island
06|092|135|Alabasta
07|136|152|Jaya Arc
08|153|195|Skypiea
09|196|206|The Naval Fortress G8
10|207|228|Davy Back Games - The Foxy Pirate Crew
11|229|263|Water Seven
12|264|325|Enies Lobby
13|326|384|Thriller Bark
14|385|407|Sabaody Archipelago
15|408|421|Island of Women / Amazon Lily
16|422|456|Impel Down
17|457|489|Marineford
18|490|516|Post-War Arc
19|517|574|Fishman Island
20|575|628|Punk Hazard
21|629|746|Dressrosa
22|747|782|Zou Arc
23|783|877|Whole Cake Island Arc
24|878|891|Reverie Arc
25|892|892|Wano Arc (unknown length)``

But when I refresh metadata, one piece stay in season, and not by arc ..

I don't know what I missed, I don't really understand ... I've put the show on tvdb4 mode with the name, and i've pute the mapping file every where ... 

I'm VERY sorry to disturb you with this, but i'm without solution for now.
Is there any way to combine sonarr season folder order with the arc order ? 

Thank a LOT

**Comment by ZeroQI** [comment]
Tvdb4 is for any season arrangement with absolute numbering, and if no
season is specified it uses the arc database. You did set up seasons on
your own so it is using it, working as designed

**Comment by Valhallle** [comment]
I see.
There is no way to bypass the season folder made by sonarr so ? 
I need to rename the anime with One Piece Episode 01 02 03 etc ?

**Comment by ZeroQI** [comment]
Either you do not specify seasons and it use the online file, or you specify your seasons
Since technically the folder content didn't change it will not rescan. Delete the last ep and rescan.
If issue persists paste the ass series specific *.scanner.log

**Comment by Valhallle** [comment]
> Either you do not specify seasons and it use the online file, or you specify your seasons
> 
> Why did you download the online file to put locally?
> 
> Refresh metadata will not change episode or season, the scanner does that...
> 
> Since technically the folder content didn't change it will not rescan. Delete the last ep and rescan. If issue persists paste the ass series specific *.scanner.log

Ok I did it.
It seem to work: "season" are made by arc. 
But it doesn't name it, and doesn't change the poster (but the poster is on my poster list on plex)
So I think it's ok, I just need to change season name and poster, wich is already a victory :)

**Comment by ZeroQI** [comment]
Agents can't change season title, at least not third party agents
Posters can be change. But once some posters were downloaded to the seasons you have to change them manually
