### ISSUE TITLE
Incorrect Season and Episode Number from File Name (11 -> Special 101)

### ISSUE THREAD

**Issue by EarthBoundX5** [ZeroQI/Absolute-Series-Scanner#416]
## Platform
Operating system and version: Windows Server 2019 - 1809 - Build 17763.2989
Plex version: 1.27.0.5897

## Expected Behavior
Scanning either of the following file names...
- Yuu Gi Ou - 11 - The Opening of a Rumoured Monster Capsule [T-N][VHS](7B8645E6).avi 
- Yuu Gi Ou - 11 - The Opening of a Rumoured Monster Capsule [YGO][VHS](CD44CDBA).avi 

...should be scanned in as Season 1, Episode 11.

## Current Behavior
Scanning either of the following file names...
- Yuu Gi Ou - 11 - The Opening of a Rumoured Monster Capsule [T-N][VHS](7B8645E6).avi 
- Yuu Gi Ou - 11 - The Opening of a Rumoured Monster Capsule [YGO][VHS](CD44CDBA).avi 

...is currently being scanned in as Season Specials, Episode 101.

Scanner Logs:
[Yuu Gi Ou (1998) [anidb-593].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8945649/Yuu.Gi.Ou.1998.anidb-593.filelist.log)
[Yuu Gi Ou (1998) [anidb-593].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8945650/Yuu.Gi.Ou.1998.anidb-593.scanner.log)

Agent Logs:
[Yuu Gi Ou (1998) [anidb-593].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8945630/Yuu.Gi.Ou.1998.anidb-593.agent-search.log)
[Yuu Gi Ou (1998) [anidb-593].agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/8945631/Yuu.Gi.Ou.1998.anidb-593.agent-update.log)

## Steps to Reproduce
1. Have the following files:
.\Video\Anime\#Expanded Universe\Yu-Gi-Oh!\TV Series\Yuu Gi Ou (1998) [anidb-593]\Yuu Gi Ou - 11 - The Opening of a Rumoured Monster Capsule [T-N][VHS](7B8645E6).avi
.\Video\Anime\#Expanded Universe\Yu-Gi-Oh!\TV Series\Yuu Gi Ou (1998) [anidb-593]\Yuu Gi Ou - 11 - The Opening of a Rumoured Monster Capsule [YGO][VHS](CD44CDBA).avi
2. Update Plex Library.
3. Find files have been imported as Specials.
![image](https://user-images.githubusercontent.com/2718666/174713177-99fd6fdb-6b22-49b6-a640-447a8d70170b.png)
![image](https://user-images.githubusercontent.com/2718666/174713312-c72168ec-b899-49e5-b8d0-eee01c47d90a.png)

## Additional information
I deleted and re-added this show after updating to the latest ASS & Hama Bundle with the same results before posting.

**Comment by ZeroQI** [comment]
You have multiple files faith the same episode number, that is not supported as there are fail guards for the EP num mber if a number comes too often..
The word search rail so I use ANIDB_RX-1 so the second one in the list to get EP number which is the opening Regex due to the presence of 'opening'

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L81

**Comment by EarthBoundX5** [comment]
> You have multiple files faith the same episode number, that is not supported as there are fail guards for the EP num mber if a number comes too often.. 
I can try again with only a single file and see if the results are different if that's what you're asking?  For reference, I have a fairly sizable library with multiple duplicate episodes (versions, dub, sub, etc) and have had no obvious issues thus far.  I don't typically have more than 3 or 4 of the same file; but this far I've seen no problems with those situations until this particular one (which is partially explained by the below quote).

> The word search rail so I use ANIDB_RX-1 so the second one in the list to get EP number which is the opening Regex due to the presence of 'opening'
> 
> https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L81
This makes sense at least as far as why it's a Special?  Is there any handling to be done to account for situations where Opening is in the title of the episode like this?  I can't think of any short of adjusting my own naming convention to use alternative words when these matched situations come up?  Should I test again without Opening in the title?

**Comment by ZeroQI** [comment]
multiple same episode is not supported due to failsafe in the code
Please try with only one video file per episode number
DUe to the lack of answer, closing

**Comment by EarthBoundX5** [comment]
@ZeroQI, my apologies!  I was expecting a reply from you to my last comment; hence why I didn't reply again.

Would you like me to test with only a single file?

I can do this; however, I'd ask reconsideration to the stance of it being unsupported due to whatever failsafe exists?  It's an impossible task to not have multiple files of the same episode, and as mentioned, I've only seen detriment with this single example out of thousands of files.

My biggest justification would be for situations where only a dub file and a sub file exist for a given Anime.  Sure, one could argue to remux them, but that'd then fail hash checks with anidb.

Please let me know what I can do for this bug submission.  Thanks!

**Comment by ZeroQI** [comment]
Hold on I explicitly said one VIDEO file per episode number as for Video files, the algorythm voids the number as episode number if it appears too many times. Non-video extensions like sub are not taken into account, only video extensions  plex would allow to view

To make the different numbering in a single folder I had to find failsafe to root out bad episode numbers and repetition was one of them.

Yuu Gi Ou - 11 - The Opening of a Rumoured Monster Capsule [T-N][VHS].avi
Yuu Gi Ou - 11 - The Opening of a Rumoured Monster Capsule [YGO][VHS].avi

You should realistically have different folders for dub and sub, grouping is unsupported. 
Issue is people don't rename files and fixing the word ep number algorythm search generally broke more than it fixes so not worth it for me
