### ISSUE TITLE
Support different order in tvdb.

### ISSUE THREAD

**Issue by Andor233** [ZeroQI/Absolute-Series-Scanner#417]
TVDB support different order like aired order and DVD order.

It will be beneficial when collecting the BD series and some director's cuts.

Sample:
https://thetvdb.com/series/seitokai-yakuindomo/seasons/dvd/1
https://thetvdb.com/series/re-zero-starting-life-in-another-world/seasons/alternate/1

**Comment by ZeroQI** [comment]
You can for now create a separate library for now with thetvdb DVD agent...

tvdb5 mode manages chronological order already so could work for some series

I don't see how to implement that without impacting already named media. Also, that would be complex to map in normal tvdb mode and map between tvdb modes...

Are you conscious the moment tvdb pull the plug on the older V2 API, that this agent will stop working altogether? I will close this for now as I am still pondering about implementing tvdb V4 api
