### ISSUE TITLE
Season folders don't work with anidb type

### ISSUE THREAD

**Issue by LuminescentMoon** [ZeroQI/Absolute-Series-Scanner#418]
Is it not possible to make season folders work with the anidb type or am I missing something? I have a few shows with a folder structure like this:

```
Show Name
  ┃
  ┠-->  Season 1
  ┃            ┃
  ┃            ┠-->  Show Name - S01E01
  ┃            ┠-->  Show Name - S01E02
  ┃            ┠-->  ...
  ┠-->  Season 2
  ┃            ┠-->  Show Name - S02E01
  ┃            ┠-->  Show Name - S02E02
  ┃            ┠-->  ...
  ┠-->  Specials
               ┠-->  Show Name - S00E01
               ┠-->  Show Name - S00E02
               ┠-->  ...
```

tvdb type works but I want the relational order of the anidb type. However, when I try to use the latter, Plex just merges season 2, 3, etc's episodes into season 1.

**Comment by ZeroQI** [comment]
If you use season 2 and more it will use tvdb numbering for specials. If you use one season it will use anidb numbering for specials.

 Do you mean anidb2 and anidb3 relationship modes?

**Comment by LuminescentMoon** [comment]
Yes. anidb4 to be precise.

**Comment by ZeroQI** [comment]
So you use anidb4 mode, so 'Show name [anidb4-xxxxx]' and it supposedly use seasons with the relationship order, and it groups all into one season ?
No logs, no example or anything allowing to reproduce the issue. No explanation of what is expected compared to what you encounter. I struggle to even see where you want this bug report to head...

**Comment by ZeroQI** [comment]
Forced IDs are for series folder
anidb4 mode requires absolute numbering so season 1
If you were to remove s02exx from each EP it may work but the season xx title will probably conflict
