### ISSUE TITLE
Teppen!!!!!!!!!!!!!!!'s absolute numbering does not correctly get mapped to relative for the metadata provider

### ISSUE THREAD

**Issue by MiraiSubject** [ZeroQI/Absolute-Series-Scanner#423]
## Platform

Operating system and version: Linux 5.15.46-Unraid 6.10.3, using the plexinc/pms-docker container
Plex version: 1.27.0.5897

## Expected Behavior

The expected behaviour is that the series correctly maps the absolute numbering to relative so the metadata provider can provide the right metadata for the episode. 

Here's a screenshot of what would be observed as the expected behaviour: 
![image](https://user-images.githubusercontent.com/803255/186025163-43b82a4a-d40a-4210-ae48-6d36002a46a9.png)

## Current Behavior
In "Teppen!!!!!!!!!!!!!!! Laughing 'til You Cry" episode 2 and so forth are incorrectly mapped due to their unconventional absolute numbering, which causes Hama to grab the incorrect metadata for each episode. 

![image](https://user-images.githubusercontent.com/803255/186023690-810a9f1d-63bd-4c7f-b8f1-5143d5c25af0.png)
As you can see here in Sonarr this is what the absolute to regular episode mapping is supposed to be like. 

![image](https://user-images.githubusercontent.com/803255/186023732-39634edb-9452-463b-a6fe-a4b4c431e55c.png)
This is how it is displayed in plex when using ASS and Hama. 

Here are the ASS logs: 

[Teppen!!!!!!!!!!!!!!! Laughing 'til You Cry.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/9397740/Teppen.Laughing.til.You.Cry.scanner.log)
[Teppen!!!!!!!!!!!!!!! Laughing 'til You Cry.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/9397741/Teppen.Laughing.til.You.Cry.filelist.log)

In the Hama agent log you can also see the failure to find s1e2: 

[Teppen!!!!!!!!!!!!!!! Laughing 'til You Cry.agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/9397818/Teppen.Laughing.til.You.Cry.agent-update.log)

## Steps to Reproduce

1. Create a folder containing the series "Teppen!!!!!!!!!!!!!!! Laughing 'til You Cry" and add the files using the absolute episode numbering. 
2. Create a new TV Show library in plex using the Absolute Series Scanner and HamaTV
3. Observe in plex that Episode 1 skips to Episode 3 and so forth, and that the metadata does not match the correct episode. 

## Additional information
- Removing the sub group, quality and hashes does not change the result of the observed issue. 
- Changing the file names to be relative (obviously) works and correctly maps the episodes. 
- Moving the files out of the season 1 folder yields no change in mapping: 
[Teppen!!!!!!!!!!!!!!! Laughing 'til You Cry.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/9397861/Teppen.Laughing.til.You.Cry.scanner.log)
[Teppen!!!!!!!!!!!!!!! Laughing 'til You Cry.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/9397862/Teppen.Laughing.til.You.Cry.filelist.log)

What really doesn't help is that [thetvdb's absolute order](https://thetvdb.com/series/teppen/seasons/absolute/1) does not match Sonarr's, but imdb [does match it](https://www.imdb.com/title/tt18939874/episodes?ref_=tt_eps_sm). AniDB also has ["relative" ordering](https://anidb.net/episode/256708): , while [Crunchyroll of all sites](https://www.crunchyroll.com/teppen-laughing-til-you-cry/episode-3-the-evil-magistrate-chapter-852193) does display the episode numbers as expected (matching sonarr as well). 
![image](https://user-images.githubusercontent.com/803255/186027498-d981b988-5577-4a9b-9dbb-f4d5831d9738.png)

**Comment by ZeroQI** [comment]
Episode 1, 3, and 4 are mapped to episode 1, 3, and 4 as they should

Files are not following anidb numbering
http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=17118

Working as designed when following anidb numbering... Issue is unsupported

**Comment by MiraiSubject** [comment]
Thanks for your time.

After some more research, I've decided to submit a db change request at AniDB to rectify the wrong numbering, because [episode 2 did in fact get skipped](https://twitter.com/teppen_anime/status/1545317935333249024) and as such the episode numbering on their side matched the wrong episodes.

**Comment by ZeroQI** [comment]
That is tricky. Tvdb may register without the episode 2 but ep 3 would become ep 2
Anidb should record ep 2, dvd/Blu-ray release change nothing unless maybe it gets aired again alongside ep2
https://thetvdb.com/series/teppen/seasons/official/1

Look like tvdb and anidb both put prod ep 3 as ep2 so renumber all to 1-11 is the official way. The fact sonar can provide all eps is irrelevant, what matter is to conform to the Metadata sources and both match so they will refuse your request I believe
