### ISSUE TITLE
[BUG] The scanner does not start with "junction" type folders on Windows.

### ISSUE THREAD

**Issue by VegethB** [ZeroQI/Absolute-Series-Scanner#424]
## Platform

Operating system and version: Windows Server 2019 LTSC x64
Plex version: 1.29.0.6244

## Expected Behavior

Auto-detect "junction" folders and their contents without having to manually force a scan of the library.

## Current Behavior

Folders of type "Junction" are not seen and therefore nothing happens until you start a manual scan of the library

## Steps to Reproduce

1. Add a new series to plex or move an already existing series and then create the Junction.

## Additional information

![image](https://user-images.githubusercontent.com/17975351/193264939-165f2444-0cda-4777-9bed-b598081e2e51.png)
"`L:\Anime Auditing\`" is the folder that plex scans.
"`O:\`" is where the files physically reside.
Unfortunately I can't use JBOD / RAID and I don't want to create 99 folders to check for a library because as soon as I can I will upgrade to a larger HDD that will contain everything: and having the folders scattered, plex deletes the series when I go to remove them despite seeing the duplicates ... and then I have to redo all the metadata and the custom cover / background (it would be a mess given the standard volume ... 300+), so instead, I just move the files back to the original disk and nothing changes.

**Comment by ZeroQI** [comment]
Does plex default scanner works correctly with these?

**Comment by ZeroQI** [comment]
New scanner is irrelevant as not written in Python and doesn't support third party agents

Plex series scanner is the old one
ASS Scanner being called by plex upon livrary/folder changes, it means Plex didn't detect the change so not a scanner issue but a Plex issue...

I cannot change code if the scanner isn't. Alled upon changes...

**Comment by ZeroQI** [comment]
If the issue is that it doesn't detect 
 changes automatically, but does manually, the scanner isn't called by Plex when there is a change and I cannot fix.

If the series folder is not located in the library root

**Comment by ZeroQI** [comment]
Your can edit the part for season folders to take into account season folders in different languages. I think is has to do with the change detection with the mount point added complexity, i believe the information is not cascaded like changes in the native un mapped file system
