### ISSUE TITLE
Mob Psycho 100 III not detecting episode number correctly

### ISSUE THREAD

**Issue by ksurl** [ZeroQI/Absolute-Series-Scanner#425]
## Platform

Operating system and version: linuxserver/plex docker image on debian 11
Plex version: 1.29.0.6244

## Expected Behavior

detect episode number for Mob Psycho 100 III

## Current Behavior

detects ep 01 as ep 100 due to title

## additional info

file name is set as `Mob Psycho 100 III 01`

season 1 and 2 detect correctly. file names like `Mob Psycho 100 01` and `Mob Psycho 100 II 01`

**Comment by ZeroQI** [comment]
Well no scanner logs so cannot assertain the series folder name which is subtracted from the filename but I can see why the scanner believes it could be 100, 3 in roman signs or 01...

**Comment by ZeroQI** [comment]
Depends on folder name and filenames inside...
Logs indicate if work algorithm or regex used so can only gués s your folder name and filenames differs

**Comment by ksurl** [comment]
wow I had a typo on the folder name. Missing the 100. Rename and rescan fixed.
