### ISSUE TITLE
E01 and E10 are both detected as S01E01 when DD2.0 is present

### ISSUE THREAD

**Issue by opello** [ZeroQI/Absolute-Series-Scanner#428]
## Platform

Operating system and version: Truenas SCALE 22.02.4
Plex version: 1.29.2.6364

## Expected Behavior

E01 and E10 should be distinct episodes.  The same applies to E02 and E20, and so on.

## Current Behavior

E01 and E10 are associated with "Episode 1" in the Plex library entry for the show.  Similarly, E02 and E20 (and so on) are associated with "Episode 2" (and so on) in the show.

## Steps to Reproduce

_I will do this if absolutely necessary, but the fix below works._

## Additional information

Adding `"DD2.0"` to `WHACK_PRE_CLEAN_RAW` resolves this and the episodes are all parsed correctly.  If desired I can make a branch with this change.

**Comment by opello** [comment]
Seems similar to #394.

**Comment by ZeroQI** [comment]
Please do, and will approve straight away
