### ISSUE TITLE
Absolute Series Scanner does not show up in Scanner section when editing library

### ISSUE THREAD

**Issue by OneSteelTank** [ZeroQI/Absolute-Series-Scanner#431]
When I try to change the scanner of a library to ASS (Manage Library --> Edit ---> Advanced), it does not show up. 
## Platform

Operating system and version: Windows 10 19044.2251
Plex version: 1.58.1.3380-ea159c52

## Expected Behavior

I expected ASS to show up in the scanner section so that I could select it
## Current Behavior

It does not show up. 

## Steps to Reproduce

What I did was:
1. Install Python 3.11 and make sure to add it to PATH
2. Download the .py file
3. Added the .py file to both C:\Users\onest\AppData\Local\Plex\Plex Media Server\Scanners\Series\Absolute Series Scanner.py AND C:\Users\onest\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py (I don't know which one is the right one so better safe than sorry)
4. Open a Library I want to edit
5. Go to Manage Library -- > Edit ---> Advanced --> Scanner

**Comment by ZeroQI** [comment]
C:\Users\onest\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py most likely

Create new library (series or movies), which is NOT the new type incompatible with scanners to test, with tvdb agent for example, then select the scanner at creation...
- https://support.plex.tv/articles/200241548-scanners/ indicate how to migrate legacy libraried but then, they are incompatible with third party scanner
- Did you try another third party scanner to check if it is showing, as if it is not, it it a plex issue and not the scanner specifically...

If it doesn't work, you need to include log [...]/Plex Media Server/Logs/Plex Media Scanner.log

**Comment by OneSteelTank** [comment]
Hey, figured it out shortly after. Didn't know it had to be TV Series, selected Other Videos
