### ISSUE TITLE
Episode 1000 is matched to special 501

### ISSUE THREAD

**Issue by mcrommert** [ZeroQI/Absolute-Series-Scanner#433]
I know that one piece is probably the only show this can happen with - but for whatever reason its matching it to special 501 instead of just in the seasons - i'm using tvdb4 for this one and everything else looks like its working correctly 
![image](https://user-images.githubusercontent.com/3512724/214578549-b3ebf8e4-d55d-401a-83dd-652d67bcfb62.png)

I checked naming and that looks right and i'm wondering what I've stepped in here :)

**Comment by mcrommert** [comment]
Apologies - i did not realize i was behind on my versions - looks like it works correctly with the newest version

Again apologies

**Comment by ZeroQI** [comment]
Thanks for giving the resolution, and detective Conan pre-empted the 1000 eps mark and had the issue before and needing the scanner to be amended, but not many 1k+ contenders indeed
