### ISSUE TITLE
When Using Group folders multiple versions and editions cannot be split apart anymore inside plex

### ISSUE THREAD

**Issue by AkitoTheGambler** [ZeroQI/Absolute-Series-Scanner#435]
## Platform
Operating system and version: Windows 11, v22H2
Plex version: 1.31.3.6868

## Expected Behavior
I have the following folder structure:
"D:\PlexLibrary\Anime\JoJo no Kimyou na Bouken\JoJo no Kimyou na Bouken (2012)\JoJo no Kimyou na Bouken (2012) - E01 - Dio the Destroyer.mp4"
"D:\PlexLibrary\Anime\JoJo no Kimyou na Bouken\JoJo no Kimyou na Bouken Re-Edited (2012)\JoJo no Kimyou na Bouken Re-Edited (2012) - E01-09.mp4"

"D:\PlexLibrary\Anime\ReZero kara Hajimeru Isekai Seikatsu\ReZero kara Hajimeru Isekai Seikatsu (2016)\ReZero kara Hajimeru Isekai Seikatsu (2016) - E01 - The End of the Beginning and the Beginning of the End - pt2.mp4"
"D:\PlexLibrary\Anime\ReZero kara Hajimeru Isekai Seikatsu\ReZero kara Hajimeru Isekai Seikatsu Director's Cut (2016)\ReZero kara Hajimeru Isekai Seikatsu Director's Cut (2016) - E01 - The End of the Beginning and the Beginning of the End.mp4"

<img width="747" alt="Pic1" src="https://user-images.githubusercontent.com/11999105/230738240-b9ac9059-699e-4012-adc3-339a549ccf49.png">
it puts them together because its the same series but a different version and im able to split them apart, so they are different entries inside plex

## Current Behavior
When using the above folder structure im not able to split them apart
<img width="737" alt="image" src="https://user-images.githubusercontent.com/11999105/230738440-bb201107-9281-4882-bdb9-5799e5400f60.png">

When removing the group folder like below im able to split them apart again

"D:\PlexLibrary\Anime\JoJo no Kimyou na Bouken (2012)\JoJo no Kimyou na Bouken (2012) - E01 - Dio the Destroyer.mp4"
"D:\PlexLibrary\Anime\JoJo no Kimyou na Bouken Re-Edited (2012)\JoJo no Kimyou na Bouken Re-Edited (2012) - E01-09.mp4"

"D:\PlexLibrary\Anime\ReZero kara Hajimeru Isekai Seikatsu (2016)\ReZero kara Hajimeru Isekai Seikatsu (2016) - E01 - The End of the Beginning and the Beginning of the End - pt2.mp4"
"D:\PlexLibrary\Anime\ReZero kara Hajimeru Isekai Seikatsu Director's Cut (2016)\ReZero kara Hajimeru Isekai Seikatsu Director's Cut (2016) - E01 - The End of the Beginning and the Beginning of the End.mp4"

## Steps to Reproduce
1. Put multiple versions/editions of a show in a group folder

## Additional information & logs
[ASS Scanner Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/11183967/ASS.Scanner.Logs.zip)

Separate small issue
When an episode is split in multiple files the episode name becomes: "The End of the Beginning and the Beginning of the End (Part 2)"
instead of "The End of the Beginning and the Beginning of the End"
Playback is normal, it plays both parts correctly and shows as 1 episode inside plex but the name suggests its only the second part
not sure if this is the scanner or agent (HAMA Agent) issue

Does not happen with default Plex Scanner & Agent

ASS + HAMA
<img width="577" alt="image" src="https://user-images.githubusercontent.com/11999105/230738817-831e5da9-9c81-4b3e-b426-f9552c7c6cad.png">
<img width="530" alt="image" src="https://user-images.githubusercontent.com/11999105/230738776-68b190c1-0b5b-4601-9097-f092e09a1912.png">

Plex Default Scanner + Agent

<img width="308" alt="image" src="https://user-images.githubusercontent.com/11999105/230739505-fe1d2ecd-0ce3-43d3-a2f0-35fa404ee1cd.png">

**Comment by ZeroQI** [comment]
Scanner Jobe is to add media files to plex, it add them sith season and ep number, and give a title
The scanner match that title to a unique ID and both series
Plex allow to split so if not allowed, that's a Plex issue, but grouping folders being a hack it may be less stable and unlike normally scanned items is rescanned at every scan, unlike standard series which uses cached scan results if the folder content didn't change

Not a scanner issue
Why the weird brackets {}?

**Comment by ZeroQI** [comment]
Scanner add series name season and ep number and ep title, but the metadata agent rewrite those.
Check in Hama custom series log at tge end which source provided the name according to your agent settings.

**Comment by AkitoTheGambler** [comment]
should i reopen the second issue under HAMA then?

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/11184317/com.plexapp.agents.hama.log)

[_Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/11184316/_Logs.zip)
