### ISSUE TITLE
How to manage extras ?

### ISSUE THREAD

**Issue by ShinoOoesu** [ZeroQI/Absolute-Series-Scanner#436]
Hi everyone!

By buying anime Blurays or DVD, there are sometimes, some extras like, trailers, interviews or  Creditless Opening or ending.
And I don't know how to Manage it with this scanner. Actually , when I read the documentation, I understand that extras are classified as "Specials"

Is that correct ? However I want them to show in the extra/bonus section of the anime since plex allow it.

Nevertheless, sometimes, i manage to do it, sometimes not.

## Zombiland Saga

![image](https://user-images.githubusercontent.com/127020606/231403118-3279490e-cf3b-4106-b52b-4c2d12a66621.png)
 
![image](https://user-images.githubusercontent.com/127020606/231403381-b1a4254e-333f-4caf-907f-2e64964baf25.png)
 

*Success*

## Dumbbell

![image](https://user-images.githubusercontent.com/127020606/231404291-319fc703-3333-45d8-9808-32b3830438ec.png)
![image](https://user-images.githubusercontent.com/127020606/231404513-67bafec0-1976-4a77-869d-2eedc20d7f13.png)

*success*

## Ergo proxy

![image](https://user-images.githubusercontent.com/127020606/231404875-da7a516f-fcfe-4db3-9782-3fbadac713da.png)

![image](https://user-images.githubusercontent.com/127020606/231406259-d25c28fc-e577-4d30-8fd8-33aad903eefc.png)

![image](https://user-images.githubusercontent.com/127020606/231405488-30ad8eec-090f-4496-9c34-02c636c9bcc4.png)

*failed, since categorised as special besides interviews don't appear on special season*

## The Tatami Galaxy

![image](https://user-images.githubusercontent.com/127020606/231407061-91fdc317-9396-4eeb-9aad-a219419ad311.png)

![image](https://user-images.githubusercontent.com/127020606/231407261-cb96b3d4-3272-4dd2-9a5e-a4602ce4410e.png)

### The tatami galaxy.filelist.log

```

The Tatami Galaxy\Interviews\Le guide de Kyoto de Europe Kikaku.mkv
The Tatami Galaxy\Scenes\Ending 1 Creditless.mkv
The Tatami Galaxy\Scenes\Ending 1 Karaoke.mkv
The Tatami Galaxy\Scenes\Opening 1 Creditless.mkv
The Tatami Galaxy\Scenes\Opening 1 Karaoke.mkv
The Tatami Galaxy\Scenes\Opening 2 Creditless.mkv

```

### The tatami galaxy.scanner.log

```
=============================================================================================================================================================
Call: "Root", path: "The Tatami Galaxy\Interviews", folder_show: "Interviews", dirs (0), files (1)
=============================================================================================================================================================
-------------------------------------------------------------------------------------------------------------------------------------------------------------
=============================================================================================================================================================
"Interviews" s01e         1                         "Word Search" "" "Le guide de Kyoto de Europe Kikaku.mkv"
=============================================================================================================================================================

=============================================================================================================================================================
Call: "Root", path: "The Tatami Galaxy\Scenes", folder_show: "Scenes", dirs (0), files (5)
=============================================================================================================================================================
-------------------------------------------------------------------------------------------------------------------------------------------------------------
=============================================================================================================================================================
"Scenes" s00e       151                         "ANIDB_RX-2" "Ending 01" "Ending 1 Creditless.mkv"
"Scenes" s00e       151                         "ANIDB_RX-2" "Karaoke" "Ending 1 Karaoke.mkv"
"Scenes" s00e       101                         "ANIDB_RX-1" "Opening 01" "Opening 1 Creditless.mkv"
"Scenes" s00e       101                         "ANIDB_RX-1" "Karaoke" "Opening 1 Karaoke.mkv"
"Scenes" s00e       102                         "ANIDB_RX-1" "Opening 2" "Opening 2 Creditless.mkv"
=============================================================================================================================================================

=============================================================================================================================================================
Call: "Plex", path: "The Tatami Galaxy", folder_show: "The Tatami Galaxy", dirs (1), files (0)

```

*Failed* 

What did I do wrong?

Thanks!

**Comment by ZeroQI** [comment]
Check Plex way of doing things first: https://support.plex.tv/articles/local-files-for-tv-show-trailers-and-extras/
- Put all files with metadata in AniDB (or TheTVDB if using seasons 2+ or force tvdbid in series foldername only) into 'Specials' folder, or the files without medatata you want to view in plex... Opening/endings are listed in ANiDB as specials...
- Put stuff which is not listed in anidb or TheTVDB in 'Extras' folder, this way they won't be included in Plex

Example: Tatami galaxy ANiDB: https://anidb.net/anime/7243 with two openings, one ending, one trailer, scanner logs show it detected perfectly the numbering fr them, just use a 'Specials' folder for these files
- The Tatami Galaxy\Extras\Le guide de Kyoto de Europe Kikaku.mkv
- The Tatami Galaxy\Specials\Ending 1 Creditless.mkv
- The Tatami Galaxy\Specials\Ending 1 Karaoke.mkv
- The Tatami Galaxy\Specials\Opening 1 Creditless.mkv
- The Tatami Galaxy\Specials\Opening 1 Karaoke.mkv
- The Tatami Galaxy\Specials\Opening 2 Creditless.mkv

The readme does state the following
> And post in either:
> [Plex Support thread for Scanner (you are unsure if it is a bug)](https://forums.plex.tv/discussion/113967/absolute-series-scanner-for-anime-mainly/#latest)
> [Github issue page (you have a bug)](https://github.com/ZeroQI/Absolute-Series-Scanner/issues)
> Creating a post or bug report without including relevant information like logs, serie impacted, or having not said the troubleshooting steps were followed will be recommended to pay the RTFM tax by donating. This part is called 'Exhibit A'.

**Comment by ShinoOoesu** [comment]
Thanks for the answer, but that does not explain why I manage to add file in the plex's extra section...

**Comment by ZeroQI** [comment]
There is a Specials section in Plex but there is no  Extras section...  Put files in 'Specials'  folders to begin with... What happens when you name files  as advised:
The Tatami Galaxy\Extras\Le guide de Kyoto de Europe Kikaku.mkv
The Tatami Galaxy\Specials\Ending 1 Creditless.mkv
The Tatami Galaxy\Specials\Ending 1 Karaoke.mkv
The Tatami Galaxy\Specials\Opening 1 Creditless.mkv
The Tatami Galaxy\Specials\Opening 1 Karaoke.mkv
The Tatami Galaxy\Specials\Opening 2 Creditless.mkv
?

**Comment by ShinoOoesu** [comment]
There IS an extra section, please see my other screens i.e. Zombiland saga...

For the renaming I can't do that before tomorrow sorry

**Comment by ZeroQI** [comment]
My scanner only support Specials folder so Plex added a bonus section recently. Plex scanner do support some folders so maybe local media assets agent flagged some files for bonus section... 

https://support.plex.tv/articles/local-files-for-tv-show-trailers-and-extras/

**Comment by ShinoOoesu** [comment]
Oh, ok then, sorry for the loss of Time...

**Comment by ZeroQI** [comment]
Follow the example I gave, all openings will be in specials section with metadata, but what is not listed in anidb should be in Extras folder to be skipped or left in specials folder to be accessible but with no metadata but the scanner would give ep number depending to the name and sort opening endings automatically...
