### ISSUE TITLE
ASS Marking Entire Seasons as Single Special File

### ISSUE THREAD

**Issue by churlkun** [ZeroQI/Absolute-Series-Scanner#438]
## Platform
Operating system and version: Windows Server 2022
Plex version: 1.32.4.7195

## Expected Behavior
Episodes following the S[X]E[Y] format should be properly assigned to the correct season/episode.

## Current Behavior
Entire Seasons are matched as duplicates of a single Special based on their season number. I.E. S04E03 becomes Special 04

## Steps to Reproduce
1. Scan Library w/ effected files
2. Observe entire season combined into single Special

## Additional information
Temporary fix was to remove the S[X] out of the filename. This is currently happening to two series, here are example filenames from each of them. The ASS logs are pretty empty, but attaching them for file2 anyway as an example. Also attaching the Scanner.log file as it seems it might be crashing on the regex. 
file1 - marked as Special 1: `High-Rise.Invasion.S01E02.Ive.Found.a.New.Goal.1080p.NF.WEB-DL.DDP2.0.H.264-NTb.mkv`
file2 - marked as Special 4: `Demon.Slayer.Kimetsu.no.Yaiba.S04E01.Someone's.Dream.1080p.AMZN.WEB-DL.DDP2.0.H.264-KQRM.mkv`

[Demon Slayer - Kimetsu no Yaiba.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/11774753/Demon.Slayer.-.Kimetsu.no.Yaiba.scanner.log)
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/11774754/Plex.Media.Scanner.log)
[Demon Slayer - Kimetsu no Yaiba.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/11774755/Demon.Slayer.-.Kimetsu.no.Yaiba.filelist.log)

**Comment by ZeroQI** [comment]
File list size 0
Scanner log show no file
Replace dots with spaces, that is an abhorrent naming convention

**Comment by churlkun** [comment]
I noticed that as well, however ASS is still scanning and adding new files to plex, regardless of the empty logs. It seems since yesterday only `_root_.scanner.log` has gotten updated, the rest haven't been touched by ASS since then. _root_.scanner.log shows that the scan is starting, outputs the libraries and their agents/scanners/etc, then nothing else until the next scan is initiated.

While I could add yet another step to my automation to handle the naming conventions, I'd rather troubleshoot the actual issue, if it is possible.

If you have any tips on troubleshooting from here, I'd appreciate any help I can get, otherwise I will continue to poke around in the logs and see if anything sticks out, but it has been a handful of hours into this issue and I haven't been able to find anything to point me in the right direction beyond stripping the season indicator as a hack to stop it from being mislabeled as a special. If its just a regex issue I can try to stumble my way through that as well.

**Comment by churlkun** [comment]
Adding `DDP2.0` to the `WHACK_PRE_CLEAN_RAW` list fixed the issue in both of the cases. Not sure if that was the actual problem or not, but FWIW it worked.
