### ISSUE TITLE
Please document how to use season-eps renumbering

### ISSUE THREAD

**Issue by efalsken** [ZeroQI/Absolute-Series-Scanner#440]
The readme does not have an example of how to renumber episodes. Just a reference to positive/negative offsets.

I could not get this to work:

```
Oreimo (2010) [anidb-7525]
Oreimo 2 (2013) [anidb-9134-s1-e-15]
    S02E16-Blah Blah Blah.mkv -> S01E01-Blah Blah Blah.mkv
```

**Comment by ZeroQI** [comment]
Advanced modes
If the season and/or episode numbers of your files don't match up with the AniDB or TVDB episodes, you can manually specify the season and the episode offset in the parent folder name.

The following suffixes are supported:

-sY] All episodes in the folder are assigned to season Y, but the episode number stays the same.

-eZ] Episode numbers found in the files are adjusted.

For positive offsets, the episode number becomes epNum+Z-1. (Episode 1 will show up as episode Z)
For negative offsets, the episode number becomes epNum+Z. (For Z=-13, episode 14 will show up as episode 1)
-sYeZ] The effects of the options above are combined.

Syntax: [anidb-9134-s1e-15] > S02E16 seen as S01E01.
No change needed to documentation, combined season episode syntax -sYeZ indicated, with negative offset possible. Cannot work if putting '-' before the 'e'
