### ISSUE TITLE
How do we get Plex to use an updated `tvdb4.mapping` file?

### ISSUE THREAD

**Issue by sgtsquiggs** [ZeroQI/Absolute-Series-Scanner#443]
I've made changes to episode -> season mapping in a `tvdb4.mapping` file but so far I cannot get get Plex to refresh without renaming the series parent folder (rename to blah then rename back).

**Comment by ZeroQI** [comment]
Yeah scanner results are cached, you need to change folder content to rescan, or do a Plex dance. Please refer to Exhibit 1 in readme
