### ISSUE TITLE
Arslan Senki (2016) OVAs are inserted in the wrong locations when using anidb4

### ISSUE THREAD

**Issue by CommanderBubble** [ZeroQI/Absolute-Series-Scanner#447]
## Platform

Operating system and version: Windows 10
Plex version: 1.32.5.7328

## Expected Behavior

with absolute episode order selected, the OVAs 1 and 2 from Arslan Senki (2016) should be inserted before episode 11 and 18, respectively, of Arslan Senki (2015) season 1. this information is correct on TVDB.com for [OVA 1](https://thetvdb.com/series/the-heroic-legend-of-arslan-2015/episodes/5715683) and [OVA 2](https://thetvdb.com/series/the-heroic-legend-of-arslan-2015/episodes/5715684). The `airsbefore_episode` information is also correct in `series_en.xml` in the TVDB folder.

## Current Behavior

the OVAs are inserted after each season

## Steps to Reproduce

1. Requires the pending (at time of report) commit in [Anime-Lists](https://github.com/Anime-Lists/anime-lists/pull/336)
2. add the required episodes - [Dummy Files.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/12207321/Arslan.Senki.2015.zip)
3. use anidb4 to force the id's for Season 1 and the sidestory season
4. select absolute episode order for the show
5. play the season and look at the episode queue

![Specials](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/8016060/5ac9f58f-b50e-4888-ac5a-c92ea778e3e9)
![Queue](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/8016060/7299c03f-c1ff-4b60-824f-4c7638660575)

**Comment by EndOfLine369** [comment]
No issue seen here.
- anidb 12113 is a side story and not a sequel series for all the anidb series using the same tvdb series. so it will stay in the 'specials' s0. It will not be put into its own season around the tvdb seasons. https://anidb.net/anime/12113/relation/graph
- Your play queue is ordering them correctly based on air date.
- You are expecting "HAMA" (not ASS) to know/utilize 'airsbefore_episode' from tvdb somehow. It does not.

**Comment by CommanderBubble** [comment]
to address in order:
* i'm not expecting them to show up in a season around the others, they belong in specials, i agree there.
* the queue is set to show them based on absolute order, not aired order, so i would expect to see them inserted in the correct location in the queue
* something in the HAMA/ASS chain understands for other shows when to insert specials, even ones from side adventures, such as [Attack on Titan](https://anidb.net/anime/9826/relation/graph) - the OVAs are inserted into the queue at the appropriate time. if this is not HAMA/ASS, what is doing this?
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/8016060/f697030b-2187-46a8-9c23-b471287a904d)
