### ISSUE TITLE
One Piece Arc Naming and Art

### ISSUE THREAD

**Issue by buckeyez** [ZeroQI/Absolute-Series-Scanner#448]
## Platform
Operating system and version: Ubuntu 22.04.2 LTS
Plex version: 4.111.1

## Expected Behavior
Should list arc names and correct art based on online mapping for One Piece.

## Current Behavior
It is breaking up the episodes according to the online mapping, but it is not setting the Arc Name or the correct Art.
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/16466948/875a2d2b-585f-49c2-a4b3-779010537ea2)

## Steps to Reproduce
1. Installed Hama & ASS
2. Restarted Plex Service
3. Scanned Library

### Folder Structure
media
-- Anime
---- One Piece [tvdb4-81797]
------ One Piece - EXXX.mkv

[One Piece [tvdb4-81797].agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/12222928/One.Piece.tvdb4-81797.agent-update.log)
[One Piece [tvdb4-81797].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/12222929/One.Piece.tvdb4-81797.agent-search.log)

**Comment by ZeroQI** [comment]
Should list arc names => season title not supported agent side by plex
Correct art based on online mapping for One Piece => Did you specify tvdb4 by renamng an already existing in plex one piece series ?

**Comment by buckeyez** [comment]
> Did you specify tvdb4 by renaming an already existing in plex one piece series?

Can you elaborate, rename what to what in the series?

For more context, I had added it as is (listed above) after installing the plugin. I am willing to try to rename something, with further clarification.

**Comment by buckeyez** [comment]
> season title not supported agent side by plex

Also, just curious, if it is not supported, why are the Arc names listed/required in the mapping?

**Comment by buckeyez** [comment]
One last thing, semi related, I had `Hunter x Hunter` already on the Plex. I renamed everything to be just `EXXX` from `SXXEXXX` and removed the dir structure, when I rescanned, it didn't not break it into Arc's but instead treated it as one big anime without seasons or arcs. Any thoughts on that?

**Comment by ZeroQI** [comment]
It is listed to know how arcs are splitted as sometimes users don't know or can't agree.
I did want season title support but Plex did not allow that to be set by metadata agents, my code is ready for it...

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/tvdb4.posters.xml

Are poster showing by default matching the table below? If so working as designed...

```
<posters tvdbid="81797" name="One Piece">
    00|https://vignette.wikia.nocookie.net/onepiece/images/2/2f/Volume_2.png
    01|https://vignette.wikia.nocookie.net/onepiece/images/7/75/Volume_3.png
    02|https://vignette.wikia.nocookie.net/onepiece/images/6/6b/Volume_10.png
    03|https://vignette.wikia.nocookie.net/onepiece/images/4/4e/Volume_12.png
    04|https://vignette.wikia.nocookie.net/onepiece/images/4/4e/Volume_15.png
    05|https://vignette.wikia.nocookie.net/onepiece/images/4/45/Volume_16.png
    06|https://vignette.wikia.nocookie.net/onepiece/images/5/5d/Volume_23.png
    07|https://vignette.wikia.nocookie.net/onepiece/images/e/ef/Volume_25.png
    08|https://vignette.wikia.nocookie.net/onepiece/images/5/52/Volume_30.png
    09|https://vignette.wikia.nocookie.net/onepiece/images/2/2b/Volume_32.png
    10|https://vignette.wikia.nocookie.net/onepiece/images/e/e6/Volume_33.png
    11|https://vignette.wikia.nocookie.net/onepiece/images/b/bd/Volume_37.png
    12|https://vignette.wikia.nocookie.net/onepiece/images/d/d2/Volume_44.png
    13|https://vignette.wikia.nocookie.net/onepiece/images/c/cc/Volume_46.png
    14|https://vignette.wikia.nocookie.net/onepiece/images/4/43/Volume_51.png
    15|https://vignette.wikia.nocookie.net/onepiece/images/8/84/Volume_53.png
    16|https://vignette.wikia.nocookie.net/onepiece/images/4/40/Volume_54.png
    17|https://vignette.wikia.nocookie.net/onepiece/images/0/04/Volume_57.png
    18|https://vignette.wikia.nocookie.net/onepiece/images/d/d8/Volume_60.png
    19|https://vignette.wikia.nocookie.net/onepiece/images/7/71/Volume_63.png
    20|https://vignette.wikia.nocookie.net/onepiece/images/e/ee/Volume_68.png
    21|https://vignette.wikia.nocookie.net/onepiece/images/e/e6/Volume_76.png
    22|https://vignette.wikia.nocookie.net/onepiece/images/8/86/Volume_81.png
    23|https://vignette.wikia.nocookie.net/onepiece/images/f/f1/Volume_87.png
    24|https://vignette.wikia.nocookie.net/onepiece/images/3/3b/Volume_90.png
    25|https://vignette.wikia.nocookie.net/onepiece/images/1/1f/Volume_92.png
  </posters>
```

For Hunter d Hunter, folder content didn't change, so scanner ould work on cache, only filenames did so it hit a scanner bug, remove or add an episode on the folder and re-scan, or do the plex dance

**Comment by buckeyez** [comment]
Oh you know what, it is showing the art. I assumed 0 would be 1, but is 0 for specials?

**Comment by ZeroQI** [comment]
Yes. Season 0 is for specials

**Comment by buckeyez** [comment]
> For Hunter d Hunter, folder content didn't change, so scanner ould work on cache, only filenames did so it hit a scanner bug, remove or add an episode on the folder and re-scan, or do the plex dance

Removing an ep did not cause a change. Is there a simple way to clear the cache for a single anime? the `plex dance` is rather time consuming.

Btw thanks for your time and help, and putting this plugin together.

**Comment by ZeroQI** [comment]
If you did remove the season it puts all in season 1... I miss seriea toldername or path from library root to assess

**Comment by buckeyez** [comment]
I just renamed the dir to include the tvdb4 id, and rescanned, that seemed to work

**Comment by buckeyez** [comment]
thanks again for everything, do you have donations setup?

**Comment by ZeroQI** [comment]
Yep, in the readme at the bottom
