### ISSUE TITLE
Custom Mappings without a DB

### ISSUE THREAD

**Issue by buckeyez** [ZeroQI/Absolute-Series-Scanner#449]
Is it possible to do custom mappings without a DB to reference? For example, I am adding One Pace to my library, I would ideally like to be able to simply create a `mapping` and `poster` file respectively and fill in the data and it still create the arcs and use the posters I provided. Is this already possible?

**Comment by ZeroQI** [comment]
You can use tvdb4 mode and use season folders or sxxexx format and it won't use default tvdb4 mappings, or use abs numbering and custom tvdb4 mapping file locally

You can put season posters lixall and local media assets will load them

**Comment by buckeyez** [comment]
Okay cool - I will give this a try.

Can you elaborate on, or provide a reference to what you mean?
> You can put season posters lixall and local media assets will load them

**Comment by ZeroQI** [comment]
Locally*
https://support.plex.tv/articles/200220717-local-media-assets-tv-shows/

**Comment by buckeyez** [comment]
There does not appear to be an option in the HAMMA agent to allow use of local assets. I followed what you have in the ReadMe and the Plex docs. The posters do not show up and the theme music I placed in the series does not work either.

**Comment by ZeroQI** [comment]
This is a separate plex secondary default agent.
Check your agent list, it needs to be enabled
