### ISSUE TITLE
Help Install on NAS with OMV and docker compose

### ISSUE THREAD

**Issue by NicolasXIII** [ZeroQI/Absolute-Series-Scanner#451]
Hi, i have mount a NAS in OMV 6. In this NAS i have created a media center using docker compose inside of OMV. Im relative new in this world. I want to unify the libraries of anime films and anime series.

- https://github.com/ZeroQI/Absolute-Series-Scanner
- https://github.com/ZeroQI/Hama.bundle

But there are not working, and the scanner doesnt show in the list of scanners in the series library.
I have follow the steps in the documentation from github, and i wondering if... maybe is it problem of the plex image cant execute python? Because i follow the steps usings the folder system and i also try to connect by putty with the NAS and try the commands.

**Comment by ZeroQI** [comment]
Be careful of new Plex type libraries, incompatible with python scanner/agents.

**Comment by ZeroQI** [comment]
Scanner is OS agnostic so could be:
- you selected a new type library at creation and they can't manage third party agent and scanners
- python based as the custom scanner runs in python
- Python library based but you would get system errors
