### ISSUE TITLE
Freebox Delta

### ISSUE THREAD

**Issue by DjapsSparrow** [ZeroQI/Absolute-Series-Scanner#453]
"Hi everyone,

I would like to be able to install the agent on my Plex, which is installed on my Freebox Delta. So in command prompt.
Any idea how to do it? Is it possible?
Thank you!"

**Comment by ZeroQI** [comment]
That is the scanner github
The agent I'd OS agnostic, you generally have to find the fight Plex folder to create the agent folder in and drop the files
There are few ways to install Plex on a Freebox delta in VMs and did not provide which so impossible to answer

You do not know how to install any custom metadata agent and didn't follow the readme for which medium to use, this is clearly an use case for which the Plex forum is recommended as I am pretty sure there are other users with free as French fiber provider...
