### ISSUE TITLE
Combine cours into shows, but leave seasons as separate shows.

### ISSUE THREAD

**Issue by Sawtaytoes** [ZeroQI/Absolute-Series-Scanner#455]
**Is your feature request related to a problem? Please describe.**
I'm currently using the default `[anidb-X]` designation, and it splits cours. For instance "Attack on Titan - The Final Season" is split into 3 separate shows: "Attack on Titan - The Final Season", "...(2022)", and "...(2023)". From a watching perspective, I'd rather they all be considered part of a "The Final Season" show because that's how I'd expect to watch them.

So while Collections make it easy to watch them in chunks, none of the other ID designations seem to combine them in a logical way so they act like a single show with a single season.

**Describe the solution you'd like**
I'd like a way to categorize shows with a year behind the name as part of the same season.

That doesn't work 100% of the time though. A show like One Punch Man is clearly 2 seasons, but the second season is only called "One Punch Man (2019)" whereas the 3rd entry is called "One Punch Man 3".

Re:ZERO is another case where it'd combine all seasons into a single season whereas it's actually 2 seasons: "Re-ZERO - Starting Life in Another World" and "Re-ZERO - Starting Life in Another World (2021)". Currently, the 2022 season is a separate show.

**Describe alternatives you've considered**
I've considered putting them in the same directories and adding either a season designation or increasing the episode numbers, but in both cases, I get no metadata.

**Additional context**
It'd be nice to combine similarly named shows with multiple cours:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/7913a3ed-b401-49b2-9c36-fbaa3caf00c1)

**Comment by ZeroQI** [comment]
Did you ever consider tvdb numbering?

**Comment by Sawtaytoes** [comment]
You mean that `tvdb4.mapping` file? Or something else? I've been scouring the docs for hours, but I'm not really sure what everything does or how it's related.

**Comment by ZeroQI** [comment]
Tvdb4 is for using any season arrangement and episode with absolute numbering

Here you could use tvdb numbering
Attack on titan [tvdb-xxxxx] / Season 4 / as per TheTVDB numbering. 

https://thetvdb.com/series/attack-on-titan/seasons/official/4

Pick anidb or tvdb numbering and stick to it... 
Tvdb is clearly better here.

**Comment by Sawtaytoes** [comment]
As, so you're saying the `tvdb` method combines them whereas the `anidb` method would keep them separate?

**Comment by Sawtaytoes** [comment]
I decided to keep with aniDB. It provides the more-accurate way to watch a show as single-season series mean I can name the seasons.

Even though it doesn't make sense for Re:Zero because of the two cours (separate aniDB entries) for Season 2, it works for just about every other series.

For instance, there's a Re:Zero movie called "The Frozen Bond" which comes after Season 1. In TVDB ordering, that movie would be 1 episode in Season 2 and all of the released "Season 2" would be listed as Season 3. Very confusing because you can't rename Seasons in Plex.

If I could make "The Frozen Bond" episode 26 (or 27) in Season 1, that would fix the issue for _this_ use case too, but it's hacky. The movie is a completely separate item that should be in the Collection, not the Season (unless I can name seasons).

It'd be nice to combine the two cours for Season 2, but I understand that without TVDB4 mapping, I can't easily do that. And it doesn't solve my issue of creating my own watch order with OVAs and episodes in a season together: https://github.com/ZeroQI/Absolute-Series-Scanner/issues/454. Solving that issue, I think I'd be able to combine the two cours into a 1-season series pretty easily rather than having a `(2020)` and `(2021)`. Variant.

This ticket is still closed, but I wanted to follow up.

**Comment by ZeroQI** [comment]
Thanks for the document post.
Only XBMC allow specials mapped in between episodes
One could use a collection and anidb but the order cannot be indicated in Plex although it could in the foldername with [01] for example for sorting the order, albeit not reflected in Plex

You have to follow either TheTVDB or Anidb and work from there... The forum had entries about the monogatary series which is the most complex to sort. You should start checking this, and see how users got around sorting it, but ultimately I cannot be responsible for Plex limitations... I think I did more for flexibility than any other agent...

**Comment by Sawtaytoes** [comment]
You've definitely added a ton of useful flexibility.

For reference, I believe the issue with Monogatari is this one: https://github.com/ZeroQI/Absolute-Series-Scanner/issues/230

Looking through it now.
