### ISSUE TITLE
"Refresh Metadata" removes customizations

### ISSUE THREAD

**Issue by Sawtaytoes** [ZeroQI/Absolute-Series-Scanner#457]
## Platform

Operating system and version: Linux Docker container `14.0.5`
Plex version: `1.32.6.755`

## Expected Behavior

When clicking "Refresh Metadata", it should leave my customizations alone once a show has been added.

Plex default scanners also do auto-collections, but once that media has been added, it stops creating auto-collections and messing with items inside even if I click "Refresh Metadata". They must have some sort of caching involved like an "already added" flag.

## Current Behavior

I clicked "Refresh Metadata" on my entire anime library, and Absolute Series Scanner moved everything out of the places I put them and out of the order I used.

Now I have a situation where I have all these Collections with nothing in them. This wouldn't be an issue if all the automatic-collections were correct, but they're not.

There are other situations where auto-collections are wrong:
1. **Patlabor** OVAs in the wrong collection. They should be in the same collection as the movies, not the TV show as they're part of the movie canon.
2. **Broken Blade** (Break Blade) has the TV show and movies in the same collection, but they're separate universes.
3. **Vision of Escaflowne** and the movie are unrelated universes, but they're in the same collection.
4. The **Gintama** collection doesn't include the TV series, only the movies. The movies are canon and need to be slotted between seasons. Absolute Series Scanner doesn't have seasons for Gintama in collections though.
5. The ordering in **Armored Troopers Votoms** is wrong, and it's supposed to be chronological.
6. The 6 OVA compilations of the original **Armored Troopers Votoms** show are out of order with Vol. II happening first, then 4 other ones in random order, and then Vol. 1 last.
7. The **Fullmetal Alchemist: Brotherhood movie** is in the Fullmetal Alchemist (2003) collection, but it's part of the Brotherhood universe and should be watched after that series completes, not the 2003 version.
8. The **Mobile Suit Gundam** collection only includes 3 of the UC series and leaves 5 of the rest outside of a collection.
9. **Legend of the Galactic Heroes: Die Neue These** is not in a collection, yet I have 3 seasons of the show.

## Steps to Reproduce

1. Customize shows by moving them around to different collections and rename collections.
2. Click "Refresh Metadata" on the anime library using Absolute Series Scanner.
3. All customizations will be reset back to the original auto-collection values from Absolute Series Scanner.

## Additional information

Screenshots of some of the situations I talked about:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/a494db71-f1cf-465e-8bc1-b168e3b01d44)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/054a64eb-9502-44ab-a851-719c9ce0e19c)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/63c58d3e-ca25-4d19-aaf3-c031b473703c)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/dd5004c6-cf64-435b-878c-cba1b2138f3f)

**Comment by ZeroQI** [comment]
https://support.plex.tv/articles/201273953-collections/
- Collection is a string associated by the agent or Plex to the series entry, nothing to do with a custom scanner. Renaming the collection string on one serie didn't change it on the other series in that collection
- HAMA agent can use grouping folders as collection, or movie collections, depending the agent settings, please check them and select hte desired metadata sources order for 'collection' field...
- This has nothing to do with the scanner in any way
- Collection unless using grouping folders (which i can't recommend as scanner can't use cache and need to all content at every scan, which takes a long time, and it is a hack to be honest) will not be perfect. It relies on the xbmc movie collection mainly and this is far from perfect.

Closing as collection is a metadata field and has nothing to do with the scanner, the agent is responsible for selecting

**Comment by Sawtaytoes** [comment]
When I create or rename a collection in Movies using the Plex scanner, it doesn't get changed and no movies movie around when clicking "Refresh Metadata".

I renamed the Collection for "Broken Blade" and also created one for the movies, but when I clicked "Refresh Metadata", it moved them both into a new collection called "Broken Blade (2014)". Which is actually wrong because the movies are from 2010-2011.

I also moved the Patlabor OVAs into the correct collection, but clicking "Refresh Metadata" moves them back to the wrong collection.

**What are grouping folders?** Should I be putting my shows into root folders? Would that form them into the correct collections?

With the Plex scanner, that doesn't form collections based on the folder structure. If I add a movie to a top-level folder, it _won't_ add that movie to a collection.

**Comment by ZeroQI** [comment]
The scanner has nothing to do with the collection, it gives the series name, season and ep number for episodes, maybe the year and temporary episode title, but nothing to do with collections, the field of data given to Plex by third party scanners doesn't include it. 

> When I create or rename a collection in Movies using the Plex scanner
- That phrase is a lie, A scanner can be ran, but has nothing to do with collections. This word doesn't mean what you think it means...
 
Should I be putting my shows into root folders: That is a requirement for any metadata agent based system, including Plex. I did add flexibility, but that is the basic for naming convention yes. 

Scanner do not have anything to do with collections, at least for ASS
You still havent't checked the HAMA agent settings, and the series specific HAMA agent logs would show the collection field used and why, and the metadata source order for the 'collections' metadata field.

**Comment by Sawtaytoes** [comment]
Ah! Now I get it. So this is a HamaTV issue. Understandable.

And I'm assuming this is the setting I need?
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/beb2afb3-0b37-4d95-ba8d-3a69aed4dda7)

I can make an issue on HamaTV, but from what you said, it's a settings and configuration issue. My bad.

**What should I be setting here?** Looks like `local` uses local folders then all the others.

I like how it will automatically create collections for me, but I'd prefer that once a media file is added, it doesn't recreate that collection again each time I click "Refresh Metadata". I'd like to be able to customize HamaTV in Plex and have it respect the places I've moved shows.

---

For anyone looking at this having the same issue:
1. Go to Plex settings.
1. Click Agents:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/e4f87db4-64d7-45be-ad11-afce210e9b77)
1. Click Shows and HamaTV:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/77b321ad-9d9e-4d67-a869-56cef09f92c3)
1. Click the settings icon:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/2c3d1a05-6171-408e-ba85-3bc5ab9481b6)
1. Scroll down to this setting:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/beb2afb3-0b37-4d95-ba8d-3a69aed4dda7)

**Comment by ZeroQI** [comment]
For some settings to be accurate, you need to wipe the old setting or you could get multiple collections when the data changes...
Here you may want nothing instead for example...
