### ISSUE TITLE
Mushoku Tensei Season 2 Episode 0 not mapping properly anymore with anidb change.

### ISSUE THREAD

**Issue by randomdice101** [ZeroQI/Absolute-Series-Scanner#458]
Hello, I believe this is the correct place to report this.

While Mushoku Tensei [anidb-17236] was airing, episode 0 was set as special 1 in anidb with episodes 1-12 following and all worked well. Now a mod has changed this and other mods agreed (its being handled similar to Chaos;Child apparently) S1 was changed to Ep1 with E1-E12 being shifted to E2-E13. this causes the scanner to fetch metadata for the wrong episode. TVDB has episode 0 mapped to S00E02 with the other S2 episodes being set to S02E01-E12. When refreshing metadata in plex it will show episode 0 with proper episode 1 title and then have an "Episode 13" since that is unmapped. I had to manually rename the files to avoid this issue but I'm hoping the scanner can be fixed to handle this and I don't need to manually handle it anymore.

**Comment by ZeroQI** [comment]
Not surprised, mini seasons are 13 episodes, the pilot was considered a Pilot but realistically it was episode one...
You have to number as per the metadata source numbering, AniDB in this case.
Working as designed. It's not even a scanner issue. Please refer to readme "Exhibit 1"

**Comment by randomdice101** [comment]
No what I'm saying is its not mapping properly. I have it named as the source using anidb'o'matic. This is the issue I'm getting please don't close it. its not mapping properly.
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/4016932/dc678b39-11b6-44ef-90fb-2bb0f96279cf)
Included is the file names. this is how it was while airing. now with the anidb names properly this is what I get:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/4016932/32f31267-c8ec-40e6-b0eb-f55d47a82c55)
Please note the episodes are all shifted by 1. the names come from tvdb: 
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/4016932/da64e4c2-d534-45c0-9ec3-a7cd664c38ef)
This should be Ep 1 title: 
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/4016932/f7c179a9-1bc9-4cfb-9c79-d7264ff9f00c)

**Comment by randomdice101** [comment]
Adding a "-e-1]" to the folder name "fixes" it but I don't think being forced to use an advance feature is how it should work by default. Also your RTFM tax is Exhibit A not Exhibit 1
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/4016932/cc570489-05ae-45b3-a7c4-5a1ba0c8fc2e)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/4016932/309ba625-b1af-44c8-8f79-5021b8ad1e28)

**Comment by randomdice101** [comment]
Looks like anidb is reverting the change another mod decided that so this issue is not needed anymore. sorry

**Comment by ZeroQI** [comment]
https://anidb.net/anime/17236 - 1-12 + SP1-4
https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-master.xml
https://thetvdb.com/series/jobless-reincarnation-it-will-be-all-out-if-i-go-to-another-world/seasons/official/2

I am sorry but you say S1 and 1-12 on anidb got moved to 1-13 but it list still 1-12 and 'I want to tell you' half season finale is tvdb s02e12 and AniDB E12 so you make no sense to me

Mapping seem to correspond, anidb Season 1 mapped to tvdb Season 2, only anidb S1 is mapped to tvdb s00e02

All is consistent, and seem to match your filenames. Seem like you have an outdated cached data issue

**Comment by randomdice101** [comment]
Hey sorry about that, here is the comment they just reverted the change as of an hour and a half ago https://anidb.net/admin/creq/17625940#msg35518510 it was E1-13 but they just reverrted back to S1 and E1-12.

**Comment by ZeroQI** [comment]
Had they left it as it was, the xml mapping file would have had to be adjusted with an offset as it would have mapped sideways between tvdb and AniDB... And up to a week delay in updating cached files from anidb and tvdb, but still not an agent or scanner issue... If one side change numbering the xml mapping file need to be altered

**Comment by randomdice101** [comment]
Ah okay so who has to update those xml mapping files? Sorry didn’t want to cause headaches.

On Oct 12, 2023, at 8:35 AM, Benjamin Brisson ***@***.***> wrote:

﻿

Had they left it as it was, the xml mapping file would have had to be adjusted with an offset as it would have mapped sideways between tvdb and AniDB... And up to a week delay in updating cached files from anidb and tvdb, but still not an agent or scanner issue... If one side change numbering the xml mapping file need to be altered

**Comment by ZeroQI** [comment]
You submit a change request to https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-master.xml as a pull request or in the bug report like you did there.
It helps to have anidb and tvdb links as mapping need to be checked.
If the mapping is already in the xml format required it will go quicker.

It used to be scudlee's anime-lists but not updated 3 years so sven7 is looking after it for the community, keeping Hama alive and accurate

**Comment by randomdice101** [comment]
Thank you, if another mapping issue occurs I’ll be sure to report it there. Sorry again.

On Oct 12, 2023, at 9:24 AM, Benjamin Brisson ***@***.***> wrote:

﻿

You submit a change request to https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-master.xml as a pull request or in the bug report like you did there.
It helps to have anidb and tvdb links as mapping need to be checked.
If the mapping is already in the xml format required it will go quicker.

It used to be scudlee's anime-lists but not updated 3 years so sven7 is looking after it for the community, keeping Hama alive and accurate
