### ISSUE TITLE
How do I mark "Other" shows from aniDB?

### ISSUE THREAD

**Issue by Sawtaytoes** [ZeroQI/Absolute-Series-Scanner#467]
I was looking for Psycho-Pass Extended Edition on aniDB, and it's not categorized as a separate release of the first season. Instead, the episodes show up as "Other" in the [Psycho-Pass](https://anidb.net/anime/9127) season:

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/82f6bd81-2eb1-414b-9017-01a67926e1d4)

What am I supposed to do with these to get metadata? Do I list them as specials or as Season 2? Or do I simply not include the original 22 episodes and only include the new edit 11?

Trying to figure out the best way to get metadata for these.

**Comment by ZeroQI** [comment]
Force anidb id for the series
Label them O01 New Edit 1.ext, anidb numbering is supported by ASS with op/ed as well, check the readme.

Psycho-Pass [anidb-13345] /Specials/O01 New Edit.ext

**Comment by Sawtaytoes** [comment]
Ah! Now I understand this chart:

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/e2b8935c-4155-484b-8e06-9d0aa24b1dba)

It all makes sense now thanks! Instead of using a separate `Specials/` folder, I can make them episodes 400+.

**Comment by ZeroQI** [comment]
Specials or season 0 folder ans Oxx or ep 401+, or S00e401+ directly
