### ISSUE TITLE
Anime series titles containing the word "Special" get treated as specials, ignoring given season and episode numbering.

### ISSUE THREAD

**Issue by Jadrie** [ZeroQI/Absolute-Series-Scanner#469]
## Platform

Operating system and version: Windows 11
Plex version: Version 1.32.8.7639 

## Expected Behavior
Title 'A Returner's Magic Should be Special (2023) - S01E01' - should be treated as Season 1 Episode 1. 
This works correctly as intended if the japanese title of the series name is used in the filename:  'Kikansha no Mahou wa Tokubetsu Desu (2023) - S01E01' 

## Current Behavior
The file is mapped as a special, episode 1.
[Kikansha no Mahou wa Tokubetsu Desu {imdb-tt28313387}.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13404630/Kikansha.no.Mahou.wa.Tokubetsu.Desu.imdb-tt28313387.filelist.log)
[Kikansha no Mahou wa Tokubetsu Desu {imdb-tt28313387}.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13404631/Kikansha.no.Mahou.wa.Tokubetsu.Desu.imdb-tt28313387.scanner.log)

## Steps to Reproduce

1. Name an video file 'A Returner's Magic Should be Special (2023) - S01E01 - 001 - Destruction [HDTV-1080p][10bit][AV1][AAC 2.0][JA]-SanKyuu.mkv'
Allow Plex to match the metadata, it will sort into Specials

2. Rename the file 'Kikansha no Mahou wa Tokubetsu Desu (2023) - S01E01 - 001 - Destruction [HDTV-1080p][10bit][AV1][AAC 2.0][JA]-SanKyuu.mkv'
3. Allow Plex to rescan the series- the file will correctly map to Season 1, Episode 1.

## Additional information

Kind of an odd one here, wonder if something can be done with a regex to detect a year after the title to determine what's part of the show name?

**Comment by ZeroQI** [comment]
Series name: Kikansha no Mahou wa Tokubetsu Desu
Forced id: {imdb-tt28313387}, 
Season folder: Season 01
Series name in filename: A Returner's Magic Should be Special (2023)
Episode numbering: S01E01 - 001 - 
Episode title: Destruction
Tag not in square brackets: -SanKyuu.mkv

Had you matched both series title, you wouldn't have had the issue.

**Comment by Jadrie** [comment]
I had tried it both ways - renaming the folder and the episodes was the only way I could get it to correctly map the episodes to their titles.

the absolute numbering was an experiment as well to try and get it to map. I can pull that out.

Preferably, I'd like to use the english series title, as Sonarr defaults to english titling. I'm going back in after it downloads and renaming them manually to correct the match.

**Comment by Jadrie** [comment]
let me swap titles back to english for episode and series, and eliminate the absolute numbering. I'll throw you some fresh logs with that setup

**Comment by ZeroQI** [comment]
Please do

**Comment by Jadrie** [comment]
well, nevermind! I renamed it back and it's all working as it should. I'm not sure what happened before that it was throwing it all as specials, but reversing all the changes to stock seems to have done the trick.

 Thanks for looking at it, apologies for the false alarm!

**Comment by ZeroQI** [comment]
If you rename files without changing the folder actual file content, scanner cache is used by Plex, resulting in no scanner changes...

**Comment by Jadrie** [comment]
so best practice when correcting scan cache issues is to what, move the files out, rename then move back in? would that retrigger a fresh scan?

**Comment by ZeroQI** [comment]
Remove or add a file si the folder content changes as renaming files do not change the folder content

**Comment by Jadrie** [comment]
OK, I'll give that a try next time if this recurs, but I think I'm all set for now - Thanks for the great scanner!
