### ISSUE TITLE
Absolute Series Scanner not sorting into Seasons

### ISSUE THREAD

**Issue by Snuffy2** [ZeroQI/Absolute-Series-Scanner#470]
I recently setup Absolute Series Scanner along with the YouTube Agent. I am using TubeSync. I am unable to sort out what is wrong, but the videos aren't sorting into seasons as expected. It is happening for all 4 of the Playlists I have setup.

TubeSync Naming Format: `{source_full} - s{yyyy}e{mm}{dd} - {title_full} [{key}] {resolution}-WEBDL.{ext}`

## Platform

Operating system and version: MacOS 14.1.1
Plex version: 1.32.7.7621

## Expected Behavior

Since it is adding `s{yyyy}e{mm}{dd}` to the filename, each year should be its own season.

## Current Behavior

It is putting all of the videos into Season 1.

Logs are below. There was nothing in `[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.youtube/DataItems`
![2023-12-01_14-29-40 749](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/6526076/1966e190-4dea-427b-9741-c4fb8f962aee)

In `Logs/Plex Media Server`:
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13531349/Plex.Media.Scanner.log)

In `ASS Scanner Logs`:
[_root_.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13531352/_root_.scanner.log)
In `YouTube` log folder: [Hot Ones.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13531371/Hot.Ones.scanner.log)
In `YouTube` log folder: [Hot Ones.filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13531374/Hot.Ones.filelist.log)
In `YouTube` log folder: [_root_.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13531376/_root_.scanner.log)

In `Logs/Plex Media Server/PMS Plugin Logs`:
[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13531354/com.plexapp.agents.youtube.log)
[com.plexapp.agents.localmedia.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13531358/com.plexapp.agents.localmedia.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13531369/com.plexapp.system.log)

## Additional information

![2023-12-01_14-13-04 048](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/6526076/d8cdbd26-e612-42a2-9148-983425e8f46b)
![2023-12-01_14-13-46 102](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/6526076/9e4f08f7-8edf-40c2-9a2d-eb17f80d3b01)
![2023-12-01_14-14-19 487](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/6526076/cd5c4a42-7ab3-48ca-9ea9-d4ce6610232a)
![2023-12-01_14-17-00 143](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/6526076/fda93e5a-e5c4-4a1e-a1d5-b3833ae25de7)
![2023-12-01_14-17-31 049](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/6526076/15d33f31-52b7-4419-b934-3414db2d4a9c)
![2023-12-01_14-19-30 569](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/6526076/ff8e07ad-58f3-45f8-821b-abb1da9d45b3)
![2023-12-01_14-22-19 835](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/6526076/25446f28-1f5d-49b5-b20a-721da673abef)

**Comment by ZeroQI** [comment]
Playlist id so single season.
Try youtube2 forced id instead
