### ISSUE TITLE
Sometimes specials use TVDB metadata (rather than aniDB)

### ISSUE THREAD

**Issue by Sawtaytoes** [ZeroQI/Absolute-Series-Scanner#472]
## Platform

Operating system and version: Debian Linux (TrueNAS-SCALE-23.10.0.1)
Plex version: 1.32.8.7639

## Expected Behavior

It should show the aniDB name for specials when using the aniDB "specials" episode numbering from the docs:

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/d735cede-e199-46c0-a160-17336d3c6fae)

## Current Behavior

Getting logs will be hard because it's in a Docker container.

It's showing the TVDB info for specials.

This is what my folder looks like:

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/3def0583-12e7-43c0-82e9-769b2a830789)

This is what Plex shows:

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/2b2401de-6f0c-4ffb-8ad5-a488c5979bf0)

The [aniDB listing](https://anidb.net/anime/98):

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/49cdc4a0-f37c-4039-8710-d75fcff34927)

The [TVDB listing](https://thetvdb.com/series/berserk/seasons/official/0):

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/b4ec0251-98d2-4446-a0d6-681852502f3d)

## Steps to Reproduce

1. Create a `Berserk [anidb-98]/` folder.
2. Add a text file as `Berserk - s00e01 - Episode R0 Recap.mkv` in this folder.
3. Open Plex to your Absolute Series Scanner folder and notice it has the wrong special episode metadata for Berserk (1997).

## Additional information

This is Berserk (1997).

**Comment by ZeroQI** [comment]
Agent settings for episode title missing
You probably have it set to "tvdb" or "?|tvdb"

**Comment by Sawtaytoes** [comment]
It looks like aniDB is first, but I'm also seeing: `AniDB, TheTVDB | TheTVDB, AniDB`. Not sure why it has both variants.

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/71b2da22-2a1f-4aa5-a8c8-497f93c16f36)

**Comment by ZeroQI** [comment]
So
- series title (1st part) is anidb then thetvdb
- episode title (after the pipe '|') is thetvdb then anidb

Working as designed

**Comment by Sawtaytoes** [comment]
I see. So that's what the pipe is for.

When I change it, do I need to Refresh Metadata?

**Comment by ZeroQI** [comment]
Yes. The settings influence the agent behaviour when it rubs, isn't pre-emptive

**Comment by Sawtaytoes** [comment]
The title is correct now, but the description is wrong. Is that a separate setting? I'm not seeing one.

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/c466ac30-3e6d-42ec-8381-57ba20ecf06e)

**Comment by ZeroQI** [comment]
Summary

**Comment by Sawtaytoes** [comment]
Separately, when I clicked "Refresh Metadata", it added shows back into default collections and took them out of my collections.

But I have Collections set to "None":
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/b12bc1ee-86aa-4cf4-9675-bd2e229f3964)

**Comment by ZeroQI** [comment]
Then it's not tge agent doing...

**Comment by Sawtaytoes** [comment]
Examples:

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/30d9ac24-a521-4f3e-9792-23b57f9c010d)

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/4cd6f10d-0a52-4d80-9201-d99a25367d1c)

None of my Shows or Movies do this with the default Plex scanner. This is specific to ASS and HamaTV.

**Comment by ZeroQI** [comment]
Custom per serirs log display all fields used and provided to Plex. You have failex to provide this
New type plex agent (as scanner do not provide metadata nor collections) and do not suport 3rd party agents so you might have secondary agents providing tge collection field
You might have a database corruption
Without logs i xannot help and i am pretty sure that with the setting fir colkection empty tgat Hama did not provide the collection field to plex
You can lock collection field per serie as a workaround

**Comment by Sawtaytoes** [comment]
Found a way to download the logs:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/609f03b0-33a2-4452-ab80-c5cce26f3748)

Plex Server Logs:
[Plex Media Server Logs_2023-12-19_03-52-06.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13714002/Plex.Media.Server.Logs_2023-12-19_03-52-06.zip)

**Comment by Sawtaytoes** [comment]
Even after refreshing metadata, this is what I'm seeing as the description of this R0 episode:

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/9cb45d70-de59-43ae-9d84-d3ebd107b282)

![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/3948069/16e14a2d-6904-4030-ac75-496d6ff342db)

**Comment by ZeroQI** [comment]
Troubleshooting steps in readme clearly state the custom logs location which create per deries logs.
These do not show hama logs, so cannot prove anything

**Comment by ZeroQI** [comment]
So AniDB has no summary for this episode (thisbis usual for anidb) and it used thetvdb episode summary...
What is your point?

**Comment by Sawtaytoes** [comment]
Figured out how to grab the logs:

[HamaTV logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13714347/HamaTV.logs.zip)

Took a while because I had to setup the codeserver, then download each log individually (I could batch it), but then Chrome wouldn't let me, so I used Firefox and got all the files.

**Comment by Sawtaytoes** [comment]
> So AniDB has no summary for this episode (thisbis usual for anidb) and it used thetvdb episode summary... What is your point?

It had a summary. Said "Karaoke / making of". Isn't that the episode description?

**Comment by ZeroQI** [comment]
metadata.seasons[ 0].episodes[  1]
[?] rank: 0, source_title:   AniDB, title: "Episode R0"
[!] title: Episode R0, language_rank 0, rank: 0, len(languages): "3"
[=] title                          Sources:  AniDB,TheTVDB| (AniDB),TheTVDB                               Inside: '['TheTVDB', 'AniDB']'  Value: 'Episode R0'
[=] summary                        Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'These "outtakes" are comedic specials from the DVDs, meant to be watched after t..'
[=] originally_available_at        Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: '1997-01-01'
[=] writers                        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Miura Kentarou'
[=] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Takahashi Naohito'
[=] duration                       Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB', 'AniDB']'  Value: '1440000'
[=] content_rating                 Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'TV-MA'

No episode summary in anidb, it rarely does
No it's not.

No collection field provided for Fafner or Eden of the east, but could have with different settings
