### ISSUE TITLE
Customizable Grouping Folder depth

### ISSUE THREAD

**Issue by BrutuZ** [ZeroQI/Absolute-Series-Scanner#474]
In order to better keep track of seasonals (and make it easier finding what to keep or delete afterwards) I've moved to a sub-folder structure:
```
├── anime-seasonals
|   ├── 2023 Q4
|   |   ├── Goblin Slayer
|   |   |   ├── anidb2.id
|   |   ├── ...
|   ├── 2024 Q1
|   |   ├── Ishura
|   |   |   ├── anidb2.id
|   |   ├── ...
```

The issue with that is I can't set the `anime-seasonals` folder as my library path. Unless I manually set each automatically generated Season subfolder (`2023 Q4`) at the library path, entries get jumbled together or not identified at all due to grouping folders.

Given that, I ask that the depth of the Grouping Folders be either increased of configurable by a variable on top so that this kind of structure is supported?

**Comment by ZeroQI** [comment]
Series folder need to be at the library folder root.
I have added some hacked leeway with grouping folders but this sorting mode is heresy...
If you make the 2003 Q4 type folders transparent folders however, this ignominy of a naming convention should work however... '[2003 q3] Ark' for example...

**Comment by BrutuZ** [comment]
There's a method to the madness, I swear 😂
This makes it easier to pick what to delete and what to move to the long-term storage that does follow the `<root>\<title>[\<season>]\<files>` scheme after every season or two.

While subfolders do make things more organized, I guess I can at least give the prefix compromise a go.
