### ISSUE TITLE
tvdb2/3 not working for Detective Conan

### ISSUE THREAD

**Issue by Roshri** [ZeroQI/Absolute-Series-Scanner#476]
## Platform

Operating system and version: W1022H2
Plex version: 4.121.1 

## Expected Behavior
Adding the series using absolute numbering, with specified guid type and the series should get arranged into seasons

## Current Behavior

Noticed Detective Conan stopped adding episodes a few months ago so I decided to check it.
It's worth noting that the naming is "Detective Conan - Exxxx [subgroup][quality]" since the series has over 1k episodes 
Set up a new test library with only Detective Conan and episodes 01-54 which would cover Seasons 01 and 02.
Added a tvdb3.id file containing the number 72454 on it.
The new library could never pick up the series, at all, always showed empty.
Tried with tvdb2.id file, same result.
Tried renaming the folder including either [tvdb3-72454] or [tvdb2-72454].
Changed to only tvdb and the series showed up, with only one season.

I have no prior logs because the series didn't get picked up before changing to tvdb.

It seems the scanner crashed as the Plex Media Scanner shows this

```
Jan 07, 2024 17:43:32.833 [200] DEBUG - Scanner: Processing directory T:\Test Anime 2 (parent: no)
Jan 07, 2024 17:43:32.839 [200] DEBUG - Scanner: Processing directory T:\Test Anime 2\Meitaintei Conan [tvdb3-72454] (parent: yes)
Jan 07, 2024 17:43:32.851 [200] DEBUG - Directory had 54 files, database had 0 files, can't skip.
Jan 07, 2024 17:43:32.892 [200] ERROR - Error in Python: Running scanner:
Traceback (most recent call last):
  File "E:\Users\Toto Saurio\AppData\Local\Plex Media Server\Scanners\Movies\Absolute Series Scanner.py", line 318, in Scan
    except Exception as e:  Log("xml loading issue"); Log(e)
  File "E:\Users\Toto Saurio\AppData\Local\Plex Media Server\Scanners\Movies\Absolute Series Scanner.py", line 104, in Log
    file.write(("" if no_timestamp else time.strftime("%Y-%m-%d %H:%M:%S") + " ") + entry + "\n")
TypeError: cannot concatenate 'str' and 'SSLError' objects
```

[_root_.agent.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13854913/_root_.agent.log)
[Meitaintei Conan [tvdb-72454].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13854914/Meitaintei.Conan.tvdb-72454.agent-search.log)
[Meitaintei Conan [tvdb-72454].agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13854915/Meitaintei.Conan.tvdb-72454.agent-update.log)
[Plex Media Scanner.3.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13854924/Plex.Media.Scanner.3.log)
[Plex Media Scanner.4.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13854925/Plex.Media.Scanner.4.log)
[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13854926/Plex.Media.Scanner.log)
[Plex Media Scanner.1.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13854927/Plex.Media.Scanner.1.log)
[Plex Media Scanner.2.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/13854928/Plex.Media.Scanner.2.log)

**Comment by ZeroQI** [comment]
"xml loading issue" line 318 making the scnaner crash

**Comment by Roshri** [comment]
Do I have to create this series xml?
Like the tvdb4 mapping xml?

**Comment by ZeroQI** [comment]
Line 104 should be str(entry) instead of just entry
There is an xml downlod error abd the url is not displayed because of the bug above

**Comment by Roshri** [comment]
In that case, is there a way to manually get this xml file so it can scan the series?

**Comment by Roshri** [comment]
After poking around for about an hour I _think_ I managed to make it work.
After reading the error again I noticed the path for the scanner was wrong
`` File "E:\Users\Toto Saurio\AppData\Local\Plex Media Server\Scanners\**Movies**\Absolute Series Scanner.py", line 318, in Scan
    except Exception as e:  Log("xml loading issue"); Log(e)``
 
 It was a REALLY old version, it reports last modified date of 2016. Removed that **Movies** folder and only kept **Series** and it seems to work
 
 I might even try to recreate my old issue #393 to see if this had something to do with it not working
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/29184137/1a5ff190-2042-4acc-9595-a284ee333fee)

**Comment by ZeroQI** [comment]
Well spotted, Imissed it, since ASS is a series scanner so should not have been onstalled as mo ie scanner nor used in a movie library

**Comment by Roshri** [comment]
Closing as this was an 8th Layer issue and I was the problem
