### ISSUE TITLE
Support for TubeArchivist

### ISSUE THREAD

**Issue by AddoSolutions** [ZeroQI/Absolute-Series-Scanner#481]
It'd be awesome if the app supported a more basic naming convention, as used by default with TubeArchivist.

Spec: `[channel_id]/[video_id].mp4`
Ex: `UCL_f53ZEJxp8TtlOkHXXXXX/DB15tXXXXX.mp4`

Note: There are no brackets in the file name, literally just the ID name.

Is this currently possible?

**Comment by ZeroQI** [comment]
TubeArchivist, \-o sets the output parameter for yt-dlp, example:

    -o "Output/Video/%(playlist_title)s
[%(playlist_id)s]/S01E%(playlist_autonumber)s - [%(upload_date)s] -
%(title)s - [%(id)s].%(ext)s


Le dim. 4 févr. 2024 à 21:25, Nick Artman ***@***.***> a
écrit :
