### ISSUE TITLE
One Piece Multiple episodes in 1 file Episode 1000+ displayed as Season 1000+

### ISSUE THREAD

**Issue by potatoxbe** [ZeroQI/Absolute-Series-Scanner#482]
First I have to thank you for this scanner in allowing me to organize my One Piece episodes beautifully. 

I'm using fan made cuts to keep up with One Piece where multiple episodes are cut down to 1 episode, with files named as One.Piece.E900-901.mkv

This has worked perfectly for the over 1000 episodes, being placed into its corresponding Season arcs. But any multiple episodes above 1000 are placed in its own Season arc (should Season 21 Wano arc in this case)
One.Piece.E1002-1003.mkv would be placed in Season 1002
One.Piece.E1065-1066.mkv in Season 1065

Single episodes above 1000 is still in the correct Season. One.Piece.E1055.mkv in Season 21 as it's supposed to.

Placing a Season marker S21 doesn't work, would still recognize the number before the dash as the season. I suppose that's also the purpose of absolute ordering. Any help?

**Comment by ZeroQI** [comment]
Hi, scanner logs needed.
- Seem like you use tvdb4 mode
- Seem like you donnt use ASS sccanner or an old version of it as this was solve couple of years back if i am not listaken

**Comment by potatoxbe** [comment]
Attaching my logs. Yes I'm using tvdb4. Tried to use tvdb3 and renaming the One Piece parent folder, same issue still persist.
Have replaced the Absolute Series Scanner.py and Hama with the latest on the git. Unless I'm missing a step on how to update. 

Another thing to note, I tried to create a new Anime library with ASS and Hama as scanner and agent. The moment the One Piece folder is placed, the Season 1000+ is automatically present.

[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14340092/Plex.Media.Scanner.log)

**Comment by ZeroQI** [comment]
Need the series specific scanner log: *.scanner.log in a library named folder in plex lofs or hamaagent data folder

**Comment by potatoxbe** [comment]
here's the log
[One Piece.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14346101/One.Piece.scanner.log)

**Comment by ZeroQI** [comment]
Most episodes are wrong due to Youtube DateRx triggering

> season: 1084, ep: 1084-10-85
> "One Piece [tvdb4-81797]" s1084e1084-10-85                         "Youtube Date Rx" "E1084-1085" "One Piece E1084-1085.mkv"
> season: 1002, ep: 1002-10-03
> "One Piece [tvdb4-81797]" s1002e1002-10-03                         "Youtube Date Rx" "Ep1002-1003" "One Piece Ep1002-1003.mkv"
> season: 1003, ep: 1003-10-04
> "One Piece [tvdb4-81797]" s1003e1003-10-04                         "Youtube Date Rx" "Ep1003-1004" "One Piece Ep1003-1004.mkv"
> season: 1005, ep: 1005-10-06
> "One Piece [tvdb4-81797]" s1005e1005-10-06                         "Youtube Date Rx" "Ep1005-1006" "One Piece Ep1005-1006.mkv"
> season: 1009, ep: 1009-10-10
> "One Piece [tvdb4-81797]" s1009e1009-10-10                         "Youtube Date Rx" "Ep1009-1010" "One Piece Ep1009-1010.mkv"
> season: 1012, ep: 1012-10-13
> "One Piece [tvdb4-81797]" s1012e1012-10-13                         "Youtube Date Rx" "Ep1012-1013" "One Piece Ep1012-1013.mkv"
> season: 1023, ep: 1023-10-24
> "One Piece [tvdb4-81797]" s1023e1023-10-24                         "Youtube Date Rx" "Ep1023-1024" "One Piece Ep1023-1024.mkv"
> season: 1028, ep: 1028-10-31
> "One Piece [tvdb4-81797]" s1028e1028-10-31                         "Youtube Date Rx" "Ep1028-1031" "One Piece Ep1028-1031.mkv"
> season: 1032, ep: 1032-10-33
> "One Piece [tvdb4-81797]" s1032e1032-10-33                         "Youtube Date Rx" "Ep1032-1033" "One Piece Ep1032-1033.mkv"
> season: 1034, ep: 1034-10-35
> "One Piece [tvdb4-81797]" s1034e1034-10-35                         "Youtube Date Rx" "Ep1034-1035" "One Piece Ep1034-1035.mkv"
> season: 1039, ep: 1039-10-40
> "One Piece [tvdb4-81797]" s1039e1039-10-40                         "Youtube Date Rx" "Ep1039-1040" "One Piece Ep1039-1040.mkv"
> season: 1043, ep: 1043-10-44
> "One Piece [tvdb4-81797]" s1043e1043-10-44                         "Youtube Date Rx" "Ep1043-1044" "One Piece Ep1043-1044.mkv"
> season: 1047, ep: 1047-10-48
> "One Piece [tvdb4-81797]" s1047e1047-10-48                         "Youtube Date Rx" "Ep1047-1048" "One Piece Ep1047-1048.mkv"
> season: 1052, ep: 1052-10-53
> "One Piece [tvdb4-81797]" s1052e1052-10-53                         "Youtube Date Rx" "Ep1052-1053" "One Piece Ep1052-1053.mkv"
> season: 1056, ep: 1056-10-57
> "One Piece [tvdb4-81797]" s1056e1056-10-57                         "Youtube Date Rx" "Ep1056-1057" "One Piece Ep1056-1057.mkv"
> season: 1060, ep: 1060-10-61
> "One Piece [tvdb4-81797]" s1060e1060-10-61                         "Youtube Date Rx" "Ep1060-1061" "One Piece Ep1060-1061.mkv"
> season: 1075, ep: 1075-10-76
> "One Piece [tvdb4-81797]" s1075e1075-10-76                         "Youtube Date Rx" "Ep1075-1076" "One Piece Ep1075-1076.mkv"
> 

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L1152 indicate date_rx is to blame in the loop above, date_rx regex definition located at this line: https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L118

Please replace line 118 with the updated version, change the folder content or the scanner will use cache and not change anything, scan, and report please
`DATE_RX         = [ cic(ur'(?P<year>(0[1-9]|[12][0-9]|3[01]))[ \-\.]?(?P<month>(0[1-9]|1[1,2]))[ \-\.]?(?P<day>(0[1-9]|[12][0-9]|3[01]))'), `

**Comment by potatoxbe** [comment]
This works much better, but now only some episodes are categorized wrong.

Another issue, HamaTV agent doesn't fill any metadata for One Piece. I had to use the TVDB agent. Any fix?

[One Piece [tvdb4-81797].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14353502/One.Piece.tvdb4-81797.scanner.log)

![Screenshot 2024-02-21 100313](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/36989096/454df133-5fbb-4635-8626-c799827a0fe2)
