### ISSUE TITLE
Naruto Arcs not being correctly named, I think my tvdb4.mapping file is being ignored and is using the online xml file?

### ISSUE THREAD

**Issue by AdamZane** [ZeroQI/Absolute-Series-Scanner#484]
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/98738284-ccce-4cdd-a1f5-46caae3b51c2)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/47528974-0d99-4489-8761-6264b090f434)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/127df5a2-ef48-43f0-82af-8bec1334b011)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/43daa7fc-5098-4a49-9458-1fb3f5d649e3)

As you can see in these pictures, I have the first 17 episodes, with some missing files because the episodes are combined (this part doesn't matter).

I am attempting to use tvdb4 mapping files to organize Naruto into arcs, here is my mapping file: 
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/5d563b57-6c5d-4568-85a1-7c5b9d922207)

(I edit my mapping files by turning them into txt's, I believe this is the way I am supposed to do it right? I did this for One Piece and I was able to edit my arcs as I saw fit correctly.

I am unsure why when I attempt Naruto though, it seems to be using tvdb's aired numbering, rather than my set numbering, because as you can see here the metadata is wrong, and is gathering the metadata from the online XML file:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/6258d3de-d595-4a9d-b9f7-f527472603c9)

I am not sure which logs you would need to help me out here, but here are a couple:
[Plex Media Server.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14304279/Plex.Media.Server.log)
[Plex Media Scanner Analysis.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14304286/Plex.Media.Scanner.Analysis.log)
[Plex Media Scanner (custom ASS).log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14304293/Plex.Media.Scanner.custom.ASS.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14304295/com.plexapp.agents.hama.log)
[Naruto [tvdb4-78857].filelist.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14304299/Naruto.tvdb4-78857.filelist.log)
[Naruto [tvdb4-78857].scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14304301/Naruto.tvdb4-78857.scanner.log)

I know this is a lot of stuff, but as far as I can tell you don't like it when people don't provide enough information for a solution in one go haha!

**Comment by AdamZane** [comment]
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/8ae663c6-a1b9-41f6-8832-57a15156fe48)
as you can see here, it seems to be working for my one piece folder & recent episode metadata as well...
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/e2bf817d-ab58-4073-a50f-a8fc3e99aa9b)
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/fb43d813-c742-424a-a516-3f3d9157fd12)

**Comment by ZeroQI** [comment]
Tvdb4 mapping file seem correct but the tvdb4. Mapping file go in the series folder only, no need for season/arc folder file. 

You can drag and drop the file into notepad without renaming it, but if you add. Txt extension at the end it won't work... 

You have created arc/season folders and put the absolute numbering episodes in your own season folders so the scanner has no tvdb4 mapping to do and the episode number and season stay the same, so i don't see a scanner issue at all, apart from season 22.5, you cannot do that

Season title cannot be updated by the agent even though it is provided to Plex, unless they fixed it so the mapping file contain just that,  mapping, unless you refer to the tvdb4 poster mapping? 

I need you to expend on:

>  it seems to be using tvdb's aired numbering, rather than my set numbering, because as you can see here the metadata is wrong, and is gathering the metadata from the online XML file

I cannot see it is wrong...

**Comment by AdamZane** [comment]
This is what I would like my Arcs to be:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/36cb0df2-b028-4991-8199-9ba19679c427)

This is the Metadata for season 2 I have received in plex:
![image](https://github.com/ZeroQI/Absolute-Series-Scanner/assets/119836760/019d988c-91a9-45a2-bd7e-9c661fc05ffd)

As you can see in that picture, say episode 13,
it should be getting this metadata: "https://thetvdb.com/series/naruto/episodes/296987"
but instead it gets this metadata: "https://thetvdb.com/series/naruto/episodes/297022"

I think it is pulling from the tvdb4.mapping.xml file rather than matching to my tvdb4.mapping file.

Let me know if further elaboration is needed

**Comment by ZeroQI** [comment]
Pure agent issue since eps at right season and episode number, closing this one
