### ISSUE TITLE
.hack series problem with mapping

### ISSUE THREAD

**Issue by koalix** [ZeroQI/Absolute-Series-Scanner#487]
Operating system and version: Windows 10 / Ubuntu 22.04 (both fully patched)
Plex version: 1.40.1.8120

## Expected Behavior
.hack seasons LIMINALITY, DUSK and ROOTS are mapped wrong

## Current Behavior
The proper behaviour would be LIMINALITY to be mapped to Special, episodes 02 to 05, DUSK mapped as season 02 and ROOTS as season 03.

Currently, LIMINALITY is mapped as season 02, ROOTS and DUSK as season 03. 

Logs for the scanner job:
[hack ROOTS.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14474624/hack.ROOTS.scanner.log)
[hack DUSK.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14474625/hack.DUSK.scanner.log)
[hack LIMINALITY.scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14474626/hack.LIMINALITY.scanner.log)

## Additional information
I don't have the files to test if .hack//Sekai no Mukou ni ([a8606](https://anidb.net/a8606)) is mapped right.

**Comment by ZeroQI** [comment]
Anidb4 mode, this is a tricky one, i didn't code it but it is located lines 910 to 993
https://github.com/ZeroQI/Absolute-Series-Scanner/commit/8a2f17e
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L910

The season_map seem correct
'222': {'max': 0, 'min': 0}, #liminality
'5459': {'max': 0, 'min': 0},
'5391': {'max': 0, 'min': 0},
'8606': {'max': 0, 'min': 0},
'1135': {'max': 0, 'min': 0},
'7883': {'max': 0, 'min': 0},
'24': {'max': 1, 'min': 1}, #.hack//sign
'447': {'max': 2, 'min': 2}, #.hack//dust / legend of the swighlight / Tasogare no Udewa Densetsu
'4324': {'max': 3, 'min': 3}, #.hack//roots

LIMINALITY is mapped as season 02, ROOTS and DUSK as season 03, that seem like it should be different seasons
Koalix expectation:
- 222 LIMINALITY s00e02 to 05
- 447 .hack//Tasogare no Udewa Densetsu season 02
- 4324 .hack//Roots season 03 but seem incorrect

Relationship graph:  https://anidb.net/anime/222/relation/graph
- 1st prequel/sequel line: 24 (tvdb season 1) > 222 > 447 (tvdb season 2)
- 2nd prequel/sequel line: 4324  (tvdb season 3)> 5459 > 5391

@EndOfLine369 Is Koalix right in his expectations? 
Should 222 liminality be season 2, 447 dust be season 3, 4324 roots be season 4, or is the relationship so messed up it is not reconciliable algorythmicaly ?

**Comment by efalsken** [comment]
If you're using Linux, you'll run into problems with folders that start with the `dot` character. Here's how I solved dotHack:

```
dotHack - 01 - Sign (2002) [anidb-24]
dotHack - 02 - Liminality (2002-2003) [anidb-222]
dotHack - 03 - Legend of the Twilight (2003) [anidb-447]
dotHack - 04 - Roots (2006) [anidb-4324]
dotHack - 05 - GU Trilogy (2007) [anidb-5459]
dotHack - 06 - Returner (2007) [anidb-5391]
dotHack - 07 - Quantum (2010) [anidb-7883]
dotHack - 08 - Beyond the World (2012) [anidb-8606]
```
