### ISSUE TITLE
Overwriting season information when adding a new one

### ISSUE THREAD

**Issue by alejakun** [ZeroQI/Absolute-Series-Scanner#489]
Platform

Linux Docker

Operating system and version: Linux, Docker (lscr.io/linuxserver/plex)
Plex version: 4.125.1

Current Behavior

Everything seems to work in separate but I discovered a show that didn't showed up information from Season 1, the files are in the same folder and the naming convention was correct, so after a few tests I identified the following behavior:

- If I have files from season 1 it correctly identifies the files as season 1
- If I have files from season 2 it correctly identifies the files as season 2
- If I have files from season 1 and 2 it just recognizes the files from season 2 (shows season 2 but not season 1)

Thanks!

[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/14733784/com.plexapp.agents.hama.log)
[Tawawa on Monday [tvdb-318271].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/14733785/Tawawa.on.Monday.tvdb-318271.agent-search.log)
[Tawawa on Monday [tvdb-318271].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/14733786/Tawawa.on.Monday.tvdb-318271.agent-update.log)

**Comment by alejakun** [comment]
Here are the logs I could find.

[Plex Media Scanner.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14733816/Plex.Media.Scanner.log)

[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Logs/root_folder_name.filelist.log [Not Present]
/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Logs/root_folder_name.scanner.log [Not Present]

/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Logs/Library_name/root_folder_name.filelist.log [Not Present]
/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/Logs/Library_name/root_folder_name.scanner.log [Not Present]

[_root_.agent.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14733826/_root_.agent.log)
[Tawawa on Monday [tvdb-318271].agent-search.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14733827/Tawawa.on.Monday.tvdb-318271.agent-search.log)
[Tawawa on Monday [tvdb-318271].agent-update.log](https://github.com/ZeroQI/Absolute-Series-Scanner/files/14733828/Tawawa.on.Monday.tvdb-318271.agent-update.log)

**Comment by ZeroQI** [comment]
*. Scanner.log
Are you sure this library has ASS enabled?

You have two episode numbers in each file name, you are on your own...
Totally unsupported

"/volume1/media/library/Videos/Anime TV/Tawawa on Monday
[tvdb-318271]/Tawawa on Monday - S01E11 - E011 - Recalling with Regret
How He Completely Missed Seeing Her in Her Adolescence
[HDTV-720p][8bit][x264][AAC 2.0][PuyaSubs!].mkv"

**Comment by alejakun** [comment]
It should be enabled:

<img width="363" alt="image" src="https://github.com/ZeroQI/Absolute-Series-Scanner/assets/72576153/183e8bbe-cc92-4051-9db9-6b72426360d0">

Te problem is, all my library is using the same convention, didn't know it was not supported, It's been working well for most items for the past couple of years, is there anything else I can do to confirm this?

**Comment by ZeroQI** [comment]
I wrote the bloody s**t? How can you expect the scanner to pick the one episode number if there are two? I have failsafe with numbers appearing too often for when a number is in the title that is different from the file name, and that will throw a spanner in it and have random results

**Comment by alejakun** [comment]
Ok man, thanks.
