### ISSUE TITLE
Scanner Errors

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#49]
Attached are my logs.  Scanner runs, but finishes super quickly.  Things I've noticed:

- No .pyc file is being generated with the latest scanner.
- Scanner runs quickly, sees that no changes need to be made (even if there were some)
- Added a show, ran the scanner, was not added

[Logs.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/355167/Logs.zip)

**Comment by EndOfLine369** [comment]
Was broken in last commit https://github.com/ZeroQI/Absolute-Series-Scanner/commit/240ad896e07dfb4e4fb65caba09ce0fd6335c819

**Comment by EndOfLine369** [comment]
Should be fixed now. Please check.

**Comment by sven-7** [comment]
Scanner seems to be running at it's normal speed now. No errors in the log.

Still puzzled why no .pyc file is generating.
