### ISSUE TITLE
Help with Youtube Syntax 

### ISSUE THREAD

**Issue by Zhiro90** [ZeroQI/Absolute-Series-Scanner#496]
Hi! I didn’t want to open an issue, but after reading the README, several closed issues, and some Reddit threads, I haven’t found a way to display my YouTube series as desired (ot even sure if it’s possible tbh). Archiving playlists has been working great for years without any issues. My questions are regarding the channel archival. I would like to know the folder syntax to these.

    Channel mode: Sort episodes by release date, seasons by release year.
    Channel mode: Sort episodes by release date without grouping by seasons.
    Bonus! Playlists mode: Invert the order.

I appreciate any help you can provide!

**Comment by ZeroQI** [comment]
You cannot have series without season in Plex, but can hide season folders if there is only one in library settings

Try [youtube2-xxxxxx] for using years as seasons
I did set up playlist to have last published episode last, if you bothered to use youtubedl command given so the file date/time is replaced by the youtube publication date/time, as playlist could be in reverse order sometime

**Comment by Zhiro90** [comment]
Thank you for your quick answers!

1 
> Try [youtube2-xxxxxx] for using years as seasons
This creates seasons based on file creation date instead of release date, if I recall correctly this happens if the scanner can't find the release date on the filename, am I right? what's the correct syntax for date on filename? currently i have yyyymmdd at the beginning. 

2. 
> You cannot have series without season in Plex, but can hide season folders if there is only one in library settings
Noted, not possible

3. 
> I did set up playlist to have last published episode last, if you bothered to use youtubedl command given so the file date/time is replaced by the youtube publication date/time, as playlist could be in reverse order sometime

Please can you point me to the right command? sorry to bother you

**Comment by ZeroQI** [comment]
In youtube agent readme the youtubedl command

**Comment by ZeroQI** [comment]
Date based numbering is buggy, if you have two releases the same day it craps itself...
Fdate base regex are towards the top of the source code, comment will give the format it expects

**Comment by Zhiro90** [comment]
Thank you.

>Date based numbering is buggy, if you have two releases the same day it craps itself...
Fdate base regex are towards the top of the source code, comment will give the format it expects

Went to the source and found these two:

`
DATE_RX         = [ cic(ur'(?P<year>(19[0-9][0-9]|20[0-3][0-9]))[\-\.\/\_](?P<month>(0[1-9]|1[0-2]))\2(?P<day>(0[1-9]|[12][0-9]|3[01]))'),                                       #2024-05-21, 2024/25/31, 2024.05.31
                    cic(ur'(?P<day>(0[1-9]|[12][0-9]|3[01]))[ \-\.\/\_](?P<month>(0[1-9]|1[0-2]))\2(?P<year>(19[0-9][0-9]|20[0-3][0-9]))')]                                        #21-05-2024, 21/05/2024, 21.05.2024
---
for rx in DATE_RX:
          match = rx.search(file)  # file starts with "yyyy-mm-dd" "yyyy.mm.dd" "yyyy mm dd" or "yyyymmdd"
          if match:
--
'
Used those formats on my file names and still the same result (seasons grouped by file date). Used youtube-, youtube2- and only the channel ID.

> In youtube agent readme the youtubedl command

Found the sample code as:

`youtube-dl -v --dateafter 20081004 --download-archive /volume1/Youtube/.Downloaded -i -o "/volume1/Youtube/%(uploader)s [%(channel_id)s]/%(playlist_index)s - %(title)s [%(id)s].%(ext)s" -f bestvideo+bestaudio -ci --batch-file=/volume1/Youtube/Channels_to_DL.txt`

**Comment by ZeroQI** [comment]
Custom scznner logs needed at this point, in logs subfolder named after the library name

**Comment by Zhiro90** [comment]
scanner.log:

=============================================================================================================================================================
Call: "Plex", path: "underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]", folder_show: "underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]", dirs (0), files (4)
=============================================================================================================================================================
-------------------------------------------------------------------------------------------------------------------------------------------------------------
=============================================================================================================================================================
Forced ID (series folder) - source: "youtube2", id: "UCyw2MJ0aRF9ckJx2hSFhKOg"
season: 2019, episode: 03170656, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv,
season: 2024, episode: 05031406, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv,
season: 2019, episode: 07161028, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv,
season: 2019, episode: 07200427, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv,
season: 2024, keys(1): ['05031406']
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2024e   5031406                         "Youtube Date" "2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv" "2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv"
season: 2019, keys(3): ['07200427', '03170656', '07161028']
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e   7200427                         "Youtube Date" "2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv" "2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv"
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e   3170656                         "Youtube Date" "2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv" "2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv"
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e   7161028                         "Youtube Date" "2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv" "2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv"

**Comment by ZeroQI** [comment]
Apologies, youtube2 mode use the file year for the season and the rest of the date for the episode number, so you are better using youtube mode

```
        for rx in DATE_RX:
          match = rx.search(file)  # file starts with "yyyy-mm-dd" "yyyy.mm.dd" "yyyy mm dd" or "yyyymmdd"
          if match:
            if source=='youtube2': 
              filedate        = time.gmtime(os.path.getmtime(filename))
              season, episode = match.group('year'), '{:>02}{:>02}{:>02}{:>02}'.format(match.group('month'), match.group('day'), filedate[3], filedate[4])
            else:
              season, episode = match.group('year'), '{}-{:>02}-{:>02}'.format(match.group('year'), match.group('month'), match.group('day'))
            break
```

You will need to change the folder content or the results will be cached and not changing even if the filename would have changed since the content itself didn't...
Attach the log file after renaming to youtube mode instead of youtube2, and rescanning after changing folder content

**Comment by Zhiro90** [comment]
and this one,using only the channel id

=============================================================================================================================================================
Call: "Plex", path: "underland [UCyw2MJ0aRF9ckJx2hSFhKOg]", folder_show: "underland [UCyw2MJ0aRF9ckJx2hSFhKOg]", dirs (0), files (4)
=============================================================================================================================================================
-------------------------------------------------------------------------------------------------------------------------------------------------------------
=============================================================================================================================================================
Forced ID (series folder) - source: "youtube", id: "UCyw2MJ0aRF9ckJx2hSFhKOg"
season: 2019, episode: 2019-03-17, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv,
season: 2024, episode: 2024-05-03, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv,
season: 2019, episode: 2019-07-16, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv,
season: 2019, episode: 2019-07-20, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv,
season: 2024, keys(1): ['2024-05-03']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2024e2024-05-03                         "Youtube Date" "2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv" "2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv"
season: 2019, keys(3): ['2019-03-17', '2019-07-20', '2019-07-16']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e2019-03-17                         "Youtube Date" "2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv" "2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv"
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e2019-07-20                         "Youtube Date" "2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv" "2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv"
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e2019-07-16                         "Youtube Date" "2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv" "2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv"

**Comment by ZeroQI** [comment]
Something is broken: s2019e2019-03-17,  s2019e2019-07-20, s2019e2019-07-16 but that's what is coded
https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py#L1051C15-L1051C142
try instead: season, episode = match.group('year'), '{:>02}{:>02}'.format(match.group('month'), match.group('day'))

**Comment by Zhiro90** [comment]
chaned the line. It now is (with context) :


if source=='youtube2': 
              filedate        = time.gmtime(os.path.getmtime(filename))
              season, episode = match.group('year'), '{:>02}{:>02}{:>02}{:>02}'.format(match.group('month'), match.group('day'), filedate[3], filedate[4])
            else:
              season, episode = match.group('year'), '{:>02}{:>02}'.format(match.group('month'), match.group('day'))
            break

Results are the same, log:

=============================================================================================================================================================
Call: "Plex", path: "underland [UCyw2MJ0aRF9ckJx2hSFhKOg]", folder_show: "underland [UCyw2MJ0aRF9ckJx2hSFhKOg]", dirs (0), files (4)
=============================================================================================================================================================
-------------------------------------------------------------------------------------------------------------------------------------------------------------
=============================================================================================================================================================
Forced ID (series folder) - source: "youtube", id: "UCyw2MJ0aRF9ckJx2hSFhKOg"
season: 2019, episode: 2019-03-17, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv,
season: 2024, episode: 2024-05-03, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv,
season: 2019, episode: 2019-07-16, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv,
season: 2019, episode: 2019-07-20, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv,
season: 2024, keys(1): ['2024-05-03']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2024e2024-05-03                         "Youtube Date" "2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv" "2008_07_09 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv"
season: 2019, keys(3): ['2019-03-17', '2019-07-20', '2019-07-16']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e2019-03-17                         "Youtube Date" "2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv" "2006_12_07 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv"
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e2019-07-20                         "Youtube Date" "2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv" "2009_02_03 - Underland    Stayin Alive Baby Got Back [zyP0eWTznO8].mkv"
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e2019-07-16                         "Youtube Date" "2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv" "2009_02_02 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv"

**Comment by ZeroQI** [comment]
Some change got published to correct date based regex, please test

**Comment by Zhiro90** [comment]
1. Right now, using the [youtube-CHANNELID]/DATE - NAME [VID-ID] correctly sorts by year, but can't fetch the video's metadata. LOG:

-------------------------------------------------------------------------------------------------------------------------------------------------------------
Call: "Plex", path: "underland [UCyw2MJ0aRF9ckJx2hSFhKOg]", folder_show: "underland [UCyw2MJ0aRF9ckJx2hSFhKOg]", dirs (0), files (3)
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Forced ID (series folder) - source: "youtube", id: "UCyw2MJ0aRF9ckJx2hSFhKOg"
season: 2006, episode: 2006-12-07, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2006-12-07 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv,
season: 2008, episode: 2008-07-09, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2008-07-09 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv,
season: 2009, episode: 2009-02-02, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\2009-02-02 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv,
season: 2008, keys(1): ['2008-07-09']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2008e2008-07-09                         "Youtube Date" "2008-07-09 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv" "2008-07-09 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv"
season: 2009, keys(1): ['2009-02-02']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2009e2009-02-02                         "Youtube Date" "2009-02-02 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv" "2009-02-02 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv"
season: 2006, keys(1): ['2006-12-07']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2006e2006-12-07                         "Youtube Date" "2006-12-07 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv" "2006-12-07 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv"

-------------------------------------------------------------------------------------------------------------------------------------------------------------

2. Removing the date from the filename makes seasons by file date but still won't fetch the youtube vid metadata.  LOG:

-------------------------------------------------------------------------------------------------------------------------------------------------------------
Call: "Plex", path: "underland [UCyw2MJ0aRF9ckJx2hSFhKOg]", folder_show: "underland [UCyw2MJ0aRF9ckJx2hSFhKOg]", dirs (0), files (3)

-------------------------------------------------------------------------------------------------------------------------------------------------------------
Forced ID (series folder) - source: "youtube", id: "UCyw2MJ0aRF9ckJx2hSFhKOg"
season: 2019, episode: 2019-07-16, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv,
season: 2024, episode: 2024-10-01, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv,
season: 2024, episode: 2024-08-11, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [UCyw2MJ0aRF9ckJx2hSFhKOg]\Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv,
season: 2024, keys(2): ['2024-08-11', '2024-10-01']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2024e2024-08-11                         "Youtube Date" "Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv" "Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv"
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2024e2024-10-01                         "Youtube Date" "Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv" "Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv"
season: 2019, keys(1): ['2019-07-16']
"underland [youtube-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e2019-07-16                         "Youtube Date" "Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv" "Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv"

-------------------------------------------------------------------------------------------------------------------------------------------------------------
3. Using youtube-2 without dates, sorts by file date but does get the video info from youtube. LOG:

Call: "Plex", path: "underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]", folder_show: "underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]", dirs (0), files (3)
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Forced ID (series folder) - source: "youtube2", id: "UCyw2MJ0aRF9ckJx2hSFhKOg"
season: 2019, episode: 07161028, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv,
season: 2024, episode: 10010242, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv,
season: 2024, episode: 08110039, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv,
season: 2024, keys(2): ['08110039', '10010242']
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2024e   8110039                         "Youtube Date" "Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv" "Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv"
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2024e  10010242                         "Youtube Date" "Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv" "Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv"
season: 2019, keys(1): ['07161028']
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2019e   7161028                         "Youtube Date" "Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv" "Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv"

-------------------------------------------------------------------------------------------------------------------------------------------------------------
4. Finally using youtube2 and date on filename sorts correctly by season but won't get the vid info from youtube. LOG:
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Call: "Plex", path: "underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]", folder_show: "underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]", dirs (0), files (3)
-------------------------------------------------------------------------------------------------------------------------------------------------------------
Forced ID (series folder) - source: "youtube2", id: "UCyw2MJ0aRF9ckJx2hSFhKOg"
season: 2006, episode: 12071028, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\2006-12-07 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv,
season: 2008, episode: 07090242, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\2008-07-09 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv,
season: 2009, episode: 02020039, filename: \\Zhiro-DSK\P\Z\Video\Youtube\Youtube Series\underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]\2009-02-02 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv,
season: 2008, keys(1): ['07090242']
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2008e   7090242                         "Youtube Date" "2008-07-09 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv" "2008-07-09 - Underland - Duality ( slipknot cover ) [N11S01IZ40o].mkv"
season: 2009, keys(1): ['02020039']
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2009e   2020039                         "Youtube Date" "2009-02-02 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv" "2009-02-02 - Underland - Pantera cover - Cowboys from Hell #panteracoversfromhell [JnOGdO_-wH8].mkv"
season: 2006, keys(1): ['12071028']
"underland [youtube2-UCyw2MJ0aRF9ckJx2hSFhKOg]" s2006e  12071028                         "Youtube Date" "2006-12-07 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv" "2006-12-07 - Underland - Damage Inc - Metallica cover [mWQkG1hc2Po].mkv"
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
SUMMARY:

- both youtube and youtube2 correctly create year seasons based on filename and seasons based on file date if no date on filename.
- None get the youtube info except for youtube2 without filename dates.
