### ISSUE TITLE
Episode num in [ ]

### ISSUE THREAD

**Issue by technobulka** [ZeroQI/Absolute-Series-Scanner#5]
Folder name looks like this - *[Dub]\_Prison\_[01]_[720p].mp4*, where:
*Dub* - dubber
*Prison* - series name
*01* - episode num

In Plex Media Server all series with names like this show only one episode with many parts.
I think problem in [ ].

**Comment by ZeroQI** [comment]
Anything inside "[ ]" is deleted. I have never seen any group putting the episode number into brackets
Please give exact filenames that you didn't rename yourself and was released like that

**Comment by technobulka** [comment]
One team name all files like this:
[AniDub]_Durarara!!_ TV-2_[01]_[720p_x264_Aac]_[MVO].mp4
[AniDub]_Gangsta_[01]_[720p_x264_Aac]_[JAM_Trina_D].mp4
[AniDub]_Gintama_TV-4_[01]_[720p_x264_Aac]_[JAM].mp4

**Comment by Sinkler** [comment]
:+1:

**Comment by ZeroQI** [comment]
So some eastern release groups indeed use that format, that is both surprising and annoying for me...
The easiest i find is to remove all brackets unless it contain only numbers (1 to 3) line 180.
removed "TV-1", "TV-2" from strings to make it work... what is that ?

 if "[" in string or "{" in string:
    string = re.sub(r'[\[\{](?![0-9]{1,3}[\]\}]).*?[\]\}]', '', string)                       # remove "[xxx]" groups as Plex cleanup keep inside () but not inside []
    if "[" in string in string: string = string.replace("[", '').replace("]", '')

Please try and let me know

**Comment by technobulka** [comment]
TV-x - yes, this is seasons.

I see problems with your markup.
I replace this regex `\[.*?\]` to this `\[(?!\d{2,3}\]).*?\]` and all wokrs fine.

**Comment by ZeroQI** [comment]
string = re.sub(r'[\[\{](?![0-9]{1,3}[\]\}]).*?[\]\}]', '', string)
