### ISSUE TITLE
Scanner logs cosmetics issues

### ISSUE THREAD

**Issue by ZeroQI** [ZeroQI/Absolute-Series-Scanner#52]
https://forums.plex.tv/discussion/comment/1227484/#Comment_1227484
Filelist are used with a batchfile to re-create library fith 0-size dummy files
Need to remove:
```
=============================================================================================================================================================
==== Starting File Scan ====
=============================================================================================================================================================
```

Custom log get incrementaly growing duplicates:
```
2016-07-31 16:15:47,344 - ASS : INFO - === Library "Аниме", Root: "F:\Anime",  Launched: '2016-07-31 16:15:47'======================================================================================
2016-07-31 16:15:47,344 - ASS : INFO - =============================================================================================================================================================
2016-07-31 16:15:47,344 - ASS : INFO - Scanner call - root: 'F:\Anime', path: '', dirs: '45', files: '0'
2016-07-31 16:15:47,345 - ASS : INFO - =============================================================================================================================================================
2016-07-31 16:15:47,359 - ASS : INFO - =============================================================================================================================================================
2016-07-31 16:15:47,359 - ASS : INFO - =============================================================================================================================================================
2016-07-31 16:15:47,359 - ASS : INFO - Scanner call - root: 'F:\Anime', path: 'Boku dake ga Inai Machi', dirs: '1', files: '0'
2016-07-31 16:15:47,359 - ASS : INFO - Scanner call - root: 'F:\Anime', path: 'Boku dake ga Inai Machi', dirs: '1', files: '0'
2016-07-31 16:15:47,361 - ASS : INFO - =============================================================================================================================================================
```

**Comment by ZeroQI** [comment]
https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d

Replace:  scudlee_file = open(tmp_filename, mode='w'); scudlee_file.write( urlopen( ANIDB_TVDB_MAPPING ).read() ); scudlee_file.close()
With:       with open(tmp_filename, 'w') as scudlee_file:  scudlee_file.write( urlopen( ANIDB_TVDB_MAPPING ).read() )

Replace: scudlee_file   = open(scudlee_filename, mode='r'); scudlee_mapping_content = etree.fromstring( scudlee_file.read() ); scudlee_file.close()
With:      with open(scudlee_filename, 'r') as scudlee_file:  scudlee_mapping_content = etree.fromstring( scudlee_file.read() )

some small code clearing

**Comment by EndOfLine369** [comment]
Single file log rotation was put in place to prevent the clearing of the filelist file and being provided a zero byte file. So as the file is not getting truncated at each run, we need a statement to make it clear which run ran against which files. Please look at putting in the log prints and update your batch script or just cut up the filelist file to the files you just needed and run your script against that.

**Comment by EndOfLine369** [comment]
Also no complaint about the scudlee file dump line as long at it auto closes (which I think it does).

**Comment by ZeroQI** [comment]
With auto-close files, which is why it is brilliant
Before the logging functions fix, the filelist log was created per library normally and reset to zero at every run, and contain all files
```
  for file in files:
    ext = os.path.splitext(file)[1].lstrip('.').lower()
    if ext in VIDEO_EXTS:
      for rx in IGNORE_FILES_RX:                                                                                        # Filter trailers and sample files
        if re.match(rx, file, re.IGNORECASE):  Log.info("File:   '%s' match IGNORE_FILES_RX: '%s'" % (file, rx)); files_to_remove.append(file);  break
      else:  LogFileList(file)  #add to filelist
```
I will add any extension to the filelist possibly, as i had questions with ASS subs and couldn't see, os wil l remove the else ...
"  LogFileList(file)  #add to filelist"
https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d

To empty the log i used before:
`open(os.path.join(LOG_PATH, FILELIST), 'w').close                                                      #Empty file for root 
`
To be fair, unsure what i can use to clear the logs, but after complaining about logging, i quite like the optimisation it brings by not reopen logs file to add a single line, and the fact it properly replace my hacky Log function, and the fact the logs don't grow infinitely anymore, that bothered me and you fixed that.

i could add all to an array and write like before all in one go, unless you have an alternative...

**Comment by EndOfLine369** [comment]
- WHACK & CHARACTERS_MAP
Your copy/paste failed as yours turned some into '?'

- Your missing some core issues that your prev setup and new proposed setup for filelist is not being resolved that mine does.
  1. If there are any libraries with multiple roots (which I have) the file will always loose any files from the roots before the last one scanned.
  2. Even if there is only one root, any re-scans will trash the filelist data we need from the bad scan.

- Your anidb2 _looks_ fine in reading and makes sense.

**Comment by EndOfLine369** [comment]
FYI, found I had missed this so added https://github.com/ZeroQI/Absolute-Series-Scanner/commit/77fa2bface595a00e5b5a4ba501f4c2bf7cc5921

**Comment by ZeroQI** [comment]
@EndOfLine369 that might fix the multiple log and '='lines showing up in custom logs
The copy and paste loosing characters, always gets me....

You are right about multiple root and after reflection ***very inaudibly*** the file issue...
The filelist is a list of files. If the files don't change, the filelist will not. However, extrapolating, if a user change naming few times, so will the filelist and your implementation allow to extract the filelist from that one time error. That is a good thing but i will have to create filelist from that log by hand. Easy enough

I would prefer an exact copy of the filelist from last scan, but for that i need to check the first root folder in the library xml to only clear on the first root call, but i need access to that file, which may require the key.... You win again this argument :D

I updated the readme a bit, list an issue happening under windows if "Microsoft Visual C++ 2010 Redistributable Package (x86)" isn't there, make "from lxml import etree" fail with "ImportError: DLL load failed: The specified module could not be found."

**Comment by EndOfLine369** [comment]
:smiley: 
So need to put back in that separator to differentiate the files between the runs. And if you want all files, we can simply move the log to the top of the `for file in files` loop.
```python
FROM:
  if not path:
    set_logging("FileList", FILELIST)
    Log.info(("=== Library \"%s\", Root: \"%s\",  Launched: '%s'" % (PLEX_LIBRARY[root] if root in PLEX_LIBRARY else "X-Plex-Token.id missing", root, time.strftime("%Y-%m-%d %H:%M:%S"))).ljust(157, '='))
  Log.info("".ljust(157, '='));  Log.info("Scanner call - root: '%s', path: '%s', dirs: '%d', files: '%d'" % (root, path, len(subdirs), len(files)));  Log.info("".ljust(157, '='))  # Exit every other iteration than the root scan
  for subdir in subdirs:                                                    #
    for rx in IGNORE_DIRS_RX:                                               # if initial scan and root folder
      if re.match(rx, os.path.basename(subdir), re.IGNORECASE): subdirs.remove(subdir);  Log.info("\"%s\" match IGNORE_DIRS_RX: \"%s\"" % (subdir, rx));  break  #skip dirs to be ignored
  reverse_path, files_to_remove = list(reversed(Utils.SplitPath(path))), []
  for file in files:
    ext = os.path.splitext(file)[1].lstrip('.').lower()
    if ext in VIDEO_EXTS:
      for rx in IGNORE_FILES_RX:                                                                                        # Filter trailers and sample files
        if re.match(rx, file, re.IGNORECASE):  Log.info("File:   '%s' match IGNORE_FILES_RX: '%s'" % (file, rx)); files_to_remove.append(file);  break
      else:  
        LogFileList(file)  #add to filelist
    else:  Log.info("file: '%s', ext: '%s' not in video_ext" % (file, ext));  files_to_remove.append(file);  continue
  for file in files_to_remove:  files.remove(file)


CHANGE TO:
  if not path:
    set_logging("FileList", FILELIST); LogFileList("".ljust(157, '=')); LogFileList("==== Starting File Scan (root:%s) ====" % root); LogFileList("".ljust(157, '='))
    Log.info(("=== Library \"%s\", Root: \"%s\",  Launched: '%s'" % (PLEX_LIBRARY[root] if root in PLEX_LIBRARY else "X-Plex-Token.id missing", root, time.strftime("%Y-%m-%d %H:%M:%S"))).ljust(157, '='))
  Log.info("".ljust(157, '='));  Log.info("Scanner call - root: '%s', path: '%s', dirs: '%d', files: '%d'" % (root, path, len(subdirs), len(files)));  Log.info("".ljust(157, '='))  # Exit every other iteration than the root scan
  for subdir in subdirs:                                                    #
    for rx in IGNORE_DIRS_RX:                                               # if initial scan and root folder
      if re.match(rx, os.path.basename(subdir), re.IGNORECASE): subdirs.remove(subdir);  Log.info("\"%s\" match IGNORE_DIRS_RX: \"%s\"" % (subdir, rx));  break  #skip dirs to be ignored
  reverse_path, files_to_remove = list(reversed(Utils.SplitPath(path))), []
  for file in files:
    LogFileList(file)  #add to filelist
    ext = os.path.splitext(file)[1].lstrip('.').lower()
    if ext in VIDEO_EXTS:
      for rx in IGNORE_FILES_RX:                                                                                        # Filter trailers and sample files
        if re.match(rx, file, re.IGNORECASE):  Log.info("File:   '%s' match IGNORE_FILES_RX: '%s'" % (file, rx)); files_to_remove.append(file);  break
    else:  Log.info("file: '%s', ext: '%s' not in video_ext" % (file, ext));  files_to_remove.append(file);  continue
  for file in files_to_remove:  files.remove(file)
```

**Comment by ZeroQI** [comment]
FATALITY!
If ever anything goes wrong, it helps having the list of all files. Updated the source
https://gist.github.com/ZeroQI/974f6335ad4f31ecdfe1e4af0404098d

**Comment by EndOfLine369** [comment]
You still need to revert all your FileList changes/removals.

Put the changes for the FileList into the master. The only thing left outstanding should be the anidb2. I'll try to test and get this ticket's changes closed out.

**Comment by EndOfLine369** [comment]
Updated, tested, & committed. Think we can close this ticket out now.

**Comment by ZeroQI** [comment]
I believe we can. Thanks again
batch for library filelist creation or restauration added to readme.
