### ISSUE TITLE
Doesn't seem to detect Special episode

### ISSUE THREAD

**Issue by srilumpa** [ZeroQI/Absolute-Series-Scanner#53]
I had the following warning when I downloaded a Special episode.

```
2016-08-07 20:44:00,176 - ASS : WARNING - show: '', s00e501-501, file: 'D:\Downloads\Manga\[Kaerizaki-Fansub]_One_Piece_Special_-_Heart_of_Gold_[VOSTFR][HD_1280x720].mp4' has show empty, report logs to dev ASAP
2016-08-07 20:44:00,176 - ASS : INFO - "" s0000e501 "[Kaerizaki-Fansub]_One_Piece_Special_-_Heart_of_Gold_[VOSTFR][HD_1280x720].mp4" "Heart of Gold" 
```

I'm not sure how the file should be named to match the "Special episode" parsing.

**Comment by EndOfLine369** [comment]
https://github.com/ZeroQI/Absolute-Series-Scanner#file-naming-conventions

**Comment by ZeroQI** [comment]
i will be lenient as you made the effort of proper English, and well Portugal beat the crap out of your country in final without their best player in...

Hama is a anidb (single season) & tvdb (multiple seasons) agent so either naming convention is fine
You didn't even went to either naming convention

http://thetvdb.com/?tab=episode&seriesid=81797&seasonid=31892&id=5687281&lid=7
"One piece/One Piece s00e35 Heart of Gold [sub fr].ext"

http://anidb.net/perl-bin/animedb.pl?show=anime&aid=69
"One piece/One Piece s00e23 Heart of Gold [sub fr].ext"
"One piece/One Piece S23 Heart of Gold [sub fr].ext"

You left the file without renaming in the root, not even in a serie folder?

There is a nuance between " not sure how" and doing nothing, therefore, please, in your own words, write what in the readme would have assisted you enough so you wouldn't have to ask this question. You can reply in french english or spanish.

I look forward to your documented answer

**Comment by ZeroQI** [comment]
@srilumpa your file was in root without episode numbering nor movie indication so was skipped. normal scanner would have skipped as well. Failsafe when a serie title became empty was triggered, closing issue
