### ISSUE TITLE
First letter of a series title gets removed

### ISSUE THREAD

**Issue by WastedMeerkat** [ZeroQI/Absolute-Series-Scanner#6]
For example, "Charlotte" becomes "harlotte", "Overlord" becomes "verlord". I have no idea why it's happening, and it only seems to be on some things with no clear pattern as far as I can tell. Tried taking a look at the python source but this definitely looks like something more easily solved by the original author, heh.

**Comment by ZeroQI** [comment]
Happens with alpha release in gits? 
Can you post custom log entries? I need to reproduce the issue.

**Comment by WastedMeerkat** [comment]
I'm actually not sure how to get the custom logs working, but here's the default log in the meantime: https://dl.dropboxusercontent.com/u/4072938/Text%20Files/Plex%20Media%20Scanner.log

**Comment by Cephia** [comment]
same thing happening here,  log below

[log.docx](https://github.com/ZeroQI/Absolute-Series-Scanner/files/75981/log.docx)

**Comment by ZeroQI** [comment]
what is wrong with this path: "D:\User backup\Downloads\uTorrent\Completed\.Anime\2015-2 Spring\Danna ga Nani wo Itteiru ka Wakaranai Ken 2 Sure-me\[Kaitou] Danna ga Nani wo Itteiru ka Wakaranai Ken 2 Sure-me (I Can't Understand What My Husband Is Saying 2nd Thread) - 01 [720p][10bit][811C80FE].mkv" ?

Does the issue happens with the alpha scanner https://gist.github.com/ZeroQI/26d26f91af04c876b1a0 ?

**Comment by WastedMeerkat** [comment]
Wait, it should be "D:\User backup\Downloads\uTorrent\Completed**\**.Anime\". Where'd you copy that path from? Also, I'm not sure, I'll try it out later.

**Comment by ZeroQI** [comment]
Does the issue happens with the alpha scanner https://gist.github.com/ZeroQI/26d26f91af04c876b1a0 ?

**Comment by Xalaxis** [comment]
The same issue does not occur with the alpha scanner for me, however it picks up my "Extras" Folders as a season which niggles me more than just a little bit.  I'm happy to provide any logs you require.

**Comment by ZeroQI** [comment]
Give me all names of folders that are seen as season so i can reproduce and
solve. Glad the alpha solve some bugs for you. Will correct the rest

**Comment by Xalaxis** [comment]
"Extras" and "TV Preview" (Which should be inside the "Extras" folder, so you mightn't want to blacklist it).  Many thanks for the quick response!

**Comment by Xalaxis** [comment]
![capture](https://cloud.githubusercontent.com/assets/12937964/12374051/089b9248-bc88-11e5-9d11-eb77b80ff178.PNG)

**Comment by ZeroQI** [comment]
Can you attach scanner logs by any chance?

**Comment by Cephia** [comment]
Thanks Zero,  alpha release fixed the missing letters just fine.

also seeing Extras marked out in its own folder here

**Comment by Xalaxis** [comment]
[Plex Media Scanner (custom ASS) - Anime (Temporary work-around).txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/93386/Plex.Media.Scanner.custom.ASS.-.Anime.Temporary.work-around.txt)
I think that's the right one?

**Comment by Xalaxis** [comment]
Okay, so this is a little strange.  I just refreshed the content for the library and got a new log that stated that it was 'Ignoring extras' (Which didn't change the library showing extras) And also removed the first letter from each show again in the log (whilst still using the alpha scanner) But did not affect the current items in the library.
[Plex Media Scanner (custom ASS) - Anime.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/93388/Plex.Media.Scanner.custom.ASS.-.Anime.txt)

I'm going to recreate the library from scratch and send a clean log for you

**Comment by Xalaxis** [comment]
Ah, it seems to have joined all the scans I did together.  Here's a clean scan (although it starts near the end of the complete log, apologies)
[Plex Media Scanner (custom ASS) - Anime.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/93411/Plex.Media.Scanner.custom.ASS.-.Anime.txt)

**Comment by ZeroQI** [comment]
I see the issue, and i think i have a fix.  Line 215 replace "subdir" with "os.path.basename(subdir)":

for rx in ignore_dirs_rx:                                               # if initial scan and root folder
        if re.match(rx, os.path.basename(subdir), re.IGNORECASE): subdirs.remove(subdir);  Log("\"%s\" match ignore_dirs_rx: \"%s\"" % (path, rx));  break  #skip dirs to be ignored

**Comment by Xalaxis** [comment]
Made the appropriate change - Testing now.

**Comment by Xalaxis** [comment]
I can confirm this fixes #6
