### ISSUE TITLE
FreeNAS 9.10 installation

### ISSUE THREAD

**Issue by SleepingPanda** [ZeroQI/Absolute-Series-Scanner#63]
Hi, I've been looking through your instructions and can't seem to find the right directory for the scanner installation. Can you add that to the readme file if possible?

(I managed to get your HAMA metadata plugin installed.)

**Comment by ZeroQI** [comment]
https://forums.plex.tv/discussion/19396/how-to-install-a-custom-scanner
Put it into [...]/Plex/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py
"Scanners" and "Series" folder are not created by default and will need creating.
"Scanners" folder will be besides "Plug-in Support" folder in the same parent directory.

**Comment by SleepingPanda** [comment]
**Thank you very much**. I'm sorry I may have missed it in the HAMA readme!
