### ISSUE TITLE
Issue with One Piece

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#66]
The latest few episodes aren't pulling the metadata.  You'll see that the latest three, for some reason, appear at the top of the season.  

But it looks like the scanner is having an issue too after ep 100?  Here is the file and a screen shot.

<img width="615" alt="screen shot 2016-12-08 at 5 38 16 pm" src="https://cloud.githubusercontent.com/assets/18091557/21030769/3bee9a04-bd6e-11e6-9e07-23d65dea67d5.png">

[Plex Media Scanner (custom ASS).log.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/640784/Plex.Media.Scanner.custom.ASS.log.zip)

EDIT:  This may be a Plex error?  http://forums.plex.tv/discussion/246253/episode-sort-order

**Comment by ZeroQI** [comment]
That is indeed bug https://github.com/ZeroQI/Hama.bundle/issues/98#
1.3.3 version doesn't solve yet apparently. waiting for next PMS release

**Comment by sven-7** [comment]
I figured it was that one.

The metadata not coming through is still odd.  TVDB has the episode titles, but they aren't downloading.  I'm not having this issue with any other show, despite the issues ongoing in 1.3.3.  

Here are some additional logs where I added the latest ep of One Piece:

[New folder.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/663908/New.folder.zip)

**Comment by ZeroQI** [comment]
noticed ep screenshot, ep title and season posters are not being populated, so it could be the same metadata issue

**Comment by sven-7** [comment]
That's what I figured.  

The scanner log still looks weird to me, but I'm guessing it's also related to the bug.

``2016-12-20 08:45:59,483 - ASS : DEBUG - ep: 549 misc.count(ep): 1 misc: b:\anime series\ \  - 1.mp4 b:\anime series\ \  - 2.mp4 b:\anime series\ \  - 3.mp4 b:\anime series\ \  - 4.mp4 b:\anime series\ \  - 5.mp4 b:\anime series\ \  - 6.mp4 b:\anime series\ \  - 7.avi b:\anime series\ \  - 8.avi b:\anime series\ \  - 9.avi b:\anime series\ \  - 10.avi b:\anime series\ \  - 11.avi b:\anime series\ \  - 12.avi b:\anime series\ \  - 13.avi b:\anime series\ \  - 14.avi b:\anime series\ \  - 15.avi b:\anime series\ \  - 16.avi b:\anime series\ \  - 17.avi b:\anime series\ \  - 18.avi b:\anime series\ \  - 19.avi b:\anime series\ \  - 20.avi b:\anime series\ \  - 21.avi b:\anime series\ \  - 22.avi b:\anime series\ \  - 23.avi b:\anime series\ \  - 24.avi b:\anime series\ \  - 25.avi b:\anime series\ \  - 26.avi b:\anime series\ \  - 27.avi b:\anime series\ \  - 28.avi b:\anime series\ \  - 29.avi b:\anime series\ \  - 30.avi b:\anime series\ \  - 31.avi b:\anime series\ \  - 32.avi b:\anime series\ \  - 33.avi b:\anime series\ \  - 34.avi b:\anime series\ \  - 35.avi b:\anime series\ \  - 36.avi b:\anime series\ \  - 37.avi b:\anime series\ \  - 38.avi b:\anime series\ \  - 39.avi b:\anime series\ \  - 40.avi b:\anime series\ \  - 41.avi b:\anime series\ \  - 42.avi b:\anime series\ \  - 43.avi b:\anime series\ \  - 44.avi b:\anime series\ \  - 45.avi b:\anime series\ \  - 46.avi b:\anime series\ \  - 47.avi b:\anime series\ \  - 48.avi b:\anime series\ \  - 49.avi b:\anime series\ \  - 50.avi b:\anime series\ \  - 51.avi b:\anime series\ \  - 52.avi b:\anime series\ \  - 53.avi b:\anime series\ \  - 54.avi b:\anime series\ \  - 55.avi b:\anime series\ \  - 56.avi b:\anime series\ \  - 57.avi b:\anime series\ \  - 58.avi b:\anime series\ \  - 59.avi b:\anime series\ \  - 60.avi b:\anime series\ \  - 61.avi b:\anime series\ \  - 62.avi b:\anime series\ \  - 63.avi b:\anime series\ \  - 64.avi b:\anime series\ \  - 65.avi b:\anime series\ \  - 66.avi b:\anime series\ \  - 67.avi b:\anime series\ \  - 68.avi b:\anime series\ \  - 69.avi b:\anime series\ \  - 70.avi b:\anime series\ \  - 71.avi b:\anime series\ \  - 72.avi b:\anime series\ \  - 73.avi b:\anime series\ \  - 74.avi b:\anime series\ \  - 75.avi b:\anime series\ \  - 76.avi b:\anime series\ \  - 77.avi b:\anime series\ \  - 78.avi b:\anime series\ \  - 79.avi b:\anime series\ \  - 80.avi b:\anime series\ \  - 81.avi b:\anime series\ \  - 82.avi b:\anime series\ \  - 83.avi b:\anime series\ \  - 84.avi b:\anime series\ \  - 85.avi b:\anime series\ \  - 86.avi b:\anime series\ \  - 87.avi b:\anime series\ \  - 88.avi b:\anime series\ \  - 89.avi b:\anime series\ \  - 90.avi b:\anime series\ \  - 91.avi b:\anime series\ \  - 92.avi b:\anime series\ \  - 93.avi b:\anime series\ \  - 94.avi b:\anime series\ \  - 95.avi b:\anime series\ \  - 96.avi b:\anime series\ \  - 97.avi b:\anime series\ \  - 98.avi b:\anime series\ \  - 99.avi b:\anime series\ \  - 100.avi b:\anime series\ \  - 101.avi b:\anime series\ \  - 102.avi b:\anime series\ \  - 103.avi b:\anime series\ \  - 104.avi b:\anime series\ \  - 105.avi b:\anime series\ \  - 106.avi b:\a``

**Comment by ZeroQI** [comment]
Its debug code for me. Use lattest pull request to have better formated misc variable. Its used to detect

**Comment by ZeroQI** [comment]
Its debug code for me. Use lattest pull request to have better formated misc variable. Its used to detect

**Comment by ZeroQI** [comment]
aren't pulling the metadata: agent issue
Closing that one since hama has bug report already
