### ISSUE TITLE
It's not listing some Bluray extras

### ISSUE THREAD

**Issue by Kuro07** [ZeroQI/Absolute-Series-Scanner#70]
Hey there,

Great plugin but I found a bug. whenever there are multiple extras in the same folder of the anime, It does not list all of them. Perfect example is something like this http://prntscr.com/doohkd and http://prntscr.com/doohqr . I noticed that it does not add the NCOP's into the library and with the case of bakuman, it was opening a different file.

**Comment by ZeroQI** [comment]
Can i please have the scanner filelist? will recreate your library and rewriting by hand all filenames is tedious and not precise if the issue is due to encoding

**Comment by Kuro07** [comment]
Here you go. One more thing though, I noticed that it happens to all bluray release extras not just these two series.


[Coalgirls] Hanasaku Iroha Home Sweet Home (1280x720 Blu-Ray FLAC) [F28F5992].mkv	
[Coalgirls]_Hanasaku_Iroha_01_(1280x720_Blu-Ray_FLAC)_[26D9FBDF].mkv
[Coalgirls]_Hanasaku_Iroha_02_(1280x720_Blu-Ray_FLAC)_[E4ADAF38].mkv
[Coalgirls]_Hanasaku_Iroha_03_(1280x720_Blu-Ray_FLAC)_[EF0113BA].mkv
[Coalgirls]_Hanasaku_Iroha_04_(1280x720_Blu-Ray_FLAC)_[CE28F216].mkv
[Coalgirls]_Hanasaku_Iroha_05_(1280x720_Blu-Ray_FLAC)_[D382281E].mkv
[Coalgirls]_Hanasaku_Iroha_06_(1280x720_Blu-Ray_FLAC)_[1EBE5CB2].mkv
[Coalgirls]_Hanasaku_Iroha_07_(1280x720_Blu-Ray_FLAC)_[AF6F1899].mkv
[Coalgirls]_Hanasaku_Iroha_08_(1280x720_Blu-Ray_FLAC)_[7F0B1B1B].mkv
[Coalgirls]_Hanasaku_Iroha_09_(1280x720_Blu-Ray_FLAC)_[B470544A].mkv
[Coalgirls]_Hanasaku_Iroha_10_(1280x720_Blu-Ray_FLAC)_[95E6D95E].mkv
[Coalgirls]_Hanasaku_Iroha_11_(1280x720_Blu-Ray_FLAC)_[982DDEA6].mkv
[Coalgirls]_Hanasaku_Iroha_12_(1280x720_Blu-Ray_FLAC)_[8D6DBDAA].mkv
[Coalgirls]_Hanasaku_Iroha_13_(1280x720_Blu-Ray_FLAC)_[F75E7611].mkv
[Coalgirls]_Hanasaku_Iroha_14_(1280x720_Blu-Ray_FLAC)_[E500A9A0].mkv
[Coalgirls]_Hanasaku_Iroha_15_(1280x720_Blu-Ray_FLAC)_[E436D197].mkv
[Coalgirls]_Hanasaku_Iroha_16_(1280x720_Blu-Ray_FLAC)_[02B6403C].mkv
[Coalgirls]_Hanasaku_Iroha_17_(1280x720_Blu-Ray_FLAC)_[15F046E1].mkv
[Coalgirls]_Hanasaku_Iroha_18_(1280x720_Blu-Ray_FLAC)_[F858A1BC].mkv
[Coalgirls]_Hanasaku_Iroha_19_(1280x720_Blu-Ray_FLAC)_[14F8C446].mkv
[Coalgirls]_Hanasaku_Iroha_20_(1280x720_Blu-Ray_FLAC)_[05933824].mkv
[Coalgirls]_Hanasaku_Iroha_21_(1280x720_Blu-Ray_FLAC)_[B48F9CF7].mkv
[Coalgirls]_Hanasaku_Iroha_22_(1280x720_Blu-Ray_FLAC)_[B6A6C126].mkv
[Coalgirls]_Hanasaku_Iroha_23_(1280x720_Blu-Ray_FLAC)_[DFCBCD71].mkv
[Coalgirls]_Hanasaku_Iroha_24_(1280x720_Blu-Ray_FLAC)_[0AA12656].mkv
[Coalgirls]_Hanasaku_Iroha_25_(1280x720_Blu-Ray_FLAC)_[3DE6A914].mkv
[Coalgirls]_Hanasaku_Iroha_26_(1280x720_Blu-Ray_FLAC)_[EE378AFF].mkv
[Coalgirls]_Hanasaku_Iroha_NCED_(1280x720_Blu-Ray_FLAC)_[39D5D9CE].mkv
[Coalgirls]_Hanasaku_Iroha_NCED2_(1280x720_Blu-Ray_FLAC)_[605A2866].mkv
[Coalgirls]_Hanasaku_Iroha_NCOP_(1280x720_Blu-Ray_FLAC)_[991762ED].mkv
[Coalgirls]_Hanasaku_Iroha_NCOP2_(1280x720_Blu-Ray_FLAC)_[6DC813DE].mkv
[Coalgirls]_Hanasaku_Iroha_Promo_(1280x720_Blu-Ray_FLAC)_[110CA049].mkv
[Coalgirls]_Hanasaku_Iroha_Promo2_(1280x720_Blu-Ray_FLAC)_[4580BD6F].mkv
[Coalgirls]_Hanasaku_Iroha_Promo3_(1280x720_Blu-Ray_FLAC)_[47194A60].mkv
[Coalgirls]_Hanasaku_Iroha_Promo4_(1280x720_Blu-Ray_FLAC)_[807EAE9E].mkv
---------------------------------------------------------------------------------------------------------
[Judgment] Bakuman - 01 [D92E6AEB].mkv
[Judgment] Bakuman - 02 [234D0991].mkv
[Judgment] Bakuman - 03 [06E97268].mkv
[Judgment] Bakuman - 04 [15E4CE93].mkv
[Judgment] Bakuman - 05 [66C3FFC6].mkv
[Judgment] Bakuman - 06 [697063A7].mkv
[Judgment] Bakuman - 07 [02803CA3].mkv
[Judgment] Bakuman - 08 [A22A8EFE].mkv
[Judgment] Bakuman - 09 [C3C81636].mkv
[Judgment] Bakuman - 10 [EC17E186].mkv
[Judgment] Bakuman - 11 [9DC70B25].mkv
[Judgment] Bakuman - 12 [B6E738E4].mkv
[Judgment] Bakuman - 13 [6B968B3A].mkv
[Judgment] Bakuman - 14 [33EAC7BA].mkv
[Judgment] Bakuman - 15 [7D012DDB].mkv
[Judgment] Bakuman - 16 [9CB0641B].mkv
[Judgment] Bakuman - 17 [9732978C].mkv
[Judgment] Bakuman - 18 [C018955D].mkv
[Judgment] Bakuman - 19 [03D84DC1].mkv
[Judgment] Bakuman - 20 [F0682781].mkv
[Judgment] Bakuman - 21 [E192D4A2].mkv
[Judgment] Bakuman - 22 [59A5300E].mkv
[Judgment] Bakuman - 23 [6833CA77].mkv
[Judgment] Bakuman - 24 [1C51DBB9].mkv
[Judgment] Bakuman - 25 [D756384B].mkv
[Judgment] Bakuman - NCED1 [17A13D6C].mkv
[Judgment] Bakuman - NCED2 [EDD39FF9].mkv
[Judgment] Bakuman - NCOP Chou Hero Densetsu [EAED3CD4].mkv
[Judgment] Bakuman - NCOP1 [21454403].mkv
[Judgment] Bakuman - NCOP2 [F119D5EC].mkv
[Judgment] Bakuman - St. Visual's Girls Academy NCED [7B14D6CE].mkv
[Judgment] Bakuman - St. Visual's Girls Academy NCOP [DA1B5574].mkv

[Plex Media Scanner (custom ASS) - filelist .txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/675406/Plex.Media.Scanner.custom.ASS.-.filelist.txt)
[Plex Media Scanner.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/675407/Plex.Media.Scanner.txt)
[Plex Media Scanner (custom ASS).txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/675408/Plex.Media.Scanner.custom.ASS.txt)

**Comment by ZeroQI** [comment]
```
Scanner call - root: 'H:\anime\Hanasaku Iroha (1280x720 Blu-Ray FLAC)[Coalgirls]', path: '', dirs: '0', files: '35'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
show: '', s00e501-501, file: 'H:\anime\Hanasaku Iroha (1280x720 Blu-Ray FLAC)[Coalgirls]\[Coalgirls] Hanasaku Iroha Home Sweet Home (1280x720 Blu-Ray FLAC) [F28F5992].mkv' has show empty, report logs to dev ASAP
"" s0000e501 "[Coalgirls] Hanasaku Iroha Home Sweet Home (1280x720 Blu-Ray FLAC) [F28F5992].mkv"
"Hanasaku Iroha" s0000e002 "[Coalgirls]_Hanasaku_Iroha_NCED2_(1280x720_Blu-Ray_FLAC)_[605A2866].mkv" "9" "Ending 2" 
"Hanasaku Iroha" s0000e001 "[Coalgirls]_Hanasaku_Iroha_NCED_(1280x720_Blu-Ray_FLAC)_[39D5D9CE].mkv" "9" "Ending 1" 
"Hanasaku Iroha" s0000e002 "[Coalgirls]_Hanasaku_Iroha_NCOP2_(1280x720_Blu-Ray_FLAC)_[6DC813DE].mkv" "8" "Opening 2" 
"Hanasaku Iroha" s0000e001 "[Coalgirls]_Hanasaku_Iroha_NCOP_(1280x720_Blu-Ray_FLAC)_[991762ED].mkv" "8" "Opening 1" 
"Hanasaku Iroha" s0000e002 "[Coalgirls]_Hanasaku_Iroha_Promo2_(1280x720_Blu-Ray_FLAC)_[4580BD6F].mkv" "10"
"Hanasaku Iroha" s0000e003 "[Coalgirls]_Hanasaku_Iroha_Promo3_(1280x720_Blu-Ray_FLAC)_[47194A60].mkv" "10"
"Hanasaku Iroha" s0000e004 "[Coalgirls]_Hanasaku_Iroha_Promo4_(1280x720_Blu-Ray_FLAC)_[807EAE9E].mkv" "10"
show: '', s00e502-502, file: 'H:\anime\Hanasaku Iroha (1280x720 Blu-Ray FLAC)[Coalgirls]\[Coalgirls]_Hanasaku_Iroha_Promo_(1280x720_Blu-Ray_FLAC)_[110CA049].mkv' has show empty, report logs to dev ASAP
"" s0000e502 "[Coalgirls]_Hanasaku_Iroha_Promo_(1280x720_Blu-Ray_FLAC)_[110CA049].mkv"

```
```
Scanner call - root: 'H:\anime', path: 'Bakuman', dirs: '0', files: '32'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
"Bakuman" s0000e001 "[Judgment] Bakuman - NCED1 [17A13D6C].mkv" "9" "Ending 1" 
"Bakuman" s0000e002 "[Judgment] Bakuman - NCED2 [EDD39FF9].mkv" "9" "Ending 2" 
"Bakuman" s0000e001 "[Judgment] Bakuman - NCOP1 [21454403].mkv" "8" "Opening 1" 
"Bakuman" s0000e002 "[Judgment] Bakuman - NCOP2 [F119D5EC].mkv" "8" "Opening 2" 
"Bakuman" s0000e001 "[Judgment] Bakuman - NCOP Chou Hero Densetsu [EAED3CD4].mkv" "8" "Chou Hero Densetsu" 
"Bakuman" s0000e001 "[Judgment] Bakuman - St. Visual's Girls Academy NCED [7B14D6CE].mkv" "9" "Ending 1" 
"Bakuman" s0000e001 "[Judgment] Bakuman - St. Visual's Girls Academy NCOP [DA1B5574].mkv" "8" "Opening 1"
```

**Comment by Kuro07** [comment]
Hm.. I must have gotten the wrong log file. I've also added those folders as non-root folder. I'll take a look at the log files later when i get back from work. I'll delete all libraries and re-add them all again later.

**Comment by ZeroQI** [comment]
I had to correct the code to get to the logs included. Uploaded the fix to github master just now.
The filelist indicate you added 'H:\anime\Hanasaku Iroha (1280x720 Blu-Ray FLAC)[Coalgirls]' as root folder when you should have added 'H:\anime'. mostly works but will get empty series in some situations.

**Comment by Kuro07** [comment]
So far I'm not finding any series that has any problems but I found a different bug this time. Whenever an anime that has the same name  is in the same directory and is added to the library, It only adds one of the folders into the library and the others are missing.

Here are some example folder names:
In this case, only S2 is showing up in the library.
Dog Days S2 [BD][720p-AAC][FFF]
Dog Days S3 [BD][720p-AAC][FFF]
--------------------------------------------------------------------
For this one, I had to rename and revert the folder names for it to appear in the library for some reason.
Haiyore! Nyaruko-san [1280x720 Hi10P BD FLAC][TenB]
Haiyore! Nyaruko-san W - 01-12 (BD 10-bit 1280x720 x264 AAC)[Final8]
--------------------------------------------------------------------
For this, only one season is showing and it's Zero no Tsukaima.
Zero no Tsukaima [Doki][1280x720 Hi10P BD FLAC]
Zero no Tsukaima F (2012) [Doki][1280x720 Hi10P BD FLAC]
Zero no Tsukaima Futatsuki no Kishi (2007) [Doki][1280x720 Hi10P BD FLAC]
Zero no Tsukaima Princess no Rondo (2008) [Doki][1280x720 Hi10P BD FLAC]

[Plex Media Scanner (custom ASS).txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/677080/Plex.Media.Scanner.custom.ASS.txt)
[Plex Media Scanner (custom ASS) - filelist .txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/677081/Plex.Media.Scanner.custom.ASS.-.filelist.txt)
[Plex Media Scanner.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/677082/Plex.Media.Scanner.txt)
[Plex Media Scanner.1.txt](https://github.com/ZeroQI/Absolute-Series-Scanner/files/677083/Plex.Media.Scanner.1.txt)

**Comment by ZeroQI** [comment]
Kuro07: i am not sure what i can do since i provide plex with the right information according custom scanner logs... Does a previous version of the scanner adds the files properly?

**Comment by Kuro07** [comment]
I was using a different scanner before i found yours and it was BABS. It was listing all shows before in each different folder only problem with that scanner is that it did not scan all files like yours.

**Comment by Kuro07** [comment]
One more thing, They are in the library when i use view by folders.

**Comment by Kuro07** [comment]
I've renamed the folders instead and they are now appearing on the library. Thanks for the support and the great plugin!

**Comment by ZeroQI** [comment]
it implies they were added ok by the scanner so possibly a plex bug?
I see no issues with the scanner logs , i believe it's a plex issue
if you didn't use back BABS with PMS 1.3.3 then we are not rulling out anything...
If working after renaming, then the scanner works...

**Comment by Kuro07** [comment]
I see. It's my first time using plex so I'm not entirely sure what might be the case but so far your plugin is the best one I've found in sorting anime content. Thanks again for the wonderful support and awesome plugin!

**Comment by ZeroQI** [comment]
Thanks. I beleive it's the only one to allow movies and sereis and detecting openings/endings and also allowing displaying absolute series using tvdb seasons (tvdb2/4 mode) or even using sagas as seasons (tvdb4). Glad you like it :D

**Comment by Kuro07** [comment]
I found another bug. It lists OVAs fine as specials but it's not adding OADs as specials.

Filenames are:
One Punch Man [BD 720p AAC][SallySubs]\[SallySubs] One Punch Man - OAD 1 [BD 720p AAC] [7426FBD5].mkv
One Punch Man [BD 720p AAC][SallySubs]\[SallySubs] One Punch Man - OAD 2 [BD 720p AAC] [6A4C93F2].mkv
One Punch Man [BD 720p AAC][SallySubs]\[SallySubs] One Punch Man - OAD 3 [BD 720p AAC] [28EAAFA5].mkv
One Punch Man [BD 720p AAC][SallySubs]\[SallySubs] One Punch Man - OAD 4 [BD 720p AAC] [22C03908].mkv
One Punch Man [BD 720p AAC][SallySubs]\[SallySubs] One Punch Man - OAD 5 [BD 720p AAC] [3D258608].mkv
One Punch Man [BD 720p AAC][SallySubs]\[SallySubs] One Punch Man - OAD 6 [BD 720p AAC] [0281FD54].mkv

**Comment by ZeroQI** [comment]
Sometimes OAD are the main movie hence season 1 sometimes a special, hence season 0.
Put them in a "Specials" folder.

**Comment by ZeroQI** [comment]
Any update?

**Comment by Kuro07** [comment]
I haven't tested this again. Sorry dude been preoccupied with the holidays. I'll test it out later after getting back from work.

**Comment by ZeroQI** [comment]
Updated the scanner, things like ED are better detected now

**Comment by Kuro07** [comment]
Finally had some time to install the new update. It seems like everything is working perfectly fine at the moment. I'll post a report when i find something. Thanks for the awesome plugin 👍

**Comment by opello** [comment]
> didn't realise i had put OAVs as specials. i put OAD too.

Looks like might have been lost in 512ab6c92eee3cb76fe45fb767a5c242738fc474:
https://github.com/ZeroQI/Absolute-Series-Scanner/commit/512ab6c92eee3cb76fe45fb767a5c242738fc474#diff-7da0de522f8dd1b3ff90ff42b22f0289b075d66b6d154a6b4394a5ab61207b13L42
