### ISSUE TITLE
How to name alternate episodes?

### ISSUE THREAD

**Issue by mcmillhj** [ZeroQI/Absolute-Series-Scanner#72]
I am trying to add the Steins;Gate specials to my Plex library, but having trouble with this one: 
http://anidb.net/perl-bin/animedb.pl?show=ep&eid=173609
http://thetvdb.com/?tab=seasonall&id=244061&lid=7

It is technically an alternate for episode 23 so I am having trouble figuring out how to name it, all of my attempts so far have not found the correct metadata. 

Currently I have it titled as this: 

    Steins;Gate Kyoukaimenjou no Missing Link - s00e01 [anidb-173609]

Any ideas on how to name it properly? 

Thanks.

**Comment by ZeroQI** [comment]
The anidb link says it's special number 2.
You numbered it as for special number 1
S2 or Sp2 or s00e02 would then do...

Tvdb link indicate s00e07 but since there is no seasons beyond the first anidb would be default since 1 season on disk only since specials don't count

**Comment by mcmillhj** [comment]
That worked perfectly, thank you!
