### ISSUE TITLE
Cannot parse Anime with number in title

### ISSUE THREAD

**Issue by azwald** [ZeroQI/Absolute-Series-Scanner#73]
Hi, when scanning Galaxy Express 999 folder, the scanner will put all of them into 1 episode because of 999, can you fix it? or make it into special case?

**Comment by ZeroQI** [comment]
readme t/s process no followed
You probably named files and folder differently, but even though it should manage.
can i have the scanner log custom ?

**Comment by azwald** [comment]
Thanks for the response, the naming is from horriblesubs torrent
I fixed it by adding "999" to WHACK LIST in the script, my guess is the
script thought [HorribleSubs]_Galaxy_Express_999_01 to 999_131 as episode
999 that splitted into 131 parts.
I think it should be safe to add 999 into the WHACK LIST permanently
assuming that there's almost no anime that reached 1000 episode

**Comment by ZeroQI** [comment]
There are 9 series that have "999" in the title. if i remove 999 from the title, they may not match anymore
http://anidb.net/perl-bin/animedb.pl?show=search&do=fulltext&adb.search=999&entity.animetb=1&field.titles=1&h=0&do.fsearch=Search

I wrote the algorithm myself that check for duplicate numbers in other filenames and that failed here, it is probably thinking it is a multi episode.
This could therefore apply to other file naming so really would like to fix.

it wouldn't have anything to correct had the folder name been "Galaxy_Express_999".
Did you name it "Ginga Tetsudou 999"?

I have the filenames, then i need the folder name to reproduce accurately please.
I will investigate as i made it super clever when all files share the same naming convention

**Comment by azwald** [comment]
As I'm currently not in front of my PC, here's the torrent link
https://www.nyaa.se/?page=view&tid=529703

based on that, the folder name is
"[HorribleSubs] Galaxy Express 999 (01-113) [480p] (Batch)"
and the file name would be
"[HorribleSubs] Galaxy Express 999 - 01 [480p].mkv"
...
"[HorribleSubs] Galaxy Express 999 - 113 [480p].mkv"

and I did have to match the series manually to anidb

I'll try to make a folder named Ginga Tetsudou 999 and see what will happen

anyway, except for the first entry of Ginga Tetsudou 999 which is a series,
the others are movie

**Comment by ZeroQI** [comment]
if the folder title match the episode naming, it should remove the title hence "Galaxy Express 999" from the episode and i made recent changes last weeks to handle that in more cases

no need to rename the serie folder "Galaxy Express 999" but "Galaxy Express 999" would help as "(01-113) (Batch)" is kept at the end of the title as some titles differs only by the presence of parenthesis, that why it doesn't match automatically. I will not change that as people naming correctly the series folder shouldn't be penalised (which is the only thing you have to do with the scanner to be fair)

so not "[HorribleSubs]_Galaxy_Express_999_01.mkv" but "[HorribleSubs] Galaxy Express 999 - 01 [480p].mkv" ?

tried in my in progress code and all works no issue and it doesn't look like the code i did recently had an impact
Are you sure you used the latest scanner code to scan ?
Pushing new code to master branch

**Comment by azwald** [comment]
After I update the scanner using the ps1 script, now it correctly state 113 episode instead of just a single episode, thanks for the help
my last update was 8/1/17 scanner
and yes, the file name is "[HorribleSubs] Galaxy Express 999 - 01 [480p].mkv"

**Comment by ZeroQI** [comment]
You use the script! i am glad, wasn't sure anybody used it...
weird bug it was... any serie with all files the same naming convention will benefit from it. thanks for reporting

**Comment by azwald** [comment]
lol that script is the easiest way to update the scanner
anyway, thanks for the hard work

**Comment by ZeroQI** [comment]
I know but nobody ever said anything. Thanks :D
