### ISSUE TITLE
[Req] Emby version

### ISSUE THREAD

**Issue by Kuro07** [ZeroQI/Absolute-Series-Scanner#74]
Would it be possible for you to port the scanner into emby perhaps? I'm liking plex so far but the app itself is limited and it doesn't allow me to use external players on android. I've found some other apps that I could use together with plex however i want to try using emby. Thanks again for the awesome plugin.

**Comment by KingJ** [comment]
I'm not the creator of the scanner, but a port to Emby would probably be extremely difficult - Emby's plugins are C# based whereas Plex's are Python based. Porting to Emby would essentially require re-writing the plugin from scratch.

Plex on Android does support using an external player - head in to Settings > Advanced > Player and check "Use External Player". There are some limitations to this (i.e direct stream only and no status tracking) but it does work.

**Comment by ZeroQI** [comment]
Emby is former "Media Browser 3" and would be available under synology to my surprise https://emby.media/nas-server.html

I just checked the anime agent source code for Emby and you're on your own, as i can't understand anything.... Here is the anime agent source, which support scudLee's anime-lists, but not the scanner benefits
https://github.com/MediaBrowser/MediaBrowser.Plugins.Anime/tree/master/MediaBrowser.Plugins.Anime
