### ISSUE TITLE
New shows not scanning or matching correctly

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Absolute-Series-Scanner#76]
This might be a HAMA/ASS combo.

I'm using the latest HAMA and ASS from a few hours ago.  Additionally, I'm hanging back on Plex 1.2.7 until those issues are sorted out.

I've added a few new shows:  Hand Shakers being the most recent.  Each time, they show up unmatched and with this one in particular as episode 501.  

Logs attached.

[New folder.ZIP](https://github.com/ZeroQI/Absolute-Series-Scanner/files/697061/New.folder.ZIP)

**Comment by ZeroQI** [comment]
Corrected code recently but broke things like that, fixed it in last 2 updates
ep number corrected in scanner.
hama responsible for matching
```
Scanner call - root: 'Z:\Anime Series', path: 'Hand Shakers', dirs: '0', files: '1'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc: '|||||||||||'
misc_count: '{'': 4, '1': 1, 'contact': 1, 'conductor': 1, 'to': 1}'
misc_words: '['1', 'contact', 'conductor', 'to']'
"Hand Shakers" s0000e501 "Hand Shakers - 1 - Conductor to Contact.mkv"

```
With latest code
```
Scanner call - root: '/volume1/downloads/_Plex_Current issues', path: 'Hand Shakers', dirs: '0', files: '1'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
misc: '1|conductor|to|contact'
misc_words: '[]'
"Hand Shakers" s0001e001 "Hand Shakers - 1 - Conductor to Contact.mkv" "Conductor To Contact" 

```

**Comment by sven-7** [comment]
Yes, good to go.  Sorry, missed the response.
