### ISSUE TITLE
Custom Seasons with anidb

### ISSUE THREAD

**Issue by isairz** [ZeroQI/Absolute-Series-Scanner#80]
Thanks for [Nice guide](https://www.reddit.com/r/PleX/comments/2yk49z/guide_plex_and_anime_a_guide_to_combining_movies/) and Nice this Plugins.

I am trying to sort `Monogatari` Series by BD released date.
But TV DB sets `Nekomonogatari` as Special, not Season 3
http://thetvdb.com/?tab=seasonall&id=102261&lid=7

How to set seasons as below (Like series of movies) ?
```
Monogatari/  -- Group
	[1] Bakemonogatari [anidb=6327]
	[2] Nisemonogatari [anidb=8658]
	[3] Nekomonogatari (Kuro) [anidb=9453]
	[4] Monogatari Series: Second Season [anidb=9183]
	[5] Hanamonogatari: Suruga Devil [anidb=10046]
	[6] Tsukimonogatari: Yotsugi Doll [anidb=10891]
	[7] Owarimonogatari [anidb=11350]
	[8] Koyomimonogatari [anidb=11827] 
```

**Comment by ZeroQI** [comment]
you could map every episode to the right tvdb season/ep or let the scanner find the tvdb mapping automatically by putting [anidb2-xxxxx] instead of [anidb-xxxxx]

**Comment by isairz** [comment]
`anidb2` could map right episode at tvdb, but `Nekomonogatari` classified as `Special`.
(Nekomonogatari 01 -> s00e03, ... , Nekomonogatari 04 -> s00e06)

Is it impossible to classify it as an independent season?

**Comment by ZeroQI** [comment]
[tvdb-102261-s5] would map as season 5 but no metadata.
my agent allow to follow anidb or tvdb naming convention...
mapping manually like that will leave metadata wrong
Easier to leave with anidb numbering and force ids and et up a collection tag "monogatari" for all

**Comment by isairz** [comment]
Finally, I understand season system of plex.

In same series, it is hard to manage S1 NCOP, S2 NCOP, S1 PV and S2 PV ... 
`collection` tag is best solution for me and it is works well with HAMA.

Thanks for your advice.
