### ISSUE TITLE
Request: Pre-fill Original Title

### ISSUE THREAD

**Issue by avluis** [ZeroQI/Absolute-Series-Scanner#89]
I hope I'm putting this in the correct repo, my apologies if I fail you there.
I currently make use of the `anidb2` `guid_type` in my directory structure, as illustrated:

![DirStructure](https://cloud.githubusercontent.com/assets/875593/24733536/f8984eb2-1a3d-11e7-88ce-ddda9967efbb.PNG)

Which grants me the AniDB to TVDB mapping that I prefer since I share my library is shared with folks not that intimate (yet) with the medium.
Ex; Instead of Kuroshisuji, they'll request Black Butler (they don't know better).

The trade-off here is that for many series, the english name is carried and I have a difficult time finding series by their Japanese name.
A simple fix is to tag the show (series) with the original title, in example:

![Actually, I Am](https://cloud.githubusercontent.com/assets/875593/24733680/a622d7a0-1a3e-11e7-9c75-3880af88e053.PNG)

Which then allows me to search for said show (series) with its original title, as such:

![Jitsu wa Watashi wa](https://cloud.githubusercontent.com/assets/875593/24733708/cb8decb4-1a3e-11e7-9c20-b4a7170719a2.PNG)

My request is just that; pre-fill the original title of a series (not asking for episodes here, but maybe someone wants that as well).

**Comment by ZeroQI** [comment]
Scanner readme:
> #Absolute Series Scanner
> 
> The Plex Scanner will make the video files showing in Plex, if not showing in Plex, it is a scanner issue. A Plex series scanner choose the following from the folders and file names:
> 
> Serie name
> Season number
> Episode number
> Episode title (not filled by plex default series scanner, until the metadata agent refreshes it)
> Episode year
> The Plex metadata agent will find metadata (Serie Title, summary year, episode title, summary, posters, fanart, tags, ... ) for files showing in Plex. Anything missing there while the file shows up in Plex is an Agent issue, refer to the Agent readme here: https://github.com/ZeroQI/Hama.bundle/blob/master/README.md#Absolute Series Scanner
> 
> The Plex Scanner will make the video files showing in Plex, if not showing in Plex, it is a scanner issue. A Plex series scanner choose the following from the folders and file names:
> 
> Serie name
> Season number
> Episode number
> Episode title (not filled by plex default series scanner, until the metadata agent refreshes it)
> Episode year
> The Plex metadata agent will find metadata (Serie Title, summary year, episode title, summary, posters, fanart, tags, ... ) for files showing in Plex. Anything missing there while the file shows up in Plex is an Agent issue, refer to the Agent readme here: https://github.com/ZeroQI/Hama.bundle/blob/master/README.md
> 
> #Absolute Series Scanner
> 
> The Plex Scanner will make the video files showing in Plex, if not showing in Plex, it is a scanner issue. A Plex series scanner choose the following from the folders and file names:
> 
> Serie name
> Season number
> Episode number
> Episode title (not filled by plex default series scanner, until the metadata agent refreshes it)
> Episode year
> The Plex metadata agent will find metadata (Serie Title, summary year, episode title, summary, posters, fanart, tags, ... ) for files showing in Plex. Anything missing there while the file shows up in Plex is an Agent issue, refer to the Agent readme here: https://github.com/ZeroQI/Hama.bundle/blob/master/README.md#Absolute Series Scanner
> 
> The Plex Scanner will make the video files showing in Plex, if not showing in Plex, it is a scanner issue. A Plex series scanner choose the following from the folders and file names:
> 
> Serie name
> Season number
> Episode number
> Episode title (not filled by plex default series scanner, until the metadata agent refreshes it)
> Episode year
> The Plex metadata agent will find metadata (Serie Title, summary year, episode title, summary, posters, fanart, tags, ... ) for files showing in Plex. Anything missing there while the file shows up in Plex is an Agent issue, refer to the Agent readme here: https://github.com/ZeroQI/Hama.bundle/blob/master/README.md
> 

Original title can be updated agent side, but doesn't show in the gui, Plex issue...
"title_sort" however can be used and does what you want:
- You can search the jap title, will show the english name serie but not the original title underneath so unlike your picture...
- Already implemented in my dev agent this morning but flatmate working from home and shut the NAS down :( Will post in https://github.com/ZeroQI/Hama.bundle/releases this evening7pm uk time

**Comment by avluis** [comment]
Is that readme copied three times? Time for bed sir.
Thanks though, good info in regards to what is currently possible.

**Comment by ZeroQI** [comment]
Corrected, indeed sticky fingers + tiredness, i typed lounged on the bad with laptop on my bedside table...

The agent can write the field, read it back so it is stored but plex doesn't search it...
It's like there's a different storage space in the gui than the field for the agent....
I made it work with "title_sort" but then the NAS was shutdown against my will :/

**Comment by ZeroQI** [comment]
Check hama agent release tab.
Fix there BUT
- title showing is 1st language choice
- sort_title is the second
- display title is sorted through the sort title so out of order
- Plex original title is buggy and not working
- got a complaint on fix since title sorted from sort tile so the order is off.   will need an option to toggle on or off.
- Will need a ticket open by plex pass member to solve original title.

**Comment by avluis** [comment]
I'm a Plex Pass member, tell me what you need and I'll get it done.

**Comment by ZeroQI** [comment]
i thought there was a forum for plex members for bug reports...
For now we use https://forums.plex.tv/discussion/comment/1415530#Comment_1415530 for this bug...

**Comment by avluis** [comment]
I'm seeing a general section -- where other pass members request support, but no bug reports unfortunately -- will just add to the bug report thread for now.

**Comment by ZeroQI** [comment]
Please do so.

**Comment by avluis** [comment]
K -- just updated Hama & ASS; so far the logs say they are doing good.
Looking forward to that tickbox to enable/disable the requested feature (will probably prefer for Plex to fix the bug first then implement the feature -- don't want to be wasting your time on this).

**Comment by ZeroQI** [comment]
for now sort title = title otherwise the list is out of order.
Once plex fix original title, will implement fix...
