### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by DragonDisk** [ZeroQI/Absolute-Series-Scanner#9]
Hi there,

Any chance you could make the code [PEP8 compliant](https://www.python.org/dev/peps/pep-0008/)? It's a bit difficult to read the code or to make changes as is.

You could use a tool such as [autopep8](https://pypi.python.org/pypi/autopep8).

Thanks!

**Comment by ZeroQI** [comment]
Can you not use the official plex series scanner as base ? If not, you can run it yourself and use the code transformed to read and apply the modification on the un-touched code.

if i were to do that, it would make the code take at least twice more lines and make it unreadable for me to have all the relevant code in one page on screen and i can't follow the inner working anymore.

Am an autodidact for python who correct bugs at times on my phone. I couldn't if i normalise the code. That would however maybe solve the error line reported being wrong, so once i solve the current bugs i might consider it.

**Comment by DragonDisk** [comment]
The problem is, while I have my own personal fork of your code with small changes and PEP8 compliant, keeping it automatically updated with your repository is difficult since git can't diff and merge the changes properly.

I just wanted you to consider it, it's fine if you don't want to at the moment. Feel free to close the issue.

**Comment by ZeroQI** [comment]
https://pep8.xyz/ i pasted the code, it's 722 lines long converted from 340.
I tried to look but it removed all the comments at the end of the line and that makes list of variables difficult to read for me...
May i ask what you changed ? i will include in my code anything usefull for the greater good

**Comment by DragonDisk** [comment]
I haven't changed much of value, just some folder scanning logic to better fit my setup.
