### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by Rebtand** [ZeroQI/Absolute-Series-Scanner#91]
i'm not sure what is happening and i am very sorry if this has been addressed already -- here is my log file (zipped so i can upload it)

[Plex Media Scanner.zip](https://github.com/ZeroQI/Absolute-Series-Scanner/files/907890/Plex.Media.Scanner.zip)

**Comment by Rebtand** [comment]
i should probably add that i have been using babs prior to this -- which has been working but doesn't seem to support combining multiple series

**Comment by EndOfLine369** [comment]
Hi @Rebtand,

Looks like you placed the scanner file in the wrong place. You should not be placing it in the Plex Scanners.bundle.

Please see the README for install instructions.
https://github.com/ZeroQI/Absolute-Series-Scanner#install

Install
=======
- https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/Scanners/Series/Absolute%20Series%20Scanner.py
Into:
- [...]/Plex/Library/Application Support/Plex Media Server/Scanners/Series/Absolute Series Scanner.py
Note:
- "Scanners" and "Series" folder are not created by default and will need creating.
- "Scanners" folder will be besides "Plug-in Support" folder in the same parent directory.

EX:
![image](https://cloud.githubusercontent.com/assets/16750699/24834853/3556c458-1cb6-11e7-8c4b-4c82cf3d8fad.png)

If on windows, like it looks like you are, and are not sure where the directory is right click the Plex server icon on your tray and select to open up the plug-ins folder.
![image](https://cloud.githubusercontent.com/assets/16750699/24834896/371788b2-1cb7-11e7-94ea-074e63c3d556.png)

**Comment by Rebtand** [comment]
thank you!!! i had the scanner in both folders for some reason
