### ISSUE TITLE
problem with Ark folder scan

### ISSUE THREAD

**Issue by ZeroQI** [ZeroQI/Absolute-Series-Scanner#96]
https://forums.plex.tv/discussion/comment/1441706/#Comment_1441706

the scanner is not taking the path
anime_name/Season X/Ark xxx/anime_name s01e001.ext
not sure to catch the issue.
here find the log :

> May 20, 2017 01:10:39.935 [2208] DEBUG - Adding subdirectory for scanner: J:\Manga\a voir\One piece [tvdb4-81797]\Season 1\Ark Morgan
> May 20, 2017 01:10:39.935 [2208] DEBUG - * Scanning directory J:\Manga\a voir\One piece [tvdb4-81797]\Season 1\Ark Morgan (parent: yes)
> May 20, 2017 01:10:39.958 [2208] DEBUG - Adding file for scanner: J:\Manga\a voir\One piece [tvdb4-81797]\Season 1\Ark Morgan\One Piece s01e001.mp4
> May 20, 2017 01:10:39.958 [2208] DEBUG - Adding file for scanner: J:\Manga\a voir\One piece [tvdb4-81797]\Season 1\Ark Morgan\One Piece s01e002.mp4
> May 20, 2017 01:10:39.959 [2208] DEBUG - Adding file for scanner: J:\Manga\a voir\One piece [tvdb4-81797]\Season 1\Ark Morgan\One Piece s01e003.mp4
> May 20, 2017 01:10:39.960 [2208] ERROR - Error in Python: Running scanner:
> Traceback (most recent call last):
> File "G:\Users\Oyoo\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 282, in Scan
> set_logging("Main", os.path.join(CACHE_PATH, (os.path.dirname(path) or path or '_root')+'.log'))
> File "G:\Users\Oyoo\AppData\Local\Plex Media Server\Scanners\Series\Absolute Series Scanner.py", line 101, in set_logging
> else: handler = logging.FileHandler (os.path.join(CACHE_PATH, filename), mode='w')
> File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging__init__.py", line 913, in init
> StreamHandler.init(self, self.open())
> File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\logging__init__.py", line 943, in _open
> stream = open(self.baseFilename, self.mode)

**Comment by ZeroQI** [comment]
try
    def Scan(path, files, mediaList, subdirs, language=None, root=None, **kwargs): #get called for root and each root folder
      Log.info("Library: '%s', root: '%s', path: '%s', dirs: '%d', files: '%d', Scan date: %s, CACHE_PATH: %s" % (PLEX_LIBRARY[root] if root in PLEX_LIBRARY else "no valid X-Plex-Token.id", root, path, len(subdirs), len(files), time.strftime("%Y-%m-%d %H:%M:%S"), CACHE_PATH))
      Log.info("".ljust(157, '='))  
      if len(files)==0:  return  # If direct scanner call on folder (not root) then skip if no files as will be called on subfolders too
      set_logging("Main", os.path.join(CACHE_PATH, (os.path.dirname(path) or path or '_root_')+'.log'))
      for subdir in subdirs:

**Comment by oyooman** [comment]
hi, 

seems there is a part of the code missing. 

i'm having the following error : 

IOError: (2, 'No such file or directory', '[.....]\\AppData\\Local\\Plex Media Server\\Plug-in Support\\Data\\com.plexapp.agents.hama\\DataItems\\Logs\\Series\\One piece [tvdb4-81797]\\Season 1.log')

**Comment by ZeroQI** [comment]
since it crash, you have the other log they are linked
scanner doesn't create right log for seasons folders, need to fix that

**Comment by ZeroQI** [comment]
really need to fix that. working on it

**Comment by ZeroQI** [comment]
@oyooman if on macosx, crete the folder in users folder and that solve issues
please try version linked above

**Comment by ZeroQI** [comment]
no answer, fix was in readme. user related issue seemingly. closing bug
