### ISSUE TITLE
wrong episode count and mapping

### ISSUE THREAD

**Issue by sadeqAlbana** [ZeroQI/Absolute-Series-Scanner#99]
this issue is regarding Phantom: Requiem for the Phantom [anidb-6256]
I have the episodes named correctly and the scanner detects and maps them properly except for episode 5, 15 and 25 (anything that contains the number "5") even though there is no different in the name pattern from the rest of the episodes
photos that might help
![episode list](https://cloud.githubusercontent.com/assets/29160428/26752849/d8fb6be6-4861-11e7-8992-4ff05942e056.jpg)
![plex 1](https://cloud.githubusercontent.com/assets/29160428/26752850/d8fbca14-4861-11e7-92d7-3da88bca3bdd.jpg)
![plex 2](https://cloud.githubusercontent.com/assets/29160428/26752848/d8f85de8-4861-11e7-8c3a-ba597454bee7.jpg)

**Comment by ZeroQI** [comment]
Add to WHACK_PRE_CLEAN array the following: "FLAC5.1", "x264-CTR"
all separated by commas, no commas after the last element
If it solve, will add to the code the fix...

**Comment by sadeqAlbana** [comment]
sorry for the late reply, it's seems adding the array character "[FLAC5.1]" solved the problem
